constantBreakup Class Reference
constantBreakup Class Reference
Constant breakup kernel. The value of the kernel is read from dictionary or assumed equal to 1. The minimum value of the abscissa after which the model is applied can be defined by the user or it is assumed to be 1.
Public Member Functions
TypeName ("constant")
Runtime type information.
constantBreakup (const dictionary &dict, const fvMesh &mesh)
Construct from components.
virtual ~constantBreakup ()
Destructor.
virtual scalar Kb (const scalar &abscissa, const label &celli) const
Breakup kernel.
Public Member Functions inherited from breakupKernel
TypeName ("breakupKernel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, breakupKernel, dictionary,(const dictionary &dict, const fvMesh &mesh),(dict, mesh))
breakupKernel (const dictionary &dict, const fvMesh &mesh)
Construct from components.
virtual ~breakupKernel ()
Destructor.
Additional Inherited Members
Static Public Member Functions inherited from breakupKernel
static autoPtr< breakupKernel > New (const dictionary &dict, const fvMesh &mesh)
Protected Attributes inherited from breakupKernel
const dictionary & dict_
Dictionary.
const fvMesh & mesh_
Mesh.
const dimensionedScalar Cb_
Coefficient of aggregation kernel.
Detailed Description
Constant breakup kernel. The value of the kernel is read from dictionary or assumed equal to 1. The minimum value of the abscissa after which the model is applied can be defined by the user or it is assumed to be 1.
Source files
constantBreakup.H
constantBreakup.C
Definition at line 54 of file constantBreakup.H.
Constructor & Destructor Documentation
constantBreakup (const dictionary & dict, const fvMesh & mesh)
Construct from components.
Definition at line 54 of file constantBreakup.C.
References constantBreakup::~constantBreakup().
~constantBreakup () virtual
Destructor.
Definition at line 67 of file constantBreakup.C.
References constantBreakup::Kb().
Referenced by constantBreakup::constantBreakup().
Member Function Documentation
TypeName ("constant")
Runtime type information.
Foam::scalar Kb (const scalar & abscissa, const label & celli) const virtual
Breakup kernel.
Implements breakupKernel.
Definition at line 75 of file constantBreakup.C.
Referenced by constantBreakup::~constantBreakup().
The documentation for this class was generated from the following files:
constantBreakup.H
constantBreakup.C