OpenQBMM: extendedFieldMomentInversion Class Reference
extendedFieldMomentInversion Class Reference
Inverts a volUnivariateMomentFieldSet using the extended quadrature method of moments.
Public Member Functions
TypeName ("extendedFieldMomentInversion")
Runtime type information.
extendedFieldMomentInversion (const dictionary &dict, const label nMoments, const label nSecondaryNodes)
Construct from dictionary.
~extendedFieldMomentInversion ()
Destructor.
virtual void invert (const volUnivariateMomentFieldSet &moments, PtrList< volScalarNode > &nodes)
Invert moments in the entire computational domain.
virtual void invertBoundaryMoments (const volUnivariateMomentFieldSet &moments, PtrList< volScalarNode > &nodes)
Invert moments on boundaries.
virtual bool invertLocalMoments (const volUnivariateMomentFieldSet &moments, PtrList< volScalarNode > &nodes, const label celli, const bool fatalErrorOnFailedRealizabilityTest=true)
Invert moments in a single cell.
Public Member Functions inherited from fieldMomentInversion
TypeName ("fieldMomentInversion")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, fieldMomentInversion, dictionary,(const dictionary &dict, const label nMoments, const label nSecondaryNodes),(dict, nMoments, nSecondaryNodes))
fieldMomentInversion (const dictionary &dict, const label nMoments, const label nSecondaryNodes)
Construct from univariateMomentSet.
virtual ~fieldMomentInversion ()
Destructor.
bool extended ()
Return extended type.
Additional Inherited Members
Static Public Member Functions inherited from fieldMomentInversion
static autoPtr< fieldMomentInversion > New (const dictionary &dict, const label nMoments, const label nSecondaryNodes)
Protected Attributes inherited from fieldMomentInversion
bool extended_
Boolean flag to indicate extended type of inversion.
Detailed Description
Inverts a volUnivariateMomentFieldSet using the extended quadrature method of moments.
Source files
extendedFieldMomentInversion.H
extendedFieldMomentInversion.C
Definition at line 51 of file extendedFieldMomentInversion.H.
Constructor & Destructor Documentation
extendedFieldMomentInversion (const dictionary & dict, const label nMoments, const label nSecondaryNodes)
Construct from dictionary.
Definition at line 46 of file extendedFieldMomentInversion.C.
~extendedFieldMomentInversion ()
Destructor.
Definition at line 69 of file extendedFieldMomentInversion.C.
References extendedFieldMomentInversion::invert().
Member Function Documentation
TypeName ("extendedFieldMomentInversion")
Runtime type information.
void invert (const volUnivariateMomentFieldSet & moments, PtrList< volScalarNode > & nodes) virtual
Invert moments in the entire computational domain.
Implements fieldMomentInversion.
Definition at line 76 of file extendedFieldMomentInversion.C.
References extendedFieldMomentInversion::invertBoundaryMoments().
Referenced by extendedFieldMomentInversion::~extendedFieldMomentInversion().
void invertBoundaryMoments (const volUnivariateMomentFieldSet & moments, PtrList< volScalarNode > & nodes) virtual
Invert moments on boundaries.
Implements fieldMomentInversion.
Definition at line 92 of file extendedFieldMomentInversion.C.
References extendedFieldMomentInversion::invertLocalMoments(), quadratureNode< weightType, abscissaType, sigmaType >::nSecondaryNodes(), quadratureNode< weightType, abscissaType, sigmaType >::primaryAbscissa(), quadratureNode< weightType, abscissaType, sigmaType >::primaryWeight(), quadratureNode< weightType, abscissaType, sigmaType >::secondaryAbscissae(), quadratureNode< weightType, abscissaType, sigmaType >::secondaryWeights(), quadratureNode< weightType, abscissaType, sigmaType >::sigma(), and momentFieldSet< momentType, nodeType >::support().
Referenced by extendedFieldMomentInversion::invert().
bool invertLocalMoments (const volUnivariateMomentFieldSet & moments, PtrList< volScalarNode > & nodes, const label celli, const bool fatalErrorOnFailedRealizabilityTest = true) virtual
Invert moments in a single cell.
Implements fieldMomentInversion.
Definition at line 156 of file extendedFieldMomentInversion.C.
References quadratureNode< weightType, abscissaType, sigmaType >::primaryAbscissa(), quadratureNode< weightType, abscissaType, sigmaType >::primaryWeight(), quadratureNode< weightType, abscissaType, sigmaType >::secondaryAbscissae(), quadratureNode< weightType, abscissaType, sigmaType >::secondaryWeights(), quadratureNode< weightType, abscissaType, sigmaType >::sigma(), and momentFieldSet< momentType, nodeType >::support().
Referenced by extendedFieldMomentInversion::invertBoundaryMoments().
The documentation for this class was generated from the following files:
extendedFieldMomentInversion.H
extendedFieldMomentInversion.C