univariateMomentInversion Class Reference
univariateMomentInversion Class Reference abstract
Abstract class for univariate quadrature on a moment set.
Public Member Functions
TypeName ("univariateMomentInversion")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, univariateMomentInversion, dictionary,(const dictionary &dict),(dict))
univariateMomentInversion (const dictionary &dict)
Construct from univariateMomentSet.
virtual ~univariateMomentInversion ()
Destructor.
virtual void calcNQuadratureNodes (univariateMomentSet &moments)=0
Calculates the number of quadrature nodes.
virtual void correctRecurrence (univariateMomentSet &moments, scalarList &alpha, scalarList &beta, const scalar minKnownAbscissa=0, const scalar maxKnownAbscissa=0)=0
Modify the recurrence relation for fixed-point quadrature.
virtual void invert (univariateMomentSet &moments, const scalar minKnownAbscissa=0, const scalar maxKnownAbscissa=0)
Invert the set of moments to compute weights and abscissae.
const scalarList & abscissae () const
Return quadrature abscissae.
label nNodes () const
Return the number of nodes.
const scalarList & weights () const
Return quadrature weigths.
Static Public Member Functions
static autoPtr< univariateMomentInversion > New (const dictionary &dict)
Protected Member Functions
void JacobiMatrix (univariateMomentSet &moments, scalarSquareMatrix &z, const scalar minKnownAbscissa=0, const scalar maxKnownAbscissa=0)
Create Jacobi matrix.
Protected Attributes
label nInvertibleMoments_
Number of invertible moments for the user-selected quadrature.
label nNodes_
Number of quadrature nodes.
scalarList abscissae_
Quadrature abscissae.
scalarList weights_
Quadrature weights.
Detailed Description
Abstract class for univariate quadrature on a moment set.
Source files
univariateMomentInversion.H
univariateMomentInversion.C
univariateMomentInversionI.H
Definition at line 51 of file univariateMomentInversion.H.
Constructor & Destructor Documentation
univariateMomentInversion (const dictionary & dict)
Construct from univariateMomentSet.
Definition at line 42 of file univariateMomentInversion.C.
~univariateMomentInversion () virtual
Destructor.
Definition at line 55 of file univariateMomentInversion.C.
References univariateMomentInversion::JacobiMatrix().
Member Function Documentation
void JacobiMatrix (univariateMomentSet & moments, scalarSquareMatrix & z, const scalar minKnownAbscissa = 0, const scalar maxKnownAbscissa = 0) protected
Create Jacobi matrix.
Definition at line 62 of file univariateMomentInversion.C.
References univariateMomentSet::alphaRecurrence(), univariateMomentSet::betaRecurrence(), and univariateMomentInversion::invert().
Referenced by univariateMomentInversion::~univariateMomentInversion().
TypeName ("univariateMomentInversion")
Runtime type information.
declareRunTimeSelectionTable (autoPtr , univariateMomentInversion , dictionary , (const dictionary &dict) , (dict))
Foam::autoPtr< Foam::univariateMomentInversion > New (const dictionary & dict) static
Definition at line 32 of file newUnivariateMomentInversion.C.
virtual void calcNQuadratureNodes (univariateMomentSet & moments) pure virtual
Calculates the number of quadrature nodes.
Implemented in gaussLobattoMomentInversion, gaussRadauMomentInversion, and gaussMomentInversion.
virtual void correctRecurrence (univariateMomentSet & moments, scalarList & alpha, scalarList & beta, const scalar minKnownAbscissa = 0, const scalar maxKnownAbscissa = 0) pure virtual
Modify the recurrence relation for fixed-point quadrature.
Implemented in gaussLobattoMomentInversion, gaussRadauMomentInversion, and gaussMomentInversion.
void invert (univariateMomentSet & moments, const scalar minKnownAbscissa = 0, const scalar maxKnownAbscissa = 0) virtual
Invert the set of moments to compute weights and abscissae.
Definition at line 92 of file univariateMomentInversion.C.
References eigenSolver::eigenvaluesRe(), eigenSolver::eigenvectors(), and univariateMomentSet::isDegenerate().
Referenced by univariateMomentInversion::JacobiMatrix().
const Foam::scalarList & abscissae () const inline
Return quadrature abscissae.
Definition at line 28 of file univariateMomentInversionI.H.
References univariateMomentInversion::abscissae_.
Foam::label nNodes () const inline
Return the number of nodes.
Definition at line 33 of file univariateMomentInversionI.H.
References univariateMomentInversion::nNodes_.
const Foam::scalarList & weights () const inline
Return quadrature weigths.
Definition at line 38 of file univariateMomentInversionI.H.
References univariateMomentInversion::weights_.
Member Data Documentation
label nInvertibleMoments_ protected
Number of invertible moments for the user-selected quadrature.
Definition at line 67 of file univariateMomentInversion.H.
label nNodes_ protected
Number of quadrature nodes.
Definition at line 70 of file univariateMomentInversion.H.
Referenced by univariateMomentInversion::nNodes().
scalarList abscissae_ protected
Quadrature abscissae.
Definition at line 73 of file univariateMomentInversion.H.
Referenced by univariateMomentInversion::abscissae().
scalarList weights_ protected
Quadrature weights.
Definition at line 76 of file univariateMomentInversion.H.
Referenced by univariateMomentInversion::weights().
The documentation for this class was generated from the following files:
univariateMomentInversion.H
newUnivariateMomentInversion.C
univariateMomentInversion.C
univariateMomentInversionI.H