OpenQBMM: univariatePDFTransportModel Class Reference
univariatePDFTransportModel Class Reference abstract
Public Member Functions
univariatePDFTransportModel (const word &name, const dictionary &dict, const fvMesh &mesh, const surfaceScalarField &phi, const word &support)
Construct from components.
virtual ~univariatePDFTransportModel ()
Destructor.
const univariateQuadratureApproximation & quadrature () const
Access.
virtual void solve ()
Edit.
Public Member Functions inherited from PDFTransportModel
PDFTransportModel (const word &name, const dictionary &dict, const fvMesh &mesh)
Construct from components.
virtual ~PDFTransportModel ()
Destructor.
Protected Member Functions
virtual tmp< fvScalarMatrix > momentDiffusion (const volUnivariateMoment &moment)=0
Diffusion term.
virtual tmp< fvScalarMatrix > implicitMomentSource (const volUnivariateMoment &moment)=0
Calculate implicit source terms.
virtual void explicitMomentSource ()
Calculate explicit source terms with realizable ODE solver.
virtual scalar cellMomentSource (label &momentOrder, label &celli)=0
Calculate source term for moment equation in the specified cell.
Protected Attributes
univariateQuadratureApproximation quadrature_
Univariate quadrature approximation used to solve PDF transport.
univariateMomentAdvection momentAdvection_
Moment advection.
Protected Attributes inherited from PDFTransportModel
const fvMesh & mesh_
Constant reference to the mesh.
Detailed Description
Definition at line 53 of file univariatePDFTransportModel.H.
Constructor & Destructor Documentation
univariatePDFTransportModel (const word & name, const dictionary & dict, const fvMesh & mesh, const surfaceScalarField & phi, const word & support)
Construct from components.
Definition at line 32 of file univariatePDFTransportModel.C.
References univariatePDFTransportModel::~univariatePDFTransportModel().
~univariatePDFTransportModel () virtual
Destructor.
Definition at line 60 of file univariatePDFTransportModel.C.
References univariatePDFTransportModel::explicitMomentSource().
Referenced by univariatePDFTransportModel::univariatePDFTransportModel().
Member Function Documentation
virtual tmp<fvScalarMatrix> momentDiffusion (const volUnivariateMoment & moment) protected pure virtual
Diffusion term.
Referenced by univariatePDFTransportModel::solve().
virtual tmp<fvScalarMatrix> implicitMomentSource (const volUnivariateMoment & moment) protected pure virtual
Calculate implicit source terms.
Referenced by univariatePDFTransportModel::solve().
void explicitMomentSource () protected virtual
Calculate explicit source terms with realizable ODE solver.
Local time
Definition at line 66 of file univariatePDFTransportModel.C.
Referenced by univariatePDFTransportModel::solve(), and univariatePDFTransportModel::~univariatePDFTransportModel().
virtual scalar cellMomentSource (label & momentOrder, label & celli) protected pure virtual
Calculate source term for moment equation in the specified cell.
const Foam::univariateQuadratureApproximation & quadrature () const inline
Access.
Returns a const reference to the quadrature approximation
Definition at line 29 of file univariatePDFTransportModelI.H.
References univariatePDFTransportModel::quadrature_.
void solve () virtual
Edit.
Solve univariate PDF transport equation
Implements PDFTransportModel.
Reimplemented in univariatePopulationBalance, and turbulentMixing.
Definition at line 236 of file univariatePDFTransportModel.C.
References univariateMomentAdvection::divMoments(), univariatePDFTransportModel::explicitMomentSource(), univariatePDFTransportModel::implicitMomentSource(), univariatePDFTransportModel::momentAdvection_, univariatePDFTransportModel::momentDiffusion(), quadratureApproximation< momentFieldSetType, nodeType >::moments(), quadratureApproximation< momentFieldSetType, nodeType >::nMoments(), univariatePDFTransportModel::quadrature_, univariateMomentAdvection::update(), and quadratureApproximation< momentFieldSetType, nodeType >::updateQuadrature().
Referenced by turbulentMixing::solve(), and univariatePopulationBalance::solve().
Member Data Documentation
univariateQuadratureApproximation quadrature_ protected
Univariate quadrature approximation used to solve PDF transport.
Definition at line 86 of file univariatePDFTransportModel.H.
Referenced by univariatePDFTransportModel::quadrature(), and univariatePDFTransportModel::solve().
univariateMomentAdvection momentAdvection_ protected
Moment advection.
Definition at line 89 of file univariatePDFTransportModel.H.
Referenced by univariatePDFTransportModel::solve().
The documentation for this class was generated from the following files:
univariatePDFTransportModel.H
univariatePDFTransportModel.C
univariatePDFTransportModelI.H