hydrodynamicAggregation Class Reference
hydrodynamicAggregation Class Reference
Hydrodynamic aggregation kernel with user defined coefficient (default Cagg = 1).
Public Member Functions
TypeName ("hydrodynamic")
Runtime type information.
hydrodynamicAggregation (const dictionary &dict, const fvMesh &mesh)
Construct from components.
virtual ~hydrodynamicAggregation ()
Destructor.
virtual scalar Ka (const scalar &abscissa1, const scalar &abscissa2, const label &celli) const
Aggregation kernel.
Public Member Functions inherited from aggregationKernel
TypeName ("aggregationKernel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, aggregationKernel, dictionary,(const dictionary &dict, const fvMesh &mesh),(dict, mesh))
aggregationKernel (const dictionary &dict, const fvMesh &mesh)
Construct from components.
virtual ~aggregationKernel ()
Destructor.
Additional Inherited Members
Static Public Member Functions inherited from aggregationKernel
static autoPtr< aggregationKernel > New (const dictionary &dict, const fvMesh &mesh)
Protected Attributes inherited from aggregationKernel
const dictionary & dict_
Dictionary.
const fvMesh & mesh_
Mesh.
const dimensionedScalar Ca_
Coefficient of aggregation kernel.
Detailed Description
Hydrodynamic aggregation kernel with user defined coefficient (default Cagg = 1).
where
= Aggregation coefficient [1/s]
= Abscissa of particle i [m]
= Abscissa of particle j [m]
Source files
hydrodynamicAggregation.H
hydrodynamicAggregation.C
Definition at line 77 of file hydrodynamicAggregation.H.
Constructor & Destructor Documentation
hydrodynamicAggregation (const dictionary & dict, const fvMesh & mesh)
Construct from components.
Definition at line 54 of file hydrodynamicAggregation.C.
References hydrodynamicAggregation::~hydrodynamicAggregation().
~hydrodynamicAggregation () virtual
Destructor.
Definition at line 66 of file hydrodynamicAggregation.C.
References hydrodynamicAggregation::Ka().
Referenced by hydrodynamicAggregation::hydrodynamicAggregation().
Member Function Documentation
TypeName ("hydrodynamic")
Runtime type information.
Foam::scalar Ka (const scalar & abscissa1, const scalar & abscissa2, const label & celli) const virtual
Aggregation kernel.
Implements aggregationKernel.
Definition at line 75 of file hydrodynamicAggregation.C.
Referenced by hydrodynamicAggregation::~hydrodynamicAggregation().
The documentation for this class was generated from the following files:
hydrodynamicAggregation.H
hydrodynamicAggregation.C