OpenQBMM: eigenSolver Class Reference
eigenSolver Class Reference
Eigenvalues and eigenvectors of a square real matrix.
Public Member Functions
eigenSolver (const scalarSquareMatrix &A)
Construct from a scalarSquareMatrix.
eigenSolver (const scalarSquareMatrix &A, bool symmetric)
Construct from a scalarSquareMatrix and symmetry information.
const scalarDiagonalMatrix & eigenvaluesRe () const
Return real part of the eigenvalues.
const scalarDiagonalMatrix & eigenvaluesIm () const
const scalarSquareMatrix & eigenvectors () const
Return eigenvectors.
Detailed Description
Eigenvalues and eigenvectors of a square real matrix.
Acknowledgments This implementation derives almost completely from TNT/JAMA, a public-domain library developed at NIST, available at http://math.nist.gov/tnt/index.html Their implementation was based upon EISPACK.
The tridiagonaliseSymmMatrix, symmTridiagQL, Hessemberg and realSchur methods are based on the Algol procedures tred2 by Bowdler, Martin, Reinsch, and Wilkinson, Handbook for Auto. Comp., Vol. II-Linear Algebra, and the corresponding FORTRAN subroutine in EISPACK.
Source files
eigenSolver.H
eigenSolver.C
Definition at line 61 of file eigenSolver.H.
Constructor & Destructor Documentation
eigenSolver (const scalarSquareMatrix & A)
Construct from a scalarSquareMatrix.
Definition at line 33 of file eigenSolver.C.
eigenSolver (const scalarSquareMatrix & A, bool symmetric)
Construct from a scalarSquareMatrix and symmetry information.
Does not perform symmetric check
Definition at line 57 of file eigenSolver.C.
References p.
Member Function Documentation
const scalarDiagonalMatrix& eigenvaluesRe () const inline
Return real part of the eigenvalues.
Definition at line 120 of file eigenSolver.H.
Referenced by hermiteQuadrature::calcHermiteQuadrature(), hermiteQuadrature::hermiteQuadrature(), univariateMomentInversion::invert(), and extendedMomentInversion::normalizedMomentError().
const scalarDiagonalMatrix& eigenvaluesIm () const inline
Definition at line 125 of file eigenSolver.H.
const scalarSquareMatrix& eigenvectors () const inline
Return eigenvectors.
Definition at line 131 of file eigenSolver.H.
Referenced by hermiteQuadrature::calcHermiteQuadrature(), hermiteQuadrature::hermiteQuadrature(), univariateMomentInversion::invert(), and extendedMomentInversion::normalizedMomentError().
The documentation for this class was generated from the following files:
eigenSolver.H
eigenSolver.C