OpenQBMM: basicFieldMomentInversion Class Reference
basicFieldMomentInversion Class Reference
Invert moment a volUnivariateMomentFieldSet using basic quadrature inversion.
Public Member Functions
TypeName ("basicFieldMomentInversion")
Runtime type information.
basicFieldMomentInversion (const dictionary &dict, const label nMoments, const label nSecondaryNodes)
Construct from dictionary.
~basicFieldMomentInversion ()
Destructor.
virtual void invert (const volUnivariateMomentFieldSet &moments, PtrList< volScalarNode > &nodes)
Invert moments in the entire computational domain.
virtual void invertBoundaryMoments (const volUnivariateMomentFieldSet &moments, PtrList< volScalarNode > &nodes)
Invert moments on boundaries.
virtual bool invertLocalMoments (const volUnivariateMomentFieldSet &moments, PtrList< volScalarNode > &nodes, const label celli, const bool fatalErrorOnFailedRealizabilityTest=true)
Invert moments in a single cell.
Public Member Functions inherited from fieldMomentInversion
TypeName ("fieldMomentInversion")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, fieldMomentInversion, dictionary,(const dictionary &dict, const label nMoments, const label nSecondaryNodes),(dict, nMoments, nSecondaryNodes))
fieldMomentInversion (const dictionary &dict, const label nMoments, const label nSecondaryNodes)
Construct from univariateMomentSet.
virtual ~fieldMomentInversion ()
Destructor.
bool extended ()
Return extended type.
Additional Inherited Members
Static Public Member Functions inherited from fieldMomentInversion
static autoPtr< fieldMomentInversion > New (const dictionary &dict, const label nMoments, const label nSecondaryNodes)
Protected Attributes inherited from fieldMomentInversion
bool extended_
Boolean flag to indicate extended type of inversion.
Detailed Description
Invert moment a volUnivariateMomentFieldSet using basic quadrature inversion.
Source files
basicFieldMomentInversion.H
basicFieldMomentInversion.C
Definition at line 51 of file basicFieldMomentInversion.H.
Constructor & Destructor Documentation
basicFieldMomentInversion (const dictionary & dict, const label nMoments, const label nSecondaryNodes)
Construct from dictionary.
Definition at line 46 of file basicFieldMomentInversion.C.
~basicFieldMomentInversion ()
Destructor.
Definition at line 76 of file basicFieldMomentInversion.C.
References basicFieldMomentInversion::invert().
Member Function Documentation
TypeName ("basicFieldMomentInversion")
Runtime type information.
void invert (const volUnivariateMomentFieldSet & moments, PtrList< volScalarNode > & nodes) virtual
Invert moments in the entire computational domain.
Implements fieldMomentInversion.
Definition at line 83 of file basicFieldMomentInversion.C.
References basicFieldMomentInversion::invertBoundaryMoments().
Referenced by basicFieldMomentInversion::~basicFieldMomentInversion().
void invertBoundaryMoments (const volUnivariateMomentFieldSet & moments, PtrList< volScalarNode > & nodes) virtual
Invert moments on boundaries.
Implements fieldMomentInversion.
Definition at line 99 of file basicFieldMomentInversion.C.
References basicFieldMomentInversion::invertLocalMoments(), quadratureNode< weightType, abscissaType, sigmaType >::primaryAbscissa(), quadratureNode< weightType, abscissaType, sigmaType >::primaryWeight(), and momentFieldSet< momentType, nodeType >::support().
Referenced by basicFieldMomentInversion::invert().
bool invertLocalMoments (const volUnivariateMomentFieldSet & moments, PtrList< volScalarNode > & nodes, const label celli, const bool fatalErrorOnFailedRealizabilityTest = true) virtual
Invert moments in a single cell.
Implements fieldMomentInversion.
Definition at line 169 of file basicFieldMomentInversion.C.
References quadratureNode< weightType, abscissaType, sigmaType >::primaryAbscissa(), quadratureNode< weightType, abscissaType, sigmaType >::primaryWeight(), and momentFieldSet< momentType, nodeType >::support().
Referenced by basicFieldMomentInversion::invertBoundaryMoments().
The documentation for this class was generated from the following files:
basicFieldMomentInversion.H
basicFieldMomentInversion.C