OpenQBMM: extendedMomentInversion Class Reference
extendedMomentInversion Class Reference abstract
Abstract class to allow run-time selection of the algorithm to be used for the extended quadrature method of moments.
Public Member Functions
TypeName ("extendedMomentInversion")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, extendedMomentInversion, dictionary,(const dictionary &dict, const label nMoments, const label nSecondaryNodes),(dict, nMoments, nSecondaryNodes))
extendedMomentInversion (const dictionary &dict, const label nMoments, const label nSecondaryNodes)
virtual ~extendedMomentInversion ()
Destructor.
void invert (const univariateMomentSet &moments)
Invert moments to find weight, abscissae and sigma.
label nMoments ()
Return number of moments.
label nPrimaryNodes ()
Return number of primary quadrature nodes.
label nSecondaryNodes ()
Return number of secondary quadrature nodes.
scalar sigma () const
Return the value of the sigma parameter.
const scalarList & primaryWeights () const
Return primary quadrature weights.
const scalarList & primaryAbscissae () const
Return primary quadrature abscissae.
const scalarRectangularMatrix & secondaryWeights () const
Return secondary quadrature weights.
const scalarRectangularMatrix & secondaryAbscissae () const
Return secondary quadrature abscissae.
Static Public Member Functions
static autoPtr< extendedMomentInversion > New (const dictionary &dict, const label nMoments, const label nSecondaryNodes)
Protected Member Functions
virtual scalar secondaryAbscissa (scalar primaryAbscissa, scalar secondaryAbscissa, scalar sigma)=0
Protected member functions.
virtual void momentsStarToMoments (scalar sigma, univariateMomentSet &moments, const univariateMomentSet &momentsStar)=0
Compute moments from starred moments.
virtual void momentsToMomentsStar (scalar sigma, const univariateMomentSet &moments, univariateMomentSet &momentsStar)=0
Compute the starred moments from moments.
virtual scalar m2N (scalar sigma, const univariateMomentSet &momentsStar)=0
Compute the last moment from starred moments.
scalar normalizedMomentError (scalar sigma, const univariateMomentSet &moments, univariateMomentSet &momentsStar)
Compute the normalized moment error.
virtual void recurrenceRelation (scalarList &a, scalarList &b, scalar primaryAbscissa, scalar sigma)=0
Recurrence relation for polynomials orthogonal to kernel function.
virtual scalar sigmaMax (univariateMomentSet &moments)=0
Compute maximum value of sigma to ensure realizability.
Protected Attributes
label nMoments_
Number of moments.
label nPrimaryNodes_
Number of primary quadrature nodes.
label nSecondaryNodes_
Number of secondary quadrature nodes.
scalarList primaryWeights_
Primary quadrature weights.
scalarList primaryAbscissae_
Primary quadrature abscissae.
scalar sigma_
Parameter sigma of the kernel density function.
scalarRectangularMatrix secondaryWeights_
Secondary quadrature weights.
scalarRectangularMatrix secondaryAbscissae_
Secondary quadrature abscissae.
scalar minMean_
Minimum mean to perform EQMOM reconstruction.
scalar minVariance_
Minimum variance to perform EQMOM reconstruction.
label maxSigmaIter_
Maximum number of iterations allowed to find sigma_.
scalar momentsTol_
Tolerance on moment conservation.
scalar sigmaMin_
Minimum allowed value of the parameter sigma of the kernel density.
scalar sigmaTol_
Tolerance for the change in the sigma parameter.
scalar targetFunctionTol_
Tolerance for the target function.
bool foundUnrealizableSigma_
Bool to track values of sigma_ that lead to unrealizable moments.
bool nullSigma_
Bool to track if sigma = 0 is root.
Detailed Description
Abstract class to allow run-time selection of the algorithm to be used for the extended quadrature method of moments.
References
    "An extended quadrature method of moments for population balance
    equations"
    C Yuan, F Laurent, R O Fox
    Journal of Aerosol Science
    Volume 51, Pages 1-23, 2012
    "The theory of canonical moments with applications in Statistics,
    Probability and Analysis"
    H Dette, W J Studden
    Wiley & Sons, 1997
    "Orthogonal Polynomials: Computation and Approximation"
    W Gautschi
    Oxford University Press, 2004
Source files
extendedMomentInversion.H
extendedMomentInversion.C
newExtendedMomentInversion.C
Definition at line 78 of file extendedMomentInversion.H.
Constructor & Destructor Documentation
extendedMomentInversion (const dictionary & dict, const label nMoments, const label nSecondaryNodes)
Definition at line 41 of file extendedMomentInversion.C.
~extendedMomentInversion () virtual
Destructor.
Definition at line 73 of file extendedMomentInversion.C.
Member Function Documentation
virtual scalar secondaryAbscissa (scalar primaryAbscissa, scalar secondaryAbscissa, scalar sigma) protected pure virtual
Protected member functions.
Computes kernel density function from abscissa and sigma
Implemented in lognormalEQMOM, betaEQMOM, and gammaEQMOM.
virtual void momentsStarToMoments (scalar sigma, univariateMomentSet & moments, const univariateMomentSet & momentsStar) protected pure virtual
Compute moments from starred moments.
Implemented in lognormalEQMOM, betaEQMOM, and gammaEQMOM.
virtual void momentsToMomentsStar (scalar sigma, const univariateMomentSet & moments, univariateMomentSet & momentsStar) protected pure virtual
Compute the starred moments from moments.
Implemented in lognormalEQMOM, betaEQMOM, and gammaEQMOM.
virtual scalar m2N (scalar sigma, const univariateMomentSet & momentsStar) protected pure virtual
Compute the last moment from starred moments.
Implemented in lognormalEQMOM, betaEQMOM, and gammaEQMOM.
Foam::scalar normalizedMomentError (scalar sigma, const univariateMomentSet & moments, univariateMomentSet & momentsStar) protected
Compute the normalized moment error.
Definition at line 429 of file extendedMomentInversion.C.
References eigenSolver::eigenvaluesRe(), eigenSolver::eigenvectors(), momentSet::support(), and univariateMomentSet::update().
Referenced by extendedMomentInversion::invert().
virtual void recurrenceRelation (scalarList & a, scalarList & b, scalar primaryAbscissa, scalar sigma) protected pure virtual
Recurrence relation for polynomials orthogonal to kernel function.
Implemented in lognormalEQMOM, betaEQMOM, and gammaEQMOM.
virtual scalar sigmaMax (univariateMomentSet & moments) protected pure virtual
Compute maximum value of sigma to ensure realizability.
The value is exact for the two-node case. For cases with a larger number of nodes, this provides an over-estimation of the maximum value of the sigma parameter which ensures moment realizability.
Implemented in lognormalEQMOM, betaEQMOM, and gammaEQMOM.
TypeName ("extendedMomentInversion")
Runtime type information.
declareRunTimeSelectionTable (autoPtr , extendedMomentInversion , dictionary , (const dictionary &dict, const label nMoments, const label nSecondaryNodes) , (dict, nMoments, nSecondaryNodes))
Foam::autoPtr< Foam::extendedMomentInversion > New (const dictionary & dict, const label nMoments, const label nSecondaryNodes) static
Definition at line 31 of file newExtendedMomentInversion.C.
void invert (const univariateMomentSet & moments)
Invert moments to find weight, abscissae and sigma.
Definition at line 78 of file extendedMomentInversion.C.
References univariateMomentSet::isOnMomentSpaceBoundary(), extendedMomentInversion::normalizedMomentError(), univariateMomentSet::nRealizableMoments(), and momentSet::support().
label nMoments () inline
Return number of moments.
Definition at line 290 of file extendedMomentInversion.H.
References extendedMomentInversion::nMoments_.
label nPrimaryNodes () inline
Return number of primary quadrature nodes.
Definition at line 296 of file extendedMomentInversion.H.
References extendedMomentInversion::nPrimaryNodes_.
label nSecondaryNodes () inline
Return number of secondary quadrature nodes.
Definition at line 302 of file extendedMomentInversion.H.
References extendedMomentInversion::nSecondaryNodes_.
scalar sigma () const inline
Return the value of the sigma parameter.
Definition at line 308 of file extendedMomentInversion.H.
References extendedMomentInversion::sigma_.
const scalarList& primaryWeights () const inline
Return primary quadrature weights.
Definition at line 314 of file extendedMomentInversion.H.
References extendedMomentInversion::primaryWeights_.
const scalarList& primaryAbscissae () const inline
Return primary quadrature abscissae.
Definition at line 320 of file extendedMomentInversion.H.
References extendedMomentInversion::primaryAbscissae_.
const scalarRectangularMatrix& secondaryWeights () const inline
Return secondary quadrature weights.
Definition at line 326 of file extendedMomentInversion.H.
References extendedMomentInversion::secondaryWeights_.
const scalarRectangularMatrix& secondaryAbscissae () const inline
Return secondary quadrature abscissae.
Definition at line 332 of file extendedMomentInversion.H.
References extendedMomentInversion::secondaryAbscissae_.
Member Data Documentation
label nMoments_ protected
Number of moments.
Definition at line 127 of file extendedMomentInversion.H.
Referenced by extendedMomentInversion::nMoments().
label nPrimaryNodes_ protected
Number of primary quadrature nodes.
Definition at line 130 of file extendedMomentInversion.H.
Referenced by extendedMomentInversion::nPrimaryNodes().
label nSecondaryNodes_ protected
Number of secondary quadrature nodes.
Definition at line 133 of file extendedMomentInversion.H.
Referenced by extendedMomentInversion::nSecondaryNodes().
scalarList primaryWeights_ protected
Primary quadrature weights.
Definition at line 136 of file extendedMomentInversion.H.
Referenced by extendedMomentInversion::primaryWeights().
scalarList primaryAbscissae_ protected
Primary quadrature abscissae.
Definition at line 139 of file extendedMomentInversion.H.
Referenced by extendedMomentInversion::primaryAbscissae().
scalar sigma_ protected
Parameter sigma of the kernel density function.
Definition at line 142 of file extendedMomentInversion.H.
Referenced by extendedMomentInversion::sigma().
scalarRectangularMatrix secondaryWeights_ protected
Secondary quadrature weights.
Definition at line 145 of file extendedMomentInversion.H.
Referenced by extendedMomentInversion::secondaryWeights().
scalarRectangularMatrix secondaryAbscissae_ protected
Secondary quadrature abscissae.
Definition at line 148 of file extendedMomentInversion.H.
Referenced by extendedMomentInversion::secondaryAbscissae().
scalar minMean_ protected
Minimum mean to perform EQMOM reconstruction.
Definition at line 151 of file extendedMomentInversion.H.
scalar minVariance_ protected
Minimum variance to perform EQMOM reconstruction.
Definition at line 154 of file extendedMomentInversion.H.
label maxSigmaIter_ protected
Maximum number of iterations allowed to find sigma_.
Definition at line 157 of file extendedMomentInversion.H.
scalar momentsTol_ protected
Tolerance on moment conservation.
Definition at line 160 of file extendedMomentInversion.H.
scalar sigmaMin_ protected
Minimum allowed value of the parameter sigma of the kernel density.
function. Below this value, QMOM is used.
Definition at line 164 of file extendedMomentInversion.H.
scalar sigmaTol_ protected
Tolerance for the change in the sigma parameter.
Definition at line 167 of file extendedMomentInversion.H.
scalar targetFunctionTol_ protected
Tolerance for the target function.
Definition at line 170 of file extendedMomentInversion.H.
bool foundUnrealizableSigma_ protected
Bool to track values of sigma_ that lead to unrealizable moments.
Definition at line 173 of file extendedMomentInversion.H.
bool nullSigma_ protected
Bool to track if sigma = 0 is root.
Definition at line 176 of file extendedMomentInversion.H.
The documentation for this class was generated from the following files:
extendedMomentInversion.H
extendedMomentInversion.C
newExtendedMomentInversion.C