constantAggregation Class Reference
constantAggregation Class Reference
Constant aggregation kernel. The value of the kernel is read from dictionary or assumed equal to 1.
Public Member Functions
TypeName ("constant")
Runtime type information.
constantAggregation (const dictionary &dict, const fvMesh &mesh)
Construct from components.
virtual ~constantAggregation ()
Destructor.
virtual scalar Ka (const scalar &abscissa1, const scalar &abscissa2, const label &celli) const
Aggregation kernel.
Public Member Functions inherited from aggregationKernel
TypeName ("aggregationKernel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, aggregationKernel, dictionary,(const dictionary &dict, const fvMesh &mesh),(dict, mesh))
aggregationKernel (const dictionary &dict, const fvMesh &mesh)
Construct from components.
virtual ~aggregationKernel ()
Destructor.
Additional Inherited Members
Static Public Member Functions inherited from aggregationKernel
static autoPtr< aggregationKernel > New (const dictionary &dict, const fvMesh &mesh)
Protected Attributes inherited from aggregationKernel
const dictionary & dict_
Dictionary.
const fvMesh & mesh_
Mesh.
const dimensionedScalar Ca_
Coefficient of aggregation kernel.
Detailed Description
Constant aggregation kernel. The value of the kernel is read from dictionary or assumed equal to 1.
where
= Aggregation coefficient [1/s]
Source files
constantAggregation.H
constantAggregation.C
Definition at line 67 of file constantAggregation.H.
Constructor & Destructor Documentation
constantAggregation (const dictionary & dict, const fvMesh & mesh)
Construct from components.
Definition at line 54 of file constantAggregation.C.
References constantAggregation::~constantAggregation().
~constantAggregation () virtual
Destructor.
Definition at line 66 of file constantAggregation.C.
References constantAggregation::Ka().
Referenced by constantAggregation::constantAggregation().
Member Function Documentation
TypeName ("constant")
Runtime type information.
Foam::scalar Ka (const scalar & abscissa1, const scalar & abscissa2, const label & celli) const virtual
Aggregation kernel.
Implements aggregationKernel.
Definition at line 74 of file constantAggregation.C.
Referenced by constantAggregation::~constantAggregation().
The documentation for this class was generated from the following files:
constantAggregation.H
constantAggregation.C