My Project: fullFragmentation Class Reference
fullFragmentation Class Reference
Daughter distribution of fragments with full fragmentation.
Public Member Functions
TypeName ("fullFragmentation")
Runtime type information.
fullFragmentation (const dictionary &dict)
Construct from components.
virtual ~fullFragmentation ()
Destructor.
virtual scalar mD (const label &order, const scalar &abscissa) const
Moment of the daughter distribution function.
Public Member Functions inherited from daughterDistribution
TypeName ("daughterDistribution")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, daughterDistribution, dictionary,(const dictionary &dict),(dict))
daughterDistribution (const dictionary &dict)
Construct from components.
virtual ~daughterDistribution ()
Destructor.
Additional Inherited Members
Static Public Member Functions inherited from daughterDistribution
static autoPtr< daughterDistribution > New (const dictionary &dict)
Protected Attributes inherited from daughterDistribution
const dictionary & dict_
Detailed Description
Daughter distribution of fragments with full fragmentation.
The moment source term corresponding to the distribution is:
where
= Order of the moment [-]
= Particle size [m]
= Primary particle size [m]
Source files
fullFragmentation.H
fullFragmentation.C
Definition at line 78 of file fullFragmentation.H.
Constructor & Destructor Documentation
fullFragmentation (const dictionary & dict)
Construct from components.
Definition at line 54 of file fullFragmentation.C.
References fullFragmentation::~fullFragmentation().
~fullFragmentation () virtual
Destructor.
Definition at line 65 of file fullFragmentation.C.
References fullFragmentation::mD().
Referenced by fullFragmentation::fullFragmentation().
Member Function Documentation
TypeName ("fullFragmentation")
Runtime type information.
Foam::scalar mD (const label & order, const scalar & abscissa) const virtual
Moment of the daughter distribution function.
Implements daughterDistribution.
Definition at line 74 of file fullFragmentation.C.
Referenced by fullFragmentation::~fullFragmentation().
The documentation for this class was generated from the following files:
fullFragmentation.H
fullFragmentation.C