My Project: hermiteQuadrature Class Reference
hermiteQuadrature Class Reference
Use spectral methods to generate samples for multivaraites Gaussian distribution.
Public Member Functions
hermiteQuadrature (const label &nDim, const label &nOrder)
Construct from a scalarDiagonalMatrix.
void calcHermiteQuadrature (const vector &mu, const symmTensor &Pp)
const scalarList & hermiteWeights () const
Return eigenvalues.
const vectorList & hermiteAbscissas () const
Return eigenvectors.
vectorList & hermiteAbscissas ()
const vectorList & hermiteOriginalAbscissas () const
const scalar & maxAbs () const
Detailed Description
Use spectral methods to generate samples for multivaraites Gaussian distribution.
Definition at line 49 of file hermiteQuadrature.H.
Constructor & Destructor Documentation
hermiteQuadrature (const label & nDim, const label & nOrder)
Construct from a scalarDiagonalMatrix.
Definition at line 36 of file hermiteQuadrature.C.
References hermiteQuadrature::calcHermiteQuadrature(), eigenSolver::eigenvaluesRe(), eigenSolver::eigenvectors(), and p.
Member Function Documentation
void calcHermiteQuadrature (const vector & mu, const symmTensor & Pp)
Definition at line 137 of file hermiteQuadrature.C.
References eigenSolver::eigenvaluesRe(), and eigenSolver::eigenvectors().
Referenced by hermiteQuadrature::hermiteQuadrature().
const scalarList& hermiteWeights () const inline
Return eigenvalues.
Definition at line 99 of file hermiteQuadrature.H.
const vectorList& hermiteAbscissas () const inline
Return eigenvectors.
Definition at line 105 of file hermiteQuadrature.H.
vectorList& hermiteAbscissas () inline
Definition at line 110 of file hermiteQuadrature.H.
const vectorList& hermiteOriginalAbscissas () const inline
Definition at line 115 of file hermiteQuadrature.H.
const scalar& maxAbs () const inline
Definition at line 120 of file hermiteQuadrature.H.
The documentation for this class was generated from the following files:
hermiteQuadrature.H
hermiteQuadrature.C