turbulentBrownian Class Reference
turbulentBrownian Class Reference
Brownian aggregation kernel supplemented for particles in turbulent flows in conditions when the particle size is smaller than the local Kolmogorov scale.
Public Member Functions
TypeName ("turbulentBrownian")
Runtime type information.
turbulentBrownian (const dictionary &dict, const fvMesh &mesh)
Construct from components.
virtual ~turbulentBrownian ()
Destructor.
virtual scalar Ka (const scalar &abscissa1, const scalar &abscissa2, const label &celli) const
Aggregation kernel.
Public Member Functions inherited from aggregationKernel
TypeName ("aggregationKernel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, aggregationKernel, dictionary,(const dictionary &dict, const fvMesh &mesh),(dict, mesh))
aggregationKernel (const dictionary &dict, const fvMesh &mesh)
Construct from components.
virtual ~aggregationKernel ()
Destructor.
Additional Inherited Members
Static Public Member Functions inherited from aggregationKernel
static autoPtr< aggregationKernel > New (const dictionary &dict, const fvMesh &mesh)
Protected Attributes inherited from aggregationKernel
const dictionary & dict_
Dictionary.
const fvMesh & mesh_
Mesh.
const dimensionedScalar Ca_
Coefficient of aggregation kernel.
Detailed Description
Brownian aggregation kernel supplemented for particles in turbulent flows in conditions when the particle size is smaller than the local Kolmogorov scale.
where
= Absolute Temperature [K]
= Turbulent dissipation rate [m2/s3]
= Boltzmann's constant [J/K]
= Molecular dynamic iscosity [Pa s]
= Turbulent Kinematic viscosity [m2/s]
= Abscissa of particle i [m]
= Abscissa of particle j [m]
References
        "Versuch Einer Mathematischen Theorie Der Koagulationskinetic Kolloider
        Losunger"
        M X Smoluchowski
        Zeitschrift fur Physikalische Chemie
        Volume 92, Pages 129-142, 1917
        "Kinetics of turbulent coagulation studied by means of end-over-end
        rotation"
        Y Adachi, M A Cohen Stuart, R Fokkink
        Journal of Colloid and Interface Science
        Volume 165, Pages 310-317, 1994
Source files
turbulentBrownian.H
turbulentBrownian.C
Definition at line 118 of file turbulentBrownian.H.
Constructor & Destructor Documentation
turbulentBrownian (const dictionary & dict, const fvMesh & mesh)
Construct from components.
Definition at line 55 of file turbulentBrownian.C.
References turbulentBrownian::~turbulentBrownian().
~turbulentBrownian () virtual
Destructor.
Definition at line 79 of file turbulentBrownian.C.
References turbulentBrownian::Ka().
Referenced by turbulentBrownian::turbulentBrownian().
Member Function Documentation
TypeName ("turbulentBrownian")
Runtime type information.
Foam::scalar Ka (const scalar & abscissa1, const scalar & abscissa2, const label & celli) const virtual
Aggregation kernel.
Implements aggregationKernel.
Definition at line 87 of file turbulentBrownian.C.
Referenced by turbulentBrownian::~turbulentBrownian().
The documentation for this class was generated from the following files:
turbulentBrownian.H
turbulentBrownian.C