erosion Class Reference
erosion Class Reference
Daughter distribution of fragments for erosion.
Public Member Functions
TypeName ("erosion")
Runtime type information.
erosion (const dictionary &dict)
Construct from components.
virtual ~erosion ()
Destructor.
virtual scalar mD (const label &order, const scalar &abscissa) const
Moment of the daughter distribution function.
Public Member Functions inherited from daughterDistribution
TypeName ("daughterDistribution")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, daughterDistribution, dictionary,(const dictionary &dict),(dict))
daughterDistribution (const dictionary &dict)
Construct from components.
virtual ~daughterDistribution ()
Destructor.
Additional Inherited Members
Static Public Member Functions inherited from daughterDistribution
static autoPtr< daughterDistribution > New (const dictionary &dict)
Protected Attributes inherited from daughterDistribution
const dictionary & dict_
Detailed Description
Daughter distribution of fragments for erosion.
The moment source term corresponding to the distribution is:
where
= Order of the moment [-]
= Particle size [m]
= Primary particle size [m]
Source files
erosion.H
erosion.C
Definition at line 78 of file erosion.H.
Constructor & Destructor Documentation
erosion (const dictionary & dict)
Construct from components.
Definition at line 54 of file erosion.C.
References erosion::~erosion().
~erosion () virtual
Destructor.
Definition at line 66 of file erosion.C.
References erosion::mD().
Referenced by erosion::erosion().
Member Function Documentation
TypeName ("erosion")
Runtime type information.
Foam::scalar mD (const label & order, const scalar & abscissa) const virtual
Moment of the daughter distribution function.
Implements daughterDistribution.
Definition at line 74 of file erosion.C.
Referenced by erosion::~erosion().
The documentation for this class was generated from the following files:
erosion.H
erosion.C