My Project: IEM Class Reference
IEM Class Reference
Interaction by exchange with the mean mixing model.
Public Member Functions
TypeName ("IEM")
Runtime type information.
IEM (const dictionary &dict)
Construct from components.
virtual ~IEM ()
Destructor.
virtual tmp< fvScalarMatrix > K (const volUnivariateMoment &moment, const volUnivariateMomentFieldSet &moments) const
Mixing kernel.
Public Member Functions inherited from mixingKernel
TypeName ("mixingKernel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, mixingKernel, dictionary,(const dictionary &dict),(dict))
mixingKernel (const dictionary &dict)
Construct from components.
virtual ~mixingKernel ()
Destructor.
Additional Inherited Members
Static Public Member Functions inherited from mixingKernel
static autoPtr< mixingKernel > New (const dictionary &dict)
Protected Attributes inherited from mixingKernel
const dictionary & dict_
const dimensionedScalar Cphi_
Coefficient of aggregation kernel.
const dimensionedScalar Cmixing_
Coefficient of relaxation control.
Detailed Description
Interaction by exchange with the mean mixing model.
References
    "Computational Models for Turbulent Reacting Flows"
    R O Fox
    Cambridge University Press
Source files
IEM.H
IEM.C
Definition at line 59 of file IEM.H.
Constructor & Destructor Documentation
IEM (const dictionary & dict)
Construct from components.
Definition at line 55 of file IEM.C.
References IEM::~IEM().
~IEM () virtual
Destructor.
Definition at line 66 of file IEM.C.
References IEM::K().
Referenced by IEM::IEM().
Member Function Documentation
TypeName ("IEM")
Runtime type information.
Foam::tmp< Foam::fvScalarMatrix > K (const volUnivariateMoment & moment, const volUnivariateMomentFieldSet & moments) const virtual
Mixing kernel.
Implements mixingKernel.
Definition at line 74 of file IEM.C.
References moment< fieldType, nodeType >::order().
Referenced by IEM::~IEM().
The documentation for this class was generated from the following files:
IEM.H
IEM.C