constantGrowth Class Reference
constantGrowth Class Reference
Constant growth model. The value of the constant is read from dictionary or assumed equal to 1. The minimum and maximum value of the abscissa to which the model is applied can be defined by the user or it is assumed to be 1.0e-10 and 1.0e10.
Public Member Functions
TypeName ("constant")
Runtime type information.
constantGrowth (const dictionary &dict)
Construct from components.
virtual ~constantGrowth ()
Destructor.
virtual scalar Kg (const scalar &abscissa) const
Growth model.
Public Member Functions inherited from growthModel
TypeName ("growthModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, growthModel, dictionary,(const dictionary &dict),(dict))
growthModel (const dictionary &dict)
Construct from components.
virtual ~growthModel ()
Destructor.
Additional Inherited Members
Static Public Member Functions inherited from growthModel
static autoPtr< growthModel > New (const dictionary &dict)
Protected Attributes inherited from growthModel
const dictionary & dict_
const dimensionedScalar Cg_
Coefficient of aggregation kernel.
Detailed Description
Constant growth model. The value of the constant is read from dictionary or assumed equal to 1. The minimum and maximum value of the abscissa to which the model is applied can be defined by the user or it is assumed to be 1.0e-10 and 1.0e10.
Source files
constantGrowth.H
constantGrowth.C
Definition at line 57 of file constantGrowth.H.
Constructor & Destructor Documentation
constantGrowth (const dictionary & dict)
Construct from components.
Definition at line 56 of file constantGrowth.C.
References constantGrowth::~constantGrowth().
~constantGrowth () virtual
Destructor.
Definition at line 69 of file constantGrowth.C.
References constantGrowth::Kg().
Referenced by constantGrowth::constantGrowth().
Member Function Documentation
TypeName ("constant")
Runtime type information.
Foam::scalar Kg (const scalar & abscissa) const virtual
Growth model.
Implements growthModel.
Definition at line 77 of file constantGrowth.C.
Referenced by constantGrowth::~constantGrowth().
The documentation for this class was generated from the following files:
constantGrowth.H
constantGrowth.C