conditionalMomentInversion Class Reference
conditionalMomentInversion Class Reference
Implementation of the conditional quadrature method of moments.
Public Member Functions
conditionalMomentInversion (const dictionary &dict, const label nMoments, const Map< label > map, const labelList &nNodes, const List< word > &support)
Disallow default bitwise copy construct.
virtual ~conditionalMomentInversion ()
Destructor.
void invert (const nDimensionalMappedList< scalar > &moments)
Invert moments to find weights and abscissae.
label nMoments ()
Return number of moments.
const labelList & nNodes ()
Return number of number of nodes in each dimension.
const PtrList< nDimensionalMappedList< scalar > > & weights () const
Return mapped quadrature weights for each dimension.
const PtrList< nDimensionalMappedList< scalar > > & abscissae () const
Return mapped quadrature abscissae for each dimension.
Detailed Description
Implementation of the conditional quadrature method of moments.
References
    "Conditional quadrature method of moments for kinetic equations"
    C Yuan, R O Fox
    Journal of Computational Physics
    Volume 230, Pages 8216-8246, 2011
Source files
conditionalMomentInversion.H
conditionalMomentInversion.C
conditionalMomentInversionI.C
Definition at line 63 of file conditionalMomentInversion.H.
Constructor & Destructor Documentation
conditionalMomentInversion (const dictionary & dict, const label nMoments, const Map< label > map, const labelList & nNodes, const List< word > & support)
Disallow default bitwise copy construct.
conditionalMomentInversion(const conditionalMomentInversion&);Disallow default bitwise assignment
void operator=(const conditionalMomentInversion&);
Definition at line 32 of file conditionalMomentInversion.C.
~conditionalMomentInversion () virtual
Destructor.
Definition at line 133 of file conditionalMomentInversion.C.
References conditionalMomentInversion::invert().
Member Function Documentation
void invert (const nDimensionalMappedList< scalar > & moments)
Invert moments to find weights and abscissae.
Definition at line 140 of file conditionalMomentInversion.C.
References conditionalMomentInversion::nNodes().
Referenced by conditionalMomentInversion::~conditionalMomentInversion().
Foam::label nMoments () inline
Return number of moments.
Return the total number of moments.
Definition at line 30 of file conditionalMomentInversionI.H.
const Foam::labelList & nNodes () inline
Return number of number of nodes in each dimension.
Return the list of nNodes.
Definition at line 36 of file conditionalMomentInversionI.H.
Referenced by conditionalMomentInversion::invert().
const Foam::PtrList< Foam::nDimensionalMappedList< Foam::scalar > > & weights () const inline
Return mapped quadrature weights for each dimension.
Return mapped list of weights.
Definition at line 43 of file conditionalMomentInversionI.H.
const Foam::PtrList< Foam::nDimensionalMappedList< Foam::scalar > > & abscissae () const inline
Return mapped quadrature abscissae for each dimension.
Return mapped list of abscissae.
Definition at line 50 of file conditionalMomentInversionI.H.
The documentation for this class was generated from the following files:
conditionalMomentInversion.H
conditionalMomentInversion.C
conditionalMomentInversionI.H