My Project: quadratureNode< weightType, abscissaType, sigmaType >::iNew Class Reference
quadratureNode< weightType, abscissaType, sigmaType >::iNew Class Reference
Return a pointer to a new quadrature node created on freestore.
Public Member Functions
iNew (const word &distributionName, const fvMesh &mesh, const dimensionSet &weightDimensions, const dimensionSet &abscissaDimensions, const wordList &boundaryTypes, const bool extended, const label nSecondaryNodes)
autoPtr< quadratureNode< weightType, abscissaType, sigmaType > > operator() (Istream &is) const
Detailed Description
template<class weightType, class abscissaType, class sigmaType>
class Foam::quadratureNode< weightType, abscissaType, sigmaType >::iNew
Return a pointer to a new quadrature node created on freestore.
from Istream
Definition at line 121 of file quadratureNode.H.
Constructor & Destructor Documentation
iNew (const word & distributionName, const fvMesh & mesh, const dimensionSet & weightDimensions, const dimensionSet & abscissaDimensions, const wordList & boundaryTypes, const bool extended, const label nSecondaryNodes) inline
Definition at line 134 of file quadratureNode.H.
Member Function Documentation
autoPtr< quadratureNode<weightType, abscissaType, sigmaType> > operator() (Istream & is) const inline
Definition at line 158 of file quadratureNode.H.
References quadratureNode< weightType, abscissaType, sigmaType >::extended(), quadratureNode< weightType, abscissaType, sigmaType >::name(), quadratureNode< weightType, abscissaType, sigmaType >::nSecondaryNodes(), quadratureNode< weightType, abscissaType, sigmaType >::primaryAbscissa(), quadratureNode< weightType, abscissaType, sigmaType >::primaryWeight(), quadratureNode< weightType, abscissaType, sigmaType >::secondaryAbscissae(), quadratureNode< weightType, abscissaType, sigmaType >::secondaryWeights(), quadratureNode< weightType, abscissaType, sigmaType >::sigma(), and quadratureNode< weightType, abscissaType, sigmaType >::~quadratureNode().
The documentation for this class was generated from the following file:
quadratureNode.H