OpenQBMM: quadratureNode< weightType, abscissaType, sigmaType > Class Template Reference
quadratureNode< weightType, abscissaType, sigmaType > Class Template Reference
Extended version of the quadrature node, which stores the list of secondary weights and abscissae associated to the primary weight and abscissa, and the sigma parameter.
Classes
class iNew
Return a pointer to a new quadrature node created on freestore.
Public Member Functions
quadratureNode (const word &name, const word &distributionName, const dictionary &nodeDict, const fvMesh &mesh, const dimensionSet &weightDimensions, const dimensionSet &abscissaDimensions, const wordList &boundaryTypes, const bool extended=false, const label nSecondaryNodes=0)
Construct from name, dictionary, mesh and dimensions.
quadratureNode (const word &name, const word &distributionName, const fvMesh &mesh, const dimensionSet &weightDimensions, const dimensionSet &abscissaDimensions, const bool extended=false, const label nSecondaryNodes=0)
Construct from name, number of secondary nodes, mesh and dimensions.
autoPtr< quadratureNode< weightType, abscissaType, sigmaType > > clone () const
Return clone.
virtual ~quadratureNode ()
Destructor.
const word & name () const
Return the name of the node.
bool extended () const
label nSecondaryNodes () const
Returns the number of secondary nodes.
const weightType & primaryWeight () const
Const access to the weight of the node.
weightType & primaryWeight ()
Non-const access to the weight of the node.
const abscissaType & primaryAbscissa () const
Const access to the abscissa of the node.
abscissaType & primaryAbscissa ()
Non-const access to the abscissa of the node.
const PtrList< weightType > & secondaryWeights () const
Const access to the secondary weights of the node.
PtrList< weightType > & secondaryWeights ()
Non-const access to the secondary weights of the node.
const PtrList< abscissaType > & secondaryAbscissae () const
Const access to the list of secondary abscissae of the node.
PtrList< abscissaType > & secondaryAbscissae ()
Non-const access to the list of secondary abscissae of the node.
const sigmaType & sigma () const
Const access to sigma.
sigmaType & sigma ()
Non-const access to sigma.
Detailed Description
template<class weightType, class abscissaType, class sigmaType>
class Foam::quadratureNode< weightType, abscissaType, sigmaType >
Extended version of the quadrature node, which stores the list of secondary weights and abscissae associated to the primary weight and abscissa, and the sigma parameter.
Source files
quadratureNode.H
quadratureNode.C
quadratureNodeI.H
Definition at line 54 of file quadratureNode.H.
Constructor & Destructor Documentation
quadratureNode (const word & name, const word & distributionName, const dictionary & nodeDict, const fvMesh & mesh, const dimensionSet & weightDimensions, const dimensionSet & abscissaDimensions, const wordList & boundaryTypes, const bool extended = false, const label nSecondaryNodes = 0)
Construct from name, dictionary, mesh and dimensions.
Definition at line 179 of file quadratureNode.C.
References quadratureNode< weightType, abscissaType, sigmaType >::~quadratureNode().
Referenced by quadratureNode< weightType, abscissaType, sigmaType >::quadratureNode().
quadratureNode (const word & name, const word & distributionName, const fvMesh & mesh, const dimensionSet & weightDimensions, const dimensionSet & abscissaDimensions, const bool extended = false, const label nSecondaryNodes = 0)
Construct from name, number of secondary nodes, mesh and dimensions.
Definition at line 32 of file quadratureNode.C.
References quadratureNode< weightType, abscissaType, sigmaType >::quadratureNode().
~quadratureNode () virtual
Destructor.
Definition at line 330 of file quadratureNode.C.
References quadratureNode< weightType, abscissaType, sigmaType >::clone().
Referenced by quadratureNode< weightType, abscissaType, sigmaType >::iNew::operator()(), and quadratureNode< weightType, abscissaType, sigmaType >::quadratureNode().
Member Function Documentation
autoPtr<quadratureNode<weightType, abscissaType, sigmaType> > clone () const
Return clone.
Referenced by quadratureNode< weightType, abscissaType, sigmaType >::~quadratureNode().
const Foam::word & name () const inline
Return the name of the node.
Definition at line 29 of file quadratureNodeI.H.
References quadratureNode< weightType, abscissaType, sigmaType >::extended().
Referenced by quadratureNode< weightType, abscissaType, sigmaType >::iNew::operator()().
bool extended () const inline
Definition at line 36 of file quadratureNodeI.H.
References quadratureNode< weightType, abscissaType, sigmaType >::nSecondaryNodes().
Referenced by quadratureNode< weightType, abscissaType, sigmaType >::name(), and quadratureNode< weightType, abscissaType, sigmaType >::iNew::operator()().
Foam::label nSecondaryNodes () const inline
Returns the number of secondary nodes.
Definition at line 44 of file quadratureNodeI.H.
References quadratureNode< weightType, abscissaType, sigmaType >::primaryWeight().
Referenced by quadratureNode< weightType, abscissaType, sigmaType >::extended(), extendedFieldMomentInversion::invertBoundaryMoments(), and quadratureNode< weightType, abscissaType, sigmaType >::iNew::operator()().
const weightType & primaryWeight () const inline
Const access to the weight of the node.
Definition at line 52 of file quadratureNodeI.H.
Referenced by univariateMomentAdvection::interpolateNodes(), extendedFieldMomentInversion::invertBoundaryMoments(), basicFieldMomentInversion::invertBoundaryMoments(), extendedFieldMomentInversion::invertLocalMoments(), basicFieldMomentInversion::invertLocalMoments(), quadratureNode< weightType, abscissaType, sigmaType >::nSecondaryNodes(), quadratureNode< weightType, abscissaType, sigmaType >::iNew::operator()(), and univariatePopulationBalance::~univariatePopulationBalance().
weightType & primaryWeight () inline
Non-const access to the weight of the node.
Definition at line 59 of file quadratureNodeI.H.
References quadratureNode< weightType, abscissaType, sigmaType >::primaryAbscissa().
const abscissaType & primaryAbscissa () const inline
Const access to the abscissa of the node.
Definition at line 67 of file quadratureNodeI.H.
Referenced by univariateMomentAdvection::interpolateNodes(), extendedFieldMomentInversion::invertBoundaryMoments(), basicFieldMomentInversion::invertBoundaryMoments(), extendedFieldMomentInversion::invertLocalMoments(), basicFieldMomentInversion::invertLocalMoments(), quadratureNode< weightType, abscissaType, sigmaType >::iNew::operator()(), quadratureNode< weightType, abscissaType, sigmaType >::primaryWeight(), and univariatePopulationBalance::~univariatePopulationBalance().
abscissaType & primaryAbscissa () inline
Non-const access to the abscissa of the node.
Definition at line 74 of file quadratureNodeI.H.
References quadratureNode< weightType, abscissaType, sigmaType >::secondaryWeights().
const Foam::PtrList< weightType > & secondaryWeights () const inline
Const access to the secondary weights of the node.
Definition at line 82 of file quadratureNodeI.H.
Referenced by extendedFieldMomentInversion::invertBoundaryMoments(), extendedFieldMomentInversion::invertLocalMoments(), quadratureNode< weightType, abscissaType, sigmaType >::iNew::operator()(), quadratureNode< weightType, abscissaType, sigmaType >::primaryAbscissa(), and univariatePopulationBalance::~univariatePopulationBalance().
Foam::PtrList< weightType > & secondaryWeights () inline
Non-const access to the secondary weights of the node.
Definition at line 98 of file quadratureNodeI.H.
References quadratureNode< weightType, abscissaType, sigmaType >::secondaryAbscissae().
const Foam::PtrList< abscissaType > & secondaryAbscissae () const inline
Const access to the list of secondary abscissae of the node.
Definition at line 113 of file quadratureNodeI.H.
Referenced by extendedFieldMomentInversion::invertBoundaryMoments(), extendedFieldMomentInversion::invertLocalMoments(), quadratureNode< weightType, abscissaType, sigmaType >::iNew::operator()(), quadratureNode< weightType, abscissaType, sigmaType >::secondaryWeights(), and univariatePopulationBalance::~univariatePopulationBalance().
Foam::PtrList< abscissaType > & secondaryAbscissae () inline
Non-const access to the list of secondary abscissae of the node.
Definition at line 129 of file quadratureNodeI.H.
References quadratureNode< weightType, abscissaType, sigmaType >::sigma().
const sigmaType & sigma () const inline
Const access to sigma.
Definition at line 145 of file quadratureNodeI.H.
Referenced by extendedFieldMomentInversion::invertBoundaryMoments(), extendedFieldMomentInversion::invertLocalMoments(), quadratureNode< weightType, abscissaType, sigmaType >::iNew::operator()(), and quadratureNode< weightType, abscissaType, sigmaType >::secondaryAbscissae().
sigmaType & sigma () inline
Non-const access to sigma.
Definition at line 160 of file quadratureNodeI.H.
The documentation for this class was generated from the following files:
quadratureNode.H
quadratureNode.C
quadratureNodeI.H