My Project: kineticTheoryModel Class Reference
kineticTheoryModel Class Reference abstract
Kinetic theory particle phase RAS model.
Public Member Functions
TypeName ("kineticTheoryModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, kineticTheoryModel, dictionary,(const dictionary &dict, const phaseModel &phase),(dict, phase))
kineticTheoryModel (const dictionary &dict, const phaseModel &phase)
Construct from components.
virtual ~kineticTheoryModel ()
Destructor.
virtual const volScalarField & Theta () const
Return the granular temperature.
virtual tmp< volSymmTensorField > Sigma () const
Return granular stress tensor.
virtual const scalarField & ThetaPatch (const label patchi) const
Return the granular temperature on a patch.
virtual const volScalarField & nu () const
Return the granular viscosity.
virtual const scalarField & nuPatch (const label patchi) const
Return the granular viscosity on a patch.
virtual tmp< volScalarField > nuEff () const
Return the effective viscosity (granular + frictional)
virtual const volScalarField & lambda () const
Return the granular bulk viscosity.
virtual const volScalarField & kappa () const
Return the granular "thermal" conductivity.
virtual const scalarField & kappaPatch (const label patchi) const
Return the granular "thermal" conductivity on a patch.
virtual const volScalarField & g0 () const
Return the radial distribution.
virtual const scalarField & g0Patch (const label patchi) const
Return the radial distribution on a patch.
virtual tmp< volScalarField > g0Prime () const
Return the radial distribution derivative w.r.t. the particulate.
virtual tmp< volScalarField > pPrime () const
Return the phase-pressure'.
virtual tmp< surfaceScalarField > pPrimef () const
Return the face-phase-pressure'.
virtual const dimensionedScalar & alphaMax () const
Return the maximum value of the phase fraction.
virtual void solve (const volScalarField &beta, const volScalarField &alpha, const volTensorField &gradU, const volSymmTensorField D)=0
Update kinetic theory quantities (turbulent correct)
virtual void transportMoments ()
Transport moments.
virtual scalar maxUxDx () const
Max time-step.
virtual tmp< volScalarField > h2 () const
Return fraction to be used for hydrodynamic flux.
virtual tmp< surfaceScalarField > h2f () const
Return interpolated fraction to be used for hydrodynamic flux.
virtual tmp< volScalarField > ddtAlphaDilute () const
void update ()
Update viscosity and conductivity.
virtual bool read ()
Read.
virtual bool writeData (Ostream &os) const
Write.
Static Public Member Functions
static autoPtr< kineticTheoryModel > New (const dictionary &dict, const phaseModel &phase)
Select null constructed.
Protected Attributes
const phaseModel & phase_
autoPtr< kineticTheoryModels::viscosityModel > viscosityModel_
Run-time selected viscosity model.
autoPtr< kineticTheoryModels::conductivityModel > conductivityModel_
Run-time selected conductivity model.
autoPtr< kineticTheoryModels::radialModel > radialModel_
Run-time selected radial distribution model.
autoPtr< kineticTheoryModels::granularPressureModel > granularPressureModel_
Run-time selected granular pressure model.
autoPtr< kineticTheoryModels::frictionalStressModel > frictionalStressModel_
Run-time selected frictional stress model.
Switch equilibrium_
Use equilibrium approximation: generation == dissipation.
dimensionedScalar e_
Coefficient of restitution.
dimensionedScalar alphaMax_
Maximum packing phase-fraction.
dimensionedScalar alphaMinFriction_
Min value for which the frictional stresses are zero.
dimensionedScalar residualAlpha_
Residual phase fraction.
dimensionedScalar maxNut_
Maximum turbulent viscosity.
volScalarField Theta_
The granular energy/temperature.
volScalarField lambda_
The granular bulk viscosity.
volScalarField g0_
The granular radial distribution.
volScalarField kappa_
The granular "thermal" conductivity.
volScalarField nu_
The particle viscosity.
volScalarField nuFric_
The frictional viscosity.
Detailed Description
Kinetic theory particle phase RAS model.
Reference:
    "Derivation, implementation, and validation of computer simulation
     models for gas-solid fluidized beds",
    van Wachem, B.G.M.,
    Ph.D. Thesis, Delft University of Technology, Amsterdam, 2000.
There are no default model coefficients.
Source files
kineticTheoryModel.H
kineticTheoryModel.C
Definition at line 70 of file kineticTheoryModel.H.
Constructor & Destructor Documentation
kineticTheoryModel (const dictionary & dict, const phaseModel & phase)
Construct from components.
virtual ~kineticTheoryModel () virtual
Destructor.
Member Function Documentation
TypeName ("kineticTheoryModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr , kineticTheoryModel , dictionary , (const dictionary &dict, const phaseModel &phase) , (dict, phase))
static autoPtr<kineticTheoryModel> New (const dictionary & dict, const phaseModel & phase) static
Select null constructed.
virtual const volScalarField& Theta () const inline virtual
Return the granular temperature.
Definition at line 191 of file kineticTheoryModel.H.
References kineticTheoryModel::Sigma(), and kineticTheoryModel::Theta_.
virtual tmp<volSymmTensorField> Sigma () const virtual
Return granular stress tensor.
Referenced by kineticTheoryModel::Theta().
virtual const scalarField& ThetaPatch (const label patchi) const inline virtual
Return the granular temperature on a patch.
Definition at line 200 of file kineticTheoryModel.H.
virtual const volScalarField& nu () const inline virtual
Return the granular viscosity.
Definition at line 206 of file kineticTheoryModel.H.
References kineticTheoryModel::nu_.
virtual const scalarField& nuPatch (const label patchi) const inline virtual
Return the granular viscosity on a patch.
Definition at line 212 of file kineticTheoryModel.H.
References kineticTheoryModel::nuEff().
virtual tmp<volScalarField> nuEff () const virtual
Return the effective viscosity (granular + frictional)
Referenced by kineticTheoryModel::nuPatch().
virtual const volScalarField& lambda () const inline virtual
Return the granular bulk viscosity.
Definition at line 221 of file kineticTheoryModel.H.
References kineticTheoryModel::lambda_.
virtual const volScalarField& kappa () const inline virtual
Return the granular "thermal" conductivity.
Definition at line 227 of file kineticTheoryModel.H.
References kineticTheoryModel::kappa_.
virtual const scalarField& kappaPatch (const label patchi) const inline virtual
Return the granular "thermal" conductivity on a patch.
Definition at line 233 of file kineticTheoryModel.H.
virtual const volScalarField& g0 () const inline virtual
Return the radial distribution.
Definition at line 239 of file kineticTheoryModel.H.
References kineticTheoryModel::g0_.
virtual const scalarField& g0Patch (const label patchi) const inline virtual
Return the radial distribution on a patch.
Definition at line 245 of file kineticTheoryModel.H.
References kineticTheoryModel::g0Prime(), kineticTheoryModel::pPrime(), and kineticTheoryModel::pPrimef().
virtual tmp<volScalarField> g0Prime () const virtual
Return the radial distribution derivative w.r.t. the particulate.
particulate phase fraction
Referenced by kineticTheoryModel::g0Patch().
virtual tmp<volScalarField> pPrime () const virtual
Return the phase-pressure'.
(derivative of phase-pressure w.r.t. phase-fraction)
Referenced by kineticTheoryModel::g0Patch().
virtual tmp<surfaceScalarField> pPrimef () const virtual
Return the face-phase-pressure'.
(derivative of phase-pressure w.r.t. phase-fraction)
Referenced by kineticTheoryModel::g0Patch().
virtual const dimensionedScalar& alphaMax () const inline virtual
Return the maximum value of the phase fraction.
Definition at line 263 of file kineticTheoryModel.H.
References kineticTheoryModel::alphaMax_, and kineticTheoryModel::solve().
virtual void solve (const volScalarField & beta, const volScalarField & alpha, const volTensorField & gradU, const volSymmTensorField D) pure virtual
Update kinetic theory quantities (turbulent correct)
Implemented in nonEquilibrium, and equilibrium.
Referenced by kineticTheoryModel::alphaMax().
virtual void transportMoments () inline virtual
Transport moments.
Definition at line 281 of file kineticTheoryModel.H.
virtual scalar maxUxDx () const inline virtual
Max time-step.
Definition at line 285 of file kineticTheoryModel.H.
virtual tmp<volScalarField> h2 () const inline virtual
Return fraction to be used for hydrodynamic flux.
Definition at line 291 of file kineticTheoryModel.H.
virtual tmp<surfaceScalarField> h2f () const inline virtual
Return interpolated fraction to be used for hydrodynamic flux.
Definition at line 313 of file kineticTheoryModel.H.
virtual tmp<volScalarField> ddtAlphaDilute () const inline virtual
Definition at line 334 of file kineticTheoryModel.H.
References kineticTheoryModel::update().
void update ()
Update viscosity and conductivity.
Referenced by kineticTheoryModel::ddtAlphaDilute().
virtual bool read () inline virtual
Read.
Definition at line 363 of file kineticTheoryModel.H.
virtual bool writeData (Ostream & os) const inline virtual
Write.
Definition at line 369 of file kineticTheoryModel.H.
Member Data Documentation
const phaseModel& phase_ protected
Definition at line 79 of file kineticTheoryModel.H.
autoPtr<kineticTheoryModels::viscosityModel> viscosityModel_ protected
Run-time selected viscosity model.
Definition at line 85 of file kineticTheoryModel.H.
autoPtr<kineticTheoryModels::conductivityModel> conductivityModel_ protected
Run-time selected conductivity model.
Definition at line 88 of file kineticTheoryModel.H.
autoPtr<kineticTheoryModels::radialModel> radialModel_ protected
Run-time selected radial distribution model.
Definition at line 91 of file kineticTheoryModel.H.
autoPtr<kineticTheoryModels::granularPressureModel> granularPressureModel_ protected
Run-time selected granular pressure model.
Definition at line 95 of file kineticTheoryModel.H.
autoPtr<kineticTheoryModels::frictionalStressModel> frictionalStressModel_ protected
Run-time selected frictional stress model.
Definition at line 99 of file kineticTheoryModel.H.
Switch equilibrium_ protected
Use equilibrium approximation: generation == dissipation.
Definition at line 105 of file kineticTheoryModel.H.
dimensionedScalar e_ protected
Coefficient of restitution.
Definition at line 108 of file kineticTheoryModel.H.
dimensionedScalar alphaMax_ protected
Maximum packing phase-fraction.
Definition at line 111 of file kineticTheoryModel.H.
Referenced by kineticTheoryModel::alphaMax().
dimensionedScalar alphaMinFriction_ protected
Min value for which the frictional stresses are zero.
Definition at line 114 of file kineticTheoryModel.H.
dimensionedScalar residualAlpha_ protected
Residual phase fraction.
Definition at line 117 of file kineticTheoryModel.H.
dimensionedScalar maxNut_ protected
Maximum turbulent viscosity.
Definition at line 120 of file kineticTheoryModel.H.
volScalarField Theta_ protected
The granular energy/temperature.
Definition at line 126 of file kineticTheoryModel.H.
Referenced by kineticTheoryModel::Theta().
volScalarField lambda_ protected
The granular bulk viscosity.
Definition at line 129 of file kineticTheoryModel.H.
Referenced by kineticTheoryModel::lambda().
volScalarField g0_ protected
The granular radial distribution.
Definition at line 132 of file kineticTheoryModel.H.
Referenced by kineticTheoryModel::g0().
volScalarField kappa_ protected
The granular "thermal" conductivity.
Definition at line 135 of file kineticTheoryModel.H.
Referenced by kineticTheoryModel::kappa().
volScalarField nu_ protected
The particle viscosity.
Definition at line 138 of file kineticTheoryModel.H.
Referenced by kineticTheoryModel::nu().
volScalarField nuFric_ protected
The frictional viscosity.
Definition at line 141 of file kineticTheoryModel.H.
The documentation for this class was generated from the following file:
kineticTheoryModel.H