zeta Class Reference
zeta Class Reference
Second-order univariate moment advection with zeta kinetic scheme.
Public Member Functions
TypeName ("zeta")
Runtime type information.
zeta (const dictionary &dict, const univariateQuadratureApproximation &quadrature, const surfaceScalarField &phi, const word &support)
Construct from univariateMomentSet.
virtual ~zeta ()
Destructor.
virtual scalar realizableCo ()
Return the maximum Courant number ensuring moment realizability.
virtual void update ()
Update moment advection.
Public Member Functions inherited from univariateMomentAdvection
TypeName ("univariateMomentAdvection")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, univariateMomentAdvection, dictionary,(const dictionary &dict, const univariateQuadratureApproximation &quadrature, const surfaceScalarField &phi, const word &support),(dict, quadrature, phi, support))
univariateMomentAdvection (const dictionary &dict, const univariateQuadratureApproximation &quadrature, const surfaceScalarField &phi, const word &support)
Construct from univariateMomentSet.
virtual ~univariateMomentAdvection ()
Destructor.
const PtrList< volScalarField > & divMoments () const
Return the advection term for the moment transport equation.
Protected Member Functions
void countFacesWithOutgoingFlux ()
Calculates the number of cells with outgoing flux.
void limiter ()
Computes the limiter used for additional limitation.
void interpolateFields ()
Reconstructs zeta_k.
void limitZetas ()
Applies additional limitation to zeta_k, if needed.
Additional Inherited Members
Static Public Member Functions inherited from univariateMomentAdvection
static autoPtr< univariateMomentAdvection > New (const dictionary &dict, const univariateQuadratureApproximation &quadrature, const surfaceScalarField &phi, const word &support)
Protected Attributes inherited from univariateMomentAdvection
const word name_
Name of the distribution associated to the quadrature approximation.
const volUnivariateMomentFieldSet & moments_
Reference to the moments to advect.
const label nMoments_
Number of moments.
PtrList< volScalarField > divMoments_
Advection terms for moment transport equations.
surfaceScalarField own_
Field used to find upwind values of the owner.
surfaceScalarField nei_
Field used to find upwind values of the neighbour.
const surfaceScalarField phi_
Conservative advection flux.
word support_
Support of the distribution function.
label nDimensions_
Dimensions of the underlying distribution.
Detailed Description
Second-order univariate moment advection with zeta kinetic scheme.
References
    "Realizable second-order finite-volume schemes for the advection of
    moment sets of the particle size distribution"
    F Laurent, T. T. Nguyen
    Journal of Computational Physics
    Volume 337, Pages 309-338, 2017
Source files
zeta.H
zeta.C
zetaI.H
Definition at line 59 of file zeta.H.
Constructor & Destructor Documentation
zeta (const dictionary & dict, const univariateQuadratureApproximation & quadrature, const surfaceScalarField & phi, const word & support)
Construct from univariateMomentSet.
Definition at line 47 of file zeta.C.
~zeta () virtual
Destructor.
Definition at line 281 of file zeta.C.
Member Function Documentation
void countFacesWithOutgoingFlux () protected
Calculates the number of cells with outgoing flux.
Definition at line 431 of file zeta.C.
void limiter () protected
Computes the limiter used for additional limitation.
void interpolateFields () protected
Reconstructs zeta_k.
Definition at line 287 of file zeta.C.
References univariateMomentSet::nRealizableMoments(), and univariateMomentSet::zetas().
void limitZetas () protected
Applies additional limitation to zeta_k, if needed.
Definition at line 470 of file zeta.C.
References univariateMomentSet::nRealizableMoments(), and p.
TypeName ("zeta")
Runtime type information.
Foam::scalar realizableCo () virtual
Return the maximum Courant number ensuring moment realizability.
Implements univariateMomentAdvection.
Definition at line 736 of file zeta.C.
void update () virtual
Update moment advection.
Implements univariateMomentAdvection.
Definition at line 761 of file zeta.C.
The documentation for this class was generated from the following files:
zeta.H
zeta.C