My Project: phaseModel Class Reference
phaseModel Class Reference
Base class for a moving phase model. Functions are made so that the class can be abstracted to a polydisperse phase.
Public Member Functions
ClassName ("phaseModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, phaseModel, dictionary,(const twoPhaseSystem &fluid, const dictionary &dict, const word &phaseName),(fluid, dict, phaseName))
phaseModel (const twoPhaseSystem &fluid, const dictionary &dict, const word &phaseName)
autoPtr< phaseModel > clone () const
Return clone.
virtual ~phaseModel ()
Destructor.
const word & name () const
Return the name of this phase.
bool BGviscosity () const
Return if B&G viscosity model is used.
const twoPhaseSystem & fluid () const
Return the twoPhaseSystem.
const phaseModel & otherPhase () const
Return the other phase in this two-phase system.
virtual label nNodes () const
Return the number of nodes.
const dimensionedScalar & residualAlpha () const
Return the residual phase-fraction for given phase.
virtual const volScalarField & alphas (const label nodei) const
Constant access to alpha field for nodei.
virtual volScalarField & alphas (const label nodei)
Non-constant access to alpha field for nodei.
const volScalarField & d () const
Return the mean diameter.
virtual const volScalarField & ds (const label nodei) const
Return diameter of nodei.
scalar alphaMax () const
Optional maximum phase-fraction (e.g. packing limit)
const PhaseCompressibleTurbulenceModel< phaseModel > & turbulence () const
Return the turbulence model.
PhaseCompressibleTurbulenceModel< phaseModel > & turbulence ()
Return non-const access to the turbulence model.
const rhoThermo & thermo () const
Return the thermophysical model.
rhoThermo & thermo ()
Return non-const access to the thermophysical model.
tmp< volScalarField > nu () const
Return the laminar viscosity.
tmp< scalarField > nu (const label patchi) const
Return the laminar viscosity for patch.
tmp< volScalarField > mu () const
Return the laminar dynamic viscosity.
tmp< scalarField > mu (const label patchi) const
Return the laminar dynamic viscosity for patch.
tmp< scalarField > kappa (const label patchi) const
Return the thermal conductivity on a patch.
tmp< volScalarField > kappa () const
Return the thermal conductivity.
tmp< volScalarField > kappaEff (const volScalarField &alphat) const
Return the laminar thermal conductivity.
tmp< scalarField > kappaEff (const scalarField &alphat, const label patchi) const
Return the laminar thermal conductivity on a patch.
tmp< volScalarField > alpha () const
Return the laminar thermal diffusivity for enthalpy.
tmp< scalarField > alpha (const label patchi) const
Return the laminar thermal diffusivity for enthalpy on a patch.
tmp< volScalarField > alphaEff (const volScalarField &alphat) const
Return the effective thermal diffusivity for enthalpy.
tmp< scalarField > alphaEff (const scalarField &alphat, const label patchi) const
Return the effective thermal diffusivity for enthalpy on a patch.
tmp< volScalarField > Cp () const
Return the specific heat capacity.
const volScalarField & rho () const
Return the density.
const volVectorField & U () const
Constant access to the mean velocity.
volVectorField & U ()
Non-const access to the mean velocity.
virtual const volVectorField & Us (const label nodei) const
Constant access to the velocity for nodei.
virtual volVectorField & Us (const label nodei)
Non-const access to the velocity for nodei.
virtual tmp< volVectorField > Vs (const label nodei) const
Deviation of velocity nodei from the mean.
const surfaceScalarField & phi () const
Constant access to the volumetric flux.
surfaceScalarField & phi ()
Non-const access to the volumetric flux.
const surfaceScalarField & alphaPhi () const
Return the volumetric flux of the phase.
surfaceScalarField & alphaPhi ()
Return non-const access to the volumetric flux of the phase.
const surfaceScalarField & alphaRhoPhi () const
Return the mass flux of the phase.
surfaceScalarField & alphaRhoPhi ()
Return non-const access to the mass flux of the phase.
void correctInflowOutflow (surfaceScalarField &alphaPhi) const
Ensure that the flux at inflow BCs is preserved.
virtual void correct ()
Correct the phase properties.
virtual void relativeTransport ()
Relative transport of moments, not used in standard phase model.
virtual void transportAlpha ()
Average transport of first size moment.
virtual void averageTransport (const PtrList< fvVectorMatrix > &AEqns)
Average transport of moments, not used in standard phase model.
virtual void solveBreakupCoalesence ()
Solve change in size moments based on breakup and coalesence.
virtual bool read (const dictionary &phaseProperties)
Read phaseProperties dictionary.
virtual bool read ()
Dummy Read for transportModel.
Static Public Member Functions
static autoPtr< phaseModel > New (const twoPhaseSystem &fluid, const dictionary &dict, const word &phaseName)
Protected Attributes
const twoPhaseSystem & fluid_
Reference to mesh.
word name_
Name of phase.
dictionary phaseDict_
Phase dictionary.
dimensionedScalar residualAlpha_
Return the residual phase-fraction for given phase.
scalar alphaMax_
Optional maximum phase-fraction (e.g. packing limit)
autoPtr< rhoThermo > thermo_
Thermophysical properties.
volVectorField U_
Mean velocity.
surfaceScalarField alphaPhi_
Volumetric flux of the phase.
surfaceScalarField alphaRhoPhi_
Mass flux of the phase.
autoPtr< surfaceScalarField > phiPtr_
Volumetric flux of the phase.
volScalarField d_
Diameter (alpha weighted diameter for polydisperse)
autoPtr< PhaseCompressibleTurbulenceModel< phaseModel > > turbulence_
Turbulence model.
bool BGviscosity_
Bool to use B&G bubble pressure based viscosity.
Detailed Description
Base class for a moving phase model. Functions are made so that the class can be abstracted to a polydisperse phase.
Source files
phaseModel.H
phaseModel.C
newPhaseModel.C
phaseModels.C
Definition at line 67 of file phaseModel.H.
Constructor & Destructor Documentation
phaseModel (const twoPhaseSystem & fluid, const dictionary & dict, const word & phaseName)
virtual ~phaseModel () virtual
Destructor.
Member Function Documentation
ClassName ("phaseModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr , phaseModel , dictionary , (const twoPhaseSystem &fluid, const dictionary &dict, const word &phaseName) , (fluid, dict, phaseName))
autoPtr<phaseModel> clone () const
Return clone.
static autoPtr<phaseModel> New (const twoPhaseSystem & fluid, const dictionary & dict, const word & phaseName) static
const word& name () const inline
Return the name of this phase.
Definition at line 166 of file phaseModel.H.
References phaseModel::name_.
bool BGviscosity () const inline
Return if B&G viscosity model is used.
Definition at line 172 of file phaseModel.H.
References phaseModel::BGviscosity_.
const twoPhaseSystem& fluid () const inline
Return the twoPhaseSystem.
Definition at line 178 of file phaseModel.H.
References phaseModel::fluid_, and phaseModel::otherPhase().
const phaseModel& otherPhase () const
Return the other phase in this two-phase system.
Referenced by phaseModel::fluid().
virtual label nNodes () const inline virtual
Return the number of nodes.
Reimplemented in pdPhaseModel.
Definition at line 188 of file phaseModel.H.
References phaseModel::residualAlpha(), and phaseModel::residualAlpha_.
const dimensionedScalar& residualAlpha () const inline
Return the residual phase-fraction for given phase.
Used to stabilize the phase momentum as the phase-fraction -> 0
Definition at line 195 of file phaseModel.H.
Referenced by phaseModel::nNodes().
virtual const volScalarField& alphas (const label nodei) const inline virtual
Constant access to alpha field for nodei.
Reimplemented in pdPhaseModel.
Definition at line 201 of file phaseModel.H.
virtual volScalarField& alphas (const label nodei) inline virtual
Non-constant access to alpha field for nodei.
Reimplemented in pdPhaseModel.
Definition at line 207 of file phaseModel.H.
const volScalarField& d () const inline
Return the mean diameter.
Definition at line 213 of file phaseModel.H.
References phaseModel::d_.
virtual const volScalarField& ds (const label nodei) const inline virtual
Return diameter of nodei.
Reimplemented in pdPhaseModel.
Definition at line 219 of file phaseModel.H.
References phaseModel::alphaMax(), phaseModel::alphaMax_, phaseModel::d_, and phaseModel::turbulence().
scalar alphaMax () const inline
Optional maximum phase-fraction (e.g. packing limit)
Defaults to 1
Definition at line 226 of file phaseModel.H.
Referenced by phaseModel::ds().
const PhaseCompressibleTurbulenceModel<phaseModel>& turbulence () const
Return the turbulence model.
Referenced by phaseModel::ds().
PhaseCompressibleTurbulenceModel<phaseModel>& turbulence ()
Return non-const access to the turbulence model.
for correction
const rhoThermo& thermo () const inline
Return the thermophysical model.
Definition at line 240 of file phaseModel.H.
References phaseModel::thermo_.
rhoThermo& thermo () inline
Return non-const access to the thermophysical model.
for correction
Definition at line 247 of file phaseModel.H.
tmp<volScalarField> nu () const inline
Return the laminar viscosity.
Definition at line 253 of file phaseModel.H.
tmp<scalarField> nu (const label patchi) const inline
Return the laminar viscosity for patch.
Definition at line 259 of file phaseModel.H.
tmp<volScalarField> mu () const inline
Return the laminar dynamic viscosity.
Definition at line 265 of file phaseModel.H.
tmp<scalarField> mu (const label patchi) const inline
Return the laminar dynamic viscosity for patch.
Definition at line 271 of file phaseModel.H.
tmp<scalarField> kappa (const label patchi) const inline
Return the thermal conductivity on a patch.
Definition at line 277 of file phaseModel.H.
tmp<volScalarField> kappa () const inline
Return the thermal conductivity.
Definition at line 283 of file phaseModel.H.
References phaseModel::kappaEff().
tmp<volScalarField> kappaEff (const volScalarField & alphat) const inline
Return the laminar thermal conductivity.
Definition at line 290 of file phaseModel.H.
Referenced by phaseModel::kappa().
tmp<scalarField> kappaEff (const scalarField & alphat, const label patchi) const inline
Return the laminar thermal conductivity on a patch.
Definition at line 299 of file phaseModel.H.
tmp<volScalarField> alpha () const inline
Return the laminar thermal diffusivity for enthalpy.
Definition at line 308 of file phaseModel.H.
tmp<scalarField> alpha (const label patchi) const inline
Return the laminar thermal diffusivity for enthalpy on a patch.
Definition at line 314 of file phaseModel.H.
References phaseModel::alphaEff().
tmp<volScalarField> alphaEff (const volScalarField & alphat) const inline
Return the effective thermal diffusivity for enthalpy.
Definition at line 321 of file phaseModel.H.
Referenced by phaseModel::alpha().
tmp<scalarField> alphaEff (const scalarField & alphat, const label patchi) const inline
Return the effective thermal diffusivity for enthalpy on a patch.
Definition at line 330 of file phaseModel.H.
tmp<volScalarField> Cp () const inline
Return the specific heat capacity.
Definition at line 339 of file phaseModel.H.
const volScalarField& rho () const inline
Return the density.
Definition at line 345 of file phaseModel.H.
const volVectorField& U () const inline
Constant access to the mean velocity.
Definition at line 351 of file phaseModel.H.
References phaseModel::U_.
volVectorField& U () inline
Non-const access to the mean velocity.
Definition at line 357 of file phaseModel.H.
References phaseModel::U_.
virtual const volVectorField& Us (const label nodei) const inline virtual
Constant access to the velocity for nodei.
Reimplemented in pdPhaseModel.
Definition at line 363 of file phaseModel.H.
References phaseModel::U_.
virtual volVectorField& Us (const label nodei) inline virtual
Non-const access to the velocity for nodei.
Reimplemented in pdPhaseModel.
Definition at line 369 of file phaseModel.H.
References phaseModel::U_, and phaseModel::Vs().
virtual tmp<volVectorField> Vs (const label nodei) const virtual
Deviation of velocity nodei from the mean.
Reimplemented in pdPhaseModel.
Referenced by phaseModel::Us().
const surfaceScalarField& phi () const inline
Constant access to the volumetric flux.
Definition at line 378 of file phaseModel.H.
References phaseModel::phiPtr_.
surfaceScalarField& phi () inline
Non-const access to the volumetric flux.
Definition at line 384 of file phaseModel.H.
References phaseModel::phiPtr_.
const surfaceScalarField& alphaPhi () const inline
Return the volumetric flux of the phase.
Definition at line 390 of file phaseModel.H.
References phaseModel::alphaPhi_.
Referenced by phaseModel::alphaRhoPhi().
surfaceScalarField& alphaPhi () inline
Return non-const access to the volumetric flux of the phase.
Definition at line 396 of file phaseModel.H.
References phaseModel::alphaPhi_.
const surfaceScalarField& alphaRhoPhi () const inline
Return the mass flux of the phase.
Definition at line 402 of file phaseModel.H.
References phaseModel::alphaRhoPhi_.
surfaceScalarField& alphaRhoPhi () inline
Return non-const access to the mass flux of the phase.
Definition at line 408 of file phaseModel.H.
References phaseModel::alphaPhi(), phaseModel::alphaRhoPhi_, phaseModel::correct(), and phaseModel::correctInflowOutflow().
void correctInflowOutflow (surfaceScalarField & alphaPhi) const
Ensure that the flux at inflow BCs is preserved.
Referenced by phaseModel::alphaRhoPhi().
virtual void correct () virtual
Correct the phase properties.
Reimplemented in pdPhaseModel.
Referenced by phaseModel::alphaRhoPhi().
virtual void relativeTransport () inline virtual
Relative transport of moments, not used in standard phase model.
Reimplemented in pdPhaseModel.
Definition at line 420 of file phaseModel.H.
virtual void transportAlpha () inline virtual
Average transport of first size moment.
Definition at line 426 of file phaseModel.H.
virtual void averageTransport (const PtrList< fvVectorMatrix > & AEqns) inline virtual
Average transport of moments, not used in standard phase model.
Reimplemented in pdPhaseModel.
Definition at line 432 of file phaseModel.H.
virtual void solveBreakupCoalesence () inline virtual
Solve change in size moments based on breakup and coalesence.
Definition at line 438 of file phaseModel.H.
virtual bool read (const dictionary & phaseProperties) inline virtual
Read phaseProperties dictionary.
Definition at line 444 of file phaseModel.H.
virtual bool read () inline virtual
Dummy Read for transportModel.
Definition at line 450 of file phaseModel.H.
Member Data Documentation
const twoPhaseSystem& fluid_ protected
Reference to mesh.
Definition at line 76 of file phaseModel.H.
Referenced by phaseModel::fluid().
word name_ protected
Name of phase.
Definition at line 79 of file phaseModel.H.
Referenced by phaseModel::name().
dictionary phaseDict_ protected
Phase dictionary.
Definition at line 82 of file phaseModel.H.
dimensionedScalar residualAlpha_ protected
Return the residual phase-fraction for given phase.
Used to stabilize the phase momentum as the phase-fraction -> 0
Definition at line 86 of file phaseModel.H.
Referenced by phaseModel::nNodes().
scalar alphaMax_ protected
Optional maximum phase-fraction (e.g. packing limit)
Definition at line 89 of file phaseModel.H.
Referenced by phaseModel::ds().
autoPtr<rhoThermo> thermo_ protected
Thermophysical properties.
Definition at line 92 of file phaseModel.H.
Referenced by phaseModel::thermo().
volVectorField U_ protected
Mean velocity.
Definition at line 95 of file phaseModel.H.
Referenced by phaseModel::U(), and phaseModel::Us().
surfaceScalarField alphaPhi_ protected
Volumetric flux of the phase.
Definition at line 98 of file phaseModel.H.
Referenced by phaseModel::alphaPhi().
surfaceScalarField alphaRhoPhi_ protected
Mass flux of the phase.
Definition at line 101 of file phaseModel.H.
Referenced by phaseModel::alphaRhoPhi().
autoPtr<surfaceScalarField> phiPtr_ protected
Volumetric flux of the phase.
Definition at line 104 of file phaseModel.H.
Referenced by phaseModel::phi().
volScalarField d_ protected
Diameter (alpha weighted diameter for polydisperse)
Definition at line 107 of file phaseModel.H.
Referenced by phaseModel::d(), and phaseModel::ds().
autoPtr<PhaseCompressibleTurbulenceModel<phaseModel> > turbulence_ protected
Turbulence model.
Definition at line 110 of file phaseModel.H.
bool BGviscosity_ protected
Bool to use B&G bubble pressure based viscosity.
Definition at line 113 of file phaseModel.H.
Referenced by phaseModel::BGviscosity().
The documentation for this class was generated from the following file:
phaseModel.H