OpenQBMM: kineticTheory Class Reference
kineticTheory Class Reference
Public Member Functions
TypeName ("kineticTheory")
Runtime type information.
kineticTheory (const volScalarField &alpha, const volScalarField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const phaseModel &transport, const word &propertiesName=turbulenceModel::propertiesName, const word &type=typeName)
Construct from components.
virtual ~kineticTheory ()
Destructor.
virtual bool read ()
Re-read model coefficients if they have changed.
virtual tmp< volScalarField > nuEff () const
Return the effective viscosity.
virtual tmp< scalarField > nuEff (const label patchi) const
Return the effective viscosity on patch.
virtual tmp< volScalarField > k () const
Return the turbulence kinetic energy.
virtual tmp< volScalarField > epsilon () const
Return the turbulence kinetic energy dissipation rate.
virtual tmp< volSymmTensorField > R () const
Return the Reynolds stress tensor.
virtual tmp< volScalarField > pPrime () const
Return the phase-pressure'.
virtual tmp< surfaceScalarField > pPrimef () const
Return the face-phase-pressure'.
virtual tmp< volSymmTensorField > devRhoReff () const
Return the effective stress tensor.
virtual tmp< fvVectorMatrix > divDevRhoReff (volVectorField &U) const
Return the source term for the momentum equation.
virtual void correct ()
Solve the kinetic theory equations and correct the viscosity.
Detailed Description
Definition at line 67 of file kineticTheory.H.
Constructor & Destructor Documentation
kineticTheory (const volScalarField & alpha, const volScalarField & rho, const volVectorField & U, const surfaceScalarField & alphaRhoPhi, const surfaceScalarField & phi, const phaseModel & transport, const word & propertiesName = turbulenceModel::propertiesName, const word & type = typeName)
Construct from components.
virtual ~kineticTheory () virtual
Destructor.
Member Function Documentation
TypeName ("kineticTheory")
Runtime type information.
virtual bool read () virtual
Re-read model coefficients if they have changed.
virtual tmp<volScalarField> nuEff () const inline virtual
Return the effective viscosity.
Definition at line 130 of file kineticTheory.H.
virtual tmp<scalarField> nuEff (const label patchi) const inline virtual
Return the effective viscosity on patch.
Definition at line 136 of file kineticTheory.H.
References kineticTheory::correct(), kineticTheory::devRhoReff(), kineticTheory::divDevRhoReff(), kineticTheory::epsilon(), kineticTheory::k(), kineticTheory::pPrime(), kineticTheory::pPrimef(), and kineticTheory::R().
virtual tmp<volScalarField> k () const virtual
Return the turbulence kinetic energy.
Referenced by kineticTheory::nuEff().
virtual tmp<volScalarField> epsilon () const virtual
Return the turbulence kinetic energy dissipation rate.
Referenced by kineticTheory::nuEff().
virtual tmp<volSymmTensorField> R () const virtual
Return the Reynolds stress tensor.
Referenced by kineticTheory::nuEff().
virtual tmp<volScalarField> pPrime () const virtual
Return the phase-pressure'.
(derivative of phase-pressure w.r.t. phase-fraction)
Referenced by kineticTheory::nuEff().
virtual tmp<surfaceScalarField> pPrimef () const virtual
Return the face-phase-pressure'.
(derivative of phase-pressure w.r.t. phase-fraction)
Referenced by kineticTheory::nuEff().
virtual tmp<volSymmTensorField> devRhoReff () const virtual
Return the effective stress tensor.
Referenced by kineticTheory::nuEff().
virtual tmp<fvVectorMatrix> divDevRhoReff (volVectorField & U) const virtual
Return the source term for the momentum equation.
Referenced by kineticTheory::nuEff().
virtual void correct () virtual
Solve the kinetic theory equations and correct the viscosity.
Referenced by kineticTheory::nuEff().
The documentation for this class was generated from the following file:
kineticTheory.H