uniform Class Reference
uniform Class Reference
Daughter distribution of fragments with uniform fragmentation.
Public Member Functions
TypeName ("uniform")
Runtime type information.
uniform (const dictionary &dict)
Construct from components.
virtual ~uniform ()
Destructor.
virtual scalar mD (const label &order, const scalar &abscissa) const
Moment of the daughter distribution function.
Public Member Functions inherited from daughterDistribution
TypeName ("daughterDistribution")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, daughterDistribution, dictionary,(const dictionary &dict),(dict))
daughterDistribution (const dictionary &dict)
Construct from components.
virtual ~daughterDistribution ()
Destructor.
Additional Inherited Members
Static Public Member Functions inherited from daughterDistribution
static autoPtr< daughterDistribution > New (const dictionary &dict)
Protected Attributes inherited from daughterDistribution
const dictionary & dict_
Detailed Description
Daughter distribution of fragments with uniform fragmentation.
The moment source term corresponding to the distribution is:
= Order of the moment [-]
= Particle size [m]
Source files
uniform.H
uniform.C
Definition at line 71 of file uniform.H.
Constructor & Destructor Documentation
uniform (const dictionary & dict)
Construct from components.
Definition at line 54 of file uniform.C.
References uniform::~uniform().
~uniform () virtual
Destructor.
Definition at line 65 of file uniform.C.
References uniform::mD().
Referenced by uniform::uniform().
Member Function Documentation
TypeName ("uniform")
Runtime type information.
Foam::scalar mD (const label & order, const scalar & abscissa) const virtual
Moment of the daughter distribution function.
Implements daughterDistribution.
Definition at line 73 of file uniform.C.
Referenced by uniform::~uniform().
The documentation for this class was generated from the following files:
uniform.H
uniform.C