My Project: noNucleation Class Reference
noNucleation Class Reference
No nucleation model.
Public Member Functions
TypeName ("none")
Runtime type information.
noNucleation (const dictionary &dict, const fvMesh &mesh)
Construct from components.
virtual ~noNucleation ()
Destructor.
virtual scalar nucleationSource (const label &momentOrder, const label celli) const
Growth model.
Public Member Functions inherited from nucleationModel
TypeName ("nucleationModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, nucleationModel, dictionary,(const dictionary &dict, const fvMesh &mesh),(dict, mesh))
nucleationModel (const dictionary &dict, const fvMesh &mesh)
Construct from components.
virtual ~nucleationModel ()
Destructor.
Additional Inherited Members
Static Public Member Functions inherited from nucleationModel
static autoPtr< nucleationModel > New (const dictionary &dict, const fvMesh &mesh)
Protected Attributes inherited from nucleationModel
const dictionary & dict_
const fvMesh & mesh_
Reference to mesh.
Detailed Description
No nucleation model.
Source files
noNucleation.H
noNucleation.C
Definition at line 52 of file noNucleation.H.
Constructor & Destructor Documentation
noNucleation (const dictionary & dict, const fvMesh & mesh)
Construct from components.
Definition at line 54 of file noNucleation.C.
References noNucleation::~noNucleation().
~noNucleation () virtual
Destructor.
Definition at line 66 of file noNucleation.C.
References noNucleation::nucleationSource().
Referenced by noNucleation::noNucleation().
Member Function Documentation
TypeName ("none")
Runtime type information.
Foam::scalar nucleationSource (const label & momentOrder, const label celli) const virtual
Growth model.
Implements nucleationModel.
Definition at line 75 of file noNucleation.C.
Referenced by noNucleation::~noNucleation().
The documentation for this class was generated from the following files:
noNucleation.H
noNucleation.C