My Project: momentFieldSet< momentType, nodeType > Class Template Reference
momentFieldSet< momentType, nodeType > Class Template Reference
Stores a list of moments, with a Map<label> that takes a label key and returns the index into the list of moments.
Public Member Functions
momentFieldSet (const word &distributionName, const dictionary &dict, const fvMesh &mesh, const autoPtr< PtrList< nodeType >> &nodes, const word &support)
Construct from dictionary and the quadrature nodes.
momentFieldSet (const word &distributionName, const label nMoments, const autoPtr< PtrList< nodeType >> &nodes, const label nDimensions, const Map< label > &momentMap, const word &support)
Construct from size, quadrature nodes, dimensions and moment map.
~momentFieldSet ()
Destructor.
const momentType & operator() () const
Const access to the zeroth moment.
momentType & operator() ()
Non-const access to the zeroth moment.
const momentType & operator() (label a) const
Const access to the first order moment in dimension a.
momentType & operator() (label a)
Non-const access to the first order moment in dimension a.
const momentType & operator() (label a, label b) const
Const access to the second order moment in dimension a+b.
momentType & operator() (label a, label b)
Non-const access to the second order moment in dimension a+b.
const momentType & operator() (label a, label b, label c) const
Const access to the third order moment in dimension a+b+c.
momentType & operator() (label a, label b, label c)
Non-const access to the third order moment in dimension a+b+c.
const Map< label > & momentMap () const
Returns const access to the moment map.
label nDimensions () const
Return the dimensionality of the distribution.
const word support () const
Return support of the measure associated to the moment set.
void update ()
Recalculate the moments from the quadrature nodes.
void updateLocalMoments (label elemi)
Recalculate the moments from the quadrature nodes in an element.
label map (label a, label b, label c) const
Return the map label of a moment.
Detailed Description
template<class momentType, class nodeType>
class Foam::momentFieldSet< momentType, nodeType >
Stores a list of moments, with a Map<label> that takes a label key and returns the index into the list of moments.
Example
Moment | Label Key | Index 0 0 0 0 0 1 0 0 100 1 0 1 0 10 2 0 0 1 1 3 2 0 0 200 4 2 1 0 210 5
operator() is overloaded in order to hide the above mapping.
Source files
momentFieldSet.H
momentFieldSetI.H
momentFieldSet.C
Definition at line 72 of file momentFieldSet.H.
Constructor & Destructor Documentation
momentFieldSet (const word & distributionName, const dictionary & dict, const fvMesh & mesh, const autoPtr< PtrList< nodeType >> & nodes, const word & support)
Construct from dictionary and the quadrature nodes.
Definition at line 37 of file momentFieldSet.C.
momentFieldSet (const word & distributionName, const label nMoments, const autoPtr< PtrList< nodeType >> & nodes, const label nDimensions, const Map< label > & momentMap, const word & support)
Construct from size, quadrature nodes, dimensions and moment map.
The list of moments is initialised but moment fields are not automatically allocated.
Definition at line 74 of file momentFieldSet.C.
~momentFieldSet ()
Destructor.
Definition at line 95 of file momentFieldSet.C.
Member Function Documentation
const momentType & operator() () const inline
Const access to the zeroth moment.
Definition at line 39 of file momentFieldSetI.H.
momentType & operator() () inline
Non-const access to the zeroth moment.
Definition at line 32 of file momentFieldSetI.H.
const momentType & operator() (label a) const inline
Const access to the first order moment in dimension a.
Definition at line 52 of file momentFieldSetI.H.
momentType & operator() (label a) inline
Non-const access to the first order moment in dimension a.
Definition at line 45 of file momentFieldSetI.H.
const momentType & operator() (label a, label b) const inline
Const access to the second order moment in dimension a+b.
Definition at line 69 of file momentFieldSetI.H.
momentType & operator() (label a, label b) inline
Non-const access to the second order moment in dimension a+b.
Definition at line 59 of file momentFieldSetI.H.
const momentType & operator() (label a, label b, label c) const inline
Const access to the third order moment in dimension a+b+c.
Definition at line 90 of file momentFieldSetI.H.
momentType & operator() (label a, label b, label c) inline
Non-const access to the third order moment in dimension a+b+c.
Definition at line 79 of file momentFieldSetI.H.
const Foam::Map< Foam::label > & momentMap () const inline
Returns const access to the moment map.
Definition at line 101 of file momentFieldSetI.H.
Foam::label nDimensions () const inline
Return the dimensionality of the distribution.
Definition at line 108 of file momentFieldSetI.H.
const Foam::word support () const inline
Return support of the measure associated to the moment set.
Definition at line 114 of file momentFieldSetI.H.
Referenced by extendedFieldMomentInversion::invertBoundaryMoments(), basicFieldMomentInversion::invertBoundaryMoments(), extendedFieldMomentInversion::invertLocalMoments(), and basicFieldMomentInversion::invertLocalMoments().
void update ()
Recalculate the moments from the quadrature nodes.
Definition at line 102 of file momentFieldSet.C.
References momentFieldSet< momentType, nodeType >::updateLocalMoments().
void updateLocalMoments (label elemi)
Recalculate the moments from the quadrature nodes in an element.
Definition at line 112 of file momentFieldSet.C.
Referenced by momentFieldSet< momentType, nodeType >::update().
label map (label a, label b, label c) const inline
Return the map label of a moment.
Definition at line 195 of file momentFieldSet.H.
The documentation for this class was generated from the following files:
momentFieldSet.H
momentFieldSet.C
momentFieldSetI.H