My Project: powerLawBreakup Class Reference
powerLawBreakup Class Reference
Power law breakup kernel. The value of the kernel is read from dictionary or assumed equal to 1. The minimum value of the abscissa after which the model is applied can be defined by the user or it is assumed to be 1.
Public Member Functions
TypeName ("powerLaw")
Runtime type information.
powerLawBreakup (const dictionary &dict, const fvMesh &mesh)
Construct from components.
virtual ~powerLawBreakup ()
Destructor.
virtual scalar Kb (const scalar &abscissa, const label celli) const
Breakup kernel.
Public Member Functions inherited from breakupKernel
TypeName ("breakupKernel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, breakupKernel, dictionary,(const dictionary &dict, const fvMesh &mesh),(dict, mesh))
breakupKernel (const dictionary &dict, const fvMesh &mesh)
Construct from components.
virtual ~breakupKernel ()
Destructor.
Additional Inherited Members
Static Public Member Functions inherited from breakupKernel
static autoPtr< breakupKernel > New (const dictionary &dict, const fvMesh &mesh)
Protected Attributes inherited from breakupKernel
const dictionary & dict_
Dictionary.
const fvMesh & mesh_
Mesh.
const dimensionedScalar Cb_
Coefficient of aggregation kernel.
Detailed Description
Power law breakup kernel. The value of the kernel is read from dictionary or assumed equal to 1. The minimum value of the abscissa after which the model is applied can be defined by the user or it is assumed to be 1.
Source files
powerLawBreakup.H
powerLawBreakup.C
Definition at line 54 of file powerLawBreakup.H.
Constructor & Destructor Documentation
powerLawBreakup (const dictionary & dict, const fvMesh & mesh)
Construct from components.
Definition at line 54 of file powerLawBreakup.C.
References powerLawBreakup::~powerLawBreakup().
~powerLawBreakup () virtual
Destructor.
Definition at line 68 of file powerLawBreakup.C.
References powerLawBreakup::Kb().
Referenced by powerLawBreakup::powerLawBreakup().
Member Function Documentation
TypeName ("powerLaw")
Runtime type information.
Foam::scalar Kb (const scalar & abscissa, const label celli) const virtual
Breakup kernel.
Implements breakupKernel.
Definition at line 76 of file powerLawBreakup.C.
Referenced by powerLawBreakup::~powerLawBreakup().
The documentation for this class was generated from the following files:
powerLawBreakup.H
powerLawBreakup.C