My Project: molecularDiffusion Class Reference
molecularDiffusion Class Reference
Molecular diffusion model.
Public Member Functions
TypeName ("molecularDiffusion")
Runtime type information.
molecularDiffusion (const dictionary &dict)
Construct from components.
virtual ~molecularDiffusion ()
Destructor.
virtual tmp< fvScalarMatrix > momentDiff (const volScalarField &moment) const
Moments of the daughter distribution.
Public Member Functions inherited from diffusionModel
TypeName ("diffusionModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, diffusionModel, dictionary,(const dictionary &dict),(dict))
diffusionModel (const dictionary &dict)
Construct from components.
virtual ~diffusionModel ()
Destructor.
Additional Inherited Members
Static Public Member Functions inherited from diffusionModel
static autoPtr< diffusionModel > New (const dictionary &dict)
Protected Attributes inherited from diffusionModel
const dictionary & dict_
Detailed Description
Molecular diffusion model.
The moment diffusion is modeled with a constant diffusion coefficient specified by the user.
where
= Diffusion term in the moment transport equation
= Moment of order k [-]
= Molecular diffusivity [m2/s]
Source files
molecularDiffusion.H
molecularDiffusion.C
Definition at line 80 of file populationBalanceModels/populationBalanceSubModels/diffusionModels/molecularDiffusion/molecularDiffusion.H.
Constructor & Destructor Documentation
molecularDiffusion (const dictionary & dict)
Construct from components.
Definition at line 57 of file populationBalanceModels/populationBalanceSubModels/diffusionModels/molecularDiffusion/molecularDiffusion.C.
References molecularDiffusion::~molecularDiffusion().
~molecularDiffusion () virtual
Destructor.
Definition at line 69 of file populationBalanceModels/populationBalanceSubModels/diffusionModels/molecularDiffusion/molecularDiffusion.C.
References molecularDiffusion::momentDiff().
Referenced by molecularDiffusion::molecularDiffusion().
Member Function Documentation
TypeName ("molecularDiffusion")
Runtime type information.
Foam::tmp< Foam::fvScalarMatrix > momentDiff (const volScalarField & moment) const virtual
Moments of the daughter distribution.
Implements diffusionModel.
Definition at line 78 of file populationBalanceModels/populationBalanceSubModels/diffusionModels/molecularDiffusion/molecularDiffusion.C.
Referenced by molecularDiffusion::~molecularDiffusion().
The documentation for this class was generated from the following files:
populationBalanceModels/populationBalanceSubModels/diffusionModels/molecularDiffusion/molecularDiffusion.H
populationBalanceModels/populationBalanceSubModels/diffusionModels/molecularDiffusion/molecularDiffusion.C