quadratureApproximation< momentFieldSetType, nodeType > Class Template Reference
quadratureApproximation< momentFieldSetType, nodeType > Class Template Reference
Provides storage for the moments and the corresponding quadrature approximation of a univariate distribution function. Methods to update the moments and the quadrature approximation are provided.
Public Member Functions
quadratureApproximation (const word &name, const fvMesh &mesh, const word &support, const label nDimensions)
Construct from mesh.
virtual ~quadratureApproximation ()
Destructor.
const word name () const
Return name.
fieldMomentInversion & momentFieldInverter ()
Extended moment inversion method.
const PtrList< nodeType > & nodes () const
Return the nodes.
const momentFieldSetType & moments () const
Const access to the moments.
momentFieldSetType & moments ()
Non-const access to the moments.
label nDimensions () const
Return the number of dimensions in the distribution.
label nMoments () const
Return the number of moments.
void updateQuadrature ()
Recalculate the quadrature nodes from the moments.
void updateMoments ()
Recalculate the moments from the quadrature nodes.
void updateLocalMoments (label celli)
Recalculate moments in the specified cell.
bool updateLocalQuadrature (label celli, bool fatalErrorOnFailedRealizabilityTest=true)
Recalculate the quadrature nodes from the moments in the.
Static Public Attributes
static const word propertiesName
Default name of the phase properties dictionary.
Protected Attributes
const word name_
Name of the quadrature approximation.
const fvMesh & mesh_
Reference to the mesh.
autoPtr< PtrList< nodeType > > nodes_
AutoPtr to the PtrList of quadrature nodes.
momentFieldSetType moments_
List of moments.
const label nDimensions_
Dimensionality of the distribution function.
const label nMoments_
Number of moments.
const label nSecondaryNodes_
Number of secondary nodes.
word support_
Support of the distribution function.
autoPtr< fieldMomentInversion > momentFieldInverter_
Extended moment inversion method.
Detailed Description
template<class momentFieldSetType, class nodeType>
class Foam::quadratureApproximation< momentFieldSetType, nodeType >
Provides storage for the moments and the corresponding quadrature approximation of a univariate distribution function. Methods to update the moments and the quadrature approximation are provided.
Source files
quadratureApproximation.H
quadratureApproximation.C
quadratureApproximationI.H
Definition at line 59 of file quadratureApproximation.H.
Constructor & Destructor Documentation
quadratureApproximation (const word & name, const fvMesh & mesh, const word & support, const label nDimensions)
Construct from mesh.
Definition at line 40 of file quadratureApproximation.C.
References quadratureApproximation< momentFieldSetType, nodeType >::~quadratureApproximation().
~quadratureApproximation () virtual
Destructor.
Definition at line 111 of file quadratureApproximation.C.
References quadratureApproximation< momentFieldSetType, nodeType >::updateQuadrature().
Referenced by quadratureApproximation< momentFieldSetType, nodeType >::quadratureApproximation().
Member Function Documentation
const word name () const inline
Return name.
Definition at line 30 of file quadratureApproximationI.H.
References quadratureApproximation< momentFieldSetType, nodeType >::momentFieldInverter().
Foam::fieldMomentInversion & momentFieldInverter () inline
Extended moment inversion method.
Definition at line 38 of file quadratureApproximationI.H.
Referenced by quadratureApproximation< momentFieldSetType, nodeType >::name().
const Foam::PtrList< nodeType > & nodes () const inline
Return the nodes.
Definition at line 45 of file quadratureApproximationI.H.
const momentFieldSetType & moments () const inline
Const access to the moments.
Definition at line 52 of file quadratureApproximationI.H.
Referenced by univariatePDFTransportModel::solve().
momentFieldSetType & moments () inline
Non-const access to the moments.
Definition at line 59 of file quadratureApproximationI.H.
Foam::label nDimensions () const inline
Return the number of dimensions in the distribution.
Definition at line 66 of file quadratureApproximationI.H.
Foam::label nMoments () const inline
Return the number of moments.
Definition at line 73 of file quadratureApproximationI.H.
Referenced by univariatePDFTransportModel::solve().
void updateQuadrature ()
Recalculate the quadrature nodes from the moments.
Definition at line 119 of file quadratureApproximation.C.
References quadratureApproximation< momentFieldSetType, nodeType >::updateMoments().
Referenced by univariatePDFTransportModel::solve(), and quadratureApproximation< momentFieldSetType, nodeType >::~quadratureApproximation().
void updateMoments ()
Recalculate the moments from the quadrature nodes.
Definition at line 127 of file quadratureApproximation.C.
References quadratureApproximation< momentFieldSetType, nodeType >::updateLocalMoments().
Referenced by quadratureApproximation< momentFieldSetType, nodeType >::updateQuadrature().
void updateLocalMoments (label celli)
Recalculate moments in the specified cell.
Definition at line 134 of file quadratureApproximation.C.
References quadratureApproximation< momentFieldSetType, nodeType >::updateLocalQuadrature().
Referenced by quadratureApproximation< momentFieldSetType, nodeType >::updateMoments().
bool updateLocalQuadrature (label celli, bool fatalErrorOnFailedRealizabilityTest = true)
Recalculate the quadrature nodes from the moments in the.
specified cell
Definition at line 141 of file quadratureApproximation.C.
Referenced by quadratureApproximation< momentFieldSetType, nodeType >::updateLocalMoments().
Member Data Documentation
const word name_ protected
Name of the quadrature approximation.
Definition at line 67 of file quadratureApproximation.H.
const fvMesh& mesh_ protected
Reference to the mesh.
Definition at line 70 of file quadratureApproximation.H.
autoPtr<PtrList<nodeType> > nodes_ protected
AutoPtr to the PtrList of quadrature nodes.
Definition at line 73 of file quadratureApproximation.H.
momentFieldSetType moments_ protected
List of moments.
Definition at line 76 of file quadratureApproximation.H.
const label nDimensions_ protected
Dimensionality of the distribution function.
Definition at line 79 of file quadratureApproximation.H.
const label nMoments_ protected
Number of moments.
Definition at line 82 of file quadratureApproximation.H.
const label nSecondaryNodes_ protected
Number of secondary nodes.
Definition at line 85 of file quadratureApproximation.H.
word support_ protected
Support of the distribution function.
Definition at line 88 of file quadratureApproximation.H.
autoPtr<fieldMomentInversion> momentFieldInverter_ protected
Extended moment inversion method.
Definition at line 91 of file quadratureApproximation.H.
const Foam::word propertiesName static
Default name of the phase properties dictionary.
Definition at line 97 of file quadratureApproximation.H.
The documentation for this class was generated from the following files:
quadratureApproximation.H
quadratureApproximation.C
quadratureApproximationI.H