My Project: monoKineticQuadratureApproximation Class Reference
monoKineticQuadratureApproximation Class Reference
Uses quadrature approximation as a base to handle size moments, while the velocity moments and abscissae are stored in this class. The one dimensional CQMOM inversion is also done.
Public Member Functions
monoKineticQuadratureApproximation (const word &name, const fvMesh &mesh, const word &support)
Construct from mesh.
virtual ~monoKineticQuadratureApproximation ()
Destructor.
const PtrList< volVectorField > & velocities () const
Const access to the velocity abscissae.
PtrList< volVectorField > & velocities ()
Const access to the velocity abscissae.
const PtrList< volVectorField > & velocityMoments () const
Const access to the velocity moments.
PtrList< volVectorField > & velocityMoments ()
Non-const access to the velocity moments.
const PtrList< surfaceScalarNode > & nodesOwn () const
Const access to the interpolated moments (owner)
const PtrList< surfaceVectorField > & velocitiesOwn () const
Const access to the interpolated velocities (owner)
const PtrList< surfaceScalarNode > & nodesNei () const
Const access to the interpolated moments (neighbour)
const PtrList< surfaceVectorField > & velocitiesNei () const
Const access to the interpolated velocities (neighbour)
void interpolateNodes ()
Interpolate nodes.
void updateBoundaryVelocities ()
Update node velocities on fixed-value boundaries.
void updateVelocities ()
Recalculate the velocity abscissae from the velocity moments.
void updateAllQuadrature ()
Recalculate the quadrature nodes from the moments.
void updateVelocityMoments ()
Recalculate the moments from the quadrature nodes.
void updateAllMoments ()
Recalculate all moments from the quadrature nodes.
Public Member Functions inherited from quadratureApproximation< volUnivariateMomentFieldSet, volScalarNode >
quadratureApproximation (const word &name, const fvMesh &mesh, const word &support, const label nDimensions)
Construct from mesh.
virtual ~quadratureApproximation ()
Destructor.
const word name () const
Return name.
fieldMomentInversion & momentFieldInverter ()
Extended moment inversion method.
const PtrList< volScalarNode > & nodes () const
Return the nodes.
const volUnivariateMomentFieldSet & moments () const
Const access to the moments.
volUnivariateMomentFieldSet & moments ()
Non-const access to the moments.
label nDimensions () const
Return the number of dimensions in the distribution.
label nMoments () const
Return the number of moments.
void updateQuadrature ()
Recalculate the quadrature nodes from the moments.
void updateMoments ()
Recalculate the moments from the quadrature nodes.
void updateLocalMoments (label celli)
Recalculate moments in the specified cell.
bool updateLocalQuadrature (label celli, bool fatalErrorOnFailedRealizabilityTest=true)
Recalculate the quadrature nodes from the moments in the.
Additional Inherited Members
Static Public Attributes inherited from quadratureApproximation< volUnivariateMomentFieldSet, volScalarNode >
static const word propertiesName
Default name of the phase properties dictionary.
Protected Attributes inherited from quadratureApproximation< volUnivariateMomentFieldSet, volScalarNode >
const word name_
Name of the quadrature approximation.
const fvMesh & mesh_
Reference to the mesh.
autoPtr< PtrList< volScalarNode > > nodes_
AutoPtr to the PtrList of quadrature nodes.
volUnivariateMomentFieldSet moments_
List of moments.
const label nDimensions_
Dimensionality of the distribution function.
const label nMoments_
Number of moments.
const label nSecondaryNodes_
Number of secondary nodes.
word support_
Support of the distribution function.
autoPtr< fieldMomentInversion > momentFieldInverter_
Extended moment inversion method.
Detailed Description
Uses quadrature approximation as a base to handle size moments, while the velocity moments and abscissae are stored in this class. The one dimensional CQMOM inversion is also done.
Source files
monoKineticQuadratureApproximation.H
monoKineticQuadratureApproximation.C
monoKineticQuadratureApproximationI.H
Definition at line 60 of file monoKineticQuadratureApproximation.H.
Constructor & Destructor Documentation
monoKineticQuadratureApproximation (const word & name, const fvMesh & mesh, const word & support) explicit
Construct from mesh.
Definition at line 40 of file monoKineticQuadratureApproximation.C.
~monoKineticQuadratureApproximation () virtual
Destructor.
Definition at line 243 of file monoKineticQuadratureApproximation.C.
Member Function Documentation
const Foam::PtrList< Foam::volVectorField > & velocities () const inline
Const access to the velocity abscissae.
Definition at line 29 of file monoKineticQuadratureApproximationI.H.
Foam::PtrList< Foam::volVectorField > & velocities () inline
Const access to the velocity abscissae.
Definition at line 35 of file monoKineticQuadratureApproximationI.H.
const Foam::PtrList< Foam::volVectorField > & velocityMoments () const inline
Const access to the velocity moments.
Definition at line 41 of file monoKineticQuadratureApproximationI.H.
Foam::PtrList< Foam::volVectorField > & velocityMoments () inline
Non-const access to the velocity moments.
Definition at line 47 of file monoKineticQuadratureApproximationI.H.
const Foam::PtrList< Foam::surfaceScalarNode > & nodesOwn () const inline
Const access to the interpolated moments (owner)
Definition at line 53 of file monoKineticQuadratureApproximationI.H.
Referenced by monoKineticQuadratureApproximation::interpolateNodes().
const Foam::PtrList< Foam::surfaceVectorField > & velocitiesOwn () const inline
Const access to the interpolated velocities (owner)
Definition at line 59 of file monoKineticQuadratureApproximationI.H.
const Foam::PtrList< Foam::surfaceScalarNode > & nodesNei () const inline
Const access to the interpolated moments (neighbour)
Definition at line 65 of file monoKineticQuadratureApproximationI.H.
Referenced by monoKineticQuadratureApproximation::interpolateNodes().
const Foam::PtrList< Foam::surfaceVectorField > & velocitiesNei () const inline
Const access to the interpolated velocities (neighbour)
Definition at line 71 of file monoKineticQuadratureApproximationI.H.
void interpolateNodes ()
Interpolate nodes.
Definition at line 249 of file monoKineticQuadratureApproximation.C.
References quadratureApproximation< volUnivariateMomentFieldSet, volScalarNode >::mesh_, quadratureApproximation< volUnivariateMomentFieldSet, volScalarNode >::nodes(), quadratureApproximation< volUnivariateMomentFieldSet, volScalarNode >::nodes_, monoKineticQuadratureApproximation::nodesNei(), monoKineticQuadratureApproximation::nodesOwn(), quadratureNode< weightType, abscissaType, sigmaType >::primaryAbscissa(), and quadratureNode< weightType, abscissaType, sigmaType >::primaryWeight().
void updateBoundaryVelocities ()
Update node velocities on fixed-value boundaries.
number of nodes with a non-negligable number of bubble or mass
Definition at line 316 of file monoKineticQuadratureApproximation.C.
References Vandermonde::inv(), quadratureApproximation< volUnivariateMomentFieldSet, volScalarNode >::moments_, and quadratureApproximation< volUnivariateMomentFieldSet, volScalarNode >::nodes_.
Referenced by monoKineticQuadratureApproximation::updateAllQuadrature().
void updateVelocities ()
Recalculate the velocity abscissae from the velocity moments.
number of nodes with a non-negligable number of bubble or mass
Definition at line 521 of file monoKineticQuadratureApproximation.C.
References Vandermonde::inv(), quadratureApproximation< volUnivariateMomentFieldSet, volScalarNode >::moments_, and quadratureApproximation< volUnivariateMomentFieldSet, volScalarNode >::nodes_.
Referenced by monoKineticQuadratureApproximation::updateAllQuadrature().
void updateAllQuadrature ()
Recalculate the quadrature nodes from the moments.
Make sure moments are below 0 before checking if they
are small enough to be neglected
Definition at line 444 of file monoKineticQuadratureApproximation.C.
References quadratureApproximation< volUnivariateMomentFieldSet, volScalarNode >::moments_, quadratureApproximation< volUnivariateMomentFieldSet, volScalarNode >::nMoments_, quadratureApproximation< volUnivariateMomentFieldSet, volScalarNode >::nodes_, monoKineticQuadratureApproximation::updateAllMoments(), monoKineticQuadratureApproximation::updateBoundaryVelocities(), quadratureApproximation< volUnivariateMomentFieldSet, volScalarNode >::updateQuadrature(), and monoKineticQuadratureApproximation::updateVelocities().
void updateVelocityMoments ()
Recalculate the moments from the quadrature nodes.
Definition at line 636 of file monoKineticQuadratureApproximation.C.
References quadratureApproximation< volUnivariateMomentFieldSet, volScalarNode >::nodes_.
Referenced by monoKineticQuadratureApproximation::updateAllMoments().
void updateAllMoments ()
Recalculate all moments from the quadrature nodes.
Definition at line 676 of file monoKineticQuadratureApproximation.C.
References quadratureApproximation< volUnivariateMomentFieldSet, volScalarNode >::updateMoments(), and monoKineticQuadratureApproximation::updateVelocityMoments().
Referenced by monoKineticQuadratureApproximation::updateAllQuadrature().
The documentation for this class was generated from the following files:
monoKineticQuadratureApproximation.H
monoKineticQuadratureApproximation.C
monoKineticQuadratureApproximationI.H