pdPhaseModel Class Reference
pdPhaseModel Class Reference
Class for a polydisperse phase model. Each bubble size hase a unique mean velocity. Size and velocity moments are stored in quadrature.
Public Member Functions
pdPhaseModel (const twoPhaseSystem &fluid, const dictionary &phaseProperties, const word &phaseName)
virtual ~pdPhaseModel ()
Destructor.
virtual label nNodes () const
Return the number of nodes.
virtual const volScalarField & alphas (const label nodei) const
Return alpha field for nodei.
virtual volScalarField & alphas (const label nodei)
Return non-constant access to alpha field for nodei.
virtual const volScalarField & ds (const label nodei) const
Return the diameter for nodei.
virtual const volVectorField & Us (const label nodei) const
Return the velocity for nodei.
virtual volVectorField & Us (const label nodei)
Return non-const access to the velocity for nodei.
virtual const volVectorField & Vs (const label nodei) const
Return deviation velocity for nodei.
virtual void correct ()
Correct the phase properties.
virtual void relativeTransport ()
Relative transport of moments.
virtual void averageTransport (const PtrList< fvVectorMatrix > &AEqns)
Average transport of moments.
Public Member Functions inherited from phaseModel
ClassName ("phaseModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, phaseModel, dictionary,(const twoPhaseSystem &fluid, const dictionary &dict, const word &phaseName),(fluid, dict, phaseName))
phaseModel (const twoPhaseSystem &fluid, const dictionary &dict, const word &phaseName)
autoPtr< phaseModel > clone () const
Return clone.
virtual ~phaseModel ()
Destructor.
const word & name () const
Return the name of this phase.
bool BGviscosity () const
Return if B&G viscosity model is used.
const twoPhaseSystem & fluid () const
Return the twoPhaseSystem.
const phaseModel & otherPhase () const
Return the other phase in this two-phase system.
const dimensionedScalar & residualAlpha () const
Return the residual phase-fraction for given phase.
const volScalarField & d () const
Return the mean diameter.
scalar alphaMax () const
Optional maximum phase-fraction (e.g. packing limit)
const PhaseCompressibleTurbulenceModel< phaseModel > & turbulence () const
Return the turbulence model.
PhaseCompressibleTurbulenceModel< phaseModel > & turbulence ()
Return non-const access to the turbulence model.
const rhoThermo & thermo () const
Return the thermophysical model.
rhoThermo & thermo ()
Return non-const access to the thermophysical model.
tmp< volScalarField > nu () const
Return the laminar viscosity.
tmp< scalarField > nu (const label patchi) const
Return the laminar viscosity for patch.
tmp< volScalarField > mu () const
Return the laminar dynamic viscosity.
tmp< scalarField > mu (const label patchi) const
Return the laminar dynamic viscosity for patch.
tmp< scalarField > kappa (const label patchi) const
Return the thermal conductivity on a patch.
tmp< volScalarField > kappa () const
Return the thermal conductivity.
tmp< volScalarField > kappaEff (const volScalarField &alphat) const
Return the laminar thermal conductivity.
tmp< scalarField > kappaEff (const scalarField &alphat, const label patchi) const
Return the laminar thermal conductivity on a patch.
tmp< volScalarField > alpha () const
Return the laminar thermal diffusivity for enthalpy.
tmp< scalarField > alpha (const label patchi) const
Return the laminar thermal diffusivity for enthalpy on a patch.
tmp< volScalarField > alphaEff (const volScalarField &alphat) const
Return the effective thermal diffusivity for enthalpy.
tmp< scalarField > alphaEff (const scalarField &alphat, const label patchi) const
Return the effective thermal diffusivity for enthalpy on a patch.
tmp< volScalarField > Cp () const
Return the specific heat capacity.
const volScalarField & rho () const
Return the density.
const volVectorField & U () const
Constant access to the mean velocity.
volVectorField & U ()
Non-const access to the mean velocity.
const surfaceScalarField & phi () const
Constant access to the volumetric flux.
surfaceScalarField & phi ()
Non-const access to the volumetric flux.
const surfaceScalarField & alphaPhi () const
Return the volumetric flux of the phase.
surfaceScalarField & alphaPhi ()
Return non-const access to the volumetric flux of the phase.
const surfaceScalarField & alphaRhoPhi () const
Return the mass flux of the phase.
surfaceScalarField & alphaRhoPhi ()
Return non-const access to the mass flux of the phase.
void correctInflowOutflow (surfaceScalarField &alphaPhi) const
Ensure that the flux at inflow BCs is preserved.
virtual bool read (const dictionary &phaseProperties)
Read phaseProperties dictionary.
virtual bool read ()
Dummy Read for transportModel.
Additional Inherited Members
Static Public Member Functions inherited from phaseModel
static autoPtr< phaseModel > New (const twoPhaseSystem &fluid, const dictionary &dict, const word &phaseName)
Protected Attributes inherited from phaseModel
const twoPhaseSystem & fluid_
Reference to mesh.
word name_
Name of phase.
dictionary phaseDict_
Phase dictionary.
dimensionedScalar residualAlpha_
Return the residual phase-fraction for given phase.
scalar alphaMax_
Optional maximum phase-fraction (e.g. packing limit)
autoPtr< rhoThermo > thermo_
Thermophysical properties.
volVectorField U_
Mean velocity.
surfaceScalarField alphaPhi_
Volumetric flux of the phase.
surfaceScalarField alphaRhoPhi_
Mass flux of the phase.
autoPtr< surfaceScalarField > phiPtr_
Volumetric flux of the phase.
volScalarField d_
Diameter (alpha weighted diameter for polydisperse)
autoPtr< PhaseCompressibleTurbulenceModel< phaseModel > > turbulence_
Turbulence model.
bool BGviscosity_
Bool to use B&G bubble pressure based viscosity.
Detailed Description
Class for a polydisperse phase model. Each bubble size hase a unique mean velocity. Size and velocity moments are stored in quadrature.
Source files
pdPhaseModel.H
pdPhaseModel.C
Definition at line 53 of file pdPhaseModel.H.
Constructor & Destructor Documentation
pdPhaseModel (const twoPhaseSystem & fluid, const dictionary & phaseProperties, const word & phaseName)
virtual ~pdPhaseModel () virtual
Destructor.
Member Function Documentation
virtual label nNodes () const inline virtual
Return the number of nodes.
Reimplemented from phaseModel.
Definition at line 112 of file pdPhaseModel.H.
virtual const volScalarField& alphas (const label nodei) const inline virtual
Return alpha field for nodei.
Reimplemented from phaseModel.
Definition at line 118 of file pdPhaseModel.H.
virtual volScalarField& alphas (const label nodei) inline virtual
Return non-constant access to alpha field for nodei.
Reimplemented from phaseModel.
Definition at line 124 of file pdPhaseModel.H.
virtual const volScalarField& ds (const label nodei) const inline virtual
Return the diameter for nodei.
Reimplemented from phaseModel.
Definition at line 130 of file pdPhaseModel.H.
virtual const volVectorField& Us (const label nodei) const inline virtual
Return the velocity for nodei.
Reimplemented from phaseModel.
Definition at line 137 of file pdPhaseModel.H.
virtual volVectorField& Us (const label nodei) inline virtual
Return non-const access to the velocity for nodei.
Reimplemented from phaseModel.
Definition at line 143 of file pdPhaseModel.H.
virtual const volVectorField& Vs (const label nodei) const inline virtual
Return deviation velocity for nodei.
Reimplemented from phaseModel.
Definition at line 149 of file pdPhaseModel.H.
References pdPhaseModel::averageTransport(), pdPhaseModel::correct(), and pdPhaseModel::relativeTransport().
virtual void correct () virtual
Correct the phase properties.
Reimplemented from phaseModel.
Referenced by pdPhaseModel::Vs().
virtual void relativeTransport () virtual
Relative transport of moments.
Reimplemented from phaseModel.
Referenced by pdPhaseModel::Vs().
virtual void averageTransport (const PtrList< fvVectorMatrix > & AEqns) virtual
Average transport of moments.
Reimplemented from phaseModel.
Referenced by pdPhaseModel::Vs().
The documentation for this class was generated from the following file:
pdPhaseModel.H