OpenQBMM: univariatePopulationBalance Class Reference
univariatePopulationBalance Class Reference
Public Member Functions
TypeName ("univariate")
Runtime type information.
univariatePopulationBalance (const word &name, const dictionary &dict, const surfaceScalarField &phi)
Construct from components.
virtual ~univariatePopulationBalance ()
Destructor.
scalar realizableCo ()
Return the maximum Courant number ensuring moment realizability.
void solve ()
Solve population balance equation.
Public Member Functions inherited from univariatePDFTransportModel
univariatePDFTransportModel (const word &name, const dictionary &dict, const fvMesh &mesh, const surfaceScalarField &phi, const word &support)
Construct from components.
virtual ~univariatePDFTransportModel ()
Destructor.
const univariateQuadratureApproximation & quadrature () const
Access.
scalar realizableCo ()
Return the maximum Courant number ensuring moment realizability.
Public Member Functions inherited from PDFTransportModel
PDFTransportModel (const word &name, const dictionary &dict, const fvMesh &mesh)
Construct from components.
virtual ~PDFTransportModel ()
Destructor.
Public Member Functions inherited from populationBalanceModel
TypeName ("populationBalanceModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, populationBalanceModel, dictionary,(const word &name, const dictionary &dict, const surfaceScalarField &phi),(name, dict, phi))
populationBalanceModel (const word &name, const dictionary &dict, const surfaceScalarField &phi)
Construct from components.
virtual ~populationBalanceModel ()
Destructor.
Additional Inherited Members
Static Public Member Functions inherited from populationBalanceModel
static autoPtr< populationBalanceModel > New (const word &name, const dictionary &dict, const surfaceScalarField &phi)
Select null constructed.
Protected Member Functions inherited from univariatePDFTransportModel
virtual void explicitMomentSource ()
Calculate explicit source terms with realizable ODE solver.
Protected Attributes inherited from univariatePDFTransportModel
univariateQuadratureApproximation quadrature_
Univariate quadrature approximation used to solve PDF transport.
autoPtr< univariateMomentAdvection > momentAdvection_
Moment advection.
Protected Attributes inherited from PDFTransportModel
const fvMesh & mesh_
Constant reference to the mesh.
Protected Attributes inherited from populationBalanceModel
const surfaceScalarField & phi_
Fluid-phase face-normal velocity.
Detailed Description
Definition at line 60 of file univariatePopulationBalance.H.
Constructor & Destructor Documentation
univariatePopulationBalance (const word & name, const dictionary & dict, const surfaceScalarField & phi)
Construct from components.
Definition at line 52 of file univariatePopulationBalance.C.
References univariatePopulationBalance::~univariatePopulationBalance().
~univariatePopulationBalance () virtual
Destructor.
Definition at line 115 of file univariatePopulationBalance.C.
References quadratureNode< weightType, abscissaType, sigmaType >::primaryAbscissa(), quadratureNode< weightType, abscissaType, sigmaType >::primaryWeight(), univariatePopulationBalance::realizableCo(), quadratureNode< weightType, abscissaType, sigmaType >::secondaryAbscissae(), and quadratureNode< weightType, abscissaType, sigmaType >::secondaryWeights().
Referenced by univariatePopulationBalance::univariatePopulationBalance().
Member Function Documentation
TypeName ("univariate")
Runtime type information.
Foam::scalar realizableCo () virtual
Return the maximum Courant number ensuring moment realizability.
Implements populationBalanceModel.
Definition at line 390 of file univariatePopulationBalance.C.
References univariatePDFTransportModel::realizableCo(), and univariatePopulationBalance::solve().
Referenced by univariatePopulationBalance::~univariatePopulationBalance().
void solve () virtual
Solve population balance equation.
Reimplemented from univariatePDFTransportModel.
Definition at line 397 of file univariatePopulationBalance.C.
References univariatePDFTransportModel::solve().
Referenced by univariatePopulationBalance::realizableCo().
The documentation for this class was generated from the following files:
univariatePopulationBalance.H
univariatePopulationBalance.C