My Project: alphaEqn.H File Reference
alphaEqn.H File Reference
Functions
surfaceScalarField pPrimeByA (h2f *fluid.pPrimeByA())
label nAlphaSubCycles (readLabel(alphaControls.lookup("nAlphaSubCycles")))
label nAlphaCorr (readLabel(alphaControls.lookup("nAlphaCorr")))
word alphaScheme ("div(phi,"+alpha1.name()+ ')')
word alpharScheme ("div(phir,"+alpha1.name()+ ')')
alpha1 correctBoundaryConditions ()
surfaceScalarField phic ("phic", phi)
surfaceScalarField phir ("phir", phi1-phi2)
if (fluid.pPrimeByA().valid())
for (int acorr=0;acorr< nAlphaCorr;acorr++)
Variables
const dictionary & alphaControls
volScalarField & dgdt = fluid.dgdt()
tmp< surfaceScalarField > alpha1alpha2f
Function Documentation
surfaceScalarField pPrimeByA (h2f *fluid. pPrimeByA())
Referenced by for().
label nAlphaSubCycles (readLabel(alphaControls.lookup("nAlphaSubCycles")))
Referenced by for().
label nAlphaCorr (readLabel(alphaControls.lookup("nAlphaCorr")))
word alphaScheme ("div(phi,"+alpha1.name()+ ')')
Referenced by for().
word alpharScheme ("div(phir,"+alpha1.name()+ ')')
Referenced by for().
alpha1 correctBoundaryConditions ()
surfaceScalarField phic ("phic" , phi)
Referenced by for().
surfaceScalarField phir ("phir" , phi1- phi2)
Referenced by for(), if(), and while().
if (fluid. pPrimeByA).valid()
Definition at line 22 of file alphaEqn.H.
References alpha2, and phir().
for ()
Definition at line 36 of file alphaEqn.H.
References AGmodel, alpha1alpha2f, alpha2, alphaPhi1, alphaPhi2, alphaRhoPhi1, alphaRhoPhi2, alpharScheme(), alphaScheme(), nAlphaSubCycles(), phi, phi1, phic(), phir(), pPrimeByA(), rho1, and rho2.
Variable Documentation
const dictionary& alphaControls
Initial value:
= mesh.solverDict
(
    alpha1.name()
)
Definition at line 1 of file alphaEqn.H.
volScalarField& dgdt = fluid.dgdt()
Definition at line 6 of file alphaEqn.H.
tmp<surfaceScalarField> alpha1alpha2f
Definition at line 20 of file alphaEqn.H.
Referenced by for().