OpenQBMM: univariateMomentSet Class Reference
univariateMomentSet Class Reference
Stores a generic moment set with the corresponding list of orders.
Public Member Functions
univariateMomentSet (const label nMoments, const word &support, const scalar initValue=0, const label nFixedQuadraturePoints=0)
Construct from number of moments and initial value.
univariateMomentSet (const scalarList &m, const word &support, const label nFixedQuadraturePoints=0)
Construct from scalarList.
virtual ~univariateMomentSet ()
Destructor.
const scalarList & alphaRecurrence () const
Returns alpha coefficients of the recurrence relation.
scalarList & alphaRecurrence ()
Returns alpha coefficients of the recurrence relation.
const scalarList & betaRecurrence () const
Returns beta coefficients of the recurrence relation.
scalarList & betaRecurrence ()
Returns beta coefficients of the recurrence relation.
scalarList & zetas ()
Returns zeta_k values for the moment set.
bool isDegenerate ()
Returns degenerate status of the moment set.
bool isFullyRealizable (bool fatalErrorOnFailedRealizabilityTest=true)
Return true if the entire moment set is realizable.
bool isRealizable (bool fatalErrorOnFailedRealizabilityTest=true)
Return true if some moments are realizable.
bool isSubsetRealizable (bool fatalErrorOnFailedRealizabilityTest=true)
Return true if a subset of moments is realizable.
bool isOnMomentSpaceBoundary (bool fatalErrorOnFailedRealizabilityTest=true)
Return true if the moment set is on the boundary of the moment space.
labelListList makeUnivariateMomentOrders (const label nMoments)
label nRealizableMoments (bool fatalErrorOnFailedRealizabilityTest=true)
Return the number of realizable moments.
label negativeZeta ()
virtual void update (const scalarList &weights, const scalarList &abscissae)
Update moments from the corresponding quadrature.
scalar & operator[] (const label)
const scalar & operator[] (const label) const
Public Member Functions inherited from momentSet
momentSet (const label nMoments, const labelListList &momentOrders, const word &support, const scalar initValue=0)
Construct from number of moments and initial value.
momentSet (const scalarList &m, const labelListList &momentOrders, const word &support)
Construct from scalarList.
virtual ~momentSet ()
Destructor.
const labelListList & momentOrders () const
Return moment orders.
label nMoments () const
Return the number of moments.
const word support () const
Return support.
Protected Attributes
bool realizabilityChecked_
Bool to indicate moment realizability was checked.
Protected Attributes inherited from momentSet
label nMoments_
Number of moments.
labelListList momentOrders_
List of moment orders.
word support_
Type of support of the measure associated to the moment set.
Detailed Description
Stores a generic moment set with the corresponding list of orders.
Source files
univariateMomentSet.H
univariateMomentSet.C
univariateMomentSet.H
Definition at line 50 of file univariateMomentSet.H.
Constructor & Destructor Documentation
univariateMomentSet (const label nMoments, const word & support, const scalar initValue = 0, const label nFixedQuadraturePoints = 0)
Construct from number of moments and initial value.
Definition at line 31 of file univariateMomentSet.C.
univariateMomentSet (const scalarList & m, const word & support, const label nFixedQuadraturePoints = 0)
Construct from scalarList.
Definition at line 80 of file univariateMomentSet.C.
~univariateMomentSet () virtual
Destructor.
Definition at line 128 of file univariateMomentSet.C.
References univariateMomentSet::isDegenerate(), univariateMomentSet::makeUnivariateMomentOrders(), momentSet::nMoments_, univariateMomentSet::realizabilityChecked_, and momentSet::support_.
Member Function Documentation
const Foam::scalarList & alphaRecurrence () const inline
Returns alpha coefficients of the recurrence relation.
Definition at line 29 of file univariateMomentSetI.H.
Referenced by univariateMomentInversion::JacobiMatrix().
Foam::scalarList & alphaRecurrence () inline
Returns alpha coefficients of the recurrence relation.
Definition at line 34 of file univariateMomentSetI.H.
const Foam::scalarList & betaRecurrence () const inline
Returns beta coefficients of the recurrence relation.
Definition at line 39 of file univariateMomentSetI.H.
Referenced by univariateMomentInversion::JacobiMatrix().
Foam::scalarList & betaRecurrence () inline
Returns beta coefficients of the recurrence relation.
Definition at line 44 of file univariateMomentSetI.H.
Foam::scalarList & zetas () inline
Returns zeta_k values for the moment set.
Definition at line 59 of file univariateMomentSetI.H.
References univariateMomentSet::realizabilityChecked_.
Referenced by zeta::interpolateFields().
bool isDegenerate () inline
Returns degenerate status of the moment set.
Definition at line 69 of file univariateMomentSetI.H.
References univariateMomentSet::isFullyRealizable().
Referenced by univariateMomentInversion::invert(), and univariateMomentSet::~univariateMomentSet().
bool isFullyRealizable (bool fatalErrorOnFailedRealizabilityTest = true) inline
Return true if the entire moment set is realizable.
Definition at line 89 of file univariateMomentSetI.H.
References univariateMomentSet::isRealizable(), and univariateMomentSet::realizabilityChecked_.
Referenced by univariateMomentSet::isDegenerate().
bool isRealizable (bool fatalErrorOnFailedRealizabilityTest = true) inline
Return true if some moments are realizable.
Definition at line 102 of file univariateMomentSetI.H.
References univariateMomentSet::isSubsetRealizable(), and univariateMomentSet::realizabilityChecked_.
Referenced by univariateMomentSet::isFullyRealizable().
bool isSubsetRealizable (bool fatalErrorOnFailedRealizabilityTest = true) inline
Return true if a subset of moments is realizable.
Definition at line 117 of file univariateMomentSetI.H.
References univariateMomentSet::isOnMomentSpaceBoundary(), and univariateMomentSet::realizabilityChecked_.
Referenced by univariateMomentSet::isRealizable().
bool isOnMomentSpaceBoundary (bool fatalErrorOnFailedRealizabilityTest = true) inline
Return true if the moment set is on the boundary of the moment space.
Definition at line 130 of file univariateMomentSetI.H.
References univariateMomentSet::nRealizableMoments(), and univariateMomentSet::realizabilityChecked_.
Referenced by extendedMomentInversion::invert(), and univariateMomentSet::isSubsetRealizable().
Foam::labelListList makeUnivariateMomentOrders (const label nMoments) inline
Definition at line 677 of file univariateMomentSet.C.
References momentSet::nMoments(), and univariateMomentSet::update().
Referenced by univariateMomentSet::~univariateMomentSet().
Foam::label nRealizableMoments (bool fatalErrorOnFailedRealizabilityTest = true) inline
Return the number of realizable moments.
Definition at line 143 of file univariateMomentSetI.H.
References univariateMomentSet::realizabilityChecked_.
Referenced by gaussMomentInversion::calcNQuadratureNodes(), gaussLobattoMomentInversion::calcNQuadratureNodes(), gaussRadauMomentInversion::calcNQuadratureNodes(), zeta::interpolateFields(), extendedMomentInversion::invert(), univariateMomentSet::isOnMomentSpaceBoundary(), zeta::limitZetas(), gammaEQMOM::m2N(), betaEQMOM::m2N(), lognormalEQMOM::m2N(), and lognormalEQMOM::sigmaMax().
Foam::label negativeZeta () inline
Definition at line 49 of file univariateMomentSetI.H.
void update (const scalarList & weights, const scalarList & abscissae) virtual
Update moments from the corresponding quadrature.
Definition at line 692 of file univariateMomentSet.C.
References momentSet::nMoments_, and univariateMomentSet::realizabilityChecked_.
Referenced by univariateMomentSet::makeUnivariateMomentOrders(), and extendedMomentInversion::normalizedMomentError().
Foam::scalar & operator[] (const label i) inline
Definition at line 155 of file univariateMomentSetI.H.
References univariateMomentSet::realizabilityChecked_.
const Foam::scalar & operator[] (const label i) const inline
Definition at line 166 of file univariateMomentSetI.H.
Member Data Documentation
bool realizabilityChecked_ protected
Bool to indicate moment realizability was checked.
Definition at line 107 of file univariateMomentSet.H.
Referenced by univariateMomentSet::isFullyRealizable(), univariateMomentSet::isOnMomentSpaceBoundary(), univariateMomentSet::isRealizable(), univariateMomentSet::isSubsetRealizable(), univariateMomentSet::nRealizableMoments(), univariateMomentSet::operator[](), univariateMomentSet::update(), univariateMomentSet::zetas(), and univariateMomentSet::~univariateMomentSet().
The documentation for this class was generated from the following files:
univariateMomentSet.H
univariateMomentSet.C
univariateMomentSetI.H