OpenQBMM: turbulentMixing Class Reference
turbulentMixing Class Reference
Public Member Functions
TypeName ("turbulentMixing")
Runtime type information.
turbulentMixing (const word &name, const dictionary &dict, const surfaceScalarField &phi)
Construct from components.
virtual ~turbulentMixing ()
Destructor.
scalar realizableCo ()
Return the maximum Courant number ensuring moment realizability.
void solve ()
Solve mixing model.
Public Member Functions inherited from univariatePDFTransportModel
univariatePDFTransportModel (const word &name, const dictionary &dict, const fvMesh &mesh, const surfaceScalarField &phi, const word &support)
Construct from components.
virtual ~univariatePDFTransportModel ()
Destructor.
const univariateQuadratureApproximation & quadrature () const
Access.
scalar realizableCo ()
Return the maximum Courant number ensuring moment realizability.
Public Member Functions inherited from PDFTransportModel
PDFTransportModel (const word &name, const dictionary &dict, const fvMesh &mesh)
Construct from components.
virtual ~PDFTransportModel ()
Destructor.
Public Member Functions inherited from mixingModel
TypeName ("mixingModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, mixingModel, dictionary,(const word &name, const dictionary &dict, const surfaceScalarField &phi),(name, dict, phi))
mixingModel (const word &name, const dictionary &dict, const surfaceScalarField &phi)
Construct from components.
virtual ~mixingModel ()
Destructor.
Additional Inherited Members
Static Public Member Functions inherited from mixingModel
static autoPtr< mixingModel > New (const word &name, const dictionary &dict, const surfaceScalarField &phi)
Select null constructed.
Protected Attributes inherited from univariatePDFTransportModel
univariateQuadratureApproximation quadrature_
Univariate quadrature approximation used to solve PDF transport.
autoPtr< univariateMomentAdvection > momentAdvection_
Moment advection.
Protected Attributes inherited from PDFTransportModel
const fvMesh & mesh_
Constant reference to the mesh.
Protected Attributes inherited from mixingModel
const surfaceScalarField & phi_
Fluid-phase face-normal velocity.
Detailed Description
Definition at line 55 of file turbulentMixing.H.
Constructor & Destructor Documentation
turbulentMixing (const word & name, const dictionary & dict, const surfaceScalarField & phi)
Construct from components.
Definition at line 51 of file turbulentMixing.C.
~turbulentMixing () virtual
Destructor.
Definition at line 79 of file turbulentMixing.C.
References turbulentMixing::realizableCo().
Member Function Documentation
TypeName ("turbulentMixing")
Runtime type information.
Foam::scalar realizableCo () virtual
Return the maximum Courant number ensuring moment realizability.
Implements mixingModel.
Definition at line 148 of file turbulentMixing.C.
References univariatePDFTransportModel::realizableCo(), and turbulentMixing::solve().
Referenced by turbulentMixing::~turbulentMixing().
void solve () virtual
Solve mixing model.
Implements mixingModel.
Definition at line 154 of file turbulentMixing.C.
References univariatePDFTransportModel::solve().
Referenced by turbulentMixing::realizableCo().
The documentation for this class was generated from the following files:
turbulentMixing.H
turbulentMixing.C