My Project: createFieldRefs.H File Reference
denseAGFoam/createFieldRefs.H File Reference
Variables
volScalarField & alpha2 = phase2
surfaceScalarField & phi1 = phase1.phi()
surfaceScalarField & alphaPhi1 = phase1.alphaPhi()
surfaceScalarField & alphaRhoPhi1 = phase1.alphaRhoPhi()
surfaceScalarField & phi2 = phase2.phi()
surfaceScalarField & alphaPhi2 = phase2.alphaPhi()
surfaceScalarField & alphaRhoPhi2 = phase2.alphaRhoPhi()
surfaceScalarField & phi = fluid.phi()
rhoThermo & thermo1 = phase1.thermo()
rhoThermo & thermo2 = phase2.thermo()
volScalarField & rho1 = thermo1.rho()
const volScalarField & psi1 = thermo1.psi()
volScalarField & rho2 = thermo2.rho()
const volScalarField & psi2 = thermo2.psi()
kineticTheoryModel & AGmodel
Variable Documentation
volScalarField& alpha2 = phase2
Definition at line 1 of file denseAGFoam/createFieldRefs.H.
Referenced by for(), if(), and while().
surfaceScalarField& phi1 = phase1.phi()
Definition at line 3 of file denseAGFoam/createFieldRefs.H.
Referenced by for(), and while().
surfaceScalarField& alphaPhi1 = phase1.alphaPhi()
Definition at line 4 of file denseAGFoam/createFieldRefs.H.
Referenced by for(), and while().
surfaceScalarField& alphaRhoPhi1 = phase1.alphaRhoPhi()
Definition at line 5 of file denseAGFoam/createFieldRefs.H.
Referenced by for().
surfaceScalarField& phi2 = phase2.phi()
Definition at line 7 of file denseAGFoam/createFieldRefs.H.
Referenced by for(), and while().
surfaceScalarField& alphaPhi2 = phase2.alphaPhi()
Definition at line 8 of file denseAGFoam/createFieldRefs.H.
Referenced by for(), and while().
surfaceScalarField& alphaRhoPhi2 = phase2.alphaRhoPhi()
Definition at line 9 of file denseAGFoam/createFieldRefs.H.
Referenced by for().
surfaceScalarField& phi = fluid.phi()
Definition at line 11 of file denseAGFoam/createFieldRefs.H.
Referenced by for(), mixingModel::New(), populationBalanceModel::New(), univariateMomentAdvection::New(), and while().
rhoThermo& thermo1 = phase1.thermo()
Definition at line 13 of file denseAGFoam/createFieldRefs.H.
rhoThermo& thermo2 = phase2.thermo()
Definition at line 14 of file denseAGFoam/createFieldRefs.H.
volScalarField& rho1 = thermo1.rho()
Definition at line 16 of file denseAGFoam/createFieldRefs.H.
Referenced by for(), and while().
const volScalarField& psi1 = thermo1.psi()
Definition at line 17 of file denseAGFoam/createFieldRefs.H.
Referenced by while().
volScalarField& rho2 = thermo2.rho()
Definition at line 19 of file denseAGFoam/createFieldRefs.H.
Referenced by for(), and while().
const volScalarField& psi2 = thermo2.psi()
Definition at line 20 of file denseAGFoam/createFieldRefs.H.
Referenced by while().
kineticTheoryModel& AGmodel
Initial value:
=
    mesh.lookupObjectRef<kineticTheoryModel>
    (
        IOobject::groupName
        (
            kineticTheoryModel::typeName,
            phase1.name()
        )
    )
Definition at line 23 of file denseAGFoam/createFieldRefs.H.
Referenced by for(), and while().