My Project: pEqn.H File Reference
buoyantPbePimpleFoam/pEqn.H File Reference
Functions
thermo rho ()- = psi*p_rgh
volScalarField rAU (1.0/UEqn.A())
surfaceScalarField rhorAUf ("rhorAUf", fvc::interpolate(rho *rAU))
volVectorField HbyA (constrainHbyA(rAU *UEqn.H(), U, p_rgh))
surfaceScalarField phig (-rhorAUf *ghf *fvc::snGrad(rho)*mesh.magSf())
surfaceScalarField phiHbyA ("phiHbyA",(fvc::flux(rho *HbyA) +rhorAUf *fvc::ddtCorr(rho, U, phi))+phig)
MRF makeRelative (fvc::interpolate(rho), phiHbyA)
constrainPressure (p_rgh, rho, U, phiHbyA, rhorAUf, MRF)
fvScalarMatrix p_rghDDtEqn (fvc::ddt(rho)+psi *correction(fvm::ddt(p_rgh))+fvc::div(phiHbyA)==fvOptions(psi, p_rgh, rho.name()))
while (pimple.correctNonOrthogonal())
if (thermo.dpdt())
Variables
p = p_rgh + rho*gh
Function Documentation
thermo rho () = psi*p_rgh
volScalarField rAU (1.0/UEqn. A())
Referenced by while().
surfaceScalarField rhorAUf ("rhorAUf" , fvc::interpolate(rho *rAU))
Referenced by while().
volVectorField HbyA (constrainHbyA(rAU *UEqn.H(), U, p_rgh))
surfaceScalarField phig (-rhorAUf *ghf * fvc::snGradrho)*mesh.magSf()
Referenced by while().
surfaceScalarField phiHbyA ("phiHbyA" , (fvc::flux(rho *HbyA) +rhorAUf *fvc::ddtCorr(rho, U, phi))+ phig)
Referenced by while().
MRF makeRelative (fvc::interpolate(rho) , phiHbyA)
constrainPressure (p_rgh , rho , U , phiHbyA , rhorAUf , MRF)
fvScalarMatrix p_rghDDtEqn (fvc::ddt(rho)+psi *correction(fvm::ddt(p_rgh))+fvc::div(phiHbyA) = =fvOptions(psi, p_rgh, rho.name()))
Referenced by while().
while (pimple. correctNonOrthogonal())
Definition at line 37 of file buoyantPbePimpleFoam/pEqn.H.
References p_rghDDtEqn(), phi, phig(), phiHbyA(), rAU(), rhorAUf(), and U().
if (thermo. dpdt())
Definition at line 69 of file buoyantPbePimpleFoam/pEqn.H.
References p.
Variable Documentation
p = p_rgh + rho*gh
Definition at line 64 of file buoyantPbePimpleFoam/pEqn.H.
Referenced by if().