My Project: pEqn.H File Reference
multiphase/polydisperseBubbleFoam/pU/pEqn.H File Reference
Functions
surfaceScalarField alphaf1 ("alphaf1", fvc::interpolate(alpha1))
surfaceScalarField alphaf2 ("alphaf2", scalar(1)-alphaf1)
volScalarField rAU1 (IOobject::groupName("rAU", phase1.name()), 1.0/(U1Eqn.A() +max(phase1.residualAlpha()-alpha1, scalar(0)) *rho1/runTime.deltaT()))
volScalarField rAU2 (IOobject::groupName("rAU", phase2.name()), 1.0/(U2Eqn.A() +max(phase2.residualAlpha()-alpha2, scalar(0)) *rho2/runTime.deltaT()))
surfaceScalarField alpharAUf1 (fvc::interpolate(max(alpha1, phase1.residualAlpha())*rAU1))
surfaceScalarField alpharAUf2 (fvc::interpolate(max(alpha2, phase2.residualAlpha())*rAU2))
surfaceScalarField snGradAlpha1 (fvc::snGrad(alpha1)*mesh.magSf())
volScalarField pPrime1 (phase1.turbulence().pPrime())
volScalarField pPrime2 (phase2.turbulence().pPrime())
fluid pPrimeByA ()
for (label nodei=0;nodei< phase1.nNodes();nodei++)
while (pimple.correct())
if (thermo1.dpdt()||thermo2.dpdt())
Variables
tmp< surfaceScalarField > phiF1 = fvc::flux(rAU1*F)
tmp< surfaceScalarField > phiF2 = - fvc::flux(rAU2*F)
K1 = 0.5*magSqr(U1)
K2 = 0.5*magSqr(U2)
Function Documentation
surfaceScalarField alphaf1 ("alphaf1" , fvc::interpolate(alpha1))
Referenced by while().
surfaceScalarField alphaf2 ("alphaf2" , scalar(1)- alphaf1)
Referenced by while().
volScalarField rAU1 (IOobject::groupName("rAU", phase1.name()) , 1.0/ U1Eqn.A() +max(phase1.residualAlpha()-alpha1, scalar(0)) *rho1/runTime.deltaT())
Referenced by for(), and while().
volScalarField rAU2 (IOobject::groupName("rAU", phase2.name()) , 1.0/ U2Eqn.A() +max(phase2.residualAlpha()-alpha2, scalar(0)) *rho2/runTime.deltaT())
Referenced by for(), and while().
surfaceScalarField alpharAUf1 (fvc::interpolate(max(alpha1, phase1.residualAlpha())*rAU1))
Referenced by while().
surfaceScalarField alpharAUf2 (fvc::interpolate(max(alpha2, phase2.residualAlpha())*rAU2))
Referenced by while().
surfaceScalarField snGradAlpha1 (fvc::snGrad(alpha1)*mesh.magSf())
Referenced by for().
volScalarField pPrime1 (phase1. turbulence).pPrime()
Referenced by for().
volScalarField pPrime2 (phase2. turbulence).pPrime()
Referenced by for().
fluid pPrimeByA ()
for ()
Definition at line 75 of file multiphase/polydisperseBubbleFoam/pU/pEqn.H.
References Df2(), pPrime1(), pPrime2(), rAU1(), rAU2(), and snGradAlpha1().
while (pimple. correct())
Definition at line 105 of file multiphase/polydisperseBubbleFoam/pU/pEqn.H.
References alpha2, alphaf1(), alphaf2(), alphaPhi1, alphaPhi2, alpharAUf1(), alpharAUf2(), contErr1, contErr2, MRF(), p, phi, phi1, phi2, phiF1, phiF2, phiHbyA(), phir(), psi1, psi2, rAU1(), rAU2(), rho(), rho1, rho2, solve(), and U().
if (thermo1. dpdt)||thermo2.dpdt()
Definition at line 439 of file multiphase/polydisperseBubbleFoam/pU/pEqn.H.
References p.
Variable Documentation
phiF1 = fvc::flux(rAU1*F)
Definition at line 35 of file multiphase/polydisperseBubbleFoam/pU/pEqn.H.
Referenced by while().
phiF2 = - fvc::flux(rAU2*F)
Definition at line 36 of file multiphase/polydisperseBubbleFoam/pU/pEqn.H.
Referenced by while().
K1 = 0.5*magSqr(U1)
Definition at line 435 of file multiphase/polydisperseBubbleFoam/pU/pEqn.H.
K2 = 0.5*magSqr(U2)
Definition at line 436 of file multiphase/polydisperseBubbleFoam/pU/pEqn.H.