OpenQBMM: pEqn.H File Reference
multiphase/denseAGFoam/pU/pEqn.H File Reference
Functions
surfaceScalarField alphaf1 ("alphaf1", fvc::interpolate(alpha1))
surfaceScalarField alphaf2 ("alphaf2", scalar(1)-alphaf1)
surfaceScalarField alpharAUf1 (fvc::interpolate(max(alpha1, phase1.residualAlpha())*rAU1))
surfaceScalarField alpharAUf2 (fvc::interpolate(max(alpha2, phase2.residualAlpha())*rAU2))
surfaceScalarField Df2 (fvc::interpolate(rAU2 *(phase2.turbulence().pPrime())))
if (implicitPhasePressure)
volVectorField F (fluid.F())
surfaceScalarField snGradAlpha1 (fvc::snGrad(alpha1)*mesh.magSf())
while (pimple.correct())
if (thermo1.dpdt()||thermo2.dpdt())
Variables
rAU1
rAU2
tmp< surfaceScalarField > phiF1 = Df1*snGradAlpha1 + fvc::flux(rAU1*F)
tmp< surfaceScalarField > phiF2 = - Df2*snGradAlpha1 - fvc::flux(rAU2*F)
K1 = 0.5*magSqr(U1)
K2 = 0.5*magSqr(U2)
Function Documentation
surfaceScalarField alphaf1 ("alphaf1" , fvc::interpolate(alpha1))
Referenced by while().
surfaceScalarField alphaf2 ("alphaf2" , scalar(1)- alphaf1)
Referenced by while().
surfaceScalarField alpharAUf1 (fvc::interpolate(max(alpha1, phase1.residualAlpha())*rAU1))
Referenced by while().
surfaceScalarField alpharAUf2 (fvc::interpolate(max(alpha2, phase2.residualAlpha())*rAU2))
Referenced by while().
surfaceScalarField Df2 (fvc::interpolate(rAU2 *(phase2.turbulence().pPrime())))
Referenced by for(), and if().
if (implicitPhasePressure)
Definition at line 60 of file multiphase/denseAGFoam/pU/pEqn.H.
References Df2(), F(), rAU1, rAU2, and snGradAlpha1().
volVectorField F (fluid. F())
Referenced by if(), and AyaziShamlou::Kb().
surfaceScalarField snGradAlpha1 (fvc::snGrad(alpha1)*mesh.magSf())
Referenced by if().
while (pimple. correct())
Definition at line 80 of file multiphase/denseAGFoam/pU/pEqn.H.
References AGmodel, alpha2, alphaf1(), alphaf2(), alphaPhi1, alphaPhi2, alpharAUf1(), alpharAUf2(), contErr1, contErr2, MRF(), p, phi, phi1, phi2, phiF1, phiF2, phiHbyA(), phir(), psi1, psi2, rAU1, rAU2, rho(), rho1, rho2, solve(), and U().
if (thermo1. dpdt)||thermo2.dpdt()
Definition at line 420 of file multiphase/denseAGFoam/pU/pEqn.H.
References p.
Variable Documentation
rAU1
Initial value:
=
(
    1.0
   /(
        U1Eqn.A()
      + max(phase1.residualAlpha() - alpha1, scalar(0))
       *rho1/runTime.deltaT()
    )
)
Definition at line 4 of file multiphase/denseAGFoam/pU/pEqn.H.
Referenced by if(), and while().
rAU2
Initial value:
=
(
    1.0
   /(
        U2Eqn.A()
      + max(phase2.residualAlpha() - alpha2, scalar(0))
       *rho2/runTime.deltaT()
    )
)
Definition at line 14 of file multiphase/denseAGFoam/pU/pEqn.H.
Referenced by if(), and while().
phiF1 = Df1*snGradAlpha1 + fvc::flux(rAU1*F)
Definition at line 34 of file multiphase/denseAGFoam/pU/pEqn.H.
Referenced by while().
phiF2 = - Df2*snGradAlpha1 - fvc::flux(rAU2*F)
Definition at line 35 of file multiphase/denseAGFoam/pU/pEqn.H.
Referenced by while().
K1 = 0.5*magSqr(U1)
Definition at line 416 of file multiphase/denseAGFoam/pU/pEqn.H.
K2 = 0.5*magSqr(U2)
Definition at line 417 of file multiphase/denseAGFoam/pU/pEqn.H.