OpenQBMM: p_rghEqn.H File Reference
p_rghEqn.H File Reference
Functions
surfaceScalarField alphaf1 ("alphaf1", fvc::interpolate(alpha1))
surfaceScalarField alphaf2 ("alphaf2", scalar(1) - alphaf1)
surfaceScalarField alpharAUf1 (fvc::interpolate(max(alpha1, phase1.residualAlpha()) *rAU1))
surfaceScalarField alpharAUf2 (fvc::interpolate(max(alpha2, phase2.residualAlpha()) *rAU2))
surfaceScalarField Df2 (fvc::interpolate(rAU2 *(phase2.turbulence().pPrime())))
if (implicitPhasePressure)
volVectorField F (fluid.F())
surfaceScalarField snGradAlpha1 (fvc::snGrad(alpha1) *mesh.magSf())
while (pimple.correct())
Variables
rAU1
rAU2
tmp< surfaceScalarField > phiF1 = Df1*snGradAlpha1 + fvc::flux(rAU1*F)
tmp< surfaceScalarField > phiF2 = - Df2*snGradAlpha1 - fvc::flux(rAU2*F)
Function Documentation
alphaf1()
surfaceScalarField alphaf1 ("alphaf1" , fvc::interpolate(alpha1))
Referenced by while().
alphaf2()
surfaceScalarField alphaf2 ("alphaf2" , scalar(1) - alphaf1)
Referenced by while().
alpharAUf1()
surfaceScalarField alpharAUf1 (fvc::interpolate(max(alpha1, phase1.residualAlpha()) *rAU1))
Referenced by while().
alpharAUf2()
surfaceScalarField alpharAUf2 (fvc::interpolate(max(alpha2, phase2.residualAlpha()) *rAU2))
Referenced by while().
Df2()
surfaceScalarField Df2 (fvc::interpolate(rAU2 *(phase2.turbulence().pPrime())))
Referenced by for(), and if().
if()
if (implicitPhasePressure)
Definition at line 61 of file p_rghEqn.H.
References Df2().
F()
volVectorField F (fluid. F())
Referenced by AyaziShamlou::Kb().
snGradAlpha1()
surfaceScalarField snGradAlpha1 (fvc::snGrad(alpha1) *mesh.magSf())
while()
while (pimple. correct())
Definition at line 79 of file p_rghEqn.H.
References AGmodel, alpha1, alpha2, alphaf1(), alphaf2(), alphaPhi1, alphaPhi2, alpharAUf1(), alpharAUf2(), contErr1, contErr2, forAll(), Kd(), max(), MRF(), p, phase1(), phase2(), phi, phi1, phi2, phiF1, phiF2, phiHbyA(), psi1, psi2, rAU1, rAU2, rho, rho1, rho2, solve(), U(), U1, and U2.
Variable Documentation
rAU1
rAU1
Initial value:
=
(
    1.0
   /(
        U1Eqn.A()
      + max(phase1.residualAlpha() - alpha1, scalar(0))
       *rho1/runTime.deltaT()
    )
)
Definition at line 5 of file p_rghEqn.H.
Referenced by while().
rAU2
rAU2
Initial value:
=
(
    1.0
   /(
        U2Eqn.A()
      + max(phase2.residualAlpha() - alpha2, scalar(0))
       *rho2/runTime.deltaT()
    )
)
Definition at line 15 of file p_rghEqn.H.
Referenced by while().
phiF1
phiF1 = Df1*snGradAlpha1 + fvc::flux(rAU1*F)
Definition at line 35 of file p_rghEqn.H.
Referenced by while().
phiF2
phiF2 = - Df2*snGradAlpha1 - fvc::flux(rAU2*F)
Definition at line 36 of file p_rghEqn.H.
Referenced by while().