OpenQBMM: alphaEqn.H File Reference
alphaEqn.H File Reference
Functions
tmp< surfaceScalarField > pPrimeByA (h2f *fluid.pPrimeByA()())
label nAlphaCorr (readLabel(alphaControls.lookup("nAlphaCorr")))
word alphaScheme ("div("+phi1.name()+','+alpha1.name()+')')
alpha1 correctBoundaryConditions ()
phase1 correctInflowOutflow (alphaPhi1)
fvScalarMatrix alpha1Eqn (alpha1, alpha1.dimensions() *dimVol/dimTime)
if (pPrimeByA.valid())
alpha1Eqn relax ()
alpha1Eqn solve ()
phase2 correctInflowOutflow (alphaPhi2)
Variables
const dictionary & alphaControls
else
alphaPhi1 = alpha1Eqn.flux()
alphaRhoPhi1 = fvc::interpolate(rho1)*alphaPhi1
alphaPhi2 = phi - alphaPhi1
alphaRhoPhi2 = fvc::interpolate(rho2)*alphaPhi2
Function Documentation
pPrimeByA()
tmp<surfaceScalarField> pPrimeByA (h2f *fluid. pPrimeByA)()
Referenced by if().
nAlphaCorr()
label nAlphaCorr (readLabel(alphaControls.lookup("nAlphaCorr")))
Referenced by if().
alphaScheme()
word alphaScheme ("div("+phi1.name()+','+alpha1.name()+')')
Referenced by if().
correctBoundaryConditions()
alpha1 correctBoundaryConditions ()
correctInflowOutflow() [1/2]
phase1 correctInflowOutflow (alphaPhi1)
alpha1Eqn()
fvScalarMatrix alpha1Eqn (alpha1 , alpha1.dimensions() *dimVol/ dimTime)
Referenced by if().
if()
if (pPrimeByA. valid())
Definition at line 16 of file alphaEqn.H.
References alpha1, alpha1Eqn(), alphaScheme(), max(), nAlphaCorr(), phi1, and pPrimeByA().
relax()
alpha1Eqn relax ()
solve()
alpha1Eqn solve ()
correctInflowOutflow() [2/2]
phase2 correctInflowOutflow (alphaPhi2)
Variable Documentation
alphaControls
const dictionary& alphaControls
Initial value:
= mesh.solverDict
(
    alpha1.name()
)
Definition at line 1 of file alphaEqn.H.
else
else
Initial value:
{
    alpha1Eqn =
    (
        fvm::ddt(alpha1)
      + fvm::div(phi1, alpha1)
    )
Definition at line 40 of file alphaEqn.H.
alphaPhi1
alphaPhi1 = alpha1Eqn.flux()
Definition at line 51 of file alphaEqn.H.
Referenced by if(), and while().
alphaRhoPhi1
alphaRhoPhi1 = fvc::interpolate(rho1)*alphaPhi1
Definition at line 52 of file alphaEqn.H.
Referenced by if().
alphaPhi2
alphaPhi2 = phi - alphaPhi1
Definition at line 54 of file alphaEqn.H.
Referenced by if(), and while().
alphaRhoPhi2
alphaRhoPhi2 = fvc::interpolate(rho2)*alphaPhi2
Definition at line 56 of file alphaEqn.H.
Referenced by if().