OpenQBMM: momentumSources.H File Reference
momentumSources.H File Reference
Functions
PtrList< fvVectorMatrix > AEqns (phase2->nNodes())
volScalarField Kd (IOobject("Kd", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::NO_WRITE), mesh, dimensionedScalar("zero", dimDensity/dimTime, 0.0))
volVectorField dragSource (IOobject("dragSource", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::NO_WRITE), mesh, dimensionedVector("zero", dimAcceleration *dimDensity, Zero))
volScalarField Cvm (IOobject("Cvm", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::NO_WRITE), mesh, dimensionedScalar("zero", dimDensity, 0.0))
volVectorField virtualMassSource (IOobject("virtualMassSource", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::NO_WRITE), mesh, dimensionedVector("zero", dimAcceleration *dimDensity, Zero))
volVectorField F (IOobject("F", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::NO_WRITE), mesh, dimensionedVector("zero", dimAcceleration *dimDensity, Zero))
volScalarField Kh (IOobject("Kh", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::NO_WRITE), mesh, dimensionedScalar("zero", dimensionSet(1, -1, -3, -1, 0), 0.0))
volVectorField DDtU (fvc::ddt(U1)+fvc::div(phi1, U1) - fvc::div(phi1) *U1)
forAll (AEqns, nodei)
Function Documentation
AEqns()
PtrList<fvVectorMatrix> AEqns (phase2-> nNodes())
Referenced by for(), and forAll().
Kd()
volScalarField Kd (IOobject("Kd", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::NO_WRITE) , mesh , dimensionedScalar("zero", dimDensity/dimTime, 0.0))
Referenced by for(), forAll(), and while().
dragSource()
volVectorField dragSource (IOobject("dragSource", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::NO_WRITE) , mesh , dimensionedVector("zero", dimAcceleration *dimDensity, Zero))
Referenced by forAll().
Cvm()
volScalarField Cvm (IOobject("Cvm", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::NO_WRITE) , mesh , dimensionedScalar("zero", dimDensity, 0.0))
Referenced by forAll().
virtualMassSource()
volVectorField virtualMassSource (IOobject("virtualMassSource", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::NO_WRITE) , mesh , dimensionedVector("zero", dimAcceleration *dimDensity, Zero))
Referenced by forAll().
F()
volVectorField F (IOobject("F", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::NO_WRITE) , mesh , dimensionedVector("zero", dimAcceleration *dimDensity, Zero))
Referenced by forAll().
Kh()
volScalarField Kh (IOobject("Kh", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::NO_WRITE) , mesh , dimensionedScalar("zero", dimensionSet(1, -1, -3, -1, 0), 0.0))
Referenced by forAll(), and if().
DDtU()
volVectorField DDtU (fvc::ddt(U1)+fvc::div(phi1, U1) - fvc::div(phi1) * U1)
Referenced by forAll().
forAll()
forAll (AEqns , nodei)
Definition at line 93 of file momentumSources.H.
References AEqns(), alpha1, Cvm(), DDtU(), drag(), dragSource(), F(), heatTransfer, Kd(), Kh(), lift, phase2(), rho, rho1, rho2, turbulentDispersion, U1, virtualMass, virtualMassSource(), and wallLubrication.
Referenced by aggregationKernel::aggregationSource(), BGKCollision::BGKCollision(), BoltzmannCollision::BoltzmannCollision(), breakupKernel::breakupSource(), hermiteQuadrature::calcHermiteQuadrature(), collisionKernel::collisionKernel(), conditional::conditional(), firstOrderKinetic::CoNum(), zeta::countFacesWithOutgoingFlux(), firstOrderKinetic::firstOrderKinetic(), hermiteQuadrature::hermiteQuadrature(), zeta::interpolateFields(), firstOrderKinetic::interpolateNodes(), monoKineticQuadratureApproximation::interpolateNodes(), extendedFieldMomentInversion::invert(), hyperbolicMomentInversion::invert(), basicFieldMomentInversion::invert(), monoKinetic::invert(), TensorProduct::invert(), sizeCHyQMOM::invert(), basicVelocityFieldMomentInversion::invert(), conditional::invert(), CHyQMOM::invert(), extendedFieldMomentInversion::invertBoundaryMoments(), basicFieldMomentInversion::invertBoundaryMoments(), basicVelocityFieldMomentInversion::invertBoundaryMoments(), extendedFieldMomentInversion::invertLocalMoments(), basicFieldMomentInversion::invertLocalMoments(), basicVelocityFieldMomentInversion::invertLocalMoments(), zeta::limitZetas(), moment< fieldType, nodeType >::listToLabel(), mappedPtrList< volScalarMoment >::listToLabel(), mappedList< scalarList >::listToLabel(), moment< fieldType, nodeType >::listToWord(), mappedPtrList< volScalarMoment >::listToWord(), mappedList< scalarList >::listToWord(), mappedList< scalarList >::mappedList(), mappedPtrList< volScalarMoment >::mappedPtrList(), momentFieldSet< surfaceScalarMoment, surfaceScalarNode >::momentFieldSet(), lognormalEQMOM::momentsStarToMoments(), lognormalEQMOM::momentsToMomentsStar(), monoKineticQuadratureApproximation::monoKineticQuadratureApproximation(), multivariateMomentInversion::multivariateMomentInversion(), growthModel::phaseSpaceConvection(), BoltzmannCollision::preUpdate(), quadratureApproximation< volVelocityMoment, volVelocityNode >::quadratureApproximation(), quadratureNode< scalarType, vectorType >::quadratureNode(), VikasQuasiSecondOrder::realizableCo(), firstOrderKinetic::realizableCo(), gammaEQMOM::recurrenceRelation(), multivariateMomentInversion::reset(), univariatePDFTransportModel::solve(), velocityPDFTransportModel::solve(), realizableOdeSolver< volVelocityMoment, volVelocityNode >::solve(), mixingPopulationBalance::solve(), TensorProduct::TensorProduct(), univariateMomentAdvection::univariateMomentAdvection(), firstOrderKinetic::update(), momentFieldSet< surfaceScalarMoment, surfaceScalarNode >::update(), zeta::update(), moment< fieldType, nodeType >::update(), monoKineticQuadratureApproximation::updateAllLocalQuadrature(), monoKineticQuadratureApproximation::updateAllQuadrature(), momentFieldSet< surfaceScalarMoment, surfaceScalarNode >::updateBoundaries(), moment< fieldType, nodeType >::updateBoundaries(), monoKineticQuadratureApproximation::updateBoundaryVelocities(), BoltzmannCollision::updateCells(), BGKCollision::updateCells(), collisionKernel::updateFields(), moment< fieldType, nodeType >::updateLocalMoment(), momentFieldSet< surfaceScalarMoment, surfaceScalarNode >::updateLocalMoments(), monoKineticQuadratureApproximation::updateLocalVelocities(), monoKineticQuadratureApproximation::updateLocalVelocityMoments(), monoKineticQuadratureApproximation::updateVelocities(), monoKineticQuadratureApproximation::updateVelocityMoments(), velocityMomentAdvection::updateWallCollisions(), velocityMomentAdvection::velocityMomentAdvection(), while(), and zeta::zeta().