OpenQBMM: computeParticleFields.H File Reference
computeParticleFields.H File Reference
Functions
labelList orderZero (momentOrders[0].size(), 0)
volScalarField m0 (moments(0))
m0 max (1e-10)
forAll (velocityIndexes, cmpt)
if (computeVariance)
if (sizeIndex !=-1 &&nodes[0].lengthBased())
Function Documentation
orderZero()
labelList orderZero (momentOrders. size()[0], 0)
Referenced by forAll(), and if().
m0()
volScalarField m0 (moments(0))
Referenced by esBGKCollision::covariance(), BGKCollision::covariance(), forAll(), if(), extendedFieldMomentInversion::invert(), basicFieldMomentInversion::invert(), sizeCHyQMOM::invert(), basicVelocityFieldMomentInversion::invert(), BGKCollision::moment000(), BGKCollision::moment001(), BGKCollision::moment002(), BGKCollision::moment003(), BGKCollision::moment004(), BGKCollision::moment005(), BGKCollision::moment010(), BGKCollision::moment011(), BGKCollision::moment012(), BGKCollision::moment013(), BGKCollision::moment014(), BGKCollision::moment015(), BGKCollision::moment020(), BGKCollision::moment021(), BGKCollision::moment022(), BGKCollision::moment023(), BGKCollision::moment024(), BGKCollision::moment025(), BGKCollision::moment030(), BGKCollision::moment031(), BGKCollision::moment032(), BGKCollision::moment040(), BGKCollision::moment041(), BGKCollision::moment042(), BGKCollision::moment050(), BGKCollision::moment051(), BGKCollision::moment052(), BGKCollision::moment100(), BGKCollision::moment101(), BGKCollision::moment102(), BGKCollision::moment103(), BGKCollision::moment104(), BGKCollision::moment105(), BGKCollision::moment110(), BGKCollision::moment111(), BGKCollision::moment120(), BGKCollision::moment130(), BGKCollision::moment140(), BGKCollision::moment150(), BGKCollision::moment200(), BGKCollision::moment201(), BGKCollision::moment202(), BGKCollision::moment203(), BGKCollision::moment204(), BGKCollision::moment205(), BGKCollision::moment210(), BGKCollision::moment220(), BGKCollision::moment230(), BGKCollision::moment240(), BGKCollision::moment250(), BGKCollision::moment300(), BGKCollision::moment301(), BGKCollision::moment302(), BGKCollision::moment310(), BGKCollision::moment320(), BGKCollision::moment400(), BGKCollision::moment401(), BGKCollision::moment402(), BGKCollision::moment410(), BGKCollision::moment420(), BGKCollision::moment500(), BGKCollision::moment501(), BGKCollision::moment502(), BGKCollision::moment510(), BGKCollision::moment520(), monoKineticQuadratureApproximation::updateAllLocalQuadrature(), monoKineticQuadratureApproximation::updateAllQuadrature(), monoKineticQuadratureApproximation::updateBoundaryVelocities(), BGKCollision::updateCells(), and monoKineticQuadratureApproximation::updateLocalVelocities().
max()
m0 max (1e- 10)
Referenced by aggregationKernel::aggregationSource(), breakupKernel::breakupSource(), collisionKernel::collisionKernel(), conditional::conditional(), firstOrderKinetic::CoNum(), esBGKCollision::covariance(), BGKCollision::covariance(), collisionKernel::d(), esBGKCollision::explicitCollisionSource(), gammaEQMOM::f(), for(), hermiteQuadrature::hermiteQuadrature(), if(), esBGKCollision::implicitCollisionSource(), hyperbolicMomentInversion::invert(), monoKinetic::invert(), TensorProduct::invert(), sizeCHyQMOM::invert(), Brownian::Ka(), turbulentBrownian::Ka(), mappedPtrList< volScalarMoment >::listToLabel(), mappedList< scalarList >::listToLabel(), mappedList< scalarList >::mappedList(), mappedPtrList< volScalarMoment >::mappedPtrList(), multivariateMomentInversion::multivariateMomentInversion(), growthModel::phaseSpaceConvection(), quadratureApproximation< volVelocityMoment, volVelocityNode >::quadratureApproximation(), VikasQuasiSecondOrder::realizableCo(), firstOrderKinetic::realizableCo(), mappedPtrList< volScalarMoment >::setMap(), realizableOdeSolver< volVelocityMoment, volVelocityNode >::solve(), TensorProduct::TensorProduct(), firstOrderKinetic::update(), zeta::update(), BGKCollision::updateCells(), velocityMomentAdvection::updateWallCollisions(), and while().
forAll()
forAll (velocityIndexes , cmpt)
Definition at line 7 of file computeParticleFields.H.
References computeVariance, m0(), moments, orderZero(), and velocityIndexes().
if() [1/2]
if (computeVariance)
Definition at line 36 of file computeParticleFields.H.
if() [2/2]
if (sizeIndex ! = -1 && nodes[0].lengthBased())
Definition at line 41 of file computeParticleFields.H.
References dMean, m0(), moments, orderZero(), and sizeIndex.