OpenQBMM: hermiteQuadrature Class Reference
hermiteQuadrature Class Reference
Use spectral methods to generate samples for multivaraites Gaussian distribution.
Public Member Functions
hermiteQuadrature (const label &nDim, const label &nOrder)
Construct from a scalarDiagonalMatrix.
void calcHermiteQuadrature (const vector &mu, const symmTensor &Pp)
hermiteQuadrature (const hermiteQuadrature &)=delete
Disallow default bitwise copy construct.
const scalarList & hermiteWeights () const
Return eigenvalues.
const vectorList & hermiteAbscissas () const
Return eigenvectors.
vectorList & hermiteAbscissas ()
const vectorList & hermiteOriginalAbscissas () const
const scalar & maxAbs () const
void operator= (const hermiteQuadrature &)=delete
Disallow default bitwise assignment.
Detailed Description
Use spectral methods to generate samples for multivaraites Gaussian distribution.
Definition at line 49 of file hermiteQuadrature.H.
Constructor & Destructor Documentation
hermiteQuadrature() [1/2]
hermiteQuadrature (const label & nDim, const label & nOrder)
Construct from a scalarDiagonalMatrix.
Definition at line 36 of file hermiteQuadrature.C.
References eigenSolver::eigenvaluesRe(), eigenSolver::eigenvectors(), forAll(), max(), and p.
hermiteQuadrature() [2/2]
hermiteQuadrature (const hermiteQuadrature &) delete
Disallow default bitwise copy construct.
Member Function Documentation
calcHermiteQuadrature()
void calcHermiteQuadrature (const vector & mu, const symmTensor & Pp)
Definition at line 137 of file hermiteQuadrature.C.
References eigenSolver::eigenvaluesRe(), eigenSolver::eigenvectors(), and forAll().
hermiteWeights()
const scalarList& hermiteWeights () const inline
Return eigenvalues.
Definition at line 95 of file hermiteQuadrature.H.
hermiteAbscissas() [1/2]
const vectorList& hermiteAbscissas () const inline
Return eigenvectors.
Definition at line 101 of file hermiteQuadrature.H.
hermiteAbscissas() [2/2]
vectorList& hermiteAbscissas () inline
Definition at line 106 of file hermiteQuadrature.H.
hermiteOriginalAbscissas()
const vectorList& hermiteOriginalAbscissas () const inline
Definition at line 111 of file hermiteQuadrature.H.
maxAbs()
const scalar& maxAbs () const inline
Definition at line 116 of file hermiteQuadrature.H.
operator=()
void operator= (const hermiteQuadrature &) delete
Disallow default bitwise assignment.
The documentation for this class was generated from the following files:
hermiteQuadrature.H
hermiteQuadrature.C