OpenQBMM: basicVelocityFieldMomentInversion Class Reference
basicVelocityFieldMomentInversion Class Reference
Invert volVectorMomentFieldSet using basic hyperbolic conditional moment inversion.
Public Member Functions
TypeName ("basicVelocityFieldMomentInversion")
Runtime type information.
basicVelocityFieldMomentInversion (const dictionary &dict, const fvMesh &mesh, const labelListList &momentOrders, const labelListList &nodeIndexes, const labelList &velocityIndexes, const label nSecondaryNodes)
Construct from dictionary.
basicVelocityFieldMomentInversion (const basicVelocityFieldMomentInversion &)=delete
Disallow default bitwise copy construct.
~basicVelocityFieldMomentInversion ()
Destructor.
virtual void invert (const volScalarMomentFieldSet &moments, mappedPtrList< volScalarNode > &nodes)
Invert moments in the entire computational domain.
virtual void invertBoundaryMoments (const volScalarMomentFieldSet &moments, mappedPtrList< volScalarNode > &nodes)
Invert moments on boundaries.
virtual bool invertLocalMoments (const volScalarMomentFieldSet &moments, mappedPtrList< volScalarNode > &nodes, const label celli, const bool fatalErrorOnFailedRealizabilityTest=true)
Invert moments in a single cell.
virtual void invert (const volVelocityMomentFieldSet &moments, mappedPtrList< volVelocityNode > &nodes)
Invert moments in the entire computational domain.
virtual void invertBoundaryMoments (const volVelocityMomentFieldSet &moments, mappedPtrList< volVelocityNode > &nodes)
Invert moments on boundaries.
virtual bool invertLocalMoments (const volVelocityMomentFieldSet &moments, mappedPtrList< volVelocityNode > &nodes, const label celli, const bool fatalErrorOnFailedRealizabilityTest=true)
Invert moments in a single cell.
void operator= (const basicVelocityFieldMomentInversion &)=delete
Disallow default bitwise assignment.
Public Member Functions inherited from fieldMomentInversion
TypeName ("fieldMomentInversion")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, fieldMomentInversion, dictionary,(const dictionary &dict, const fvMesh &mesh, const labelListList &momentOrders, const labelListList &nodeIndexes, const labelList &velocityIndexes, const label nSecondaryNodes),(dict, mesh, momentOrders, nodeIndexes, velocityIndexes, nSecondaryNodes))
fieldMomentInversion (const dictionary &dict, const fvMesh &mesh, const labelListList &momentOrders, const labelListList &nodeIndexes, const labelList &velocityIndexes, const label nSecondaryNodes)
Construct from univariateMomentSet.
fieldMomentInversion (const fieldMomentInversion &)=delete
Disallow default bitwise copy construct.
virtual ~fieldMomentInversion ()
Destructor.
bool extended ()
Return extended type.
void operator= (const fieldMomentInversion &)=delete
Disallow default bitwise assignment.
Additional Inherited Members
Static Public Member Functions inherited from fieldMomentInversion
static autoPtr< fieldMomentInversion > New (const dictionary &dict, const fvMesh &mesh, const labelListList &momentOrders, const labelListList &nodeIndexes, const labelList &velocityIndexes, const label nSecondaryNodes)
Protected Attributes inherited from fieldMomentInversion
const fvMesh & mesh_
Const refrence to the mesh.
bool extended_
Boolean flag to indicate extended type of inversion.
const labelListList & momentOrders_
Moment orders used to map moments.
const labelListList & nodeIndexes_
Node indexes used to map nodes.
Detailed Description
Invert volVectorMomentFieldSet using basic hyperbolic conditional moment inversion.
Source files
basicVelocityFieldMomentInversion.H
basicVelocityFieldMomentInversion.C
Definition at line 51 of file basicVelocityFieldMomentInversion.H.
Constructor & Destructor Documentation
basicVelocityFieldMomentInversion() [1/2]
basicVelocityFieldMomentInversion (const dictionary & dict, const fvMesh & mesh, const labelListList & momentOrders, const labelListList & nodeIndexes, const labelList & velocityIndexes, const label nSecondaryNodes)
Construct from dictionary.
Definition at line 47 of file basicVelocityFieldMomentInversion.C.
basicVelocityFieldMomentInversion() [2/2]
basicVelocityFieldMomentInversion (const basicVelocityFieldMomentInversion &) delete
Disallow default bitwise copy construct.
~basicVelocityFieldMomentInversion()
~basicVelocityFieldMomentInversion ()
Destructor.
Definition at line 80 of file basicVelocityFieldMomentInversion.C.
Member Function Documentation
TypeName()
TypeName ("basicVelocityFieldMomentInversion")
Runtime type information.
invert() [1/2]
void invert (const volScalarMomentFieldSet & moments, mappedPtrList< volScalarNode > & nodes) virtual
Invert moments in the entire computational domain.
Implements fieldMomentInversion.
Definition at line 87 of file basicVelocityFieldMomentInversion.C.
invertBoundaryMoments() [1/2]
void invertBoundaryMoments (const volScalarMomentFieldSet & moments, mappedPtrList< volScalarNode > & nodes) virtual
Invert moments on boundaries.
Implements fieldMomentInversion.
Definition at line 96 of file basicVelocityFieldMomentInversion.C.
invertLocalMoments() [1/2]
bool invertLocalMoments (const volScalarMomentFieldSet & moments, mappedPtrList< volScalarNode > & nodes, const label celli, const bool fatalErrorOnFailedRealizabilityTest = true) virtual
Invert moments in a single cell.
Implements fieldMomentInversion.
Definition at line 105 of file basicVelocityFieldMomentInversion.C.
invert() [2/2]
void invert (const volVelocityMomentFieldSet & moments, mappedPtrList< volVelocityNode > & nodes) virtual
Invert moments in the entire computational domain.
Implements fieldMomentInversion.
Definition at line 118 of file basicVelocityFieldMomentInversion.C.
References forAll(), m0(), moments, and nodes.
invertBoundaryMoments() [2/2]
void invertBoundaryMoments (const volVelocityMomentFieldSet & moments, mappedPtrList< volVelocityNode > & nodes) virtual
Invert moments on boundaries.
Implements fieldMomentInversion.
Definition at line 134 of file basicVelocityFieldMomentInversion.C.
References forAll(), moments, nodes, quadratureNode< scalarType, vectorType >::primaryAbscissae(), quadratureNode< scalarType, vectorType >::primaryWeight(), quadratureNode< scalarType, vectorType >::scalarIndexes(), and velocityQuadratureNode< scalarType, vectorType >::velocityAbscissae().
invertLocalMoments() [2/2]
bool invertLocalMoments (const volVelocityMomentFieldSet & moments, mappedPtrList< volVelocityNode > & nodes, const label celli, const bool fatalErrorOnFailedRealizabilityTest = true) virtual
Invert moments in a single cell.
Implements fieldMomentInversion.
Definition at line 203 of file basicVelocityFieldMomentInversion.C.
References forAll(), moments, nodes, quadratureNode< scalarType, vectorType >::primaryAbscissae(), quadratureNode< scalarType, vectorType >::primaryWeight(), quadratureNode< scalarType, vectorType >::scalarIndexes(), and velocityQuadratureNode< scalarType, vectorType >::velocityAbscissae().
operator=()
void operator= (const basicVelocityFieldMomentInversion &) delete
Disallow default bitwise assignment.
The documentation for this class was generated from the following files:
basicVelocityFieldMomentInversion.H
basicVelocityFieldMomentInversion.C