OpenQBMM: mappedList< mappedType > Class Template Reference
mappedList< mappedType > Class Template Reference
Stores a list, with a Map<label> that takes a label key and returns the index into the list.
Public Member Functions
mappedList (const label size, const labelListList &indexes)
Construct from size and labelListList.
mappedList (const label size, const labelListList &indexes, const mappedType &initValue)
Construct from size and labelListList with initial value for.
mappedList (const label size, const Map< label > &map, const mappedType &initValue)
Construct from size and map with initial value for all elements.
mappedList (const List< mappedType > &initList, const labelListList &indexes)
Construct from List<mappedType> and labelListList.
~mappedList ()
Destructor.
void resize (const label newSize)
Resize mapped list.
void setSize (const label newSize)
Set mapped list size.
bool found (const labelList &l) const
Is label list index used.
template<typename ... ArgsT>
bool found (ArgsT ...args) const
Is label list index used.
template<typename ... ArgsT>
mappedType & operator() (ArgsT ...args)
Non-const access to a moment given the list of orders.
template<typename ... ArgsT>
const mappedType & operator() (ArgsT ...args) const
Const access to a moment given the list of orders.
const mappedType & operator() (const labelList &l) const
Constant access given a label list.
mappedType & operator() (const labelList &l)
Non-constant access given a label list.
const Map< label > & map () const
Returns const access to the moment map.
template<typename ... ArgsT>
bool found (ArgsT...args) const
template<class mappedType >
const mappedType & operator() (const Foam::labelList &l) const
template<class mappedType >
mappedType & operator() (const Foam::labelList &l)
Static Public Member Functions
static word listToWord (const labelList &lst)
Convert a list of labels to a word. {1, 2, 3} -> 123.
static label listToLabel (const labelList &lst, const label nDims=0)
Convert a list of labels to a single label. {0, 2, 3} -> 23.
Detailed Description
template<class mappedType>
class Foam::mappedList< mappedType >
Stores a list, with a Map<label> that takes a label key and returns the index into the list.
Example
Lookup | Label Key | Index 0 0 0 0 0 1 0 0 100 1 0 1 0 10 2 0 0 1 1 3 2 0 0 200 4 2 1 0 210 5
The operator () is overloaded in order to hide the above mapping.
Source files
mappedList.H
mappedListI.H
mappedList.C
Definition at line 66 of file mappedList.H.
Constructor & Destructor Documentation
mappedList() [1/4]
mappedList (const label size, const labelListList & indexes)
Construct from size and labelListList.
Definition at line 64 of file mappedList.C.
mappedList() [2/4]
mappedList (const label size, const labelListList & indexes, const mappedType & initValue)
Construct from size and labelListList with initial value for.
all elements
Definition at line 89 of file mappedList.C.
mappedList() [3/4]
mappedList (const label size, const Map< label > & map, const mappedType & initValue)
Construct from size and map with initial value for all elements.
Definition at line 114 of file mappedList.C.
mappedList() [4/4]
mappedList (const List< mappedType > & initList, const labelListList & indexes)
Construct from List<mappedType> and labelListList.
Definition at line 138 of file mappedList.C.
~mappedList()
~mappedList ()
Destructor.
Definition at line 166 of file mappedList.C.
Member Function Documentation
listToWord()
Foam::word listToWord (const labelList & lst) static
Convert a list of labels to a word. {1, 2, 3} -> 123.
Definition at line 33 of file mappedList.C.
Referenced by velocityQuadratureNode< scalarType, vectorType >::iNew::operator()(), and quadratureNode< scalarType, vectorType >::iNew::operator()().
listToLabel()
Foam::label listToLabel (const labelList & lst, const label nDims = 0) static
Convert a list of labels to a single label. {0, 2, 3} -> 23.
Definition at line 47 of file mappedList.C.
resize()
void resize (const label newSize)
Resize mapped list.
Definition at line 205 of file mappedList.C.
setSize()
void setSize (const label newSize)
Set mapped list size.
Definition at line 198 of file mappedList.C.
Referenced by momentSet::setSize().
found() [1/3]
bool found (const labelList & l) const
Is label list index used.
Definition at line 211 of file mappedList.C.
found() [2/3]
bool found (ArgsT ... args) const
Is label list index used.
operator()() [1/6]
mappedType & operator() (ArgsT ... args) inline
Non-const access to a moment given the list of orders.
Definition at line 30 of file mappedListI.H.
operator()() [2/6]
const mappedType & operator() (ArgsT ... args) const inline
Const access to a moment given the list of orders.
Definition at line 40 of file mappedListI.H.
operator()() [3/6]
const mappedType& operator() (const labelList & l) const inline
Constant access given a label list.
operator()() [4/6]
mappedType& operator() (const labelList & l) inline
Non-constant access given a label list.
map()
const Foam::Map< Foam::label > & map () const inline
Returns const access to the moment map.
Definition at line 66 of file mappedListI.H.
found() [3/3]
bool found (ArgsT... args) const
Definition at line 230 of file mappedList.C.
operator()() [5/6]
const mappedType& operator() (const Foam::labelList & l) const
Definition at line 49 of file mappedListI.H.
operator()() [6/6]
mappedType& operator() (const Foam::labelList & l)
Definition at line 58 of file mappedListI.H.
The documentation for this class was generated from the following files:
mappedList.H
mappedList.C
mappedListI.H