OpenQBMM: eigenSolver Class Reference
eigenSolver Class Reference
Eigenvalues and eigenvectors of a square real matrix.
Public Member Functions
eigenSolver (const scalarSquareMatrix &A)
Construct from a scalarSquareMatrix.
eigenSolver (const scalarSquareMatrix &A, bool symmetric)
Construct from a scalarSquareMatrix and symmetry information.
eigenSolver (const eigenSolver &)=delete
Disallow default bitwise copy construct.
const scalarDiagonalMatrix & eigenvaluesRe () const
Return real part of the eigenvalues.
const scalarDiagonalMatrix & eigenvaluesIm () const
const scalarSquareMatrix & eigenvectors () const
Return eigenvectors.
void operator= (const eigenSolver &)=delete
Disallow default bitwise assignment.
Detailed Description
Eigenvalues and eigenvectors of a square real matrix.
Acknowledgments This implementation derives almost completely from TNT/JAMA, a public-domain library developed at NIST, available at http://math.nist.gov/tnt/index.html Their implementation was based upon EISPACK.
The tridiagonaliseSymmMatrix, symmTridiagQL, Hessemberg and realSchur methods are based on the Algol procedures tred2 by Bowdler, Martin, Reinsch, and Wilkinson, Handbook for Auto. Comp., Vol. II-Linear Algebra, and the corresponding FORTRAN subroutine in EISPACK.
Source files
eigenSolver.H
eigenSolver.C
Definition at line 61 of file eigenSolver.H.
Constructor & Destructor Documentation
eigenSolver() [1/3]
eigenSolver (const scalarSquareMatrix & A)
Construct from a scalarSquareMatrix.
Definition at line 33 of file eigenSolver.C.
eigenSolver() [2/3]
eigenSolver (const scalarSquareMatrix & A, bool symmetric)
Construct from a scalarSquareMatrix and symmetry information.
Does not perform symmetric check
Definition at line 57 of file eigenSolver.C.
eigenSolver() [3/3]
eigenSolver (const eigenSolver &) delete
Disallow default bitwise copy construct.
Member Function Documentation
eigenvaluesRe()
const scalarDiagonalMatrix& eigenvaluesRe () const inline
Return real part of the eigenvalues.
Definition at line 118 of file eigenSolver.H.
Referenced by hermiteQuadrature::calcHermiteQuadrature(), hermiteQuadrature::hermiteQuadrature(), and univariateMomentInversion::invert().
eigenvaluesIm()
const scalarDiagonalMatrix& eigenvaluesIm () const inline
Definition at line 123 of file eigenSolver.H.
eigenvectors()
const scalarSquareMatrix& eigenvectors () const inline
Return eigenvectors.
Definition at line 129 of file eigenSolver.H.
Referenced by hermiteQuadrature::calcHermiteQuadrature(), hermiteQuadrature::hermiteQuadrature(), and univariateMomentInversion::invert().
operator=()
void operator= (const eigenSolver &) delete
Disallow default bitwise assignment.
The documentation for this class was generated from the following files:
eigenSolver.H
eigenSolver.C