OpenQBMM: zeta Class Reference
zeta Class Reference
Public Member Functions
TypeName ("zeta")
Runtime type information.
zeta (const dictionary &dict, const scalarQuadratureApproximation &quadrature, const surfaceScalarField &phi, const word &support)
Construct from univariateMomentSet.
virtual ~zeta ()
Destructor.
virtual scalar realizableCo () const
Return the maximum Courant number ensuring moment realizability.
virtual void update ()
Update moment advection.
Public Member Functions inherited from univariateMomentAdvection
TypeName ("univariateMomentAdvection")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, univariateMomentAdvection, dictionary,(const dictionary &dict, const scalarQuadratureApproximation &quadrature, const surfaceScalarField &phi, const word &support),(dict, quadrature, phi, support))
univariateMomentAdvection (const dictionary &dict, const scalarQuadratureApproximation &quadrature, const surfaceScalarField &phi, const word &support)
Construct from univariateMomentSet.
univariateMomentAdvection (const univariateMomentAdvection &)=delete
Disallow default bitwise copy construct.
virtual ~univariateMomentAdvection ()
Destructor.
const mappedPtrList< volScalarField > & divMoments () const
Return the advection term for the moment transport equation.
void operator= (const univariateMomentAdvection &)=delete
Disallow default bitwise assignment.
Protected Member Functions
void countFacesWithOutgoingFlux ()
Calculates the number of cells with outgoing flux.
void limiter ()
Computes the limiter used for additional limitation.
void interpolateFields ()
Reconstructs zeta_k.
void limitZetas ()
Applies additional limitation to zeta_k, if needed.
Protected Member Functions inherited from univariateMomentAdvection
word fieldName (const word &name, const labelList &order) const
Construct field name from name, order.
Additional Inherited Members
Static Public Member Functions inherited from univariateMomentAdvection
static autoPtr< univariateMomentAdvection > New (const dictionary &dict, const scalarQuadratureApproximation &quadrature, const surfaceScalarField &phi, const word &support)
Protected Attributes inherited from univariateMomentAdvection
const word name_
Name of the distribution associated to the quadrature approximation.
const volScalarMomentFieldSet & moments_
Reference to the moments to advect.
const label nMoments_
Number of moments.
mappedPtrList< volScalarField > divMoments_
Advection terms for moment transport equations.
surfaceScalarField own_
Field used to find upwind values of the owner.
surfaceScalarField nei_
Field used to find upwind values of the neighbour.
const surfaceScalarField & phi_
Conservative advection flux.
word support_
Support of the distribution function.
label nDimensions_
Dimensions of the underlying distribution.
Detailed Description
Definition at line 60 of file zetaUnivariateAdvection.H.
Constructor & Destructor Documentation
zeta()
zeta (const dictionary & dict, const scalarQuadratureApproximation & quadrature, const surfaceScalarField & phi, const word & support)
Construct from univariateMomentSet.
Definition at line 50 of file zetaUnivariateAdvection.C.
References forAll(), phi, and quadrature.
~zeta()
~zeta () virtual
Destructor.
Definition at line 287 of file zetaUnivariateAdvection.C.
Member Function Documentation
countFacesWithOutgoingFlux()
void countFacesWithOutgoingFlux () protected
Calculates the number of cells with outgoing flux.
Definition at line 458 of file zetaUnivariateAdvection.C.
References forAll().
limiter()
void limiter () protected
Computes the limiter used for additional limitation.
interpolateFields()
void interpolateFields () protected
Reconstructs zeta_k.
Definition at line 293 of file zetaUnivariateAdvection.C.
References forAll().
limitZetas()
void limitZetas () protected
Applies additional limitation to zeta_k, if needed.
Definition at line 497 of file zetaUnivariateAdvection.C.
References forAll(), univariateMomentSet::nRealizableMoments(), and p.
TypeName()
TypeName ("zeta")
Runtime type information.
realizableCo()
Foam::scalar realizableCo () const virtual
Return the maximum Courant number ensuring moment realizability.
Implements univariateMomentAdvection.
Definition at line 762 of file zetaUnivariateAdvection.C.
update()
void update () virtual
Update moment advection.
Implements univariateMomentAdvection.
Definition at line 787 of file zetaUnivariateAdvection.C.
References forAll(), and max().
The documentation for this class was generated from the following files:
zetaUnivariateAdvection.H
zetaUnivariateAdvection.C