OpenQBMM: multivariateMomentInversion Class Reference
multivariateMomentInversion Class Reference abstract
General class for multivariate moment inversions.
Public Member Functions
TypeName ("multivariateMomentInversion")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, multivariateMomentInversion, dictionary,(const dictionary &dict, const labelListList &momentOrders, const labelListList &nodeIndexes, const labelList &velocityIndexes),(dict, momentOrders, nodeIndexes, velocityIndexes))
multivariateMomentInversion (const dictionary &dict, const labelListList &momentOrders, const labelListList &nodeIndexes, const labelList &velocityIndexes)
virtual ~multivariateMomentInversion ()
Destructor.
virtual void invert (const multivariateMomentSet &moments)=0
Invert moments to find weights and abscissae.
const mappedScalarList & weights () const
Return mapped quadrature weights for each dimension.
const mappedList< scalarList > & abscissae () const
Return mapped quadrature size abscissae for each dimension.
const mappedVectorList & velocityAbscissae () const
Return mapped quadrature velocity abscissae for each dimension.
Static Public Member Functions
static autoPtr< multivariateMomentInversion > New (const dictionary &dict, const labelListList &momentOrders, const labelListList &nodeIndexes, const labelList &velocityIndexes)
Protected Member Functions
void reset ()
Reset inverter.
Static Protected Member Functions
static bool compare (const labelList &index1, const labelList &index2)
Compare indexes up to the minimum size.
static bool compare (const labelList &index1, const labelList &index2, const label size)
Compare indexes up to dimi.
Protected Attributes
const label nDistributionDims_
Number of dimensions in distribution.
const label nvelocityDimensions_
Number of dimensions in velocity space.
const labelListList & momentOrders_
Moment orders of full distribution.
const labelListList & nodeIndexes_
Node indexes of full distribution.
labelList velocityIndexes_
List of velocity indexes.
labelList nNodes_
Number of nodes in each direction.
mappedScalarList weights_
Quadratrure weights.
mappedList< scalarList > abscissae_
Quadratrure size abscissae.
mappedVectorList velocityAbscissae_
Quadratrure velocity abscissae.
Detailed Description
General class for multivariate moment inversions.
Source files
multivariateMomentInversion.H
multivariateMomentInversion.C
multivariateMomentInversionI.H
Definition at line 56 of file multivariateMomentInversion.H.
Constructor & Destructor Documentation
multivariateMomentInversion()
multivariateMomentInversion (const dictionary & dict, const labelListList & momentOrders, const labelListList & nodeIndexes, const labelList & velocityIndexes)
Definition at line 79 of file multivariateMomentInversion.C.
References forAll(), and max().
~multivariateMomentInversion()
~multivariateMomentInversion () virtual
Destructor.
Definition at line 120 of file multivariateMomentInversion.C.
Member Function Documentation
reset()
void reset () protected
Reset inverter.
Definition at line 126 of file multivariateMomentInversion.C.
References forAll().
compare() [1/2]
bool compare (const labelList & index1, const labelList & index2) static protected
Compare indexes up to the minimum size.
Definition at line 41 of file multivariateMomentInversion.C.
compare() [2/2]
bool compare (const labelList & index1, const labelList & index2, const label size) static protected
Compare indexes up to dimi.
Definition at line 59 of file multivariateMomentInversion.C.
TypeName()
TypeName ("multivariateMomentInversion")
Runtime type information.
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , multivariateMomentInversion , dictionary , (const dictionary &dict, const labelListList &momentOrders, const labelListList &nodeIndexes, const labelList &velocityIndexes) , (dict, momentOrders, nodeIndexes, velocityIndexes))
New()
Foam::autoPtr< Foam::multivariateMomentInversion > New (const dictionary & dict, const labelListList & momentOrders, const labelListList & nodeIndexes, const labelList & velocityIndexes) static
Definition at line 28 of file newMultivariateMomentInversion.C.
References momentOrders, and velocityIndexes().
invert()
virtual void invert (const multivariateMomentSet & moments) pure virtual
Invert moments to find weights and abscissae.
Implemented in CHyQMOM, conditional, sizeCHyQMOM, TensorProduct, and monoKinetic.
weights()
const Foam::mappedScalarList & weights () const inline
Return mapped quadrature weights for each dimension.
Definition at line 30 of file multivariateMomentInversionI.H.
References multivariateMomentInversion::weights_.
abscissae()
const Foam::mappedList< Foam::scalarList > & abscissae () const inline
Return mapped quadrature size abscissae for each dimension.
Definition at line 36 of file multivariateMomentInversionI.H.
velocityAbscissae()
const Foam::mappedVectorList & velocityAbscissae () const inline
Return mapped quadrature velocity abscissae for each dimension.
Definition at line 42 of file multivariateMomentInversionI.H.
Member Data Documentation
nDistributionDims_
const label nDistributionDims_ protected
Number of dimensions in distribution.
Definition at line 62 of file multivariateMomentInversion.H.
nvelocityDimensions_
const label nvelocityDimensions_ protected
Number of dimensions in velocity space.
Definition at line 65 of file multivariateMomentInversion.H.
momentOrders_
const labelListList& momentOrders_ protected
Moment orders of full distribution.
Definition at line 68 of file multivariateMomentInversion.H.
nodeIndexes_
const labelListList& nodeIndexes_ protected
Node indexes of full distribution.
Definition at line 71 of file multivariateMomentInversion.H.
velocityIndexes_
labelList velocityIndexes_ protected
List of velocity indexes.
Definition at line 74 of file multivariateMomentInversion.H.
nNodes_
labelList nNodes_ protected
Number of nodes in each direction.
Definition at line 77 of file multivariateMomentInversion.H.
weights_
mappedScalarList weights_ protected
Quadratrure weights.
Definition at line 80 of file multivariateMomentInversion.H.
Referenced by multivariateMomentInversion::weights().
abscissae_
mappedList<scalarList> abscissae_ protected
Quadratrure size abscissae.
Definition at line 83 of file multivariateMomentInversion.H.
velocityAbscissae_
mappedVectorList velocityAbscissae_ protected
Quadratrure velocity abscissae.
Definition at line 86 of file multivariateMomentInversion.H.
The documentation for this class was generated from the following files:
multivariateMomentInversion.H
multivariateMomentInversion.C
multivariateMomentInversionI.H
newMultivariateMomentInversion.C