OpenQBMM: velocityMomentAdvection Class Reference
velocityMomentAdvection Class Reference abstract
Abstract class for the advection of a velocity moment set.
Public Member Functions
TypeName ("velocityMomentAdvection")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, velocityMomentAdvection, dictionary,(const dictionary &dict, const velocityQuadratureApproximation &quadrature, const word &support),(dict, quadrature, support))
velocityMomentAdvection (const dictionary &dict, const velocityQuadratureApproximation &quadrature, const word &support)
Construct from velocityMomentSet.
velocityMomentAdvection (const velocityMomentAdvection &)=delete
Disallow default bitwise copy construct.
virtual ~velocityMomentAdvection ()
Destructor.
const PtrList< volScalarField > & divMoments () const
Return the advection term for the moment transport equation.
virtual scalar realizableCo () const =0
Return the maximum Courant number ensuring moment realizability.
virtual scalar CoNum () const =0
Return the maximum Courant number based on velocities.
virtual void update ()=0
Update moment advection.
virtual void update (const surfaceScalarField &U, const bool wallCollisions)=0
Update moment advection using a specified velocity field.
virtual void update (const mappedPtrList< volVectorField > &Us, const bool wallCollisions)=0
Update moment advection using a specified list of velocity fields.
void operator= (const velocityMomentAdvection &)=delete
Disallow default bitwise assignment.
Static Public Member Functions
static autoPtr< velocityMomentAdvection > New (const dictionary &dict, const velocityQuadratureApproximation &quadrature, const word &support)
Protected Member Functions
void updateWallCollisions (const PtrList< volVelocityNode > &nodes, PtrList< surfaceVelocityNode > &nodesOwn, PtrList< surfaceVelocityNode > &nodesNei)
Protected member function.
Protected Attributes
const word name_
Name of the distribution associated to the quadrature approximation.
const volVelocityMomentFieldSet & moments_
Reference to the moments to advect.
const label nMoments_
Number of moments.
surfaceScalarField own_
Field used to find upwind values of the owner.
surfaceScalarField nei_
Field used to find upwind values of the neighbour.
tmp< surfaceInterpolationScheme< scalar > > weightOwnScheme_
Interpolation #include "limitedSurfaceInterpolationScheme.H"schemes.
tmp< surfaceInterpolationScheme< scalar > > weightNeiScheme_
tmp< surfaceInterpolationScheme< scalar > > scalarAbscissaeOwnScheme_
tmp< surfaceInterpolationScheme< scalar > > scalarAbscissaeNeiScheme_
tmp< surfaceInterpolationScheme< vector > > velocityAbscissaeOwnScheme_
tmp< surfaceInterpolationScheme< vector > > velocityAbscissaeNeiScheme_
word support_
Support of the distribution function.
labelListList momentOrders_
Moment indicies ues to map moments.
labelListList nodeIndexes_
Node indicies used to map nodes.
PtrList< volScalarField > divMoments_
Advection terms for moment transport equations.
wordList fixedWalls_
List of boundaries using fixed temperatures.
scalarList wallTemperatures_
List of temperatures used at walls.
scalar ew_
Coefficient of restitution.
Detailed Description
Abstract class for the advection of a velocity moment set.
Source files
velocityMomentAdvection.H
velocityMomentAdvection.C
velocityMomentAdvectionI.H
Definition at line 56 of file velocityMomentAdvection.H.
Constructor & Destructor Documentation
velocityMomentAdvection() [1/2]
velocityMomentAdvection (const dictionary & dict, const velocityQuadratureApproximation & quadrature, const word & support)
Construct from velocityMomentSet.
Definition at line 41 of file velocityMomentAdvection.C.
References forAll().
velocityMomentAdvection() [2/2]
velocityMomentAdvection (const velocityMomentAdvection &) delete
Disallow default bitwise copy construct.
~velocityMomentAdvection()
~velocityMomentAdvection () virtual
Destructor.
Definition at line 133 of file velocityMomentAdvection.C.
Member Function Documentation
updateWallCollisions()
void updateWallCollisions (const PtrList< volVelocityNode > & nodes, PtrList< surfaceVelocityNode > & nodesOwn, PtrList< surfaceVelocityNode > & nodesNei) protected
Protected member function.
Update fluxes due to wall callisions
Definition at line 140 of file velocityMomentAdvection.C.
References forAll(), max(), nodes, quadratureNode< scalarType, vectorType >::primaryWeight(), U(), and velocityQuadratureNode< scalarType, vectorType >::velocityAbscissae().
TypeName()
TypeName ("velocityMomentAdvection")
Runtime type information.
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , velocityMomentAdvection , dictionary , (const dictionary &dict, const velocityQuadratureApproximation &quadrature, const word &support) , (dict, quadrature, support))
New()
Foam::autoPtr< Foam::velocityMomentAdvection > New (const dictionary & dict, const velocityQuadratureApproximation & quadrature, const word & support) static
Definition at line 32 of file newVelocityMomentAdvection.C.
References quadrature.
divMoments()
const Foam::PtrList< Foam::volScalarField > & divMoments () const inline
Return the advection term for the moment transport equation.
Definition at line 29 of file velocityMomentAdvectionI.H.
References velocityMomentAdvection::divMoments_.
realizableCo()
virtual scalar realizableCo () const pure virtual
Return the maximum Courant number ensuring moment realizability.
Implemented in firstOrderKinetic, VikasQuasiSecondOrder, and noAdvection.
CoNum()
virtual scalar CoNum () const pure virtual
Return the maximum Courant number based on velocities.
Implemented in firstOrderKinetic, and noAdvection.
update() [1/3]
virtual void update () pure virtual
Update moment advection.
Implemented in firstOrderKinetic, and noAdvection.
update() [2/3]
virtual void update (const surfaceScalarField & U, const bool wallCollisions) pure virtual
Update moment advection using a specified velocity field.
Implemented in firstOrderKinetic, and noAdvection.
update() [3/3]
virtual void update (const mappedPtrList< volVectorField > & Us, const bool wallCollisions) pure virtual
Update moment advection using a specified list of velocity fields.
Implemented in firstOrderKinetic, and noAdvection.
operator=()
void operator= (const velocityMomentAdvection &) delete
Disallow default bitwise assignment.
Member Data Documentation
name_
const word name_ protected
Name of the distribution associated to the quadrature approximation.
Definition at line 63 of file velocityMomentAdvection.H.
moments_
const volVelocityMomentFieldSet& moments_ protected
Reference to the moments to advect.
Definition at line 66 of file velocityMomentAdvection.H.
nMoments_
const label nMoments_ protected
Number of moments.
Definition at line 69 of file velocityMomentAdvection.H.
own_
surfaceScalarField own_ protected
Field used to find upwind values of the owner.
Definition at line 72 of file velocityMomentAdvection.H.
nei_
surfaceScalarField nei_ protected
Field used to find upwind values of the neighbour.
Definition at line 75 of file velocityMomentAdvection.H.
weightOwnScheme_
tmp<surfaceInterpolationScheme<scalar> > weightOwnScheme_ protected
Interpolation #include "limitedSurfaceInterpolationScheme.H"schemes.
used to interpolated the quadrature
Definition at line 79 of file velocityMomentAdvection.H.
weightNeiScheme_
tmp<surfaceInterpolationScheme<scalar> > weightNeiScheme_ protected
Definition at line 80 of file velocityMomentAdvection.H.
scalarAbscissaeOwnScheme_
tmp<surfaceInterpolationScheme<scalar> > scalarAbscissaeOwnScheme_ protected
Definition at line 81 of file velocityMomentAdvection.H.
scalarAbscissaeNeiScheme_
tmp<surfaceInterpolationScheme<scalar> > scalarAbscissaeNeiScheme_ protected
Definition at line 82 of file velocityMomentAdvection.H.
velocityAbscissaeOwnScheme_
tmp<surfaceInterpolationScheme<vector> > velocityAbscissaeOwnScheme_ protected
Definition at line 83 of file velocityMomentAdvection.H.
velocityAbscissaeNeiScheme_
tmp<surfaceInterpolationScheme<vector> > velocityAbscissaeNeiScheme_ protected
Definition at line 84 of file velocityMomentAdvection.H.
support_
word support_ protected
Support of the distribution function.
Definition at line 87 of file velocityMomentAdvection.H.
momentOrders_
labelListList momentOrders_ protected
Moment indicies ues to map moments.
Definition at line 90 of file velocityMomentAdvection.H.
nodeIndexes_
labelListList nodeIndexes_ protected
Node indicies used to map nodes.
Definition at line 93 of file velocityMomentAdvection.H.
divMoments_
PtrList<volScalarField> divMoments_ protected
Advection terms for moment transport equations.
Definition at line 96 of file velocityMomentAdvection.H.
Referenced by velocityMomentAdvection::divMoments().
fixedWalls_
wordList fixedWalls_ protected
List of boundaries using fixed temperatures.
Definition at line 99 of file velocityMomentAdvection.H.
wallTemperatures_
scalarList wallTemperatures_ protected
List of temperatures used at walls.
Definition at line 102 of file velocityMomentAdvection.H.
ew_
scalar ew_ protected
Coefficient of restitution.
Definition at line 105 of file velocityMomentAdvection.H.
The documentation for this class was generated from the following files:
velocityMomentAdvection.H
newVelocityMomentAdvection.C
velocityMomentAdvection.C
velocityMomentAdvectionI.H