OpenQBMM: conditional Class Reference
conditional Class Reference
Implementation of the conditional quadrature method of moments.
Public Member Functions
TypeName ("conditional")
Runtime type information.
conditional (const dictionary &dict, const labelListList &momentOrders, const labelListList &nodeIndexes, const labelList &velocityIndexes)
virtual ~conditional ()
Destructor.
void invert (const multivariateMomentSet &moments)
Invert moments to find weights and abscissae.
Public Member Functions inherited from multivariateMomentInversion
TypeName ("multivariateMomentInversion")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, multivariateMomentInversion, dictionary,(const dictionary &dict, const labelListList &momentOrders, const labelListList &nodeIndexes, const labelList &velocityIndexes),(dict, momentOrders, nodeIndexes, velocityIndexes))
multivariateMomentInversion (const dictionary &dict, const labelListList &momentOrders, const labelListList &nodeIndexes, const labelList &velocityIndexes)
virtual ~multivariateMomentInversion ()
Destructor.
const mappedScalarList & weights () const
Return mapped quadrature weights for each dimension.
const mappedList< scalarList > & abscissae () const
Return mapped quadrature size abscissae for each dimension.
const mappedVectorList & velocityAbscissae () const
Return mapped quadrature velocity abscissae for each dimension.
Additional Inherited Members
Static Public Member Functions inherited from multivariateMomentInversion
static autoPtr< multivariateMomentInversion > New (const dictionary &dict, const labelListList &momentOrders, const labelListList &nodeIndexes, const labelList &velocityIndexes)
Protected Member Functions inherited from multivariateMomentInversion
void reset ()
Reset inverter.
Static Protected Member Functions inherited from multivariateMomentInversion
static bool compare (const labelList &index1, const labelList &index2)
Compare indexes up to the minimum size.
static bool compare (const labelList &index1, const labelList &index2, const label size)
Compare indexes up to dimi.
Protected Attributes inherited from multivariateMomentInversion
const label nDistributionDims_
Number of dimensions in distribution.
const label nvelocityDimensions_
Number of dimensions in velocity space.
const labelListList & momentOrders_
Moment orders of full distribution.
const labelListList & nodeIndexes_
Node indexes of full distribution.
labelList velocityIndexes_
List of velocity indexes.
labelList nNodes_
Number of nodes in each direction.
mappedScalarList weights_
Quadratrure weights.
mappedList< scalarList > abscissae_
Quadratrure size abscissae.
mappedVectorList velocityAbscissae_
Quadratrure velocity abscissae.
Detailed Description
Implementation of the conditional quadrature method of moments.
References
    "Conditional quadrature method of moments for kinetic equations"
    C Yuan, R O Fox
    Journal of Computational Physics
    Volume 230, Pages 8216-8246, 2011
Source files
conditionalMomentInversion.H
conditionalMomentInversion.C
Definition at line 67 of file conditionalMomentInversion.H.
Constructor & Destructor Documentation
conditional()
conditional (const dictionary & dict, const labelListList & momentOrders, const labelListList & nodeIndexes, const labelList & velocityIndexes)
Definition at line 49 of file conditionalMomentInversion.C.
References forAll(), and max().
~conditional()
~conditional () virtual
Destructor.
Definition at line 166 of file conditionalMomentInversion.C.
Member Function Documentation
TypeName()
TypeName ("conditional")
Runtime type information.
invert()
void invert (const multivariateMomentSet & moments) virtual
Invert moments to find weights and abscissae.
Set invVR matrices
Implements multivariateMomentInversion.
Definition at line 173 of file conditionalMomentInversion.C.
References forAll(), and moments.
The documentation for this class was generated from the following files:
conditionalMomentInversion.H
conditionalMomentInversion.C