OpenQBMM: firstOrderKinetic Class Reference
firstOrderKinetic Class Reference
Public Member Functions
TypeName ("firstOrderKinetic")
Runtime type information.
firstOrderKinetic (const dictionary &dict, const scalarQuadratureApproximation &quadrature, const surfaceScalarField &phi, const word &support)
Construct from univariateMomentSet.
virtual ~firstOrderKinetic ()
Destructor.
virtual scalar realizableCo () const
Return the maximum Courant number ensuring moment realizability.
virtual void update ()
Update moment advection.
Public Member Functions inherited from univariateMomentAdvection
TypeName ("univariateMomentAdvection")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, univariateMomentAdvection, dictionary,(const dictionary &dict, const scalarQuadratureApproximation &quadrature, const surfaceScalarField &phi, const word &support),(dict, quadrature, phi, support))
univariateMomentAdvection (const dictionary &dict, const scalarQuadratureApproximation &quadrature, const surfaceScalarField &phi, const word &support)
Construct from univariateMomentSet.
univariateMomentAdvection (const univariateMomentAdvection &)=delete
Disallow default bitwise copy construct.
virtual ~univariateMomentAdvection ()
Destructor.
const mappedPtrList< volScalarField > & divMoments () const
Return the advection term for the moment transport equation.
void operator= (const univariateMomentAdvection &)=delete
Disallow default bitwise assignment.
Protected Member Functions
void interpolateNodes ()
Protected member functions.
Protected Member Functions inherited from univariateMomentAdvection
word fieldName (const word &name, const labelList &order) const
Construct field name from name, order.
Additional Inherited Members
Static Public Member Functions inherited from univariateMomentAdvection
static autoPtr< univariateMomentAdvection > New (const dictionary &dict, const scalarQuadratureApproximation &quadrature, const surfaceScalarField &phi, const word &support)
Protected Attributes inherited from univariateMomentAdvection
const word name_
Name of the distribution associated to the quadrature approximation.
const volScalarMomentFieldSet & moments_
Reference to the moments to advect.
const label nMoments_
Number of moments.
mappedPtrList< volScalarField > divMoments_
Advection terms for moment transport equations.
surfaceScalarField own_
Field used to find upwind values of the owner.
surfaceScalarField nei_
Field used to find upwind values of the neighbour.
const surfaceScalarField & phi_
Conservative advection flux.
word support_
Support of the distribution function.
label nDimensions_
Dimensions of the underlying distribution.
Detailed Description
Definition at line 51 of file firstOrderKineticUnivariateAdvection.H.
Constructor & Destructor Documentation
firstOrderKinetic()
firstOrderKinetic (const dictionary & dict, const scalarQuadratureApproximation & quadrature, const surfaceScalarField & phi, const word & support)
Construct from univariateMomentSet.
Definition at line 49 of file firstOrderKineticUnivariateAdvection.C.
References forAll(), nodes, quadrature, and mappedPtrList< mappedType >::set().
~firstOrderKinetic()
~firstOrderKinetic () virtual
Destructor.
Definition at line 199 of file firstOrderKineticUnivariateAdvection.C.
Member Function Documentation
interpolateNodes()
void interpolateNodes () protected
Protected member functions.
Definition at line 205 of file firstOrderKineticUnivariateAdvection.C.
References forAll(), nodes, quadratureNode< scalarType, vectorType >::primaryAbscissae(), and quadratureNode< scalarType, vectorType >::primaryWeight().
TypeName()
TypeName ("firstOrderKinetic")
Runtime type information.
realizableCo()
Foam::scalar realizableCo () const virtual
Return the maximum Courant number ensuring moment realizability.
Implements univariateMomentAdvection.
Definition at line 261 of file firstOrderKineticUnivariateAdvection.C.
update()
void update () virtual
Update moment advection.
Implements univariateMomentAdvection.
Definition at line 268 of file firstOrderKineticUnivariateAdvection.C.
References forAll(), and max().
The documentation for this class was generated from the following files:
firstOrderKineticUnivariateAdvection.H
firstOrderKineticUnivariateAdvection.C