OpenQBMM: TensorProduct Class Reference
TensorProduct Class Reference
Tensor product moment inversion for multidimensional moment sets.
Public Member Functions
TypeName ("TensorProduct")
Runtime type information.
TensorProduct (const dictionary &dict, const labelListList &momentOrders, const labelListList &nodeIndexes, const labelList &velocityIndexes)
virtual ~TensorProduct ()
Destructor.
virtual void invert (const multivariateMomentSet &moments)
Invert moments to find weights and abscissae.
Public Member Functions inherited from multivariateMomentInversion
TypeName ("multivariateMomentInversion")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, multivariateMomentInversion, dictionary,(const dictionary &dict, const labelListList &momentOrders, const labelListList &nodeIndexes, const labelList &velocityIndexes),(dict, momentOrders, nodeIndexes, velocityIndexes))
multivariateMomentInversion (const dictionary &dict, const labelListList &momentOrders, const labelListList &nodeIndexes, const labelList &velocityIndexes)
virtual ~multivariateMomentInversion ()
Destructor.
const mappedScalarList & weights () const
Return mapped quadrature weights for each dimension.
const mappedList< scalarList > & abscissae () const
Return mapped quadrature size abscissae for each dimension.
const mappedVectorList & velocityAbscissae () const
Return mapped quadrature velocity abscissae for each dimension.
Additional Inherited Members
Static Public Member Functions inherited from multivariateMomentInversion
static autoPtr< multivariateMomentInversion > New (const dictionary &dict, const labelListList &momentOrders, const labelListList &nodeIndexes, const labelList &velocityIndexes)
Protected Member Functions inherited from multivariateMomentInversion
void reset ()
Reset inverter.
Static Protected Member Functions inherited from multivariateMomentInversion
static bool compare (const labelList &index1, const labelList &index2)
Compare indexes up to the minimum size.
static bool compare (const labelList &index1, const labelList &index2, const label size)
Compare indexes up to dimi.
Protected Attributes inherited from multivariateMomentInversion
const label nDistributionDims_
Number of dimensions in distribution.
const label nvelocityDimensions_
Number of dimensions in velocity space.
const labelListList & momentOrders_
Moment orders of full distribution.
const labelListList & nodeIndexes_
Node indexes of full distribution.
labelList velocityIndexes_
List of velocity indexes.
labelList nNodes_
Number of nodes in each direction.
mappedScalarList weights_
Quadratrure weights.
mappedList< scalarList > abscissae_
Quadratrure size abscissae.
mappedVectorList velocityAbscissae_
Quadratrure velocity abscissae.
Detailed Description
Tensor product moment inversion for multidimensional moment sets.
Source files
TensorProductMomentInversion.H
TensorProductMomentInversion.C
Definition at line 59 of file TensorProductMomentInversion.H.
Constructor & Destructor Documentation
TensorProduct()
TensorProduct (const dictionary & dict, const labelListList & momentOrders, const labelListList & nodeIndexes, const labelList & velocityIndexes)
Definition at line 73 of file TensorProductMomentInversion.C.
References forAll(), max(), and univariateMomentInversion::New().
~TensorProduct()
~TensorProduct () virtual
Destructor.
Definition at line 119 of file TensorProductMomentInversion.C.
Member Function Documentation
TypeName()
TypeName ("TensorProduct")
Runtime type information.
invert()
void invert (const multivariateMomentSet & moments) virtual
Invert moments to find weights and abscissae.
Implements multivariateMomentInversion.
Definition at line 126 of file TensorProductMomentInversion.C.
References forAll(), max(), moments, and solve().
The documentation for this class was generated from the following files:
TensorProductMomentInversion.H
TensorProductMomentInversion.C