OpenQBMM: firstOrderKinetic Class Reference
firstOrderKinetic Class Reference
Public Member Functions
TypeName ("firstOrderKinetic")
Runtime type information.
firstOrderKinetic (const dictionary &dict, const velocityQuadratureApproximation &quadrature, const word &support)
Construct from velocityMomentSet.
virtual ~firstOrderKinetic ()
Destructor.
virtual scalar realizableCo () const
Return the maximum Courant number ensuring moment realizability.
virtual scalar CoNum () const
Return the maximum Courant number based on velocities.
virtual void update ()
Update moment advection.
virtual void update (const surfaceScalarField &U, const bool wallCollisions)
Update moment advection using a specified velocity field.
virtual void update (const mappedPtrList< volVectorField > &Us, const bool wallCollisions)
Update moment advection using a specified list of velocity fields.
Public Member Functions inherited from velocityMomentAdvection
TypeName ("velocityMomentAdvection")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, velocityMomentAdvection, dictionary,(const dictionary &dict, const velocityQuadratureApproximation &quadrature, const word &support),(dict, quadrature, support))
velocityMomentAdvection (const dictionary &dict, const velocityQuadratureApproximation &quadrature, const word &support)
Construct from velocityMomentSet.
velocityMomentAdvection (const velocityMomentAdvection &)=delete
Disallow default bitwise copy construct.
virtual ~velocityMomentAdvection ()
Destructor.
const PtrList< volScalarField > & divMoments () const
Return the advection term for the moment transport equation.
void operator= (const velocityMomentAdvection &)=delete
Disallow default bitwise assignment.
Protected Member Functions
void interpolateNodes ()
Flux moment inversion method.
Protected Member Functions inherited from velocityMomentAdvection
void updateWallCollisions (const PtrList< volVelocityNode > &nodes, PtrList< surfaceVelocityNode > &nodesOwn, PtrList< surfaceVelocityNode > &nodesNei)
Protected member function.
Protected Attributes
const PtrList< volVelocityNode > & nodes_
List of quadrature nodes used for moment advection.
autoPtr< PtrList< surfaceVelocityNode > > nodesNei_
List of interpolated nodes (neighbour)
autoPtr< PtrList< surfaceVelocityNode > > nodesOwn_
List of interpolated nodes (owner)
word weightScheme_
Interpolation schemes.
word scalarAbscissaeScheme_
word velocityAbscissaeScheme_
Protected Attributes inherited from velocityMomentAdvection
const word name_
Name of the distribution associated to the quadrature approximation.
const volVelocityMomentFieldSet & moments_
Reference to the moments to advect.
const label nMoments_
Number of moments.
surfaceScalarField own_
Field used to find upwind values of the owner.
surfaceScalarField nei_
Field used to find upwind values of the neighbour.
tmp< surfaceInterpolationScheme< scalar > > weightOwnScheme_
Interpolation #include "limitedSurfaceInterpolationScheme.H"schemes.
tmp< surfaceInterpolationScheme< scalar > > weightNeiScheme_
tmp< surfaceInterpolationScheme< scalar > > scalarAbscissaeOwnScheme_
tmp< surfaceInterpolationScheme< scalar > > scalarAbscissaeNeiScheme_
tmp< surfaceInterpolationScheme< vector > > velocityAbscissaeOwnScheme_
tmp< surfaceInterpolationScheme< vector > > velocityAbscissaeNeiScheme_
word support_
Support of the distribution function.
labelListList momentOrders_
Moment indicies ues to map moments.
labelListList nodeIndexes_
Node indicies used to map nodes.
PtrList< volScalarField > divMoments_
Advection terms for moment transport equations.
wordList fixedWalls_
List of boundaries using fixed temperatures.
scalarList wallTemperatures_
List of temperatures used at walls.
scalar ew_
Coefficient of restitution.
Additional Inherited Members
Static Public Member Functions inherited from velocityMomentAdvection
static autoPtr< velocityMomentAdvection > New (const dictionary &dict, const velocityQuadratureApproximation &quadrature, const word &support)
Detailed Description
Definition at line 51 of file firstOrderKineticVelocityAdvection.H.
Constructor & Destructor Documentation
firstOrderKinetic()
firstOrderKinetic (const dictionary & dict, const velocityQuadratureApproximation & quadrature, const word & support)
Construct from velocityMomentSet.
Definition at line 49 of file firstOrderKineticVelocityAdvection.C.
References forAll().
~firstOrderKinetic()
~firstOrderKinetic () virtual
Destructor.
Definition at line 131 of file firstOrderKineticVelocityAdvection.C.
Member Function Documentation
interpolateNodes()
void interpolateNodes () protected
Flux moment inversion method.
autoPtr<hyperbolicFieldMomentInversion> momentFieldInverter_;
Definition at line 137 of file firstOrderKineticVelocityAdvection.C.
References forAll(), quadratureNode< scalarType, vectorType >::primaryAbscissae(), quadratureNode< scalarType, vectorType >::primaryWeight(), and velocityQuadratureNode< scalarType, vectorType >::velocityAbscissae().
TypeName()
TypeName ("firstOrderKinetic")
Runtime type information.
realizableCo()
Foam::scalar realizableCo () const virtual
Return the maximum Courant number ensuring moment realizability.
Implements velocityMomentAdvection.
Reimplemented in VikasQuasiSecondOrder.
Definition at line 224 of file firstOrderKineticVelocityAdvection.C.
References forAll(), and max().
CoNum()
Foam::scalar CoNum () const virtual
Return the maximum Courant number based on velocities.
Implements velocityMomentAdvection.
Definition at line 274 of file firstOrderKineticVelocityAdvection.C.
References CoNum, forAll(), and max().
update() [1/3]
void update () virtual
Update moment advection.
Implements velocityMomentAdvection.
Definition at line 296 of file firstOrderKineticVelocityAdvection.C.
References forAll(), max(), quadratureNode< scalarType, vectorType >::primaryAbscissae(), quadratureNode< scalarType, vectorType >::primaryWeight(), velocityQuadratureNode< scalarType, vectorType >::velocityAbscissae(), and velocityIndexes().
update() [2/3]
void update (const surfaceScalarField & U, const bool wallCollisions) virtual
Update moment advection using a specified velocity field.
Implements velocityMomentAdvection.
Definition at line 427 of file firstOrderKineticVelocityAdvection.C.
References forAll(), max(), phi, quadratureNode< scalarType, vectorType >::primaryAbscissae(), quadratureNode< scalarType, vectorType >::primaryWeight(), velocityQuadratureNode< scalarType, vectorType >::velocityAbscissae(), and velocityIndexes().
update() [3/3]
void update (const mappedPtrList< volVectorField > & Us, const bool wallCollisions) virtual
Update moment advection using a specified list of velocity fields.
Implements velocityMomentAdvection.
Definition at line 560 of file firstOrderKineticVelocityAdvection.C.
References forAll(), max(), quadratureNode< scalarType, vectorType >::primaryAbscissae(), quadratureNode< scalarType, vectorType >::primaryWeight(), velocityQuadratureNode< scalarType, vectorType >::velocityAbscissae(), and velocityIndexes().
Member Data Documentation
nodes_
const PtrList<volVelocityNode>& nodes_ protected
List of quadrature nodes used for moment advection.
Definition at line 59 of file firstOrderKineticVelocityAdvection.H.
nodesNei_
autoPtr<PtrList<surfaceVelocityNode> > nodesNei_ protected
List of interpolated nodes (neighbour)
Definition at line 62 of file firstOrderKineticVelocityAdvection.H.
nodesOwn_
autoPtr<PtrList<surfaceVelocityNode> > nodesOwn_ protected
List of interpolated nodes (owner)
Definition at line 65 of file firstOrderKineticVelocityAdvection.H.
weightScheme_
word weightScheme_ protected
Interpolation schemes.
Definition at line 68 of file firstOrderKineticVelocityAdvection.H.
scalarAbscissaeScheme_
word scalarAbscissaeScheme_ protected
Definition at line 69 of file firstOrderKineticVelocityAdvection.H.
velocityAbscissaeScheme_
word velocityAbscissaeScheme_ protected
Definition at line 70 of file firstOrderKineticVelocityAdvection.H.
The documentation for this class was generated from the following files:
firstOrderKineticVelocityAdvection.H
firstOrderKineticVelocityAdvection.C