OpenQBMM: univariateMomentSet Class Reference
univariateMomentSet Class Reference
Stores a generic moment set with the corresponding list of orders.
Public Member Functions
univariateMomentSet (const label nMoments, const word &support, const scalar initValue=0, const label nFixedQuadraturePoints=0)
Construct from number of moments and initial value.
univariateMomentSet (const scalarList &m, const word &support, const label nFixedQuadraturePoints=0)
Construct from scalarList.
virtual ~univariateMomentSet ()
Destructor.
const scalarList & alphaRecurrence () const
Returns alpha coefficients of the recurrence relation.
scalarList & alphaRecurrence ()
Returns alpha coefficients of the recurrence relation.
const scalarList & betaRecurrence () const
Returns beta coefficients of the recurrence relation.
scalarList & betaRecurrence ()
Returns beta coefficients of the recurrence relation.
scalarList & zetas ()
Returns zeta_k values for the moment set.
bool isDegenerate ()
Returns degenerate status of the moment set.
bool isFullyRealizable (bool fatalErrorOnFailedRealizabilityTest=true)
Return true if the entire moment set is realizable.
bool isRealizable (bool fatalErrorOnFailedRealizabilityTest=true)
Return true if some moments are realizable.
bool isSubsetRealizable (bool fatalErrorOnFailedRealizabilityTest=true)
Return true if a subset of moments is realizable.
bool isOnMomentSpaceBoundary (bool fatalErrorOnFailedRealizabilityTest=true)
Return true if the moment set is on the boundary of the moment space.
labelListList makeUnivariateMomentOrders (const label nMoments)
label nRealizableMoments (bool fatalErrorOnFailedRealizabilityTest=true)
Return the number of realizable moments.
label negativeZeta ()
virtual void update (const scalarList &weights, const scalarList &abscissae)
Update moments from the corresponding quadrature.
const scalar & operator[] (const label index) const
Const access to element.
scalar & operator[] (const label index)
Non-const access to element, reinitializing realizaibility check.
const scalar & operator() (const label momentOrder) const
Const access to the moment of order momentOrder.
scalar & operator() (const label momentOrder)
Non-const access to the moment of order momentOrder.
void resize (const label newSize)
Resizes moment set.
void setSize (const label newSize)
Set size of moment set.
Public Member Functions inherited from momentSet
momentSet (const label nMoments, const label nDimensions, const labelListList &momentOrders, const word &support, const scalar initValue=0)
Construct from number of moments and initial value.
momentSet (const scalarList &m, const label nDimensions, const labelListList &momentOrders, const word &support)
Construct from scalarList.
virtual ~momentSet ()
Destructor.
const labelListList & momentOrders () const
Return moment orders.
label nDimensions () const
Return the number of dimensions of the NDF.
label nMoments () const
Return the number of moments.
void resize (const label newSize)
Resizes moment set.
void setSize (const label newSize)
Set size of moment set.
const word support () const
Return support.
Public Member Functions inherited from mappedList< scalar >
mappedList (const label size, const labelListList &indexes)
Construct from size and labelListList.
mappedList (const label size, const labelListList &indexes, const scalar &initValue)
Construct from size and labelListList with initial value for.
mappedList (const label size, const Map< label > &map, const scalar &initValue)
Construct from size and map with initial value for all elements.
mappedList (const List< scalar > &initList, const labelListList &indexes)
Construct from List<mappedType> and labelListList.
~mappedList ()
Destructor.
void resize (const label newSize)
Resize mapped list.
void setSize (const label newSize)
Set mapped list size.
bool found (const labelList &l) const
Is label list index used.
bool found (ArgsT ...args) const
Is label list index used.
bool found (ArgsT...args) const
scalar & operator() (ArgsT ...args)
Non-const access to a moment given the list of orders.
const scalar & operator() (ArgsT ...args) const
Const access to a moment given the list of orders.
const scalar & operator() (const labelList &l) const
Constant access given a label list.
scalar & operator() (const labelList &l)
Non-constant access given a label list.
const scalar & operator() (const Foam::labelList &l) const
scalar & operator() (const Foam::labelList &l)
const Map< label > & map () const
Returns const access to the moment map.
Protected Attributes
bool realizabilityChecked_
Bool to indicate moment realizability was checked.
Protected Attributes inherited from momentSet
label nMoments_
Number of moments.
label nDimensions_
Number of dimensions of the the NDF associated to the moment set.
labelListList momentOrders_
List of moment orders.
word support_
Type of support of the measure associated to the moment set.
Additional Inherited Members
Static Public Member Functions inherited from mappedList< scalar >
static word listToWord (const labelList &lst)
Convert a list of labels to a word. {1, 2, 3} -> 123.
static label listToLabel (const labelList &lst, const label nDims=0)
Convert a list of labels to a single label. {0, 2, 3} -> 23.
Detailed Description
Stores a generic moment set with the corresponding list of orders.
Source files
univariateMomentSet.H
univariateMomentSet.C
univariateMomentSet.H
Definition at line 50 of file univariateMomentSet.H.
Constructor & Destructor Documentation
univariateMomentSet() [1/2]
univariateMomentSet (const label nMoments, const word & support, const scalar initValue = 0, const label nFixedQuadraturePoints = 0)
Construct from number of moments and initial value.
Definition at line 31 of file univariateMomentSet.C.
univariateMomentSet() [2/2]
univariateMomentSet (const scalarList & m, const word & support, const label nFixedQuadraturePoints = 0)
Construct from scalarList.
Definition at line 81 of file univariateMomentSet.C.
~univariateMomentSet()
~univariateMomentSet () virtual
Destructor.
Definition at line 130 of file univariateMomentSet.C.
Member Function Documentation
alphaRecurrence() [1/2]
const Foam::scalarList & alphaRecurrence () const inline
Returns alpha coefficients of the recurrence relation.
Definition at line 29 of file univariateMomentSetI.H.
alphaRecurrence() [2/2]
Foam::scalarList & alphaRecurrence () inline
Returns alpha coefficients of the recurrence relation.
Definition at line 34 of file univariateMomentSetI.H.
betaRecurrence() [1/2]
const Foam::scalarList & betaRecurrence () const inline
Returns beta coefficients of the recurrence relation.
Definition at line 39 of file univariateMomentSetI.H.
betaRecurrence() [2/2]
Foam::scalarList & betaRecurrence () inline
Returns beta coefficients of the recurrence relation.
Definition at line 44 of file univariateMomentSetI.H.
zetas()
Foam::scalarList & zetas () inline
Returns zeta_k values for the moment set.
Definition at line 59 of file univariateMomentSetI.H.
isDegenerate()
bool isDegenerate () inline
Returns degenerate status of the moment set.
Definition at line 69 of file univariateMomentSetI.H.
isFullyRealizable()
bool isFullyRealizable (bool fatalErrorOnFailedRealizabilityTest = true) inline
Return true if the entire moment set is realizable.
Definition at line 89 of file univariateMomentSetI.H.
isRealizable()
bool isRealizable (bool fatalErrorOnFailedRealizabilityTest = true) inline
Return true if some moments are realizable.
Definition at line 102 of file univariateMomentSetI.H.
isSubsetRealizable()
bool isSubsetRealizable (bool fatalErrorOnFailedRealizabilityTest = true) inline
Return true if a subset of moments is realizable.
Definition at line 117 of file univariateMomentSetI.H.
isOnMomentSpaceBoundary()
bool isOnMomentSpaceBoundary (bool fatalErrorOnFailedRealizabilityTest = true) inline
Return true if the moment set is on the boundary of the moment space.
Definition at line 130 of file univariateMomentSetI.H.
Referenced by extendedMomentInversion::invert().
makeUnivariateMomentOrders()
Foam::labelListList makeUnivariateMomentOrders (const label nMoments) inline
Definition at line 689 of file univariateMomentSet.C.
nRealizableMoments()
Foam::label nRealizableMoments (bool fatalErrorOnFailedRealizabilityTest = true) inline
Return the number of realizable moments.
Definition at line 143 of file univariateMomentSetI.H.
Referenced by extendedMomentInversion::invert(), zeta::limitZetas(), betaEQMOM::m2N(), gammaEQMOM::m2N(), and lognormalEQMOM::m2N().
negativeZeta()
Foam::label negativeZeta () inline
Definition at line 49 of file univariateMomentSetI.H.
update()
void update (const scalarList & weights, const scalarList & abscissae) virtual
Update moments from the corresponding quadrature.
Definition at line 704 of file univariateMomentSet.C.
operator[]() [1/2]
const Foam::scalar & operator[] (const label index) const inline
Const access to element.
Definition at line 167 of file univariateMomentSetI.H.
operator[]() [2/2]
Foam::scalar & operator[] (const label index) inline
Non-const access to element, reinitializing realizaibility check.
Definition at line 155 of file univariateMomentSetI.H.
operator()() [1/2]
const Foam::scalar & operator() (const label momentOrder) const inline
Const access to the moment of order momentOrder.
Definition at line 173 of file univariateMomentSetI.H.
operator()() [2/2]
Foam::scalar & operator() (const label momentOrder) inline
Non-const access to the moment of order momentOrder.
Definition at line 178 of file univariateMomentSetI.H.
resize()
void resize (const label newSize)
Resizes moment set.
Definition at line 736 of file univariateMomentSet.C.
Referenced by extendedMomentInversion::invert().
setSize()
void setSize (const label newSize)
Set size of moment set.
Definition at line 724 of file univariateMomentSet.C.
References momentSet::setSize().
Member Data Documentation
realizabilityChecked_
bool realizabilityChecked_ protected
Bool to indicate moment realizability was checked.
Definition at line 107 of file univariateMomentSet.H.
The documentation for this class was generated from the following files:
univariateMomentSet.H
univariateMomentSet.C
univariateMomentSetI.H