OpenQBMM: moment< fieldType, nodeType > Class Template Reference
moment< fieldType, nodeType > Class Template Reference
Stores a moment of a distribution function with arbitrary dimensionality.
Classes
class iNew
Return a pointer to a new moment created on freestore.
Public Member Functions
moment (const word &distributionName, const labelList &cmptOrders, const fvMesh &mesh, const autoPtr< mappedPtrList< nodeType >> &nodes)
Construct from a list of orders of each dimension of the moment.
moment (const word &distributionName, const labelList &cmptOrders, const autoPtr< mappedPtrList< nodeType >> &nodes, const fieldType &initMoment, const word momentSetName=word::null)
Construct from name, orders, and quadrature nodes.
autoPtr< moment > clone () const
Return clone.
~moment ()
Destructor.
word momentName (const word &momentSetName, const word &order, const word &distributionName)
Creates the name of the moment.
const word & name () const
Return the name of the moment.
const word & keyword () const
Return the name of the moment.
label nDimensions () const
Return the dimensionality of the distribution.
label order () const
Return the overall order of the moment.
const labelList & cmptOrders () const
Return the order of each dimension.
void update ()
Update the moment from the quadrature nodes.
void updateBoundaries ()
Update the moment from the quadrature nodes.
void updateLocalMoment (label elemi)
Update the moment from the quadrature nodes in a single element.
Static Public Member Functions
static word listToWord (const labelList &lst)
Convert a list of labels to a word. {1, 2, 3} -> 123.
static label listToLabel (const labelList &lst)
Convert a list of labels to a single label. {0, 2, 3} -> 23.
Detailed Description
template<class fieldType, class nodeType>
class Foam::moment< fieldType, nodeType >
Stores a moment of a distribution function with arbitrary dimensionality.
Source files
moment.H
momentI.H
moment.C
Definition at line 65 of file moment.H.
Constructor & Destructor Documentation
moment() [1/2]
moment (const word & distributionName, const labelList & cmptOrders, const fvMesh & mesh, const autoPtr< mappedPtrList< nodeType >> & nodes)
Construct from a list of orders of each dimension of the moment.
and the quadrature nodes
Definition at line 75 of file moment.C.
moment() [2/2]
moment (const word & distributionName, const labelList & cmptOrders, const autoPtr< mappedPtrList< nodeType >> & nodes, const fieldType & initMoment, const word momentSetName = word::null)
Construct from name, orders, and quadrature nodes.
Definition at line 104 of file moment.C.
~moment()
~moment ()
Destructor.
Definition at line 142 of file moment.C.
Member Function Documentation
listToWord()
Foam::word listToWord (const labelList & lst) static
Convert a list of labels to a word. {1, 2, 3} -> 123.
Definition at line 44 of file moment.C.
References forAll().
listToLabel()
Foam::label listToLabel (const labelList & lst) static
Convert a list of labels to a single label. {0, 2, 3} -> 23.
Definition at line 58 of file moment.C.
References forAll().
clone()
Foam::autoPtr< Foam::moment< fieldType, nodeType > > clone () const
Return clone.
Definition at line 150 of file moment.C.
momentName()
word momentName (const word & momentSetName, const word & order, const word & distributionName) inline
Creates the name of the moment.
Definition at line 170 of file moment.H.
References moment< fieldType, nodeType >::order().
name()
const Foam::word & name () const inline
Return the name of the moment.
Definition at line 35 of file momentI.H.
keyword()
const Foam::word & keyword () const inline
Return the name of the moment.
Definition at line 41 of file momentI.H.
nDimensions()
Foam::label nDimensions () const inline
Return the dimensionality of the distribution.
Definition at line 47 of file momentI.H.
order()
Foam::label order () const inline
Return the overall order of the moment.
Definition at line 53 of file momentI.H.
Referenced by FokkerPlanck::K(), IEM::K(), and moment< fieldType, nodeType >::momentName().
cmptOrders()
const Foam::labelList & cmptOrders () const inline
Return the order of each dimension.
Definition at line 60 of file momentI.H.
Referenced by esBGKCollision::implicitCollisionSource(), BoltzmannCollision::implicitCollisionSource(), and BGKCollision::implicitCollisionSource().
update()
void update ()
Update the moment from the quadrature nodes.
Definition at line 157 of file moment.C.
References forAll(), nodes, and velocityIndexes().
updateBoundaries()
void updateBoundaries ()
Update the moment from the quadrature nodes.
on boundaries
Definition at line 253 of file moment.C.
References forAll(), nodes, and velocityIndexes().
updateLocalMoment()
void updateLocalMoment (label elemi)
Update the moment from the quadrature nodes in a single element.
Definition at line 342 of file moment.C.
References forAll(), nodes, and velocityIndexes().
The documentation for this class was generated from the following files:
moment.H
moment.C
momentI.H