OpenQBMM: aggregationKernel Class Reference
aggregationKernel Class Reference abstract
Abstract class for aggregation kernels.
Public Member Functions
TypeName ("aggregationKernel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, aggregationKernel, dictionary,(const dictionary &dict, const fvMesh &mesh),(dict, mesh))
aggregationKernel (const dictionary &dict, const fvMesh &mesh)
Construct from components.
aggregationKernel (const aggregationKernel &)=delete
Disallow default bitwise copy construct.
virtual ~aggregationKernel ()
Destructor.
virtual scalar Ka (const scalar &abscissa1, const scalar &abscissa2, const label celli, const label environment=0) const =0
Aggregation kernel.
scalar aggregationSource (const labelList &momentOrder, const label celli, const scalarQuadratureApproximation &quadrature, const label enviroment)
Return aggregation source terms.
scalar aggregationSource (const labelList &momentOrder, const label celli, const velocityQuadratureApproximation &quadrature, const label enviroment)
Return aggregation source terms.
void operator= (const aggregationKernel &)=delete
Disallow default bitwise assignment.
Static Public Member Functions
static autoPtr< aggregationKernel > New (const dictionary &dict, const fvMesh &mesh)
Protected Member Functions
scalar nodeSource (const scalar &abscissa1, const scalar &abscissa2, const label momentOrder) const
Length based aggregation source given two abscissae and an order.
scalar massNodeSource (const scalar &abscissa1, const scalar &abscissa2, const label momentOrder) const
Mass based aggregation source given two abscissae and an order.
Protected Attributes
const dictionary & dict_
Dictionary.
const fvMesh & mesh_
Mesh.
const dimensionedScalar Ca_
Coefficient of aggregation kernel.
Detailed Description
Abstract class for aggregation kernels.
Source files
aggregationKernel.H
aggregationKernel.C
Definition at line 54 of file aggregationKernel.H.
Constructor & Destructor Documentation
aggregationKernel() [1/2]
aggregationKernel (const dictionary & dict, const fvMesh & mesh)
Construct from components.
Definition at line 44 of file aggregationKernel.C.
aggregationKernel() [2/2]
aggregationKernel (const aggregationKernel &) delete
Disallow default bitwise copy construct.
~aggregationKernel()
~aggregationKernel () virtual
Destructor.
Definition at line 64 of file aggregationKernel.C.
Member Function Documentation
nodeSource()
Foam::scalar nodeSource (const scalar & abscissa1, const scalar & abscissa2, const label momentOrder) const protected
Length based aggregation source given two abscissae and an order.
Definition at line 72 of file aggregationKernel.C.
massNodeSource()
Foam::scalar massNodeSource (const scalar & abscissa1, const scalar & abscissa2, const label momentOrder) const protected
Mass based aggregation source given two abscissae and an order.
Definition at line 91 of file aggregationKernel.C.
TypeName()
TypeName ("aggregationKernel")
Runtime type information.
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , aggregationKernel , dictionary , (const dictionary &dict, const fvMesh &mesh) , (dict, mesh))
New()
Foam::autoPtr< Foam::populationBalanceSubModels::aggregationKernel > New (const dictionary & dict, const fvMesh & mesh) static
Definition at line 32 of file newAggregationKernel.C.
Referenced by sizeVelocityPopulationBalance::sizeVelocityPopulationBalance(), and univariatePopulationBalance::univariatePopulationBalance().
Ka()
virtual scalar Ka (const scalar & abscissa1, const scalar & abscissa2, const label celli, const label environment = 0) const pure virtual
Aggregation kernel.
Implemented in turbulentBrownian, Brownian, differentialForceAggregation, hydrodynamicAggregation, sumAggregation, and constantAggregation.
aggregationSource() [1/2]
Foam::scalar aggregationSource (const labelList & momentOrder, const label celli, const scalarQuadratureApproximation & quadrature, const label enviroment)
Return aggregation source terms.
Definition at line 110 of file aggregationKernel.C.
References forAll(), max(), nodes, quadratureNode< scalarType, vectorType >::primaryAbscissae(), quadratureNode< scalarType, vectorType >::primaryWeight(), quadrature, quadratureNode< scalarType, vectorType >::secondaryAbscissae(), quadratureNode< scalarType, vectorType >::secondaryWeights(), and sizeIndex.
aggregationSource() [2/2]
Foam::scalar aggregationSource (const labelList & momentOrder, const label celli, const velocityQuadratureApproximation & quadrature, const label enviroment)
Return aggregation source terms.
Definition at line 308 of file aggregationKernel.C.
References forAll(), max(), nodes, quadratureNode< scalarType, vectorType >::primaryAbscissae(), quadratureNode< scalarType, vectorType >::primaryWeight(), quadrature, quadratureNode< scalarType, vectorType >::secondaryAbscissae(), quadratureNode< scalarType, vectorType >::secondaryWeights(), sizeIndex, velocityQuadratureNode< scalarType, vectorType >::velocityAbscissae(), quadratureNode< scalarType, vectorType >::velocityAbscissae(), and velocityIndexes().
operator=()
void operator= (const aggregationKernel &) delete
Disallow default bitwise assignment.
Member Data Documentation
dict_
const dictionary& dict_ protected
Dictionary.
Definition at line 61 of file aggregationKernel.H.
mesh_
const fvMesh& mesh_ protected
Mesh.
Definition at line 64 of file aggregationKernel.H.
Ca_
const dimensionedScalar Ca_ protected
Coefficient of aggregation kernel.
Definition at line 67 of file aggregationKernel.H.
The documentation for this class was generated from the following files:
aggregationKernel.H
aggregationKernel.C
newAggregationKernel.C