OpenQBMM: univariatePDFTransportModel Class Reference
univariatePDFTransportModel Class Reference abstract
Public Member Functions
univariatePDFTransportModel (const word &name, const dictionary &dict, const fvMesh &mesh, const surfaceScalarField &phi, const word &support)
Construct from components.
virtual ~univariatePDFTransportModel ()
Destructor.
const scalarQuadratureApproximation & quadrature () const
Access.
scalar realizableCo () const
Return the maximum Courant number ensuring moment realizability.
virtual void solve ()
Edit.
Public Member Functions inherited from PDFTransportModel
PDFTransportModel (const word &name, const dictionary &dict, const fvMesh &mesh)
Construct from components.
PDFTransportModel (const PDFTransportModel &)=delete
Disallow default bitwise copy construct.
virtual ~PDFTransportModel ()
Destructor.
void operator= (const PDFTransportModel &)=delete
Disallow default bitwise assignment.
Protected Member Functions
virtual tmp< fvScalarMatrix > implicitMomentSource (const volScalarMoment &moment)=0
Calculate implicit source terms.
virtual void explicitMomentSource ()=0
Calculate explicit source terms with realizable ODE solver.
virtual bool solveMomentSources () const =0
Are moments updated due to sources.
virtual bool solveMomentOde () const =0
Is the realizable ode solver used to solve sources.
Protected Attributes
scalarQuadratureApproximation quadrature_
Univariate quadrature approximation used to solve PDF transport.
autoPtr< univariateMomentAdvection > momentAdvection_
Moment advection.
Protected Attributes inherited from PDFTransportModel
const fvMesh & mesh_
Constant reference to the mesh.
Detailed Description
Definition at line 53 of file univariatePDFTransportModel.H.
Constructor & Destructor Documentation
univariatePDFTransportModel()
univariatePDFTransportModel (const word & name, const dictionary & dict, const fvMesh & mesh, const surfaceScalarField & phi, const word & support)
Construct from components.
Definition at line 32 of file univariatePDFTransportModel.C.
~univariatePDFTransportModel()
~univariatePDFTransportModel () virtual
Destructor.
Definition at line 57 of file univariatePDFTransportModel.C.
Member Function Documentation
implicitMomentSource()
virtual tmp<fvScalarMatrix> implicitMomentSource (const volScalarMoment & moment) protected pure virtual
Calculate implicit source terms.
Referenced by univariatePDFTransportModel::solve().
explicitMomentSource()
virtual void explicitMomentSource () protected pure virtual
Calculate explicit source terms with realizable ODE solver.
Referenced by univariatePDFTransportModel::solve().
solveMomentSources()
virtual bool solveMomentSources () const protected pure virtual
Are moments updated due to sources.
Referenced by univariatePDFTransportModel::solve().
solveMomentOde()
virtual bool solveMomentOde () const protected pure virtual
Is the realizable ode solver used to solve sources.
quadrature()
const Foam::scalarQuadratureApproximation & quadrature () const inline
Access.
Returns a const reference to the quadrature approximation
Definition at line 29 of file univariatePDFTransportModelI.H.
References univariatePDFTransportModel::quadrature_.
realizableCo()
Foam::scalar realizableCo () const inline
Return the maximum Courant number ensuring moment realizability.
Definition at line 35 of file univariatePDFTransportModelI.H.
Referenced by turbulentMixing::realizableCo(), and univariatePopulationBalance::realizableCo().
solve()
void solve () virtual
Edit.
Solve univariate PDF transport equation
Implements PDFTransportModel.
Reimplemented in univariatePopulationBalance, and turbulentMixing.
Definition at line 62 of file univariatePDFTransportModel.C.
References univariatePDFTransportModel::explicitMomentSource(), forAll(), univariatePDFTransportModel::implicitMomentSource(), univariatePDFTransportModel::momentAdvection_, quadratureApproximation< momentType, nodeType >::moments(), quadratureApproximation< momentType, nodeType >::nMoments(), univariatePDFTransportModel::quadrature_, mappedPtrList< mappedType >::set(), univariatePDFTransportModel::solveMomentSources(), and quadratureApproximation< momentType, nodeType >::updateQuadrature().
Referenced by turbulentMixing::solve(), and univariatePopulationBalance::solve().
Member Data Documentation
quadrature_
scalarQuadratureApproximation quadrature_ protected
Univariate quadrature approximation used to solve PDF transport.
Definition at line 62 of file univariatePDFTransportModel.H.
Referenced by univariatePDFTransportModel::quadrature(), and univariatePDFTransportModel::solve().
momentAdvection_
autoPtr<univariateMomentAdvection> momentAdvection_ protected
Moment advection.
Definition at line 65 of file univariatePDFTransportModel.H.
Referenced by univariatePDFTransportModel::solve().
The documentation for this class was generated from the following files:
univariatePDFTransportModel.H
univariatePDFTransportModel.C
univariatePDFTransportModelI.H