OpenQBMM: univariateMomentInversion Class Reference
univariateMomentInversion Class Reference abstract
Abstract class for univariate quadrature on a moment set.
Public Member Functions
TypeName ("univariateMomentInversion")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, univariateMomentInversion, dictionary,(const dictionary &dict),(dict))
univariateMomentInversion (const dictionary &dict)
Construct from univariateMomentSet.
univariateMomentInversion (const univariateMomentInversion &)=delete
Disallow default bitwise copy construct.
virtual ~univariateMomentInversion ()
Destructor.
virtual void calcNQuadratureNodes (univariateMomentSet &moments)=0
Calculates the number of quadrature nodes.
virtual void correctRecurrence (univariateMomentSet &moments, scalarList &alpha, scalarList &beta, const scalar minKnownAbscissa=0, const scalar maxKnownAbscissa=0)=0
Modify the recurrence relation for fixed-point quadrature.
virtual void invert (univariateMomentSet &moments, const scalar minKnownAbscissa=0, const scalar maxKnownAbscissa=0)
Invert the set of moments to compute weights and abscissae.
const scalarList & abscissae () const
Return quadrature abscissae.
label nNodes () const
Return the number of nodes.
const scalarList & weights () const
Return quadrature weigths.
void operator= (const univariateMomentInversion &)=delete
Disallow default bitwise assignment.
Static Public Member Functions
static autoPtr< univariateMomentInversion > New (const dictionary &dict)
Protected Member Functions
void JacobiMatrix (univariateMomentSet &moments, scalarSquareMatrix &z, const scalar minKnownAbscissa=0, const scalar maxKnownAbscissa=0)
Create Jacobi matrix.
Protected Attributes
label nInvertibleMoments_
Number of invertible moments for the user-selected quadrature.
label nNodes_
Number of quadrature nodes.
scalarList abscissae_
Quadrature abscissae.
scalarList weights_
Quadrature weights.
Detailed Description
Abstract class for univariate quadrature on a moment set.
Source files
univariateMomentInversion.H
univariateMomentInversion.C
univariateMomentInversionI.H
Definition at line 51 of file univariateMomentInversion.H.
Constructor & Destructor Documentation
univariateMomentInversion() [1/2]
univariateMomentInversion (const dictionary & dict)
Construct from univariateMomentSet.
Definition at line 42 of file univariateMomentInversion.C.
univariateMomentInversion() [2/2]
univariateMomentInversion (const univariateMomentInversion &) delete
Disallow default bitwise copy construct.
~univariateMomentInversion()
~univariateMomentInversion () virtual
Destructor.
Definition at line 56 of file univariateMomentInversion.C.
Member Function Documentation
JacobiMatrix()
void JacobiMatrix (univariateMomentSet & moments, scalarSquareMatrix & z, const scalar minKnownAbscissa = 0, const scalar maxKnownAbscissa = 0) protected
Create Jacobi matrix.
Definition at line 63 of file univariateMomentInversion.C.
TypeName()
TypeName ("univariateMomentInversion")
Runtime type information.
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , univariateMomentInversion , dictionary , (const dictionary &dict) , (dict))
New()
Foam::autoPtr< Foam::univariateMomentInversion > New (const dictionary & dict) static
Definition at line 32 of file newUnivariateMomentInversion.C.
Referenced by TensorProduct::TensorProduct().
calcNQuadratureNodes()
virtual void calcNQuadratureNodes (univariateMomentSet & moments) pure virtual
Calculates the number of quadrature nodes.
Implemented in hyperbolicMomentInversion, gaussLobattoMomentInversion, gaussRadauMomentInversion, and gaussMomentInversion.
correctRecurrence()
virtual void correctRecurrence (univariateMomentSet & moments, scalarList & alpha, scalarList & beta, const scalar minKnownAbscissa = 0, const scalar maxKnownAbscissa = 0) pure virtual
Modify the recurrence relation for fixed-point quadrature.
Implemented in hyperbolicMomentInversion, gaussLobattoMomentInversion, gaussRadauMomentInversion, and gaussMomentInversion.
invert()
void invert (univariateMomentSet & moments, const scalar minKnownAbscissa = 0, const scalar maxKnownAbscissa = 0) virtual
Invert the set of moments to compute weights and abscissae.
Reimplemented in hyperbolicMomentInversion.
Definition at line 93 of file univariateMomentInversion.C.
References eigenSolver::eigenvaluesRe(), and eigenSolver::eigenvectors().
abscissae()
const Foam::scalarList & abscissae () const inline
Return quadrature abscissae.
Definition at line 28 of file univariateMomentInversionI.H.
References univariateMomentInversion::abscissae_.
nNodes()
Foam::label nNodes () const inline
Return the number of nodes.
Definition at line 33 of file univariateMomentInversionI.H.
weights()
const Foam::scalarList & weights () const inline
Return quadrature weigths.
Definition at line 38 of file univariateMomentInversionI.H.
operator=()
void operator= (const univariateMomentInversion &) delete
Disallow default bitwise assignment.
Member Data Documentation
nInvertibleMoments_
label nInvertibleMoments_ protected
Number of invertible moments for the user-selected quadrature.
Definition at line 63 of file univariateMomentInversion.H.
nNodes_
label nNodes_ protected
Number of quadrature nodes.
Definition at line 66 of file univariateMomentInversion.H.
abscissae_
scalarList abscissae_ protected
Quadrature abscissae.
Definition at line 69 of file univariateMomentInversion.H.
Referenced by univariateMomentInversion::abscissae().
weights_
scalarList weights_ protected
Quadrature weights.
Definition at line 72 of file univariateMomentInversion.H.
The documentation for this class was generated from the following files:
univariateMomentInversion.H
newUnivariateMomentInversion.C
univariateMomentInversion.C
univariateMomentInversionI.H