OpenQBMM: gammaEQMOM Class Reference
gammaEQMOM Class Reference
Extended quadrature method of moments with gamma kernel density functions.
Public Member Functions
TypeName ("gamma")
Runtime type information.
gammaEQMOM (const dictionary &dict, const label nMoments, const label nSecondaryNodes)
Construct from a dictionary and label.
virtual ~gammaEQMOM ()
Destructor.
virtual scalar secondaryAbscissa (scalar primaryAbscissa, scalar secondaryAbscissa, scalar sigma)
Computes the secondary abscissa.
virtual void momentsStarToMoments (scalar sigma, univariateMomentSet &moments, const univariateMomentSet &momentsStar)
Compute moments from starred moments.
virtual void momentsToMomentsStar (scalar sigma, const univariateMomentSet &moments, univariateMomentSet &momentsStar)
Compute the starred moments.
virtual scalar m2N (scalar sigma, const univariateMomentSet &momentsStar)
Compute the last moment from starred moments.
virtual void recurrenceRelation (scalarList &a, scalarList &b, scalar primaryAbscissa, scalar sigma)
Recurrence relation for polynomials orthogonal to kernel function.
virtual scalar sigmaMax (univariateMomentSet &moments)
Compute maximum value of sigma to ensure realizability.
virtual tmp< scalarField > f (const scalarField &x) const
Return the sum of the kernel density functions at a field of points.
Public Member Functions inherited from extendedMomentInversion
TypeName ("extendedMomentInversion")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, extendedMomentInversion, dictionary,(const dictionary &dict, const label nMoments, const label nSecondaryNodes),(dict, nMoments, nSecondaryNodes))
extendedMomentInversion (const dictionary &dict, const label nMoments, const label nSecondaryNodes)
extendedMomentInversion (const extendedMomentInversion &)=delete
Disallow default bitwise copy construct.
virtual ~extendedMomentInversion ()
Destructor.
void invert (const univariateMomentSet &moments)
Invert moments to find weight, abscissae and sigma.
label nMoments ()
Return number of moments.
label nPrimaryNodes ()
Return number of primary quadrature nodes.
label nSecondaryNodes ()
Return number of secondary quadrature nodes.
scalar sigma () const
Return the value of the sigma parameter.
const scalarList & primaryWeights () const
Return primary quadrature weights.
const scalarList & primaryAbscissae () const
Return primary quadrature abscissae.
const scalarRectangularMatrix & secondaryWeights () const
Return secondary quadrature weights.
const scalarRectangularMatrix & secondaryAbscissae () const
Return secondary quadrature abscissae.
void operator= (const extendedMomentInversion &)=delete
Disallow default bitwise assignment.
Additional Inherited Members
Static Public Member Functions inherited from extendedMomentInversion
static autoPtr< extendedMomentInversion > New (const dictionary &dict, const label nMoments, const label nSecondaryNodes)
Protected Member Functions inherited from extendedMomentInversion
scalar normalizedMomentError (scalar sigma, const univariateMomentSet &moments, univariateMomentSet &momentsStar)
Compute the normalized moment error.
Protected Attributes inherited from extendedMomentInversion
label nMoments_
Number of moments.
label nPrimaryNodes_
Number of primary quadrature nodes.
label nSecondaryNodes_
Number of secondary quadrature nodes.
scalarList primaryWeights_
Primary quadrature weights.
scalarList primaryAbscissae_
Primary quadrature abscissae.
scalar sigma_
Parameter sigma of the kernel density function.
scalarRectangularMatrix secondaryWeights_
Secondary quadrature weights.
scalarRectangularMatrix secondaryAbscissae_
Secondary quadrature abscissae.
scalar minMean_
Minimum mean to perform EQMOM reconstruction.
scalar minVariance_
Minimum variance to perform EQMOM reconstruction.
label maxSigmaIter_
Maximum number of iterations allowed to find sigma_.
scalar momentsTol_
Tolerance on moment conservation.
scalar sigmaMin_
Minimum allowed value of the parameter sigma of the kernel density.
scalar sigmaTol_
Tolerance for the change in the sigma parameter.
scalar targetFunctionTol_
Tolerance for the target function.
bool foundUnrealizableSigma_
Bool to track values of sigma_ that lead to unrealizable moments.
bool nullSigma_
Bool to track if sigma = 0 is root.
Detailed Description
Extended quadrature method of moments with gamma kernel density functions.
References
    "An extended quadrature method of moments for population balance
    equations"
    C Yuan, F Laurent, R O Fox
    Journal of Aerosol Science
    Volume 51, Pages 1-23, 2012
    "The theory of canonical moments with applications in Statistics,
    Probability and Analysis"
    H Dette, W J Studden
    Wiley & Sons, 1997
Source files
gammaEQMOM.H
gammaEQMOM.C
Definition at line 63 of file gammaEQMOM.H.
Constructor & Destructor Documentation
gammaEQMOM()
gammaEQMOM (const dictionary & dict, const label nMoments, const label nSecondaryNodes)
Construct from a dictionary and label.
Definition at line 50 of file gammaEQMOM.C.
~gammaEQMOM()
~gammaEQMOM () virtual
Destructor.
Definition at line 62 of file gammaEQMOM.C.
Member Function Documentation
TypeName()
TypeName ("gamma")
Runtime type information.
secondaryAbscissa()
Foam::scalar secondaryAbscissa (scalar primaryAbscissa, scalar secondaryAbscissa, scalar sigma) virtual
Computes the secondary abscissa.
Implements extendedMomentInversion.
Definition at line 68 of file gammaEQMOM.C.
momentsStarToMoments()
void momentsStarToMoments (scalar sigma, univariateMomentSet & moments, const univariateMomentSet & momentsStar) virtual
Compute moments from starred moments.
Implements extendedMomentInversion.
Definition at line 78 of file gammaEQMOM.C.
momentsToMomentsStar()
void momentsToMomentsStar (scalar sigma, const univariateMomentSet & moments, univariateMomentSet & momentsStar) virtual
Compute the starred moments.
Implements extendedMomentInversion.
Definition at line 154 of file gammaEQMOM.C.
m2N()
Foam::scalar m2N (scalar sigma, const univariateMomentSet & momentsStar) virtual
Compute the last moment from starred moments.
Implements extendedMomentInversion.
Definition at line 223 of file gammaEQMOM.C.
References univariateMomentSet::nRealizableMoments().
recurrenceRelation()
void recurrenceRelation (scalarList & a, scalarList & b, scalar primaryAbscissa, scalar sigma) virtual
Recurrence relation for polynomials orthogonal to kernel function.
Implements extendedMomentInversion.
Definition at line 244 of file gammaEQMOM.C.
References forAll().
sigmaMax()
Foam::scalar sigmaMax (univariateMomentSet & moments) virtual
Compute maximum value of sigma to ensure realizability.
Implements extendedMomentInversion.
Definition at line 266 of file gammaEQMOM.C.
f()
Foam::tmp< Foam::scalarField > f (const scalarField & x) const virtual
Return the sum of the kernel density functions at a field of points.
Implements extendedMomentInversion.
Definition at line 274 of file gammaEQMOM.C.
References max().
The documentation for this class was generated from the following files:
gammaEQMOM.H
gammaEQMOM.C