OpenQBMM: extendedMomentInversion Class Reference
extendedMomentInversion Class Reference abstract
Abstract class to allow run-time selection of the algorithm to be used for the extended quadrature method of moments.
Public Member Functions
TypeName ("extendedMomentInversion")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, extendedMomentInversion, dictionary,(const dictionary &dict, const label nMoments, const label nSecondaryNodes),(dict, nMoments, nSecondaryNodes))
extendedMomentInversion (const dictionary &dict, const label nMoments, const label nSecondaryNodes)
extendedMomentInversion (const extendedMomentInversion &)=delete
Disallow default bitwise copy construct.
virtual ~extendedMomentInversion ()
Destructor.
void invert (const univariateMomentSet &moments)
Invert moments to find weight, abscissae and sigma.
label nMoments ()
Return number of moments.
label nPrimaryNodes ()
Return number of primary quadrature nodes.
label nSecondaryNodes ()
Return number of secondary quadrature nodes.
scalar sigma () const
Return the value of the sigma parameter.
const scalarList & primaryWeights () const
Return primary quadrature weights.
const scalarList & primaryAbscissae () const
Return primary quadrature abscissae.
const scalarRectangularMatrix & secondaryWeights () const
Return secondary quadrature weights.
const scalarRectangularMatrix & secondaryAbscissae () const
Return secondary quadrature abscissae.
virtual tmp< scalarField > f (const scalarField &x) const =0
Return the sum of the kernel density functions at a field of points.
void operator= (const extendedMomentInversion &)=delete
Disallow default bitwise assignment.
Static Public Member Functions
static autoPtr< extendedMomentInversion > New (const dictionary &dict, const label nMoments, const label nSecondaryNodes)
Protected Member Functions
virtual scalar secondaryAbscissa (scalar primaryAbscissa, scalar secondaryAbscissa, scalar sigma)=0
Protected member functions.
virtual void momentsStarToMoments (scalar sigma, univariateMomentSet &moments, const univariateMomentSet &momentsStar)=0
Compute moments from starred moments.
virtual void momentsToMomentsStar (scalar sigma, const univariateMomentSet &moments, univariateMomentSet &momentsStar)=0
Compute the starred moments from moments.
virtual scalar m2N (scalar sigma, const univariateMomentSet &momentsStar)=0
Compute the last moment from starred moments.
scalar normalizedMomentError (scalar sigma, const univariateMomentSet &moments, univariateMomentSet &momentsStar)
Compute the normalized moment error.
virtual void recurrenceRelation (scalarList &a, scalarList &b, scalar primaryAbscissa, scalar sigma)=0
Recurrence relation for polynomials orthogonal to kernel function.
virtual scalar sigmaMax (univariateMomentSet &moments)=0
Compute maximum value of sigma to ensure realizability.
Protected Attributes
label nMoments_
Number of moments.
label nPrimaryNodes_
Number of primary quadrature nodes.
label nSecondaryNodes_
Number of secondary quadrature nodes.
scalarList primaryWeights_
Primary quadrature weights.
scalarList primaryAbscissae_
Primary quadrature abscissae.
scalar sigma_
Parameter sigma of the kernel density function.
scalarRectangularMatrix secondaryWeights_
Secondary quadrature weights.
scalarRectangularMatrix secondaryAbscissae_
Secondary quadrature abscissae.
scalar minMean_
Minimum mean to perform EQMOM reconstruction.
scalar minVariance_
Minimum variance to perform EQMOM reconstruction.
label maxSigmaIter_
Maximum number of iterations allowed to find sigma_.
scalar momentsTol_
Tolerance on moment conservation.
scalar sigmaMin_
Minimum allowed value of the parameter sigma of the kernel density.
scalar sigmaTol_
Tolerance for the change in the sigma parameter.
scalar targetFunctionTol_
Tolerance for the target function.
bool foundUnrealizableSigma_
Bool to track values of sigma_ that lead to unrealizable moments.
bool nullSigma_
Bool to track if sigma = 0 is root.
Detailed Description
Abstract class to allow run-time selection of the algorithm to be used for the extended quadrature method of moments.
References
    "An extended quadrature method of moments for population balance
    equations"
    C Yuan, F Laurent, R O Fox
    Journal of Aerosol Science
    Volume 51, Pages 1-23, 2012
    "The theory of canonical moments with applications in Statistics,
    Probability and Analysis"
    H Dette, W J Studden
    Wiley & Sons, 1997
    "Orthogonal Polynomials: Computation and Approximation"
    W Gautschi
    Oxford University Press, 2004
Source files
extendedMomentInversion.H
extendedMomentInversion.C
newExtendedMomentInversion.C
Definition at line 78 of file extendedMomentInversion.H.
Constructor & Destructor Documentation
extendedMomentInversion() [1/2]
extendedMomentInversion (const dictionary & dict, const label nMoments, const label nSecondaryNodes)
Definition at line 41 of file extendedMomentInversion.C.
extendedMomentInversion() [2/2]
extendedMomentInversion (const extendedMomentInversion &) delete
Disallow default bitwise copy construct.
~extendedMomentInversion()
~extendedMomentInversion () virtual
Destructor.
Definition at line 73 of file extendedMomentInversion.C.
Member Function Documentation
secondaryAbscissa()
virtual scalar secondaryAbscissa (scalar primaryAbscissa, scalar secondaryAbscissa, scalar sigma) protected pure virtual
Protected member functions.
Computes kernel density function from abscissa and sigma
Implemented in lognormalEQMOM, betaEQMOM, and gammaEQMOM.
momentsStarToMoments()
virtual void momentsStarToMoments (scalar sigma, univariateMomentSet & moments, const univariateMomentSet & momentsStar) protected pure virtual
Compute moments from starred moments.
Implemented in lognormalEQMOM, betaEQMOM, and gammaEQMOM.
momentsToMomentsStar()
virtual void momentsToMomentsStar (scalar sigma, const univariateMomentSet & moments, univariateMomentSet & momentsStar) protected pure virtual
Compute the starred moments from moments.
Implemented in lognormalEQMOM, betaEQMOM, and gammaEQMOM.
m2N()
virtual scalar m2N (scalar sigma, const univariateMomentSet & momentsStar) protected pure virtual
Compute the last moment from starred moments.
Implemented in lognormalEQMOM, betaEQMOM, and gammaEQMOM.
normalizedMomentError()
Foam::scalar normalizedMomentError (scalar sigma, const univariateMomentSet & moments, univariateMomentSet & momentsStar) protected
Compute the normalized moment error.
Definition at line 429 of file extendedMomentInversion.C.
recurrenceRelation()
virtual void recurrenceRelation (scalarList & a, scalarList & b, scalar primaryAbscissa, scalar sigma) protected pure virtual
Recurrence relation for polynomials orthogonal to kernel function.
Implemented in lognormalEQMOM, betaEQMOM, and gammaEQMOM.
sigmaMax()
virtual scalar sigmaMax (univariateMomentSet & moments) protected pure virtual
Compute maximum value of sigma to ensure realizability.
The value is exact for the two-node case. For cases with a larger number of nodes, this provides an over-estimation of the maximum value of the sigma parameter which ensures moment realizability.
Implemented in lognormalEQMOM, betaEQMOM, and gammaEQMOM.
TypeName()
TypeName ("extendedMomentInversion")
Runtime type information.
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , extendedMomentInversion , dictionary , (const dictionary &dict, const label nMoments, const label nSecondaryNodes) , (dict, nMoments, nSecondaryNodes))
New()
Foam::autoPtr< Foam::extendedMomentInversion > New (const dictionary & dict, const label nMoments, const label nSecondaryNodes) static
Definition at line 31 of file newExtendedMomentInversion.C.
invert()
void invert (const univariateMomentSet & moments)
Invert moments to find weight, abscissae and sigma.
Definition at line 78 of file extendedMomentInversion.C.
References univariateMomentSet::isOnMomentSpaceBoundary(), univariateMomentSet::nRealizableMoments(), univariateMomentSet::resize(), and momentSet::support().
nMoments()
label nMoments () inline
Return number of moments.
Definition at line 287 of file extendedMomentInversion.H.
References extendedMomentInversion::nMoments_.
nPrimaryNodes()
label nPrimaryNodes () inline
Return number of primary quadrature nodes.
Definition at line 293 of file extendedMomentInversion.H.
References extendedMomentInversion::nPrimaryNodes_.
nSecondaryNodes()
label nSecondaryNodes () inline
Return number of secondary quadrature nodes.
Definition at line 299 of file extendedMomentInversion.H.
References extendedMomentInversion::nSecondaryNodes_.
sigma()
scalar sigma () const inline
Return the value of the sigma parameter.
Definition at line 305 of file extendedMomentInversion.H.
References extendedMomentInversion::sigma_.
primaryWeights()
const scalarList& primaryWeights () const inline
Return primary quadrature weights.
Definition at line 311 of file extendedMomentInversion.H.
References extendedMomentInversion::primaryWeights_.
primaryAbscissae()
const scalarList& primaryAbscissae () const inline
Return primary quadrature abscissae.
Definition at line 317 of file extendedMomentInversion.H.
References extendedMomentInversion::primaryAbscissae_.
secondaryWeights()
const scalarRectangularMatrix& secondaryWeights () const inline
Return secondary quadrature weights.
Definition at line 323 of file extendedMomentInversion.H.
References extendedMomentInversion::secondaryWeights_.
secondaryAbscissae()
const scalarRectangularMatrix& secondaryAbscissae () const inline
Return secondary quadrature abscissae.
Definition at line 329 of file extendedMomentInversion.H.
References extendedMomentInversion::secondaryAbscissae_.
f()
virtual tmp<scalarField> f (const scalarField & x) const pure virtual
Return the sum of the kernel density functions at a field of points.
Implemented in lognormalEQMOM, betaEQMOM, and gammaEQMOM.
operator=()
void operator= (const extendedMomentInversion &) delete
Disallow default bitwise assignment.
Member Data Documentation
nMoments_
label nMoments_ protected
Number of moments.
Definition at line 121 of file extendedMomentInversion.H.
Referenced by extendedMomentInversion::nMoments().
nPrimaryNodes_
label nPrimaryNodes_ protected
Number of primary quadrature nodes.
Definition at line 124 of file extendedMomentInversion.H.
Referenced by extendedMomentInversion::nPrimaryNodes().
nSecondaryNodes_
label nSecondaryNodes_ protected
Number of secondary quadrature nodes.
Definition at line 127 of file extendedMomentInversion.H.
Referenced by extendedMomentInversion::nSecondaryNodes().
primaryWeights_
scalarList primaryWeights_ protected
Primary quadrature weights.
Definition at line 130 of file extendedMomentInversion.H.
Referenced by extendedMomentInversion::primaryWeights().
primaryAbscissae_
scalarList primaryAbscissae_ protected
Primary quadrature abscissae.
Definition at line 133 of file extendedMomentInversion.H.
Referenced by extendedMomentInversion::primaryAbscissae().
sigma_
scalar sigma_ protected
Parameter sigma of the kernel density function.
Definition at line 136 of file extendedMomentInversion.H.
Referenced by extendedMomentInversion::sigma().
secondaryWeights_
scalarRectangularMatrix secondaryWeights_ protected
Secondary quadrature weights.
Definition at line 139 of file extendedMomentInversion.H.
Referenced by extendedMomentInversion::secondaryWeights().
secondaryAbscissae_
scalarRectangularMatrix secondaryAbscissae_ protected
Secondary quadrature abscissae.
Definition at line 142 of file extendedMomentInversion.H.
Referenced by extendedMomentInversion::secondaryAbscissae().
minMean_
scalar minMean_ protected
Minimum mean to perform EQMOM reconstruction.
Definition at line 145 of file extendedMomentInversion.H.
minVariance_
scalar minVariance_ protected
Minimum variance to perform EQMOM reconstruction.
Definition at line 148 of file extendedMomentInversion.H.
maxSigmaIter_
label maxSigmaIter_ protected
Maximum number of iterations allowed to find sigma_.
Definition at line 151 of file extendedMomentInversion.H.
momentsTol_
scalar momentsTol_ protected
Tolerance on moment conservation.
Definition at line 154 of file extendedMomentInversion.H.
sigmaMin_
scalar sigmaMin_ protected
Minimum allowed value of the parameter sigma of the kernel density.
function. Below this value, QMOM is used.
Definition at line 158 of file extendedMomentInversion.H.
sigmaTol_
scalar sigmaTol_ protected
Tolerance for the change in the sigma parameter.
Definition at line 161 of file extendedMomentInversion.H.
targetFunctionTol_
scalar targetFunctionTol_ protected
Tolerance for the target function.
Definition at line 164 of file extendedMomentInversion.H.
foundUnrealizableSigma_
bool foundUnrealizableSigma_ protected
Bool to track values of sigma_ that lead to unrealizable moments.
Definition at line 167 of file extendedMomentInversion.H.
nullSigma_
bool nullSigma_ protected
Bool to track if sigma = 0 is root.
Definition at line 170 of file extendedMomentInversion.H.
The documentation for this class was generated from the following files:
extendedMomentInversion.H
extendedMomentInversion.C
newExtendedMomentInversion.C