OpenQBMM: BGKCollision Class Reference
BGKCollision Class Reference
Public Member Functions
TypeName ("BGK")
Runtime type information.
BGKCollision (const dictionary &dict, const fvMesh &mesh, const velocityQuadratureApproximation &quadrature)
Construct from components.
virtual ~BGKCollision ()
Destructor.
virtual bool implicit () const
Is an implicit source used.
virtual void updateCells (const label celli)
Update equilibrium moments.
virtual scalar explicitCollisionSource (const labelList &momentOrder, const label celli) const
Return explicit collision source term.
virtual tmp< fvScalarMatrix > implicitCollisionSource (const volVelocityMoment &m) const
Return implicit collision source matrix.
Public Member Functions inherited from collisionKernel
TypeName ("collisionKernel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, collisionKernel, dictionary,(const dictionary &dict, const fvMesh &mesh, const velocityQuadratureApproximation &quadrature),(dict, mesh, quadrature))
collisionKernel (const dictionary &dict, const fvMesh &mesh, const velocityQuadratureApproximation &quadrature)
Construct from components.
collisionKernel (const collisionKernel &)=delete
Disallow default bitwise copy construct.
virtual ~collisionKernel ()
Destructor.
virtual void preUpdate ()
Update unchanged fields before solving ode system.
virtual void updateFields ()
Update collision sources.
void operator= (const collisionKernel &)=delete
Disallow default bitwise assignment.
Protected Types
typedef void(* momentFunction) (mappedScalarList &Meq, const scalar &, const scalar &, const scalar &, const scalar &, const symmTensor &)
Typedef of function pointer list.
Protected Member Functions
virtual symmTensor covariance (const label celli, const scalar &u, const scalar &v, const scalar &w)
Return the covariance tensor using quadrature moments.
virtual symmTensor covariance (const mappedScalarList &moments, const scalar &u, const scalar &v, const scalar &w)
Return the covariance tensor given a list of moments.
virtual scalar e () const
Return the coefficient of restitution.
Protected Member Functions inherited from collisionKernel
scalar d (const label node, const label celli) const
Return the diameter given a node and cell.
Static Protected Member Functions
static void moment000 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
Functions used to define equilibrium moments.
static void moment001 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment010 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment100 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment002 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment011 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment020 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment101 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment110 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment200 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment003 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment012 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment021 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment030 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment102 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment111 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment120 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment201 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment210 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment300 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment004 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment013 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment022 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment031 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment040 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment103 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment130 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment202 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment220 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment301 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment310 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment400 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment005 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment014 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment023 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment032 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment041 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment050 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment104 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment140 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment203 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment230 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment302 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment320 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment401 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment410 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment500 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment015 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment024 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment042 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment051 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment204 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment240 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment105 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment150 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment402 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment420 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment501 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment510 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment025 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment052 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment205 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment250 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment502 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment520 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
Static Protected Member Functions inherited from collisionKernel
static tmp< volScalarField > lookupOrInitialize (const fvMesh &mesh, const word &name, const dictionary &dict, const word &entryName, const dimensionSet &dims)
Protected Attributes
mappedPtrList< volScalarField > Meq_
Equilibrium velocity moments (for each size)
List< momentFunction > equilibriumMomentFunctions_
List of functions used to calculate equilibrium moments.
PtrList< mappedScalarList > velocityMoments_
Conditioned velocity moments.
PtrList< PtrList< mappedScalarList > > Gs_
Size conditioned equilibrium veloicity moments (Gaussian)
scalarListList Ks_
Collisional times.
scalar minM0_
Minimum volume fraction.
Protected Attributes inherited from collisionKernel
const dictionary & dict_
Dictionary.
const fvMesh & mesh_
Mesh.
const velocityQuadratureApproximation & quadrature_
Quadrature approximation.
const labelListList & momentOrders_
Moment indicies ues to map moments.
const labelListList & nodeIndexes_
Nodes indexes.
const labelList & velocityIndexes_
Velocity indexes.
const label nDimensions_
Number of dimensions.
labelListList velocityMomentOrders_
List of velocity moment orders.
labelListList velocityNodeIndexes_
List of velocity node indexes.
label sizeIndex_
Size index.
label nSizes_
Number of sizes.
tmp< volScalarField > dp_
Refrence to particle diameter.
scalarList rhos_
List of patricle densities.
scalar minD_
Minimum diameter.
Switch implicit_
Is an implicit solution used.
Additional Inherited Members
Static Public Member Functions inherited from collisionKernel
static autoPtr< collisionKernel > New (const dictionary &dict, const fvMesh &mesh, const velocityQuadratureApproximation &quadrature)
Detailed Description
Definition at line 69 of file BGKCollision.H.
Member Typedef Documentation
momentFunction
typedef void(* momentFunction) (mappedScalarList &Meq, const scalar &, const scalar &, const scalar &, const scalar &, const symmTensor &) protected
Typedef of function pointer list.
Definition at line 83 of file BGKCollision.H.
Constructor & Destructor Documentation
BGKCollision()
BGKCollision (const dictionary & dict, const fvMesh & mesh, const velocityQuadratureApproximation & quadrature)
Construct from components.
Definition at line 418 of file BGKCollision.C.
References addMomentFunction1, addMomentFunction2, addMomentFunction3, forAll(), and quadrature.
~BGKCollision()
~BGKCollision () virtual
Destructor.
Definition at line 584 of file BGKCollision.C.
Member Function Documentation
covariance() [1/2]
Foam::symmTensor covariance (const label celli, const scalar & u, const scalar & v, const scalar & w) protected virtual
Return the covariance tensor using quadrature moments.
Reimplemented in esBGKCollision.
Definition at line 54 of file BGKCollision.C.
References m0(), max(), and moments.
covariance() [2/2]
Foam::symmTensor covariance (const mappedScalarList & moments, const scalar & u, const scalar & v, const scalar & w) protected virtual
Return the covariance tensor given a list of moments.
Reimplemented in esBGKCollision.
Definition at line 84 of file BGKCollision.C.
References m0(), max(), and moments.
e()
virtual scalar e () const inline protected virtual
Return the coefficient of restitution.
Reimplemented in esBGKCollision.
Definition at line 134 of file BGKCollision.H.
moment000()
void moment000 (mappedScalarList & Meq_, const scalar & m0, const scalar & u, const scalar & v, const scalar & w, const symmTensor & sigma) static protected
Functions used to define equilibrium moments.
Stored in a list so that moment existance does not have to be checked at every cell, for every itteration. The implementation of equilibrium moment functions are in equilibriumMomentFunctions.C
Definition at line 28 of file equilibriumMomentFunctions.C.
References m0(), and moments.
moment001()
void moment001 (mappedScalarList & Meq_, const scalar & m0, const scalar & u, const scalar & v, const scalar & w, const symmTensor & sigma) static protected
Definition at line 34 of file equilibriumMomentFunctions.C.
References m0(), and moments.
moment010()
void moment010 (mappedScalarList & Meq_, const scalar & m0, const scalar & u, const scalar & v, const scalar & w, const symmTensor & sigma) static protected
Definition at line 39 of file equilibriumMomentFunctions.C.
References m0(), and moments.
moment100()
void moment100 (mappedScalarList & Meq_, const scalar & m0, const scalar & u, const scalar & v, const scalar & w, const symmTensor & sigma) static protected
Definition at line 44 of file equilibriumMomentFunctions.C.
References m0(), and moments.
moment002()
void moment002 (mappedScalarList & Meq_, const scalar & m0, const scalar & u, const scalar & v, const scalar & w, const symmTensor & sigma) static protected
Definition at line 50 of file equilibriumMomentFunctions.C.
References m0(), and moments.
moment011()
void moment011 (mappedScalarList & Meq_, const scalar & m0, const scalar & u, const scalar & v, const scalar & w, const symmTensor & sigma) static protected
Definition at line 55 of file equilibriumMomentFunctions.C.
References m0(), and moments.
moment020()
void moment020 (mappedScalarList & Meq_, const scalar & m0, const scalar & u, const scalar & v, const scalar & w, const symmTensor & sigma) static protected
Definition at line 70 of file equilibriumMomentFunctions.C.
References m0(), and moments.
moment101()
void moment101 (mappedScalarList & Meq_, const scalar & m0, const scalar & u, const scalar & v, const scalar & w, const symmTensor & sigma) static protected
Definition at line 60 of file equilibriumMomentFunctions.C.
References m0(), and moments.
moment110()
void moment110 (mappedScalarList & Meq_, const scalar & m0, const scalar & u, const scalar & v, const scalar & w, const symmTensor & sigma) static protected
Definition at line 65 of file equilibriumMomentFunctions.C.
References m0(), and moments.
moment200()
void moment200 (mappedScalarList & Meq_, const scalar & m0, const scalar & u, const scalar & v, const scalar & w, const symmTensor & sigma) static protected
Definition at line 75 of file equilibriumMomentFunctions.C.
References m0(), and moments.
moment003()
void moment003 (mappedScalarList & Meq_, const scalar & m0, const scalar & u, const scalar & v, const scalar & w, const symmTensor & sigma) static protected
Definition at line 81 of file equilibriumMomentFunctions.C.
References m0(), and moments.
moment012()
void moment012 (mappedScalarList & Meq_, const scalar & m0, const scalar & u, const scalar & v, const scalar & w, const symmTensor & sigma) static protected
Definition at line 86 of file equilibriumMomentFunctions.C.
References m0(), and moments.
moment021()
void moment021 (mappedScalarList & Meq_, const scalar & m0, const scalar & u, const scalar & v, const scalar & w, const symmTensor & sigma) static protected
Definition at line 91 of file equilibriumMomentFunctions.C.
References m0(), and moments.
moment030()
void moment030 (mappedScalarList & Meq_, const scalar & m0, const scalar & u, const scalar & v, const scalar & w, const symmTensor & sigma) static protected
Definition at line 96 of file equilibriumMomentFunctions.C.
References m0(), and moments.
moment102()
void moment102 (mappedScalarList & Meq_, const scalar & m0, const scalar & u, const scalar & v, const scalar & w, const symmTensor & sigma) static protected
Definition at line 101 of file equilibriumMomentFunctions.C.
References m0(), and moments.
moment111()
void moment111 (mappedScalarList & Meq_, const scalar & m0, const scalar & u, const scalar & v, const scalar & w, const symmTensor & sigma) static protected
Definition at line 106 of file equilibriumMomentFunctions.C.
References m0(), and moments.
moment120()
void moment120 (mappedScalarList & Meq_, const scalar & m0, const scalar & u, const scalar & v, const scalar & w, const symmTensor & sigma) static protected
Definition at line 111 of file equilibriumMomentFunctions.C.
References m0(), and moments.
moment201()
void moment201 (mappedScalarList & Meq_, const scalar & m0, const scalar & u, const scalar & v, const scalar & w, const symmTensor & sigma) static protected
Definition at line 116 of file equilibriumMomentFunctions.C.
References m0(), and moments.
moment210()
void moment210 (mappedScalarList & Meq_, const scalar & m0, const scalar & u, const scalar & v, const scalar & w, const symmTensor & sigma) static protected
Definition at line 121 of file equilibriumMomentFunctions.C.
References m0(), and moments.
moment300()
void moment300 (mappedScalarList & Meq_, const scalar & m0, const scalar & u, const scalar & v, const scalar & w, const symmTensor & sigma) static protected
Definition at line 126 of file equilibriumMomentFunctions.C.
References m0(), and moments.
moment004()
void moment004 (mappedScalarList & Meq_, const scalar & m0, const scalar & u, const scalar & v, const scalar & w, const symmTensor & sigma) static protected
Definition at line 132 of file equilibriumMomentFunctions.C.
References m0(), and moments.
moment013()
void moment013 (mappedScalarList & Meq_, const scalar & m0, const scalar & u, const scalar & v, const scalar & w, const symmTensor & sigma) static protected
Definition at line 138 of file equilibriumMomentFunctions.C.
References m0(), and moments.
moment022()
void moment022 (mappedScalarList & Meq_, const scalar & m0, const scalar & u, const scalar & v, const scalar & w, const symmTensor & sigma) static protected
Definition at line 150 of file equilibriumMomentFunctions.C.
References m0(), and moments.
moment031()
void moment031 (mappedScalarList & Meq_, const scalar & m0, const scalar & u, const scalar & v, const scalar & w, const symmTensor & sigma) static protected
Definition at line 165 of file equilibriumMomentFunctions.C.
References m0(), and moments.
moment040()
void moment040 (mappedScalarList & Meq_, const scalar & m0, const scalar & u, const scalar & v, const scalar & w, const symmTensor & sigma) static protected
Definition at line 177 of file equilibriumMomentFunctions.C.
References m0(), and moments.
moment103()
void moment103 (mappedScalarList & Meq_, const scalar & m0, const scalar & u, const scalar & v, const scalar & w, const symmTensor & sigma) static protected
Definition at line 183 of file equilibriumMomentFunctions.C.
References m0(), and moments.
moment130()
void moment130 (mappedScalarList & Meq_, const scalar & m0, const scalar & u, const scalar & v, const scalar & w, const symmTensor & sigma) static protected
Definition at line 222 of file equilibriumMomentFunctions.C.
References m0(), and moments.
moment202()
void moment202 (mappedScalarList & Meq_, const scalar & m0, const scalar & u, const scalar & v, const scalar & w, const symmTensor & sigma) static protected
Definition at line 195 of file equilibriumMomentFunctions.C.
References m0(), and moments.
moment220()
void moment220 (mappedScalarList & Meq_, const scalar & m0, const scalar & u, const scalar & v, const scalar & w, const symmTensor & sigma) static protected
Definition at line 208 of file equilibriumMomentFunctions.C.
References m0(), and moments.
moment301()
void moment301 (mappedScalarList & Meq_, const scalar & m0, const scalar & u, const scalar & v, const scalar & w, const symmTensor & sigma) static protected
Definition at line 234 of file equilibriumMomentFunctions.C.
References m0(), and moments.
moment310()
void moment310 (mappedScalarList & Meq_, const scalar & m0, const scalar & u, const scalar & v, const scalar & w, const symmTensor & sigma) static protected
Definition at line 246 of file equilibriumMomentFunctions.C.
References m0(), and moments.
moment400()
void moment400 (mappedScalarList & Meq_, const scalar & m0, const scalar & u, const scalar & v, const scalar & w, const symmTensor & sigma) static protected
Definition at line 258 of file equilibriumMomentFunctions.C.
References m0(), and moments.
moment005()
void moment005 (mappedScalarList & Meq_, const scalar & m0, const scalar & u, const scalar & v, const scalar & w, const symmTensor & sigma) static protected
Definition at line 266 of file equilibriumMomentFunctions.C.
References m0(), and moments.
moment014()
void moment014 (mappedScalarList & Meq_, const scalar & m0, const scalar & u, const scalar & v, const scalar & w, const symmTensor & sigma) static protected
Definition at line 272 of file equilibriumMomentFunctions.C.
References m0(), and moments.
moment023()
void moment023 (mappedScalarList & Meq_, const scalar & m0, const scalar & u, const scalar & v, const scalar & w, const symmTensor & sigma) static protected
Definition at line 285 of file equilibriumMomentFunctions.C.
References m0(), and moments.
moment032()
void moment032 (mappedScalarList & Meq_, const scalar & m0, const scalar & u, const scalar & v, const scalar & w, const symmTensor & sigma) static protected
Definition at line 300 of file equilibriumMomentFunctions.C.
References m0(), and moments.
moment041()
void moment041 (mappedScalarList & Meq_, const scalar & m0, const scalar & u, const scalar & v, const scalar & w, const symmTensor & sigma) static protected
Definition at line 315 of file equilibriumMomentFunctions.C.
References m0(), and moments.
moment050()
void moment050 (mappedScalarList & Meq_, const scalar & m0, const scalar & u, const scalar & v, const scalar & w, const symmTensor & sigma) static protected
Definition at line 328 of file equilibriumMomentFunctions.C.
References m0(), and moments.
moment104()
void moment104 (mappedScalarList & Meq_, const scalar & m0, const scalar & u, const scalar & v, const scalar & w, const symmTensor & sigma) static protected
Definition at line 334 of file equilibriumMomentFunctions.C.
References m0(), and moments.
moment140()
void moment140 (mappedScalarList & Meq_, const scalar & m0, const scalar & u, const scalar & v, const scalar & w, const symmTensor & sigma) static protected
Definition at line 347 of file equilibriumMomentFunctions.C.
References m0(), and moments.
moment203()
void moment203 (mappedScalarList & Meq_, const scalar & m0, const scalar & u, const scalar & v, const scalar & w, const symmTensor & sigma) static protected
Definition at line 360 of file equilibriumMomentFunctions.C.
References m0(), and moments.
moment230()
void moment230 (mappedScalarList & Meq_, const scalar & m0, const scalar & u, const scalar & v, const scalar & w, const symmTensor & sigma) static protected
Definition at line 375 of file equilibriumMomentFunctions.C.
References m0(), and moments.
moment302()
void moment302 (mappedScalarList & Meq_, const scalar & m0, const scalar & u, const scalar & v, const scalar & w, const symmTensor & sigma) static protected
Definition at line 390 of file equilibriumMomentFunctions.C.
References m0(), and moments.
moment320()
void moment320 (mappedScalarList & Meq_, const scalar & m0, const scalar & u, const scalar & v, const scalar & w, const symmTensor & sigma) static protected
Definition at line 405 of file equilibriumMomentFunctions.C.
References m0(), and moments.
moment401()
void moment401 (mappedScalarList & Meq_, const scalar & m0, const scalar & u, const scalar & v, const scalar & w, const symmTensor & sigma) static protected
Definition at line 420 of file equilibriumMomentFunctions.C.
References m0(), and moments.
moment410()
void moment410 (mappedScalarList & Meq_, const scalar & m0, const scalar & u, const scalar & v, const scalar & w, const symmTensor & sigma) static protected
Definition at line 433 of file equilibriumMomentFunctions.C.
References m0(), and moments.
moment500()
void moment500 (mappedScalarList & Meq_, const scalar & m0, const scalar & u, const scalar & v, const scalar & w, const symmTensor & sigma) static protected
Definition at line 446 of file equilibriumMomentFunctions.C.
References m0(), and moments.
moment015()
void moment015 (mappedScalarList & Meq_, const scalar & m0, const scalar & u, const scalar & v, const scalar & w, const symmTensor & sigma) static protected
Definition at line 454 of file equilibriumMomentFunctions.C.
References m0(), and moments.
moment024()
void moment024 (mappedScalarList & Meq_, const scalar & m0, const scalar & u, const scalar & v, const scalar & w, const symmTensor & sigma) static protected
Definition at line 468 of file equilibriumMomentFunctions.C.
References m0(), and moments.
moment042()
void moment042 (mappedScalarList & Meq_, const scalar & m0, const scalar & u, const scalar & v, const scalar & w, const symmTensor & sigma) static protected
Definition at line 486 of file equilibriumMomentFunctions.C.
References m0(), and moments.
moment051()
void moment051 (mappedScalarList & Meq_, const scalar & m0, const scalar & u, const scalar & v, const scalar & w, const symmTensor & sigma) static protected
Definition at line 504 of file equilibriumMomentFunctions.C.
References m0(), and moments.
moment204()
void moment204 (mappedScalarList & Meq_, const scalar & m0, const scalar & u, const scalar & v, const scalar & w, const symmTensor & sigma) static protected
Definition at line 546 of file equilibriumMomentFunctions.C.
References m0(), and moments.
moment240()
void moment240 (mappedScalarList & Meq_, const scalar & m0, const scalar & u, const scalar & v, const scalar & w, const symmTensor & sigma) static protected
Definition at line 564 of file equilibriumMomentFunctions.C.
References m0(), and moments.
moment105()
void moment105 (mappedScalarList & Meq_, const scalar & m0, const scalar & u, const scalar & v, const scalar & w, const symmTensor & sigma) static protected
Definition at line 518 of file equilibriumMomentFunctions.C.
References m0(), and moments.
moment150()
void moment150 (mappedScalarList & Meq_, const scalar & m0, const scalar & u, const scalar & v, const scalar & w, const symmTensor & sigma) static protected
Definition at line 532 of file equilibriumMomentFunctions.C.
References m0(), and moments.
moment402()
void moment402 (mappedScalarList & Meq_, const scalar & m0, const scalar & u, const scalar & v, const scalar & w, const symmTensor & sigma) static protected
Definition at line 582 of file equilibriumMomentFunctions.C.
References m0(), and moments.
moment420()
void moment420 (mappedScalarList & Meq_, const scalar & m0, const scalar & u, const scalar & v, const scalar & w, const symmTensor & sigma) static protected
Definition at line 600 of file equilibriumMomentFunctions.C.
References m0(), and moments.
moment501()
void moment501 (mappedScalarList & Meq_, const scalar & m0, const scalar & u, const scalar & v, const scalar & w, const symmTensor & sigma) static protected
Definition at line 618 of file equilibriumMomentFunctions.C.
References m0(), and moments.
moment510()
void moment510 (mappedScalarList & Meq_, const scalar & m0, const scalar & u, const scalar & v, const scalar & w, const symmTensor & sigma) static protected
Definition at line 632 of file equilibriumMomentFunctions.C.
References m0(), and moments.
moment025()
void moment025 (mappedScalarList & Meq_, const scalar & m0, const scalar & u, const scalar & v, const scalar & w, const symmTensor & sigma) static protected
Definition at line 646 of file equilibriumMomentFunctions.C.
References m0(), and moments.
moment052()
void moment052 (mappedScalarList & Meq_, const scalar & m0, const scalar & u, const scalar & v, const scalar & w, const symmTensor & sigma) static protected
Definition at line 665 of file equilibriumMomentFunctions.C.
References m0(), and moments.
moment205()
void moment205 (mappedScalarList & Meq_, const scalar & m0, const scalar & u, const scalar & v, const scalar & w, const symmTensor & sigma) static protected
Definition at line 684 of file equilibriumMomentFunctions.C.
References m0(), and moments.
moment250()
void moment250 (mappedScalarList & Meq_, const scalar & m0, const scalar & u, const scalar & v, const scalar & w, const symmTensor & sigma) static protected
Definition at line 703 of file equilibriumMomentFunctions.C.
References m0(), and moments.
moment502()
void moment502 (mappedScalarList & Meq_, const scalar & m0, const scalar & u, const scalar & v, const scalar & w, const symmTensor & sigma) static protected
Definition at line 722 of file equilibriumMomentFunctions.C.
References m0(), and moments.
moment520()
void moment520 (mappedScalarList & Meq_, const scalar & m0, const scalar & u, const scalar & v, const scalar & w, const symmTensor & sigma) static protected
Definition at line 741 of file equilibriumMomentFunctions.C.
References m0(), and moments.
TypeName()
TypeName ("BGK")
Runtime type information.
implicit()
virtual bool implicit () const inline virtual
Is an implicit source used.
Reimplemented from collisionKernel.
Definition at line 241 of file BGKCollision.H.
References collisionKernel::implicit_.
updateCells()
void updateCells (const label celli) virtual
Update equilibrium moments.
Monodisperse case
Do not compute null moment sets
Implements collisionKernel.
Definition at line 119 of file BGKCollision.C.
References forAll(), m0(), max(), moments, quadratureNode< scalarType, vectorType >::primaryWeight(), and velocityQuadratureNode< scalarType, vectorType >::velocityAbscissae().
explicitCollisionSource()
Foam::scalar explicitCollisionSource (const labelList & momentOrder, const label celli) const virtual
Return explicit collision source term.
Return calculated source
Implements collisionKernel.
Reimplemented in esBGKCollision.
Definition at line 593 of file BGKCollision.C.
implicitCollisionSource()
Foam::tmp< Foam::fvScalarMatrix > implicitCollisionSource (const volVelocityMoment & m) const virtual
Return implicit collision source matrix.
Implements collisionKernel.
Reimplemented in esBGKCollision.
Definition at line 619 of file BGKCollision.C.
References moment< fieldType, nodeType >::cmptOrders().
Member Data Documentation
Meq_
mappedPtrList<volScalarField> Meq_ protected
Equilibrium velocity moments (for each size)
Definition at line 95 of file BGKCollision.H.
equilibriumMomentFunctions_
List<momentFunction> equilibriumMomentFunctions_ protected
List of functions used to calculate equilibrium moments.
Definition at line 98 of file BGKCollision.H.
velocityMoments_
PtrList<mappedScalarList> velocityMoments_ protected
Conditioned velocity moments.
Definition at line 101 of file BGKCollision.H.
Gs_
PtrList<PtrList<mappedScalarList> > Gs_ protected
Size conditioned equilibrium veloicity moments (Gaussian)
Definition at line 104 of file BGKCollision.H.
Ks_
scalarListList Ks_ protected
Collisional times.
Definition at line 107 of file BGKCollision.H.
minM0_
scalar minM0_ protected
Minimum volume fraction.
Definition at line 110 of file BGKCollision.H.
The documentation for this class was generated from the following files:
BGKCollision.H
BGKCollision.C
equilibriumMomentFunctions.C