OpenQBMM: breakupKernel Class Reference
breakupKernel Class Reference abstract
Abstract class for breakup kernels.
Public Member Functions
TypeName ("breakupKernel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, breakupKernel, dictionary,(const dictionary &dict, const fvMesh &mesh),(dict, mesh))
breakupKernel (const dictionary &dict, const fvMesh &mesh)
Construct from components.
breakupKernel (const breakupKernel &)=delete
Disallow default bitwise copy construct.
virtual ~breakupKernel ()
Destructor.
virtual scalar Kb (const scalar &abscissa, const label celli, const label environment=0) const =0
Breakup kernel.
scalar breakupSource (const labelList &momentOrder, const label celli, const scalarQuadratureApproximation &quadrature)
Return Breakup source term.
scalar breakupSource (const labelList &momentOrder, const label celli, const velocityQuadratureApproximation &quadrature)
Return Breakup source term.
void operator= (const breakupKernel &)=delete
Disallow default bitwise assignment.
Static Public Member Functions
static autoPtr< breakupKernel > New (const dictionary &dict, const fvMesh &mesh)
Protected Member Functions
scalar nodeSource (const scalar &abscissa, const label momentOrder) const
Length based breakup source given two abscissae and an order.
scalar massNodeSource (const scalar &abscissa, const label momentOrder) const
Mass based breakup source given two abscissae and an order.
Protected Attributes
const dictionary & dict_
Dictionary.
const fvMesh & mesh_
Mesh.
const dimensionedScalar Cb_
Coefficient of breakup kernel.
autoPtr< Foam::populationBalanceSubModels::daughterDistribution > daughterDistribution_
Daughter distribution function.
Detailed Description
Abstract class for breakup kernels.
Source files
breakupKernel.H
breakupKernel.C
Definition at line 55 of file breakupKernel.H.
Constructor & Destructor Documentation
breakupKernel() [1/2]
breakupKernel (const dictionary & dict, const fvMesh & mesh)
Construct from components.
Definition at line 44 of file breakupKernel.C.
breakupKernel() [2/2]
breakupKernel (const breakupKernel &) delete
Disallow default bitwise copy construct.
~breakupKernel()
~breakupKernel () virtual
Destructor.
Definition at line 71 of file breakupKernel.C.
Member Function Documentation
nodeSource()
Foam::scalar nodeSource (const scalar & abscissa, const label momentOrder) const protected
Length based breakup source given two abscissae and an order.
Definition at line 77 of file breakupKernel.C.
massNodeSource()
Foam::scalar massNodeSource (const scalar & abscissa, const label momentOrder) const protected
Mass based breakup source given two abscissae and an order.
Definition at line 90 of file breakupKernel.C.
TypeName()
TypeName ("breakupKernel")
Runtime type information.
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , breakupKernel , dictionary , (const dictionary &dict, const fvMesh &mesh) , (dict, mesh))
New()
Foam::autoPtr< Foam::populationBalanceSubModels::breakupKernel > New (const dictionary & dict, const fvMesh & mesh) static
Definition at line 32 of file newBreakupKernel.C.
Referenced by sizeVelocityPopulationBalance::sizeVelocityPopulationBalance(), and univariatePopulationBalance::univariatePopulationBalance().
Kb()
virtual scalar Kb (const scalar & abscissa, const label celli, const label environment = 0) const pure virtual
Breakup kernel.
Implemented in AyaziShamlou, LuoSvendsen, exponentialBreakup, powerLawBreakup, and constantBreakup.
breakupSource() [1/2]
Foam::scalar breakupSource (const labelList & momentOrder, const label celli, const scalarQuadratureApproximation & quadrature)
Return Breakup source term.
Definition at line 103 of file breakupKernel.C.
References forAll(), max(), nodes, quadratureNode< scalarType, vectorType >::primaryAbscissae(), quadratureNode< scalarType, vectorType >::primaryWeight(), quadrature, quadratureNode< scalarType, vectorType >::secondaryAbscissae(), quadratureNode< scalarType, vectorType >::secondaryWeights(), and sizeIndex.
breakupSource() [2/2]
Foam::scalar breakupSource (const labelList & momentOrder, const label celli, const velocityQuadratureApproximation & quadrature)
Return Breakup source term.
Definition at line 248 of file breakupKernel.C.
References forAll(), max(), nodes, quadratureNode< scalarType, vectorType >::primaryAbscissae(), quadratureNode< scalarType, vectorType >::primaryWeight(), quadrature, quadratureNode< scalarType, vectorType >::secondaryAbscissae(), quadratureNode< scalarType, vectorType >::secondaryWeights(), sizeIndex, velocityQuadratureNode< scalarType, vectorType >::velocityAbscissae(), and velocityIndexes().
operator=()
void operator= (const breakupKernel &) delete
Disallow default bitwise assignment.
Member Data Documentation
dict_
const dictionary& dict_ protected
Dictionary.
Definition at line 62 of file breakupKernel.H.
mesh_
const fvMesh& mesh_ protected
Mesh.
Definition at line 65 of file breakupKernel.H.
Cb_
const dimensionedScalar Cb_ protected
Coefficient of breakup kernel.
Definition at line 68 of file breakupKernel.H.
daughterDistribution_
autoPtr< Foam::populationBalanceSubModels::daughterDistribution > daughterDistribution_ protected
Daughter distribution function.
Definition at line 74 of file breakupKernel.H.
The documentation for this class was generated from the following files:
breakupKernel.H
breakupKernel.C
newBreakupKernel.C