OpenQBMM: esBGKCollision Class Reference
esBGKCollision Class Reference
Collision model which returns the velocity distribution to a Maxwellian distribution (multivariate Gaussian) with at a given collisional time scale. Used as a base class for esBGK as well, but a different covariance tensor is used as well a variable collision time scale. Polydispersity is also handled, but a variabel time scale is used.
Public Member Functions
TypeName ("esBGK")
Runtime type information.
esBGKCollision (const dictionary &dict, const fvMesh &mesh, const velocityQuadratureApproximation &quadrature)
Construct from components.
virtual ~esBGKCollision ()
Destructor.
virtual scalar explicitCollisionSource (const labelList &momentOrder, const label celli) const
Return explicit collision source term.
virtual tmp< fvScalarMatrix > implicitCollisionSource (const volVelocityMoment &m) const
Return implicit collision source matrix.
Public Member Functions inherited from BGKCollision
TypeName ("BGK")
Runtime type information.
BGKCollision (const dictionary &dict, const fvMesh &mesh, const velocityQuadratureApproximation &quadrature)
Construct from components.
virtual ~BGKCollision ()
Destructor.
virtual bool implicit () const
Is an implicit source used.
virtual void updateCells (const label celli)
Update equilibrium moments.
Public Member Functions inherited from collisionKernel
TypeName ("collisionKernel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, collisionKernel, dictionary,(const dictionary &dict, const fvMesh &mesh, const velocityQuadratureApproximation &quadrature),(dict, mesh, quadrature))
collisionKernel (const dictionary &dict, const fvMesh &mesh, const velocityQuadratureApproximation &quadrature)
Construct from components.
collisionKernel (const collisionKernel &)=delete
Disallow default bitwise copy construct.
virtual ~collisionKernel ()
Destructor.
virtual void preUpdate ()
Update unchanged fields before solving ode system.
virtual void updateFields ()
Update collision sources.
void operator= (const collisionKernel &)=delete
Disallow default bitwise assignment.
Protected Member Functions
virtual symmTensor covariance (const label celli, const scalar &u, const scalar &v, const scalar &w)
Return the covariance tensor using quadrature moments.
virtual symmTensor covariance (const mappedScalarList &moments, const scalar &u, const scalar &v, const scalar &w)
Return the covariance tensor given a list of moments.
virtual scalar e () const
Return the coefficient of restitution.
Protected Member Functions inherited from collisionKernel
scalar d (const label node, const label celli) const
Return the diameter given a node and cell.
Additional Inherited Members
Static Public Member Functions inherited from collisionKernel
static autoPtr< collisionKernel > New (const dictionary &dict, const fvMesh &mesh, const velocityQuadratureApproximation &quadrature)
Protected Types inherited from BGKCollision
typedef void(* momentFunction) (mappedScalarList &Meq, const scalar &, const scalar &, const scalar &, const scalar &, const symmTensor &)
Typedef of function pointer list.
Static Protected Member Functions inherited from BGKCollision
static void moment000 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
Functions used to define equilibrium moments.
static void moment001 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment010 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment100 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment002 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment011 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment020 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment101 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment110 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment200 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment003 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment012 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment021 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment030 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment102 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment111 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment120 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment201 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment210 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment300 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment004 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment013 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment022 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment031 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment040 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment103 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment130 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment202 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment220 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment301 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment310 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment400 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment005 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment014 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment023 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment032 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment041 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment050 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment104 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment140 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment203 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment230 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment302 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment320 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment401 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment410 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment500 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment015 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment024 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment042 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment051 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment204 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment240 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment105 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment150 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment402 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment420 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment501 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment510 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment025 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment052 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment205 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment250 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment502 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
static void moment520 (mappedScalarList &Meq_, const scalar &m0, const scalar &u, const scalar &v, const scalar &w, const symmTensor &sigma)
Static Protected Member Functions inherited from collisionKernel
static tmp< volScalarField > lookupOrInitialize (const fvMesh &mesh, const word &name, const dictionary &dict, const word &entryName, const dimensionSet &dims)
Protected Attributes inherited from BGKCollision
mappedPtrList< volScalarField > Meq_
Equilibrium velocity moments (for each size)
List< momentFunction > equilibriumMomentFunctions_
List of functions used to calculate equilibrium moments.
PtrList< mappedScalarList > velocityMoments_
Conditioned velocity moments.
PtrList< PtrList< mappedScalarList > > Gs_
Size conditioned equilibrium veloicity moments (Gaussian)
scalarListList Ks_
Collisional times.
scalar minM0_
Minimum volume fraction.
Protected Attributes inherited from collisionKernel
const dictionary & dict_
Dictionary.
const fvMesh & mesh_
Mesh.
const velocityQuadratureApproximation & quadrature_
Quadrature approximation.
const labelListList & momentOrders_
Moment indicies ues to map moments.
const labelListList & nodeIndexes_
Nodes indexes.
const labelList & velocityIndexes_
Velocity indexes.
const label nDimensions_
Number of dimensions.
labelListList velocityMomentOrders_
List of velocity moment orders.
labelListList velocityNodeIndexes_
List of velocity node indexes.
label sizeIndex_
Size index.
label nSizes_
Number of sizes.
tmp< volScalarField > dp_
Refrence to particle diameter.
scalarList rhos_
List of patricle densities.
scalar minD_
Minimum diameter.
Switch implicit_
Is an implicit solution used.
Detailed Description
Collision model which returns the velocity distribution to a Maxwellian distribution (multivariate Gaussian) with at a given collisional time scale. Used as a base class for esBGK as well, but a different covariance tensor is used as well a variable collision time scale. Polydispersity is also handled, but a variabel time scale is used.
Extension of the BGK collisional model that includes the coefficient of restitution.
Source files
BGKCollision.H
BGKCollision.C
equilibriumMomentFunctions.C
Source files
esBGKCollision.H
esBGKCollision.C
Definition at line 54 of file esBGKCollision.H.
Constructor & Destructor Documentation
esBGKCollision()
esBGKCollision (const dictionary & dict, const fvMesh & mesh, const velocityQuadratureApproximation & quadrature)
Construct from components.
Definition at line 154 of file esBGKCollision.C.
~esBGKCollision()
~esBGKCollision () virtual
Destructor.
Definition at line 186 of file esBGKCollision.C.
Member Function Documentation
covariance() [1/2]
Foam::symmTensor covariance (const label celli, const scalar & u, const scalar & v, const scalar & w) protected virtual
Return the covariance tensor using quadrature moments.
Reimplemented from BGKCollision.
Definition at line 53 of file esBGKCollision.C.
References m0(), max(), and moments.
covariance() [2/2]
Foam::symmTensor covariance (const mappedScalarList & moments, const scalar & u, const scalar & v, const scalar & w) protected virtual
Return the covariance tensor given a list of moments.
Reimplemented from BGKCollision.
Definition at line 104 of file esBGKCollision.C.
References m0(), max(), and moments.
e()
virtual scalar e () const inline protected virtual
Return the coefficient of restitution.
Reimplemented from BGKCollision.
Definition at line 102 of file esBGKCollision.H.
TypeName()
TypeName ("esBGK")
Runtime type information.
explicitCollisionSource()
Foam::scalar explicitCollisionSource (const labelList & momentOrder, const label celli) const virtual
Return explicit collision source term.
Reimplemented from BGKCollision.
Definition at line 195 of file esBGKCollision.C.
References max().
implicitCollisionSource()
Foam::tmp< Foam::fvScalarMatrix > implicitCollisionSource (const volVelocityMoment & m) const virtual
Return implicit collision source matrix.
Reimplemented from BGKCollision.
Definition at line 229 of file esBGKCollision.C.
References moment< fieldType, nodeType >::cmptOrders(), and max().
The documentation for this class was generated from the following files:
esBGKCollision.H
esBGKCollision.C