OpenQBMM: BoltzmannCollision Class Reference
BoltzmannCollision Class Reference
Analytical expansion of Boltzmann collision intergral for monodisperse and polydisperse particulate systems.
Public Member Functions
TypeName ("Boltzmann")
Runtime type information.
BoltzmannCollision (const dictionary &dict, const fvMesh &mesh, const velocityQuadratureApproximation &quadrature)
Construct from components.
virtual ~BoltzmannCollision ()
Destructor.
virtual void preUpdate ()
Update unchanged fields before solving ode system.
virtual void updateCells (const label celli)
Update equilibrium moments.
virtual scalar explicitCollisionSource (const labelList &momentOrder, const label celli) const
Return explicit collision source term.
virtual tmp< fvScalarMatrix > implicitCollisionSource (const volVelocityMoment &m) const
Return implicit collision source matrix.
Public Member Functions inherited from collisionKernel
TypeName ("collisionKernel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, collisionKernel, dictionary,(const dictionary &dict, const fvMesh &mesh, const velocityQuadratureApproximation &quadrature),(dict, mesh, quadrature))
collisionKernel (const dictionary &dict, const fvMesh &mesh, const velocityQuadratureApproximation &quadrature)
Construct from components.
collisionKernel (const collisionKernel &)=delete
Disallow default bitwise copy construct.
virtual ~collisionKernel ()
Destructor.
virtual bool implicit () const
Is an implicit source used.
virtual void updateFields ()
Update collision sources.
void operator= (const collisionKernel &)=delete
Disallow default bitwise assignment.
Additional Inherited Members
Static Public Member Functions inherited from collisionKernel
static autoPtr< collisionKernel > New (const dictionary &dict, const fvMesh &mesh, const velocityQuadratureApproximation &quadrature)
Protected Member Functions inherited from collisionKernel
scalar d (const label node, const label celli) const
Return the diameter given a node and cell.
Static Protected Member Functions inherited from collisionKernel
static tmp< volScalarField > lookupOrInitialize (const fvMesh &mesh, const word &name, const dictionary &dict, const word &entryName, const dimensionSet &dims)
Protected Attributes inherited from collisionKernel
const dictionary & dict_
Dictionary.
const fvMesh & mesh_
Mesh.
const velocityQuadratureApproximation & quadrature_
Quadrature approximation.
const labelListList & momentOrders_
Moment indicies ues to map moments.
const labelListList & nodeIndexes_
Nodes indexes.
const labelList & velocityIndexes_
Velocity indexes.
const label nDimensions_
Number of dimensions.
labelListList velocityMomentOrders_
List of velocity moment orders.
labelListList velocityNodeIndexes_
List of velocity node indexes.
label sizeIndex_
Size index.
label nSizes_
Number of sizes.
tmp< volScalarField > dp_
Refrence to particle diameter.
scalarList rhos_
List of patricle densities.
scalar minD_
Minimum diameter.
Switch implicit_
Is an implicit solution used.
Detailed Description
Analytical expansion of Boltzmann collision intergral for monodisperse and polydisperse particulate systems.
Reference:
    "Computational Models for Polydisperse Particulate and Multiphase Systems"
    Marchisio, D.L., Fox, R.O.,
    Cambridge Core, 2013
Source files
BoltzmannCollision.H
BoltzmannCollision.C
ICoefficientFunctions.C
IxCoefficientFunctions.C
IyCoefficientFunctions.C
IzCoefficientFunctions.C
Definition at line 103 of file BoltzmannCollision.H.
Constructor & Destructor Documentation
BoltzmannCollision()
BoltzmannCollision (const dictionary & dict, const fvMesh & mesh, const velocityQuadratureApproximation & quadrature)
Construct from components.
Check if moments exist and add coefficient functions
Definition at line 119 of file BoltzmannCollision.C.
References addIFunction1, addIFunction2, addIFunction3, forAll(), mappedList< scalar >::listToWord(), and quadrature.
~BoltzmannCollision()
~BoltzmannCollision () virtual
Destructor.
Definition at line 308 of file BoltzmannCollision.C.
Member Function Documentation
TypeName()
TypeName ("Boltzmann")
Runtime type information.
preUpdate()
void preUpdate () virtual
Update unchanged fields before solving ode system.
Reimplemented from collisionKernel.
Definition at line 315 of file BoltzmannCollision.C.
References forAll().
updateCells()
void updateCells (const label celli) virtual
Update equilibrium moments.
Zero order source term
Enskog term
Zero order source term
Enskog term
Implements collisionKernel.
Definition at line 329 of file BoltzmannCollision.C.
References forAll(), quadratureNode< scalarType, vectorType >::primaryAbscissae(), quadratureNode< scalarType, vectorType >::primaryWeight(), and velocityQuadratureNode< scalarType, vectorType >::velocityAbscissae().
explicitCollisionSource()
Foam::scalar explicitCollisionSource (const labelList & momentOrder, const label celli) const virtual
Return explicit collision source term.
Implements collisionKernel.
Definition at line 538 of file BoltzmannCollision.C.
implicitCollisionSource()
Foam::tmp< Foam::fvScalarMatrix > implicitCollisionSource (const volVelocityMoment & m) const virtual
Return implicit collision source matrix.
Implements collisionKernel.
Definition at line 549 of file BoltzmannCollision.C.
References moment< fieldType, nodeType >::cmptOrders().
The documentation for this class was generated from the following files:
BoltzmannCollision.H
BoltzmannCollision.C
ICoefficientFunctions.C
IxCoefficientFunctions.C
IyCoefficientFunctions.C
IzCoefficientFunctions.C