OpenQBMM: collisionKernel Class Reference
collisionKernel Class Reference abstract
Abstract class for collision kernels.
Public Member Functions
TypeName ("collisionKernel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, collisionKernel, dictionary,(const dictionary &dict, const fvMesh &mesh, const velocityQuadratureApproximation &quadrature),(dict, mesh, quadrature))
collisionKernel (const dictionary &dict, const fvMesh &mesh, const velocityQuadratureApproximation &quadrature)
Construct from components.
collisionKernel (const collisionKernel &)=delete
Disallow default bitwise copy construct.
virtual ~collisionKernel ()
Destructor.
virtual bool implicit () const
Is an implicit source used.
virtual void preUpdate ()
Update unchanged fields before solving ode system.
virtual void updateCells (const label celli)=0
Update collision sources in a cell.
virtual void updateFields ()
Update collision sources.
virtual scalar explicitCollisionSource (const labelList &momentOrder, const label celli) const =0
Return explicit collision source term.
virtual tmp< fvScalarMatrix > implicitCollisionSource (const volVelocityMoment &m) const =0
Return implicit collision source matrix.
void operator= (const collisionKernel &)=delete
Disallow default bitwise assignment.
Static Public Member Functions
static autoPtr< collisionKernel > New (const dictionary &dict, const fvMesh &mesh, const velocityQuadratureApproximation &quadrature)
Protected Member Functions
scalar d (const label node, const label celli) const
Return the diameter given a node and cell.
Static Protected Member Functions
static tmp< volScalarField > lookupOrInitialize (const fvMesh &mesh, const word &name, const dictionary &dict, const word &entryName, const dimensionSet &dims)
Protected Attributes
const dictionary & dict_
Dictionary.
const fvMesh & mesh_
Mesh.
const velocityQuadratureApproximation & quadrature_
Quadrature approximation.
const labelListList & momentOrders_
Moment indicies ues to map moments.
const labelListList & nodeIndexes_
Nodes indexes.
const labelList & velocityIndexes_
Velocity indexes.
const label nDimensions_
Number of dimensions.
labelListList velocityMomentOrders_
List of velocity moment orders.
labelListList velocityNodeIndexes_
List of velocity node indexes.
label sizeIndex_
Size index.
label nSizes_
Number of sizes.
tmp< volScalarField > dp_
Refrence to particle diameter.
scalarList rhos_
List of patricle densities.
scalar minD_
Minimum diameter.
Switch implicit_
Is an implicit solution used.
Detailed Description
Abstract class for collision kernels.
Source files
collisionKernel.H
collisionKernel.C
Definition at line 56 of file collisionKernel.H.
Constructor & Destructor Documentation
collisionKernel() [1/2]
collisionKernel (const dictionary & dict, const fvMesh & mesh, const velocityQuadratureApproximation & quadrature)
Construct from components.
Definition at line 101 of file collisionKernel.C.
References forAll(), max(), quadrature, and rho.
collisionKernel() [2/2]
collisionKernel (const collisionKernel &) delete
Disallow default bitwise copy construct.
~collisionKernel()
~collisionKernel () virtual
Destructor.
Definition at line 240 of file collisionKernel.C.
Member Function Documentation
lookupOrInitialize()
Foam::tmp< Foam::volScalarField > lookupOrInitialize (const fvMesh & mesh, const word & name, const dictionary & dict, const word & entryName, const dimensionSet & dims) static protected
Definition at line 45 of file collisionKernel.C.
d()
Foam::scalar d (const label node, const label celli) const protected
Return the diameter given a node and cell.
Definition at line 75 of file collisionKernel.C.
References quadratureNode< scalarType, vectorType >::lengthBased(), max(), and quadratureNode< scalarType, vectorType >::primaryAbscissae().
TypeName()
TypeName ("collisionKernel")
Runtime type information.
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , collisionKernel , dictionary , (const dictionary &dict, const fvMesh &mesh, const velocityQuadratureApproximation &quadrature) , (dict, mesh, quadrature))
New()
Foam::autoPtr< Foam::populationBalanceSubModels::collisionKernel > New (const dictionary & dict, const fvMesh & mesh, const velocityQuadratureApproximation & quadrature) static
Definition at line 32 of file newCollisionKernel.C.
References quadrature.
implicit()
virtual bool implicit () const inline virtual
Is an implicit source used.
Reimplemented in BGKCollision.
Definition at line 173 of file collisionKernel.H.
References collisionKernel::implicit_.
preUpdate()
void preUpdate () virtual
Update unchanged fields before solving ode system.
Reimplemented in BoltzmannCollision.
Definition at line 247 of file collisionKernel.C.
updateCells()
virtual void updateCells (const label celli) pure virtual
Update collision sources in a cell.
Implemented in BGKCollision, BoltzmannCollision, and noCollision.
updateFields()
void updateFields () virtual
Update collision sources.
Definition at line 251 of file collisionKernel.C.
References forAll().
explicitCollisionSource()
virtual scalar explicitCollisionSource (const labelList & momentOrder, const label celli) const pure virtual
Return explicit collision source term.
Implemented in BGKCollision, BoltzmannCollision, esBGKCollision, and noCollision.
implicitCollisionSource()
virtual tmp<fvScalarMatrix> implicitCollisionSource (const volVelocityMoment & m) const pure virtual
Return implicit collision source matrix.
Implemented in BGKCollision, BoltzmannCollision, esBGKCollision, and noCollision.
operator=()
void operator= (const collisionKernel &) delete
Disallow default bitwise assignment.
Member Data Documentation
dict_
const dictionary& dict_ protected
Dictionary.
Definition at line 63 of file collisionKernel.H.
mesh_
const fvMesh& mesh_ protected
Mesh.
Definition at line 66 of file collisionKernel.H.
quadrature_
const velocityQuadratureApproximation& quadrature_ protected
Quadrature approximation.
Definition at line 69 of file collisionKernel.H.
momentOrders_
const labelListList& momentOrders_ protected
Moment indicies ues to map moments.
Definition at line 72 of file collisionKernel.H.
nodeIndexes_
const labelListList& nodeIndexes_ protected
Nodes indexes.
Definition at line 75 of file collisionKernel.H.
velocityIndexes_
const labelList& velocityIndexes_ protected
Velocity indexes.
Definition at line 78 of file collisionKernel.H.
nDimensions_
const label nDimensions_ protected
Number of dimensions.
Definition at line 81 of file collisionKernel.H.
velocityMomentOrders_
labelListList velocityMomentOrders_ protected
List of velocity moment orders.
Definition at line 84 of file collisionKernel.H.
velocityNodeIndexes_
labelListList velocityNodeIndexes_ protected
List of velocity node indexes.
Definition at line 87 of file collisionKernel.H.
sizeIndex_
label sizeIndex_ protected
Size index.
Definition at line 90 of file collisionKernel.H.
nSizes_
label nSizes_ protected
Number of sizes.
Definition at line 93 of file collisionKernel.H.
dp_
tmp<volScalarField> dp_ protected
Refrence to particle diameter.
Definition at line 96 of file collisionKernel.H.
rhos_
scalarList rhos_ protected
List of patricle densities.
Definition at line 99 of file collisionKernel.H.
minD_
scalar minD_ protected
Minimum diameter.
Definition at line 102 of file collisionKernel.H.
implicit_
Switch implicit_ protected
Is an implicit solution used.
Definition at line 105 of file collisionKernel.H.
Referenced by collisionKernel::implicit(), and BGKCollision::implicit().
The documentation for this class was generated from the following files:
collisionKernel.H
collisionKernel.C
newCollisionKernel.C