OpenQBMM: quadratureNode< scalarType, vectorType > Class Template Reference
quadratureNode< scalarType, vectorType > Class Template Reference
Extended version of the quadrature node, which stores the list of secondary weights and abscissae associated to the primary weight and abscissa, and the sigma parameter.
Classes
class iNew
Return a pointer to a new quadrature node created on freestore.
Public Member Functions
quadratureNode (const word &name, const word &distributionName, const fvMesh &mesh, const dimensionSet &weightDimensions, const PtrList< dimensionSet > &abscissaeDimensions, const wordList &boundaryTypes, const bool extended=false, const label nSecondaryNodes=0)
Construct from name, mesh and dimensions.
quadratureNode (const word &name, const word &distributionName, const fvMesh &mesh, const dimensionSet &weightDimensions, const PtrList< dimensionSet > &abscissaeDimensions, const bool extended=false, const label nSecondaryNodes=0)
Construct from name, number of secondary nodes, mesh and dimensions.
autoPtr< quadratureNode< scalarType, vectorType > > clone () const
Return clone.
virtual ~quadratureNode ()
Destructor.
const word & name () const
Return the name of the node.
const labelList & scalarIndexes () const
Return abscissa indexes.
const labelList & velocityIndexes () const
Return velocity indexes.
label sizeIndex () const
Return size index.
bool lengthBased () const
Is the node length based.
bool useVolumeFraction () const
Is the weight in terms of volume fraction.
bool extended () const
Is the node extended.
label nSecondaryNodes () const
Returns the number of secondary nodes.
const weightType & primaryWeight () const
Const access to the weight of the node.
weightType & primaryWeight ()
Non-const access to the weight of the node.
const abscissaeType & primaryAbscissae () const
Const access to the scalar abscissa of the node.
abscissaeType & primaryAbscissae ()
Non-const access to the scalar abscissa of the node.
const secondaryWeightsType & secondaryWeights () const
Const access to the secondary weights of the node.
secondaryWeightsType & secondaryWeights ()
Non-const access to the secondary weights of the node.
const secondaryAbscissaeType & secondaryAbscissae () const
Const access to the list of secondary abscissae of the node.
secondaryAbscissaeType & secondaryAbscissae ()
Non-const access to the list of secondary abscissae of the node.
const sigmasType & sigmas () const
Const access to sigma.
sigmasType & sigmas ()
Non-const access to sigma.
virtual const velocityAbscissaeType & velocityAbscissae () const
Const access to the velocity abscissa of the node.
virtual velocityAbscissaeType & velocityAbscissae ()
Non-const access to the velcity abscissa of the node.
Protected Types
typedef scalarType weightType
Typedefs.
typedef PtrList< PtrList< weightType > > secondaryWeightsType
typedef scalarType abscissaType
typedef PtrList< abscissaType > abscissaeType
typedef PtrList< abscissaeType > secondaryAbscissaeType
typedef vectorType velocityAbscissaeType
typedef scalarType sigmaType
typedef PtrList< sigmaType > sigmasType
Protected Attributes
word name_
Name of the quadrature node.
weightType weight_
Primary weight of the node.
abscissaeType abscissae_
Primary abscissae of the node.
labelList scalarIndexes_
Indicies of abscissa components.
labelList velocityIndexes_
Indicies of velocity components.
label sizeIndex_
Index of size component.
bool lengthBased_
Is the size length based.
bool useVolumeFraction_
Are weights in volume fraction.
secondaryWeightsType secondaryWeights_
List of secondary weights of the node.
secondaryAbscissaeType secondaryAbscissae_
List of secondary abscissae of the node.
sigmasType sigmas_
Parameter of the kernel density function used in EQMOM.
label nSecondaryNodes_
Number of secondary nodes.
bool extended_
Boolean variable to identify extended nodes.
Detailed Description
template<class scalarType, class vectorType>
class Foam::quadratureNode< scalarType, vectorType >
Extended version of the quadrature node, which stores the list of secondary weights and abscissae associated to the primary weight and abscissa, and the sigma parameter.
Source files
quadratureNode.H
quadratureNode.C
quadratureNodeI.H
Definition at line 55 of file quadratureNode.H.
Member Typedef Documentation
weightType
typedef scalarType weightType protected
Typedefs.
Definition at line 61 of file quadratureNode.H.
secondaryWeightsType
typedef PtrList<PtrList<weightType> > secondaryWeightsType protected
Definition at line 62 of file quadratureNode.H.
abscissaType
typedef scalarType abscissaType protected
Definition at line 64 of file quadratureNode.H.
abscissaeType
typedef PtrList<abscissaType> abscissaeType protected
Definition at line 65 of file quadratureNode.H.
secondaryAbscissaeType
typedef PtrList<abscissaeType> secondaryAbscissaeType protected
Definition at line 66 of file quadratureNode.H.
velocityAbscissaeType
typedef vectorType velocityAbscissaeType protected
Definition at line 68 of file quadratureNode.H.
sigmaType
typedef scalarType sigmaType protected
Definition at line 70 of file quadratureNode.H.
sigmasType
typedef PtrList<sigmaType> sigmasType protected
Definition at line 71 of file quadratureNode.H.
Constructor & Destructor Documentation
quadratureNode() [1/2]
quadratureNode (const word & name, const word & distributionName, const fvMesh & mesh, const dimensionSet & weightDimensions, const PtrList< dimensionSet > & abscissaeDimensions, const wordList & boundaryTypes, const bool extended = false, const label nSecondaryNodes = 0)
Construct from name, mesh and dimensions.
Definition at line 238 of file quadratureNode.C.
References forAll().
quadratureNode() [2/2]
quadratureNode (const word & name, const word & distributionName, const fvMesh & mesh, const dimensionSet & weightDimensions, const PtrList< dimensionSet > & abscissaeDimensions, const bool extended = false, const label nSecondaryNodes = 0)
Construct from name, number of secondary nodes, mesh and dimensions.
Definition at line 27 of file quadratureNode.C.
References forAll().
~quadratureNode()
~quadratureNode () virtual
Destructor.
Definition at line 456 of file quadratureNode.C.
Member Function Documentation
clone()
Foam::autoPtr< Foam::quadratureNode< scalarType, vectorType > > clone () const
Return clone.
Definition at line 463 of file quadratureNode.C.
name()
const Foam::word & name () const
Return the name of the node.
Definition at line 25 of file quadratureNodeI.H.
scalarIndexes()
const Foam::labelList & scalarIndexes () const
Return abscissa indexes.
Definition at line 38 of file quadratureNodeI.H.
Referenced by basicVelocityFieldMomentInversion::invertBoundaryMoments(), and basicVelocityFieldMomentInversion::invertLocalMoments().
velocityIndexes()
const Foam::labelList & velocityIndexes () const
Return velocity indexes.
Definition at line 45 of file quadratureNodeI.H.
sizeIndex()
Foam::label sizeIndex () const
Return size index.
Definition at line 52 of file quadratureNodeI.H.
lengthBased()
bool lengthBased () const
Is the node length based.
Definition at line 58 of file quadratureNodeI.H.
Referenced by collisionKernel::d().
useVolumeFraction()
bool useVolumeFraction () const
Is the weight in terms of volume fraction.
Definition at line 64 of file quadratureNodeI.H.
extended()
bool extended () const
Is the node extended.
Definition at line 31 of file quadratureNodeI.H.
nSecondaryNodes()
Foam::label nSecondaryNodes () const
Returns the number of secondary nodes.
Definition at line 71 of file quadratureNodeI.H.
Referenced by extendedFieldMomentInversion::invertBoundaryMoments().
primaryWeight() [1/2]
const scalarType & primaryWeight () const
Const access to the weight of the node.
Definition at line 78 of file quadratureNodeI.H.
Referenced by aggregationKernel::aggregationSource(), breakupKernel::breakupSource(), firstOrderKinetic::interpolateNodes(), monoKineticQuadratureApproximation::interpolateNodes(), extendedFieldMomentInversion::invertBoundaryMoments(), basicFieldMomentInversion::invertBoundaryMoments(), basicVelocityFieldMomentInversion::invertBoundaryMoments(), extendedFieldMomentInversion::invertLocalMoments(), basicFieldMomentInversion::invertLocalMoments(), basicVelocityFieldMomentInversion::invertLocalMoments(), growthModel::phaseSpaceConvection(), firstOrderKinetic::update(), BoltzmannCollision::updateCells(), BGKCollision::updateCells(), and velocityMomentAdvection::updateWallCollisions().
primaryWeight() [2/2]
scalarType & primaryWeight ()
Non-const access to the weight of the node.
Definition at line 85 of file quadratureNodeI.H.
primaryAbscissae() [1/2]
const Foam::PtrList< scalarType > & primaryAbscissae () const
Const access to the scalar abscissa of the node.
Definition at line 92 of file quadratureNodeI.H.
Referenced by aggregationKernel::aggregationSource(), breakupKernel::breakupSource(), collisionKernel::d(), firstOrderKinetic::interpolateNodes(), monoKineticQuadratureApproximation::interpolateNodes(), extendedFieldMomentInversion::invertBoundaryMoments(), basicFieldMomentInversion::invertBoundaryMoments(), basicVelocityFieldMomentInversion::invertBoundaryMoments(), extendedFieldMomentInversion::invertLocalMoments(), basicFieldMomentInversion::invertLocalMoments(), basicVelocityFieldMomentInversion::invertLocalMoments(), growthModel::phaseSpaceConvection(), firstOrderKinetic::update(), and BoltzmannCollision::updateCells().
primaryAbscissae() [2/2]
Foam::PtrList< scalarType > & primaryAbscissae ()
Non-const access to the scalar abscissa of the node.
Definition at line 99 of file quadratureNodeI.H.
secondaryWeights() [1/2]
const Foam::PtrList< Foam::PtrList< scalarType > > & secondaryWeights () const
Const access to the secondary weights of the node.
Definition at line 106 of file quadratureNodeI.H.
Referenced by aggregationKernel::aggregationSource(), breakupKernel::breakupSource(), extendedFieldMomentInversion::invertBoundaryMoments(), extendedFieldMomentInversion::invertLocalMoments(), and growthModel::phaseSpaceConvection().
secondaryWeights() [2/2]
Foam::PtrList< Foam::PtrList< scalarType > > & secondaryWeights ()
Non-const access to the secondary weights of the node.
Definition at line 121 of file quadratureNodeI.H.
secondaryAbscissae() [1/2]
const Foam::PtrList< Foam::PtrList< scalarType > > & secondaryAbscissae () const
Const access to the list of secondary abscissae of the node.
Definition at line 135 of file quadratureNodeI.H.
Referenced by aggregationKernel::aggregationSource(), breakupKernel::breakupSource(), extendedFieldMomentInversion::invertBoundaryMoments(), extendedFieldMomentInversion::invertLocalMoments(), and growthModel::phaseSpaceConvection().
secondaryAbscissae() [2/2]
Foam::PtrList< Foam::PtrList< scalarType > > & secondaryAbscissae ()
Non-const access to the list of secondary abscissae of the node.
Definition at line 150 of file quadratureNodeI.H.
sigmas() [1/2]
const Foam::PtrList< scalarType > & sigmas () const
Const access to sigma.
Definition at line 165 of file quadratureNodeI.H.
Referenced by extendedFieldMomentInversion::invertBoundaryMoments(), and extendedFieldMomentInversion::invertLocalMoments().
sigmas() [2/2]
Foam::PtrList< scalarType > & sigmas ()
Non-const access to sigma.
Definition at line 180 of file quadratureNodeI.H.
velocityAbscissae() [1/2]
const vectorType & velocityAbscissae () const virtual
Const access to the velocity abscissa of the node.
Reimplemented in velocityQuadratureNode< scalarType, vectorType >.
Definition at line 195 of file quadratureNodeI.H.
Referenced by aggregationKernel::aggregationSource().
velocityAbscissae() [2/2]
vectorType & velocityAbscissae () virtual
Non-const access to the velcity abscissa of the node.
Reimplemented in velocityQuadratureNode< scalarType, vectorType >.
Definition at line 207 of file quadratureNodeI.H.
Member Data Documentation
name_
word name_ protected
Name of the quadrature node.
Definition at line 77 of file quadratureNode.H.
weight_
weightType weight_ protected
Primary weight of the node.
Definition at line 80 of file quadratureNode.H.
abscissae_
abscissaeType abscissae_ protected
Primary abscissae of the node.
Definition at line 83 of file quadratureNode.H.
scalarIndexes_
labelList scalarIndexes_ protected
Indicies of abscissa components.
Definition at line 86 of file quadratureNode.H.
velocityIndexes_
labelList velocityIndexes_ protected
Indicies of velocity components.
Definition at line 89 of file quadratureNode.H.
sizeIndex_
label sizeIndex_ protected
Index of size component.
Definition at line 92 of file quadratureNode.H.
lengthBased_
bool lengthBased_ protected
Is the size length based.
Definition at line 95 of file quadratureNode.H.
useVolumeFraction_
bool useVolumeFraction_ protected
Are weights in volume fraction.
Definition at line 98 of file quadratureNode.H.
secondaryWeights_
secondaryWeightsType secondaryWeights_ protected
List of secondary weights of the node.
Definition at line 101 of file quadratureNode.H.
secondaryAbscissae_
secondaryAbscissaeType secondaryAbscissae_ protected
List of secondary abscissae of the node.
Definition at line 104 of file quadratureNode.H.
sigmas_
sigmasType sigmas_ protected
Parameter of the kernel density function used in EQMOM.
Definition at line 107 of file quadratureNode.H.
nSecondaryNodes_
label nSecondaryNodes_ protected
Number of secondary nodes.
Definition at line 110 of file quadratureNode.H.
extended_
bool extended_ protected
Boolean variable to identify extended nodes.
Definition at line 113 of file quadratureNode.H.
The documentation for this class was generated from the following files:
quadratureNode.H
quadratureNode.C
quadratureNodeI.H