OpenQBMM: univariatePopulationBalance Class Reference
univariatePopulationBalance Class Reference
Public Member Functions
TypeName ("univariate")
Runtime type information.
univariatePopulationBalance (const word &name, const dictionary &dict, const surfaceScalarField &phi)
Construct from components.
virtual ~univariatePopulationBalance ()
Destructor.
virtual scalar realizableCo () const
Return the maximum Courant number ensuring moment realizability.
virtual scalar CoNum () const
Return the courant number based on abscissae.
void solve ()
Solve population balance equation.
virtual bool readIfModified ()
Read.
Public Member Functions inherited from univariatePDFTransportModel
univariatePDFTransportModel (const word &name, const dictionary &dict, const fvMesh &mesh, const surfaceScalarField &phi, const word &support)
Construct from components.
virtual ~univariatePDFTransportModel ()
Destructor.
const scalarQuadratureApproximation & quadrature () const
Access.
scalar realizableCo () const
Return the maximum Courant number ensuring moment realizability.
Public Member Functions inherited from PDFTransportModel
PDFTransportModel (const word &name, const dictionary &dict, const fvMesh &mesh)
Construct from components.
PDFTransportModel (const PDFTransportModel &)=delete
Disallow default bitwise copy construct.
virtual ~PDFTransportModel ()
Destructor.
void operator= (const PDFTransportModel &)=delete
Disallow default bitwise assignment.
Public Member Functions inherited from populationBalanceModel
TypeName ("populationBalanceModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, populationBalanceModel, dictionary,(const word &name, const dictionary &dict, const surfaceScalarField &phi),(name, dict, phi))
populationBalanceModel (const word &name, const dictionary &dict, const surfaceScalarField &phi)
Construct from components.
populationBalanceModel (const populationBalanceModel &)=delete
Disallow default bitwise copy construct.
virtual ~populationBalanceModel ()
Destructor.
virtual bool writeData (Ostream &) const
Read.
void operator= (const populationBalanceModel &)=delete
Disallow default bitwise assignment.
Additional Inherited Members
Static Public Member Functions inherited from populationBalanceModel
static autoPtr< populationBalanceModel > New (const word &name, const dictionary &dict, const surfaceScalarField &phi)
Select null constructed.
Protected Attributes inherited from univariatePDFTransportModel
scalarQuadratureApproximation quadrature_
Univariate quadrature approximation used to solve PDF transport.
autoPtr< univariateMomentAdvection > momentAdvection_
Moment advection.
Protected Attributes inherited from PDFTransportModel
const fvMesh & mesh_
Constant reference to the mesh.
Protected Attributes inherited from populationBalanceModel
IOdictionary & populationBalanceProperties_
Reference to populationBalanceProperties.
const surfaceScalarField & phi_
Fluid-phase face-normal velocity.
Detailed Description
Definition at line 60 of file univariatePopulationBalance.H.
Constructor & Destructor Documentation
univariatePopulationBalance()
univariatePopulationBalance (const word & name, const dictionary & dict, const surfaceScalarField & phi)
Construct from components.
Definition at line 53 of file univariatePopulationBalance.C.
References growthModel::New(), nucleationModel::New(), aggregationKernel::New(), and breakupKernel::New().
~univariatePopulationBalance()
~univariatePopulationBalance () virtual
Destructor.
Definition at line 119 of file univariatePopulationBalance.C.
Member Function Documentation
TypeName()
TypeName ("univariate")
Runtime type information.
realizableCo()
Foam::scalar realizableCo () const virtual
Return the maximum Courant number ensuring moment realizability.
Implements populationBalanceModel.
Definition at line 195 of file univariatePopulationBalance.C.
References univariatePDFTransportModel::realizableCo().
CoNum()
Foam::scalar CoNum () const virtual
Return the courant number based on abscissae.
Implements populationBalanceModel.
Definition at line 203 of file univariatePopulationBalance.C.
solve()
void solve () virtual
Solve population balance equation.
Reimplemented from univariatePDFTransportModel.
Definition at line 239 of file univariatePopulationBalance.C.
References univariatePDFTransportModel::solve().
readIfModified()
bool readIfModified () virtual
Read.
Reimplemented from populationBalanceModel.
Definition at line 246 of file univariatePopulationBalance.C.
The documentation for this class was generated from the following files:
univariatePopulationBalance.H
univariatePopulationBalance.C