OpenQBMM: Vandermonde Class Reference
Vandermonde Class Reference
Stores the second row of a Vandermonde matrix, and solves the associated linear system.
Public Member Functions
Vandermonde (const scalarDiagonalMatrix &A)
Construct from a given vector.
Vandermonde (const scalarSquareMatrix &A, const bool checkVandermonde=false)
Construct from a square Vandermonde matrix.
~Vandermonde ()
Destructor.
void solve (scalarDiagonalMatrix &x, const scalarDiagonalMatrix &source)
Solve the Vandermonde linear system with the given source vector.
scalarSquareMatrix inv ()
Invert Vandermonde matrix.
scalarSquareMatrix operator() ()
Return the complete Vandermonde matrix.
scalar operator() (label i, label j)
Return a given component of the Vandermonde matrix.
Detailed Description
Stores the second row of a Vandermonde matrix, and solves the associated linear system.
References
    William H. Press, Saul A. Teukolsky,
    William T. Vetterling, and Brian P. Flannery. 1992.
    "Numerical Recipes in C (2nd Ed.): The Art of Scientific Computing."
    Cambridge University Press, New York, NY, USA.
Source files
Vandermonde.H
Vandermonde.C
Definition at line 58 of file Vandermonde.H.
Constructor & Destructor Documentation
Vandermonde() [1/2]
Vandermonde (const scalarDiagonalMatrix & A)
Construct from a given vector.
Definition at line 31 of file Vandermonde.C.
Vandermonde() [2/2]
Vandermonde (const scalarSquareMatrix & A, const bool checkVandermonde = false)
Construct from a square Vandermonde matrix.
Definition at line 41 of file Vandermonde.C.
~Vandermonde()
~Vandermonde ()
Destructor.
Definition at line 72 of file Vandermonde.C.
Member Function Documentation
solve()
void solve (scalarDiagonalMatrix & x, const scalarDiagonalMatrix & source)
Solve the Vandermonde linear system with the given source vector.
Definition at line 79 of file Vandermonde.C.
inv()
Foam::scalarSquareMatrix inv ()
Invert Vandermonde matrix.
Definition at line 129 of file Vandermonde.C.
References solve().
Referenced by monoKinetic::invert(), sizeCHyQMOM::invert(), monoKineticQuadratureApproximation::updateBoundaryVelocities(), and monoKineticQuadratureApproximation::updateLocalVelocities().
operator()() [1/2]
Foam::scalarSquareMatrix operator() () inline
Return the complete Vandermonde matrix.
Definition at line 29 of file VandermondeI.H.
operator()() [2/2]
Foam::scalar operator() (label i, label j) inline
Return a given component of the Vandermonde matrix.
Definition at line 44 of file VandermondeI.H.
The documentation for this class was generated from the following files:
Vandermonde.H
Vandermonde.C
VandermondeI.H