OpenQBMM: quadratureApproximation< momentType, nodeType > Class Template Reference
quadratureApproximation< momentType, nodeType > Class Template Reference
Provides storage for the moments and the corresponding quadrature approximation of a distribution function. Methods to update the moments and the quadrature approximation are provided.
Public Member Functions
quadratureApproximation (const word &name, const fvMesh &mesh, const word &support)
Construct from mesh.
quadratureApproximation (const word &dictName, const word &name, const momentFieldSetType &mFieldSet, bool calcQuadratureOnCreation=false)
Construct from dictionary name, name, momentFieldSet.
virtual ~quadratureApproximation ()
Destructor.
const word name () const
Return name.
const labelList & nNodes () const
Return the nmber of nodes in each direction.
fieldMomentInversion & momentFieldInverter ()
Extended moment inversion method.
const mappedPtrList< nodeType > & nodes () const
Const access to the nodes.
mappedPtrList< nodeType > & nodes ()
Non-Const access to the nodes.
const momentFieldSetType & moments () const
Const access to the moments.
momentFieldSetType & moments ()
Non-const access to the moments.
label nDimensions () const
Return the number of dimensions in the distribution.
label nMoments () const
Return the number of moments.
const labelListList & momentOrders () const
Return moment orders.
const labelListList & nodeIndexes () const
return node indexes
void updateQuadrature ()
Recalculate the quadrature nodes from the moments.
void updateBoundaryQuadrature ()
Recalculate the quadrature nodes from the moments.
void updateMoments ()
Recalculate the moments from the quadrature nodes.
void updateLocalMoments (label celli)
Recalculate moments in the specified cell.
bool updateLocalQuadrature (label celli, bool fatalErrorOnFailedRealizabilityTest=true)
Recalculate the quadrature nodes from the moments in the.
Static Public Attributes
static const word propertiesName
Default name of the phase properties dictionary.
Protected Types
typedef momentFieldSet< momentType, nodeType > momentFieldSetType
Protected Attributes
const word name_
Name of the quadrature approximation.
const fvMesh & mesh_
Reference to the mesh.
const dictionary & dict_
const labelListList momentOrders_
Moment orders used to map moments.
const labelListList nodeIndexes_
Node indexes used to map nodes.
labelList nNodes_
Number of nodes in each direction.
autoPtr< mappedPtrList< nodeType > > nodes_
AutoPtr to the mappedPtrList of quadrature nodes.
momentFieldSetType moments_
List of moments.
const label nDimensions_
Dimensionality of the distribution function.
const label nMoments_
Number of moments.
const label nSecondaryNodes_
Number of secondary nodes.
word support_
Support of the distribution function.
autoPtr< fieldMomentInversion > momentFieldInverter_
Extended moment inversion method.
Detailed Description
template<class momentType, class nodeType>
class Foam::quadratureApproximation< momentType, nodeType >
Provides storage for the moments and the corresponding quadrature approximation of a distribution function. Methods to update the moments and the quadrature approximation are provided.
Source files
quadratureApproximation.H
quadratureApproximation.C
quadratureApproximationI.H
Definition at line 61 of file quadratureApproximation.H.
Member Typedef Documentation
momentFieldSetType
typedef momentFieldSet<momentType, nodeType> momentFieldSetType protected
Definition at line 68 of file quadratureApproximation.H.
Constructor & Destructor Documentation
quadratureApproximation() [1/2]
quadratureApproximation (const word & name, const fvMesh & mesh, const word & support)
Construct from mesh.
Definition at line 40 of file quadratureApproximation.C.
quadratureApproximation() [2/2]
quadratureApproximation (const word & dictName, const word & name, const momentFieldSetType & mFieldSet, bool calcQuadratureOnCreation = false)
Construct from dictionary name, name, momentFieldSet.
Moment fields in the momentFieldSet passed as reference are used to initialise the local copy of moments. Inversion on creation is optional.
Definition at line 160 of file quadratureApproximation.C.
~quadratureApproximation()
~quadratureApproximation () virtual
Destructor.
Definition at line 314 of file quadratureApproximation.C.
Member Function Documentation
name()
const word name () const inline
Return name.
Definition at line 30 of file quadratureApproximationI.H.
nNodes()
const labelList & nNodes () const
Return the nmber of nodes in each direction.
Definition at line 37 of file quadratureApproximationI.H.
momentFieldInverter()
Foam::fieldMomentInversion & momentFieldInverter () inline
Extended moment inversion method.
Definition at line 45 of file quadratureApproximationI.H.
nodes() [1/2]
const Foam::mappedPtrList< nodeType > & nodes () const inline
Const access to the nodes.
Definition at line 52 of file quadratureApproximationI.H.
nodes() [2/2]
Foam::mappedPtrList< nodeType > & nodes () inline
Non-Const access to the nodes.
Definition at line 59 of file quadratureApproximationI.H.
moments() [1/2]
const momentFieldSet< momentType, nodeType > & moments () const inline
Const access to the moments.
Definition at line 66 of file quadratureApproximationI.H.
Referenced by univariatePDFTransportModel::solve().
moments() [2/2]
momentFieldSet< momentType, nodeType > & moments () inline
Non-const access to the moments.
Definition at line 73 of file quadratureApproximationI.H.
nDimensions()
Foam::label nDimensions () const inline
Return the number of dimensions in the distribution.
Definition at line 80 of file quadratureApproximationI.H.
nMoments()
Foam::label nMoments () const inline
Return the number of moments.
Definition at line 87 of file quadratureApproximationI.H.
Referenced by univariatePDFTransportModel::solve().
momentOrders()
const Foam::labelListList & momentOrders () const inline
Return moment orders.
Definition at line 94 of file quadratureApproximationI.H.
nodeIndexes()
const Foam::labelListList & nodeIndexes () const inline
return node indexes
Definition at line 101 of file quadratureApproximationI.H.
updateQuadrature()
void updateQuadrature ()
Recalculate the quadrature nodes from the moments.
Definition at line 322 of file quadratureApproximation.C.
Referenced by univariatePDFTransportModel::solve().
updateBoundaryQuadrature()
void updateBoundaryQuadrature ()
Recalculate the quadrature nodes from the moments.
on boundaries
Definition at line 330 of file quadratureApproximation.C.
updateMoments()
void updateMoments ()
Recalculate the moments from the quadrature nodes.
Definition at line 338 of file quadratureApproximation.C.
updateLocalMoments()
void updateLocalMoments (label celli)
Recalculate moments in the specified cell.
Definition at line 345 of file quadratureApproximation.C.
updateLocalQuadrature()
bool updateLocalQuadrature (label celli, bool fatalErrorOnFailedRealizabilityTest = true)
Recalculate the quadrature nodes from the moments in the.
specified cell
Definition at line 352 of file quadratureApproximation.C.
Member Data Documentation
name_
const word name_ protected
Name of the quadrature approximation.
Definition at line 71 of file quadratureApproximation.H.
mesh_
const fvMesh& mesh_ protected
Reference to the mesh.
Definition at line 74 of file quadratureApproximation.H.
dict_
const dictionary& dict_ protected
Definition at line 76 of file quadratureApproximation.H.
momentOrders_
const labelListList momentOrders_ protected
Moment orders used to map moments.
Definition at line 79 of file quadratureApproximation.H.
nodeIndexes_
const labelListList nodeIndexes_ protected
Node indexes used to map nodes.
Definition at line 82 of file quadratureApproximation.H.
nNodes_
labelList nNodes_ protected
Number of nodes in each direction.
Definition at line 85 of file quadratureApproximation.H.
nodes_
autoPtr<mappedPtrList<nodeType> > nodes_ protected
AutoPtr to the mappedPtrList of quadrature nodes.
Definition at line 88 of file quadratureApproximation.H.
moments_
momentFieldSetType moments_ protected
List of moments.
Definition at line 91 of file quadratureApproximation.H.
nDimensions_
const label nDimensions_ protected
Dimensionality of the distribution function.
Definition at line 94 of file quadratureApproximation.H.
nMoments_
const label nMoments_ protected
Number of moments.
Definition at line 97 of file quadratureApproximation.H.
nSecondaryNodes_
const label nSecondaryNodes_ protected
Number of secondary nodes.
Definition at line 100 of file quadratureApproximation.H.
support_
word support_ protected
Support of the distribution function.
Definition at line 103 of file quadratureApproximation.H.
momentFieldInverter_
autoPtr<fieldMomentInversion> momentFieldInverter_ protected
Extended moment inversion method.
Definition at line 106 of file quadratureApproximation.H.
propertiesName
const Foam::word propertiesName static
Default name of the phase properties dictionary.
Definition at line 112 of file quadratureApproximation.H.
The documentation for this class was generated from the following files:
quadratureApproximation.H
quadratureApproximation.C
quadratureApproximationI.H