OpenQBMM: sizeVelocityPopulationBalance Class Reference
sizeVelocityPopulationBalance Class Reference
Public Member Functions
TypeName ("sizeVelocity")
Runtime type information.
sizeVelocityPopulationBalance (const word &name, const dictionary &dict, const surfaceScalarField &phi)
Construct from components.
virtual ~sizeVelocityPopulationBalance ()
Destructor.
Public Member Functions inherited from velocityPopulationBalance
TypeName ("velocity")
Runtime type information.
velocityPopulationBalance (const word &name, const dictionary &dict, const surfaceScalarField &phi)
Construct from components.
virtual ~velocityPopulationBalance ()
Destructor.
virtual scalar realizableCo () const
Return the maximum Courant number ensuring moment realizability.
virtual scalar CoNum () const
Return the maximum Courant number based on velocities.
virtual void solve ()
Solve population balance equation.
virtual bool readIfModified ()
Read.
Public Member Functions inherited from velocityPDFTransportModel
velocityPDFTransportModel (const word &name, const dictionary &dict, const fvMesh &mesh, const word &support)
Construct from components.
virtual ~velocityPDFTransportModel ()
Destructor.
virtual const velocityQuadratureApproximation & quadrature () const
Access.
Public Member Functions inherited from PDFTransportModel
PDFTransportModel (const word &name, const dictionary &dict, const fvMesh &mesh)
Construct from components.
PDFTransportModel (const PDFTransportModel &)=delete
Disallow default bitwise copy construct.
virtual ~PDFTransportModel ()
Destructor.
void operator= (const PDFTransportModel &)=delete
Disallow default bitwise assignment.
Public Member Functions inherited from populationBalanceModel
TypeName ("populationBalanceModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, populationBalanceModel, dictionary,(const word &name, const dictionary &dict, const surfaceScalarField &phi),(name, dict, phi))
populationBalanceModel (const word &name, const dictionary &dict, const surfaceScalarField &phi)
Construct from components.
populationBalanceModel (const populationBalanceModel &)=delete
Disallow default bitwise copy construct.
virtual ~populationBalanceModel ()
Destructor.
virtual bool writeData (Ostream &) const
Read.
void operator= (const populationBalanceModel &)=delete
Disallow default bitwise assignment.
Public Member Functions inherited from realizableOdeSolver< volVelocityMoment, volVelocityNode >
realizableOdeSolver (const fvMesh &mesh, const dictionary &dict)
Construct from components.
virtual ~realizableOdeSolver ()
Destructor.
void solve (quadratureType &quadrature, const label enviroment)
Solve univariate PDF transport equation.
void read (const dictionary &dict)
Read coefficients from dictionary.
Additional Inherited Members
Static Public Member Functions inherited from populationBalanceModel
static autoPtr< populationBalanceModel > New (const word &name, const dictionary &dict, const surfaceScalarField &phi)
Select null constructed.
Protected Types inherited from velocityPopulationBalance
typedef realizableOdeSolver< volVelocityMoment, volVelocityNode > odeType
Protected Member Functions inherited from velocityPopulationBalance
virtual void updateImplicitMomentSource ()
Update implicit collison source terms.
virtual bool solveMomentSources () const
Are moments updated due to sources.
virtual bool solveMomentOde () const
Is the realizable ode solver used to solve sources.
virtual void updateCellMomentSource (const label celli)
Update explicit collison source terms.
Protected Attributes inherited from velocityPopulationBalance
Switch collision_
Switch indicating the status of the aggregation model.
autoPtr< Foam::populationBalanceSubModels::collisionKernel > collisionKernel_
Aggregation kernel model.
Protected Attributes inherited from velocityPDFTransportModel
velocityQuadratureApproximation quadrature_
velocity quadrature approximation used to solve PDF transport
autoPtr< velocityMomentAdvection > momentAdvection_
Moment advection.
Protected Attributes inherited from PDFTransportModel
const fvMesh & mesh_
Constant reference to the mesh.
Protected Attributes inherited from populationBalanceModel
IOdictionary & populationBalanceProperties_
Reference to populationBalanceProperties.
const surfaceScalarField & phi_
Fluid-phase face-normal velocity.
Protected Attributes inherited from realizableOdeSolver< volVelocityMoment, volVelocityNode >
Switch solveSources_
Are the moments updated due to sources.
Switch solveOde_
Is the realizable ode solver used.
Detailed Description
Definition at line 59 of file sizeVelocityPopulationBalance.H.
Constructor & Destructor Documentation
sizeVelocityPopulationBalance()
sizeVelocityPopulationBalance (const word & name, const dictionary & dict, const surfaceScalarField & phi)
Construct from components.
Definition at line 52 of file sizeVelocityPopulationBalance.C.
References diffusionModel::New(), growthModel::New(), nucleationModel::New(), aggregationKernel::New(), and breakupKernel::New().
~sizeVelocityPopulationBalance()
~sizeVelocityPopulationBalance () virtual
Destructor.
Definition at line 117 of file sizeVelocityPopulationBalance.C.
Member Function Documentation
TypeName()
TypeName ("sizeVelocity")
Runtime type information.
The documentation for this class was generated from the following files:
sizeVelocityPopulationBalance.H
sizeVelocityPopulationBalance.C