OpenQBMM: growthModel Class Reference
growthModel Class Reference abstract
Abstract class for growth model.
Public Member Functions
TypeName ("growthModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, growthModel, dictionary,(const dictionary &dict),(dict))
growthModel (const dictionary &dict)
Construct from components.
growthModel (const growthModel &)=delete
Disallow default bitwise copy construct.
virtual ~growthModel ()
Destructor.
virtual scalar Kg (const scalar &abscissa, const label environment=0) const =0
Growth model.
scalar phaseSpaceConvection (const labelList &momentOrder, const label celli, const scalarQuadratureApproximation &quadrature)
Return phase space convection.
scalar phaseSpaceConvection (const labelList &momentOrder, const label celli, const velocityQuadratureApproximation &quadrature)
Return phase space convection.
void operator= (const growthModel &)=delete
Disallow default bitwise assignment.
Static Public Member Functions
static autoPtr< growthModel > New (const dictionary &dict)
Protected Attributes
const dictionary & dict_
const dimensionedScalar Cg_
Coefficient of aggregation kernel.
Detailed Description
Abstract class for growth model.
Source files
growthModel.H
growthModel.C
Definition at line 54 of file growthModel.H.
Constructor & Destructor Documentation
growthModel() [1/2]
growthModel (const dictionary & dict)
Construct from components.
Definition at line 44 of file growthModel.C.
growthModel() [2/2]
growthModel (const growthModel &) delete
Disallow default bitwise copy construct.
~growthModel()
~growthModel () virtual
Destructor.
Definition at line 62 of file growthModel.C.
Member Function Documentation
TypeName()
TypeName ("growthModel")
Runtime type information.
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , growthModel , dictionary , (const dictionary &dict) , (dict))
New()
Foam::autoPtr< Foam::populationBalanceSubModels::growthModel > New (const dictionary & dict) static
Definition at line 32 of file newGrowthModel.C.
Referenced by sizeVelocityPopulationBalance::sizeVelocityPopulationBalance(), and univariatePopulationBalance::univariatePopulationBalance().
Kg()
virtual scalar Kg (const scalar & abscissa, const label environment = 0) const pure virtual
Growth model.
Implemented in constantGrowth.
phaseSpaceConvection() [1/2]
Foam::scalar phaseSpaceConvection (const labelList & momentOrder, const label celli, const scalarQuadratureApproximation & quadrature)
Return phase space convection.
Definition at line 68 of file growthModel.C.
References forAll(), max(), nodes, quadratureNode< scalarType, vectorType >::primaryAbscissae(), quadratureNode< scalarType, vectorType >::primaryWeight(), quadrature, quadratureNode< scalarType, vectorType >::secondaryAbscissae(), quadratureNode< scalarType, vectorType >::secondaryWeights(), and sizeIndex.
phaseSpaceConvection() [2/2]
Foam::scalar phaseSpaceConvection (const labelList & momentOrder, const label celli, const velocityQuadratureApproximation & quadrature)
Return phase space convection.
Definition at line 161 of file growthModel.C.
References forAll(), max(), nodes, quadratureNode< scalarType, vectorType >::primaryAbscissae(), quadratureNode< scalarType, vectorType >::primaryWeight(), quadrature, quadratureNode< scalarType, vectorType >::secondaryAbscissae(), quadratureNode< scalarType, vectorType >::secondaryWeights(), sizeIndex, velocityQuadratureNode< scalarType, vectorType >::velocityAbscissae(), and velocityIndexes().
operator=()
void operator= (const growthModel &) delete
Disallow default bitwise assignment.
Member Data Documentation
dict_
const dictionary& dict_ protected
Definition at line 60 of file growthModel.H.
Cg_
const dimensionedScalar Cg_ protected
Coefficient of aggregation kernel.
Definition at line 63 of file growthModel.H.
The documentation for this class was generated from the following files:
growthModel.H
growthModel.C
newGrowthModel.C