OpenQBMM: monoKineticQuadratureApproximation Class Reference
monoKineticQuadratureApproximation Class Reference
Uses quadrature approximation as a base to handle size moments, while the velocity moments and abscissae are stored in this class. The one dimensional CQMOM inversion is also done.
Public Member Functions
monoKineticQuadratureApproximation (const word &name, const fvMesh &mesh, const word &support)
Construct from mesh.
virtual ~monoKineticQuadratureApproximation ()
Destructor.
const PtrList< volVectorField > & velocities () const
Const access to the velocity abscissae.
PtrList< volVectorField > & velocities ()
Const access to the velocity abscissae.
const PtrList< volVectorField > & velocityMoments () const
Const access to the velocity moments.
PtrList< volVectorField > & velocityMoments ()
Non-const access to the velocity moments.
const PtrList< surfaceScalarNode > & nodesOwn () const
Const access to the interpolated moments (owner)
const PtrList< surfaceVectorField > & velocitiesOwn () const
Const access to the interpolated velocities (owner)
const PtrList< surfaceScalarNode > & nodesNei () const
Const access to the interpolated moments (neighbour)
const PtrList< surfaceVectorField > & velocitiesNei () const
Const access to the interpolated velocities (neighbour)
void interpolateNodes ()
Interpolate nodes.
void updateBoundaryVelocities ()
Update node velocities on fixed-value boundaries.
void updateVelocities ()
Recalculate the velocity abscissae from the velocity moments.
void updateLocalVelocities (const label celli)
Recalculate the velocity abscissae from the velocity moments.
void updateAllQuadrature ()
Recalculate the quadrature nodes from the moments.
bool updateAllLocalQuadrature (const label celli, const bool failOnRealizability=true)
Recalculate the quadrature nodes from the moments.
void updateVelocityMoments ()
Recalculate the moments from the quadrature nodes.
void updateLocalVelocityMoments (const label celli)
Recalculate the moments from the quadrature nodes.
void updateAllMoments ()
Recalculate all moments from the quadrature nodes.
void updateAllLocalMoments (const label celli)
Recalculate all moments from the quadrature nodes.
Public Member Functions inherited from quadratureApproximation< volScalarMoment, volScalarNode >
quadratureApproximation (const word &name, const fvMesh &mesh, const word &support)
Construct from mesh.
quadratureApproximation (const word &dictName, const word &name, const momentFieldSetType &mFieldSet, bool calcQuadratureOnCreation=false)
Construct from dictionary name, name, momentFieldSet.
virtual ~quadratureApproximation ()
Destructor.
const word name () const
Return name.
const labelList & nNodes () const
Return the nmber of nodes in each direction.
fieldMomentInversion & momentFieldInverter ()
Extended moment inversion method.
const mappedPtrList< volScalarNode > & nodes () const
Const access to the nodes.
mappedPtrList< volScalarNode > & nodes ()
Non-Const access to the nodes.
const momentFieldSetType & moments () const
Const access to the moments.
momentFieldSetType & moments ()
Non-const access to the moments.
label nDimensions () const
Return the number of dimensions in the distribution.
label nMoments () const
Return the number of moments.
const labelListList & momentOrders () const
Return moment orders.
const labelListList & nodeIndexes () const
return node indexes
void updateQuadrature ()
Recalculate the quadrature nodes from the moments.
void updateBoundaryQuadrature ()
Recalculate the quadrature nodes from the moments.
void updateMoments ()
Recalculate the moments from the quadrature nodes.
void updateLocalMoments (label celli)
Recalculate moments in the specified cell.
bool updateLocalQuadrature (label celli, bool fatalErrorOnFailedRealizabilityTest=true)
Recalculate the quadrature nodes from the moments in the.
Additional Inherited Members
Static Public Attributes inherited from quadratureApproximation< volScalarMoment, volScalarNode >
static const word propertiesName
Default name of the phase properties dictionary.
Protected Types inherited from quadratureApproximation< volScalarMoment, volScalarNode >
typedef momentFieldSet< volScalarMoment, volScalarNode > momentFieldSetType
Protected Attributes inherited from quadratureApproximation< volScalarMoment, volScalarNode >
const word name_
Name of the quadrature approximation.
const fvMesh & mesh_
Reference to the mesh.
const dictionary & dict_
const labelListList momentOrders_
Moment orders used to map moments.
const labelListList nodeIndexes_
Node indexes used to map nodes.
labelList nNodes_
Number of nodes in each direction.
autoPtr< mappedPtrList< volScalarNode > > nodes_
AutoPtr to the mappedPtrList of quadrature nodes.
momentFieldSetType moments_
List of moments.
const label nDimensions_
Dimensionality of the distribution function.
const label nMoments_
Number of moments.
const label nSecondaryNodes_
Number of secondary nodes.
word support_
Support of the distribution function.
autoPtr< fieldMomentInversion > momentFieldInverter_
Extended moment inversion method.
Detailed Description
Uses quadrature approximation as a base to handle size moments, while the velocity moments and abscissae are stored in this class. The one dimensional CQMOM inversion is also done.
Source files
monoKineticQuadratureApproximation.H
monoKineticQuadratureApproximation.C
monoKineticQuadratureApproximationI.H
Definition at line 60 of file monoKineticQuadratureApproximation.H.
Constructor & Destructor Documentation
monoKineticQuadratureApproximation()
monoKineticQuadratureApproximation (const word & name, const fvMesh & mesh, const word & support) explicit
Construct from mesh.
Definition at line 40 of file monoKineticQuadratureApproximation.C.
References forAll().
~monoKineticQuadratureApproximation()
~monoKineticQuadratureApproximation () virtual
Destructor.
Definition at line 260 of file monoKineticQuadratureApproximation.C.
Member Function Documentation
velocities() [1/2]
const Foam::PtrList< Foam::volVectorField > & velocities () const inline
Const access to the velocity abscissae.
Definition at line 29 of file monoKineticQuadratureApproximationI.H.
velocities() [2/2]
Foam::PtrList< Foam::volVectorField > & velocities () inline
Const access to the velocity abscissae.
Definition at line 35 of file monoKineticQuadratureApproximationI.H.
velocityMoments() [1/2]
const Foam::PtrList< Foam::volVectorField > & velocityMoments () const inline
Const access to the velocity moments.
Definition at line 41 of file monoKineticQuadratureApproximationI.H.
velocityMoments() [2/2]
Foam::PtrList< Foam::volVectorField > & velocityMoments () inline
Non-const access to the velocity moments.
Definition at line 47 of file monoKineticQuadratureApproximationI.H.
nodesOwn()
const Foam::PtrList< Foam::surfaceScalarNode > & nodesOwn () const inline
Const access to the interpolated moments (owner)
Definition at line 53 of file monoKineticQuadratureApproximationI.H.
velocitiesOwn()
const Foam::PtrList< Foam::surfaceVectorField > & velocitiesOwn () const inline
Const access to the interpolated velocities (owner)
Definition at line 59 of file monoKineticQuadratureApproximationI.H.
nodesNei()
const Foam::PtrList< Foam::surfaceScalarNode > & nodesNei () const inline
Const access to the interpolated moments (neighbour)
Definition at line 65 of file monoKineticQuadratureApproximationI.H.
velocitiesNei()
const Foam::PtrList< Foam::surfaceVectorField > & velocitiesNei () const inline
Const access to the interpolated velocities (neighbour)
Definition at line 71 of file monoKineticQuadratureApproximationI.H.
interpolateNodes()
void interpolateNodes ()
Interpolate nodes.
Definition at line 266 of file monoKineticQuadratureApproximation.C.
References forAll(), nodes, quadratureNode< scalarType, vectorType >::primaryAbscissae(), and quadratureNode< scalarType, vectorType >::primaryWeight().
updateBoundaryVelocities()
void updateBoundaryVelocities ()
Update node velocities on fixed-value boundaries.
number of nodes with a non-negligable number of bubble or mass
Definition at line 336 of file monoKineticQuadratureApproximation.C.
References forAll(), Vandermonde::inv(), and m0().
updateVelocities()
void updateVelocities ()
Recalculate the velocity abscissae from the velocity moments.
Definition at line 578 of file monoKineticQuadratureApproximation.C.
References forAll().
updateLocalVelocities()
void updateLocalVelocities (const label celli)
Recalculate the velocity abscissae from the velocity moments.
number of nodes with a non-negligable number of bubble or mass
Definition at line 587 of file monoKineticQuadratureApproximation.C.
References forAll(), Vandermonde::inv(), and m0().
updateAllQuadrature()
void updateAllQuadrature ()
Recalculate the quadrature nodes from the moments.
Make sure moments are below 0 before checking if they
are small enough to be neglected
Definition at line 464 of file monoKineticQuadratureApproximation.C.
References forAll(), and m0().
updateAllLocalQuadrature()
bool updateAllLocalQuadrature (const label celli, const bool failOnRealizability = true)
Recalculate the quadrature nodes from the moments.
Make sure moments are below 0 before checking if they
are small enough to be neglected
Definition at line 537 of file monoKineticQuadratureApproximation.C.
References forAll(), and m0().
updateVelocityMoments()
void updateVelocityMoments ()
Recalculate the moments from the quadrature nodes.
Definition at line 701 of file monoKineticQuadratureApproximation.C.
References forAll().
updateLocalVelocityMoments()
void updateLocalVelocityMoments (const label celli)
Recalculate the moments from the quadrature nodes.
Definition at line 740 of file monoKineticQuadratureApproximation.C.
References forAll().
updateAllMoments()
void updateAllMoments ()
Recalculate all moments from the quadrature nodes.
Definition at line 773 of file monoKineticQuadratureApproximation.C.
updateAllLocalMoments()
void updateAllLocalMoments (const label celli)
Recalculate all moments from the quadrature nodes.
Definition at line 783 of file monoKineticQuadratureApproximation.C.
The documentation for this class was generated from the following files:
monoKineticQuadratureApproximation.H
monoKineticQuadratureApproximation.C
monoKineticQuadratureApproximationI.H