OpenQBMM: velocityQuadratureNode< scalarType, vectorType > Class Template Reference
velocityQuadratureNode< scalarType, vectorType > Class Template Reference
Extended version of the quadrature node, which stores the list of secondary weights and abscissae associated to the primary weight and abscissa, and the sigma parameter.
Classes
class iNew
Return a pointer to a new quadrature node created on freestore.
Public Member Functions
velocityQuadratureNode (const word &name, const word &distributionName, const fvMesh &mesh, const dimensionSet &weightDimensions, const PtrList< dimensionSet > &abscissaDimensions, const wordList &boundaryTypes, const bool extended=false, const label nSecondaryNodes=0)
Construct from name, mesh and dimensions.
velocityQuadratureNode (const word &name, const word &distributionName, const fvMesh &mesh, const dimensionSet &weightDimensions, const PtrList< dimensionSet > &abscissaDimensions, const bool extended=false, const label nSecondaryNodes=0)
Construct from name, number of secondary nodes, mesh and dimensions.
autoPtr< velocityQuadratureNode< scalarType, vectorType > > clone () const
Return clone.
virtual ~velocityQuadratureNode ()
Destructor.
virtual const vectorType & velocityAbscissae () const
Const access to the velocity abscissa of the node.
virtual vectorType & velocityAbscissae ()
Non-const access to the velcity abscissa of the node.
Public Member Functions inherited from quadratureNode< scalarType, vectorType >
quadratureNode (const word &name, const word &distributionName, const fvMesh &mesh, const dimensionSet &weightDimensions, const PtrList< dimensionSet > &abscissaeDimensions, const wordList &boundaryTypes, const bool extended=false, const label nSecondaryNodes=0)
Construct from name, mesh and dimensions.
quadratureNode (const word &name, const word &distributionName, const fvMesh &mesh, const dimensionSet &weightDimensions, const PtrList< dimensionSet > &abscissaeDimensions, const bool extended=false, const label nSecondaryNodes=0)
Construct from name, number of secondary nodes, mesh and dimensions.
autoPtr< quadratureNode< scalarType, vectorType > > clone () const
Return clone.
virtual ~quadratureNode ()
Destructor.
const word & name () const
Return the name of the node.
const labelList & scalarIndexes () const
Return abscissa indexes.
const labelList & velocityIndexes () const
Return velocity indexes.
label sizeIndex () const
Return size index.
bool lengthBased () const
Is the node length based.
bool useVolumeFraction () const
Is the weight in terms of volume fraction.
bool extended () const
Is the node extended.
label nSecondaryNodes () const
Returns the number of secondary nodes.
const weightType & primaryWeight () const
Const access to the weight of the node.
weightType & primaryWeight ()
Non-const access to the weight of the node.
const abscissaeType & primaryAbscissae () const
Const access to the scalar abscissa of the node.
abscissaeType & primaryAbscissae ()
Non-const access to the scalar abscissa of the node.
const secondaryWeightsType & secondaryWeights () const
Const access to the secondary weights of the node.
secondaryWeightsType & secondaryWeights ()
Non-const access to the secondary weights of the node.
const secondaryAbscissaeType & secondaryAbscissae () const
Const access to the list of secondary abscissae of the node.
secondaryAbscissaeType & secondaryAbscissae ()
Non-const access to the list of secondary abscissae of the node.
const sigmasType & sigmas () const
Const access to sigma.
sigmasType & sigmas ()
Non-const access to sigma.
Additional Inherited Members
Protected Types inherited from quadratureNode< scalarType, vectorType >
typedef scalarType weightType
Typedefs.
typedef PtrList< PtrList< weightType > > secondaryWeightsType
typedef scalarType abscissaType
typedef PtrList< abscissaType > abscissaeType
typedef PtrList< abscissaeType > secondaryAbscissaeType
typedef vectorType velocityAbscissaeType
typedef scalarType sigmaType
typedef PtrList< sigmaType > sigmasType
Protected Attributes inherited from quadratureNode< scalarType, vectorType >
word name_
Name of the quadrature node.
weightType weight_
Primary weight of the node.
abscissaeType abscissae_
Primary abscissae of the node.
labelList scalarIndexes_
Indicies of abscissa components.
labelList velocityIndexes_
Indicies of velocity components.
label sizeIndex_
Index of size component.
bool lengthBased_
Is the size length based.
bool useVolumeFraction_
Are weights in volume fraction.
secondaryWeightsType secondaryWeights_
List of secondary weights of the node.
secondaryAbscissaeType secondaryAbscissae_
List of secondary abscissae of the node.
sigmasType sigmas_
Parameter of the kernel density function used in EQMOM.
label nSecondaryNodes_
Number of secondary nodes.
bool extended_
Boolean variable to identify extended nodes.
Detailed Description
template<class scalarType, class vectorType>
class Foam::velocityQuadratureNode< scalarType, vectorType >
Extended version of the quadrature node, which stores the list of secondary weights and abscissae associated to the primary weight and abscissa, and the sigma parameter.
Source files
velocityQuadratureNode.H
velocityQuadratureNode.C
velocityQuadratureNodeI.H
Definition at line 55 of file velocityQuadratureNode.H.
Constructor & Destructor Documentation
velocityQuadratureNode() [1/2]
velocityQuadratureNode (const word & name, const word & distributionName, const fvMesh & mesh, const dimensionSet & weightDimensions, const PtrList< dimensionSet > & abscissaDimensions, const wordList & boundaryTypes, const bool extended = false, const label nSecondaryNodes = 0)
Construct from name, mesh and dimensions.
Definition at line 57 of file velocityQuadratureNode.C.
velocityQuadratureNode() [2/2]
velocityQuadratureNode (const word & name, const word & distributionName, const fvMesh & mesh, const dimensionSet & weightDimensions, const PtrList< dimensionSet > & abscissaDimensions, const bool extended = false, const label nSecondaryNodes = 0)
Construct from name, number of secondary nodes, mesh and dimensions.
Definition at line 31 of file velocityQuadratureNode.C.
~velocityQuadratureNode()
~velocityQuadratureNode () virtual
Destructor.
Definition at line 86 of file velocityQuadratureNode.C.
Member Function Documentation
clone()
Foam::autoPtr< Foam::velocityQuadratureNode< scalarType, vectorType > > clone () const
Return clone.
Definition at line 128 of file velocityQuadratureNode.C.
velocityAbscissae() [1/2]
const vectorType & velocityAbscissae () const virtual
Const access to the velocity abscissa of the node.
Reimplemented from quadratureNode< scalarType, vectorType >.
Definition at line 29 of file velocityQuadratureNodeI.H.
Referenced by aggregationKernel::aggregationSource(), breakupKernel::breakupSource(), firstOrderKinetic::interpolateNodes(), basicVelocityFieldMomentInversion::invertBoundaryMoments(), basicVelocityFieldMomentInversion::invertLocalMoments(), growthModel::phaseSpaceConvection(), firstOrderKinetic::update(), BoltzmannCollision::updateCells(), BGKCollision::updateCells(), and velocityMomentAdvection::updateWallCollisions().
velocityAbscissae() [2/2]
vectorType & velocityAbscissae () virtual
Non-const access to the velcity abscissa of the node.
Reimplemented from quadratureNode< scalarType, vectorType >.
Definition at line 36 of file velocityQuadratureNodeI.H.
The documentation for this class was generated from the following files:
velocityQuadratureNode.H
velocityQuadratureNode.C
velocityQuadratureNodeI.H