OpenQBMM: createFields.H File Reference
buoyantPbePimpleFoam/createFields.H File Reference
Functions
Info<< "Reading thermophysical properties\"<< endl;autoPtr< rhoThermo > pThermo (rhoThermo::New(mesh))
thermo validate (args.executable(), "h", "e")
volScalarField rho (IOobject("rho", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::NO_WRITE), thermo.rho())
Info<< "Reading field U\"<< endl;volVectorField U(IOobject("U", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE), mesh);Info<< "Creating turbulence model\"<< endl;autoPtr< compressible::turbulenceModel > turbulence (compressible::turbulenceModel::New(rho, U, phi, thermo))
Variables
rhoThermo & thermo = pThermo()
volScalarField & p = thermo.p()
const volScalarField & psi = thermo.psi()
Info<< "Reading field p_rgh\"<< endl;volScalarField p_rgh(IOobject("p_rgh", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE), mesh);p_rgh=p - rho *gh;mesh.setFluxRequired(p_rgh.name());Info<< "Creating field dpdt\"<< endl;volScalarField dpdt(IOobject("dpdt", runTime.timeName(), mesh), mesh, dimensionedScalar("dpdt", p.dimensions()/dimTime, 0));Info<< "Creating field kinetic energy K\"<< endl;volScalarField K("K", 0.5 *magSqr(U));Info<< "Reading populationBalanceProperties\"<< endl;IOdictionary populationBalanceProperties(IOobject("populationBalanceProperties", runTime.constant(), mesh, IOobject::MUST_READ_IF_MODIFIED, IOobject::NO_WRITE));surfaceScalarField phiByRho("phiByRho", phi/fvc::interpolate(rho));autoPtr< populationBalanceModel > populationBalance (populationBalanceModel::New("populationBalance", populationBalanceProperties, phiByRho))
Function Documentation
pThermo()
Info<< "Reading thermophysical properties\n" << endl; autoPtr<rhoThermo> pThermo (rhoThermo::New(mesh))
validate()
thermo validate (args. executable(), "h" , "e")
rho()
volScalarField rho (IOobject("rho", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::NO_WRITE) , thermo. rho())
turbulence()
Info<< "Reading field U\n" << endl; volVectorField U (IOobject ("U", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE), mesh); Info<< "Creating turbulence model\n" << endl; autoPtr<compressible::turbulenceModel> turbulence (compressible::turbulenceModel::New(rho, U, phi, thermo))
Variable Documentation
thermo
rhoThermo& thermo = pThermo()
Definition at line 4 of file buoyantPbePimpleFoam/createFields.H.
p
volScalarField& p = thermo.p()
Definition at line 20 of file buoyantPbePimpleFoam/createFields.H.
Referenced by gaussLobattoMomentInversion::correctRecurrence(), gaussRadauMomentInversion::correctRecurrence(), hermiteQuadrature::hermiteQuadrature(), if(), zeta::limitZetas(), and while().
psi
const volScalarField& psi = thermo.psi()
Definition at line 21 of file buoyantPbePimpleFoam/createFields.H.
populationBalance
Info<< "Reading field p_rgh\n" << endl; volScalarField p_rgh (IOobject ("p_rgh", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE), mesh); p_rgh = p - rho*gh; mesh.setFluxRequired(p_rgh.name()); Info<< "Creating field dpdt\n" << endl; volScalarField dpdt (IOobject ("dpdt", runTime.timeName(), mesh), mesh, dimensionedScalar("dpdt", p.dimensions()/dimTime, 0)); Info<< "Creating field kinetic energy K\n" << endl; volScalarField K("K", 0.5*magSqr(U)); Info<< "Reading populationBalanceProperties\n" << endl; IOdictionary populationBalanceProperties (IOobject ("populationBalanceProperties", runTime.constant(), mesh, IOobject::MUST_READ_IF_MODIFIED, IOobject::NO_WRITE)); surfaceScalarField phiByRho("phiByRho", phi/fvc::interpolate(rho)); autoPtr<populationBalanceModel> populationBalance(populationBalanceModel::New("populationBalance", populationBalanceProperties, phiByRho))
Definition at line 110 of file buoyantPbePimpleFoam/createFields.H.