OpenQBMM: createFields.H File Reference
velocityDistributionTransport/vdfTransportFoam/createFields.H File Reference
Functions
surfaceScalarField phi (IOobject("phi", runTime.timeName(), mesh), mesh, dimensionedScalar("zero", dimVolume/dimTime, 0.0))
Empty phi field to pass into poplation balance model.
Info<< "Reading populationBalanceProperties\"<< endl;IOdictionary populationBalanceProperties(IOobject("populationBalanceProperties", runTime.constant(), mesh, IOobject::MUST_READ_IF_MODIFIED, IOobject::NO_WRITE));volVectorField Up(IOobject("U.particles", runTime.timeName(), mesh, IOobject::READ_IF_PRESENT, IOobject::AUTO_WRITE), mesh, dimensionedVector("U", dimVelocity, Zero));volTensorField Sigmap(IOobject("Sigma.particles", runTime.timeName(), mesh, IOobject::READ_IF_PRESENT, IOobject::NO_WRITE), mesh, dimensionedTensor("Sigma", sqr(dimVelocity), Zero));volScalarField Thetap(IOobject("Theta.particles", runTime.timeName(), mesh, IOobject::READ_IF_PRESENT, IOobject::NO_WRITE), mesh, dimensionedScalar("Theta", sqr(dimVelocity), Zero));autoPtr< populationBalanceModel > populationBalance (populationBalanceModel::New("particles", populationBalanceProperties, phi))
const labelList & velocityIndexes (nodes[0].velocityIndexes())
forAll (momentOrders, mi)
if (sizeIndex !=-1)
Variables
velocityQuadratureApproximation & quadrature
const labelListList & momentOrders = quadrature.momentOrders()
volVelocityMomentFieldSet & moments = quadrature.moments()
mappedPtrList< volVelocityNode > & nodes = quadrature.nodes()
label sizeIndex = nodes[0].sizeIndex()
bool computeVariance = false
tmp< volScalarField > dMean
Function Documentation
phi()
surfaceScalarField phi (IOobject("phi", runTime.timeName(), mesh) , mesh , dimensionedScalar("zero", dimVolume/dimTime, 0.0))
Empty phi field to pass into poplation balance model.
populationBalance()
Info<< "Reading populationBalanceProperties\n" << endl;IOdictionary populationBalanceProperties(IOobject ("populationBalanceProperties", runTime.constant(), mesh, IOobject::MUST_READ_IF_MODIFIED, IOobject::NO_WRITE));volVectorField Up(IOobject ("U.particles", runTime.timeName(), mesh, IOobject::READ_IF_PRESENT, IOobject::AUTO_WRITE), mesh, dimensionedVector("U", dimVelocity, Zero));volTensorField Sigmap(IOobject ("Sigma.particles", runTime.timeName(), mesh, IOobject::READ_IF_PRESENT, IOobject::NO_WRITE), mesh, dimensionedTensor("Sigma", sqr(dimVelocity), Zero));volScalarField Thetap(IOobject ("Theta.particles", runTime.timeName(), mesh, IOobject::READ_IF_PRESENT, IOobject::NO_WRITE), mesh, dimensionedScalar("Theta", sqr(dimVelocity), Zero));autoPtr<populationBalanceModel> populationBalance (populationBalanceModel::New("particles", populationBalanceProperties, phi))
velocityIndexes()
const labelList& velocityIndexes (nodes. velocityIndexes()[0])
Referenced by aggregationKernel::aggregationSource(), breakupKernel::breakupSource(), forAll(), fieldMomentInversion::New(), multivariateMomentInversion::New(), growthModel::phaseSpaceConvection(), quadratureApproximation< volVelocityMoment, volVelocityNode >::quadratureApproximation(), firstOrderKinetic::update(), moment< fieldType, nodeType >::update(), moment< fieldType, nodeType >::updateBoundaries(), and moment< fieldType, nodeType >::updateLocalMoment().
forAll()
forAll (momentOrders , mi)
Definition at line 85 of file velocityDistributionTransport/vdfTransportFoam/createFields.H.
References computeVariance, momentOrders, and velocityIndexes().
if()
if (sizeIndex ! = -1)
Definition at line 99 of file velocityDistributionTransport/vdfTransportFoam/createFields.H.
References dMean.
Variable Documentation
quadrature
velocityQuadratureApproximation& quadrature
Initial value:
=
    mesh.lookupObjectRef<velocityQuadratureApproximation>("quadratureProperties.particles")
Definition at line 75 of file velocityDistributionTransport/vdfTransportFoam/createFields.H.
Referenced by aggregationKernel::aggregationSource(), BGKCollision::BGKCollision(), BoltzmannCollision::BoltzmannCollision(), breakupKernel::breakupSource(), collisionKernel::collisionKernel(), firstOrderKinetic::firstOrderKinetic(), univariateMomentAdvection::New(), collisionKernel::New(), velocityMomentAdvection::New(), growthModel::phaseSpaceConvection(), realizableOdeSolver< volVelocityMoment, volVelocityNode >::solve(), and zeta::zeta().
momentOrders
const labelListList& momentOrders = quadrature.momentOrders()
Definition at line 78 of file velocityDistributionTransport/vdfTransportFoam/createFields.H.
Referenced by forAll(), fieldMomentInversion::New(), multivariateMomentInversion::New(), and realizableOdeSolver< volVelocityMoment, volVelocityNode >::solve().
moments
volVelocityMomentFieldSet& moments = quadrature.moments()
Definition at line 79 of file velocityDistributionTransport/vdfTransportFoam/createFields.H.
Referenced by esBGKCollision::covariance(), BGKCollision::covariance(), forAll(), if(), extendedFieldMomentInversion::invert(), basicFieldMomentInversion::invert(), monoKinetic::invert(), TensorProduct::invert(), sizeCHyQMOM::invert(), basicVelocityFieldMomentInversion::invert(), conditional::invert(), extendedFieldMomentInversion::invertBoundaryMoments(), basicVelocityFieldMomentInversion::invertBoundaryMoments(), basicVelocityFieldMomentInversion::invertLocalMoments(), FokkerPlanck::K(), IEM::K(), BGKCollision::moment000(), BGKCollision::moment001(), BGKCollision::moment002(), BGKCollision::moment003(), BGKCollision::moment004(), BGKCollision::moment005(), BGKCollision::moment010(), BGKCollision::moment011(), BGKCollision::moment012(), BGKCollision::moment013(), BGKCollision::moment014(), BGKCollision::moment015(), BGKCollision::moment020(), BGKCollision::moment021(), BGKCollision::moment022(), BGKCollision::moment023(), BGKCollision::moment024(), BGKCollision::moment025(), BGKCollision::moment030(), BGKCollision::moment031(), BGKCollision::moment032(), BGKCollision::moment040(), BGKCollision::moment041(), BGKCollision::moment042(), BGKCollision::moment050(), BGKCollision::moment051(), BGKCollision::moment052(), BGKCollision::moment100(), BGKCollision::moment101(), BGKCollision::moment102(), BGKCollision::moment103(), BGKCollision::moment104(), BGKCollision::moment105(), BGKCollision::moment110(), BGKCollision::moment111(), BGKCollision::moment120(), BGKCollision::moment130(), BGKCollision::moment140(), BGKCollision::moment150(), BGKCollision::moment200(), BGKCollision::moment201(), BGKCollision::moment202(), BGKCollision::moment203(), BGKCollision::moment204(), BGKCollision::moment205(), BGKCollision::moment210(), BGKCollision::moment220(), BGKCollision::moment230(), BGKCollision::moment240(), BGKCollision::moment250(), BGKCollision::moment300(), BGKCollision::moment301(), BGKCollision::moment302(), BGKCollision::moment310(), BGKCollision::moment320(), BGKCollision::moment400(), BGKCollision::moment401(), BGKCollision::moment402(), BGKCollision::moment410(), BGKCollision::moment420(), BGKCollision::moment500(), BGKCollision::moment501(), BGKCollision::moment502(), BGKCollision::moment510(), BGKCollision::moment520(), realizableOdeSolver< volVelocityMoment, volVelocityNode >::solve(), and BGKCollision::updateCells().
nodes
mappedPtrList<volVelocityNode>& nodes = quadrature.nodes()
Definition at line 80 of file velocityDistributionTransport/vdfTransportFoam/createFields.H.
Referenced by aggregationKernel::aggregationSource(), breakupKernel::breakupSource(), firstOrderKinetic::firstOrderKinetic(), firstOrderKinetic::interpolateNodes(), monoKineticQuadratureApproximation::interpolateNodes(), extendedFieldMomentInversion::invert(), basicFieldMomentInversion::invert(), basicVelocityFieldMomentInversion::invert(), extendedFieldMomentInversion::invertBoundaryMoments(), basicFieldMomentInversion::invertBoundaryMoments(), basicVelocityFieldMomentInversion::invertBoundaryMoments(), extendedFieldMomentInversion::invertLocalMoments(), basicFieldMomentInversion::invertLocalMoments(), basicVelocityFieldMomentInversion::invertLocalMoments(), growthModel::phaseSpaceConvection(), moment< fieldType, nodeType >::update(), moment< fieldType, nodeType >::updateBoundaries(), moment< fieldType, nodeType >::updateLocalMoment(), and velocityMomentAdvection::updateWallCollisions().
sizeIndex
label sizeIndex = nodes[0].sizeIndex()
Definition at line 82 of file velocityDistributionTransport/vdfTransportFoam/createFields.H.
Referenced by aggregationKernel::aggregationSource(), breakupKernel::breakupSource(), if(), and growthModel::phaseSpaceConvection().
computeVariance
bool computeVariance = false
Definition at line 84 of file velocityDistributionTransport/vdfTransportFoam/createFields.H.
Referenced by forAll().
dMean
tmp<volScalarField> dMean
Definition at line 98 of file velocityDistributionTransport/vdfTransportFoam/createFields.H.
Referenced by if().