OpenQBMM: createFields.H File Reference
velocityDistributionTransport/diluteVdfTransportFoam/createFields.H File Reference
Functions
Info<< "Reading phaseProperties\"<< endl;IOdictionary phaseProperties(IOobject("phaseProperties", runTime.constant(), mesh, IOobject::MUST_READ_IF_MODIFIED, IOobject::NO_WRITE));word dilutePhaseName(phaseProperties.lookup("dilutePhase"));word fluidName(phaseProperties.lookup("continuousPhase"));autoPtr< phaseModel > phase1 (new phaseModel(mesh, phaseProperties, fluidName))
Info<< "Creating field kinetic energy K\"<< endl;volScalarField K1(IOobject::groupName("K", phase1->name()), 0.5 *magSqr(U1));autoPtr< phaseModel > phase2 (new vdfPhaseModel(mesh, phaseProperties, dilutePhaseName))
volScalarField & alpha2 (phase2())
volScalarField K2 (IOobject::groupName("K", phase2->name()), 0.5 *magSqr(U2))
volScalarField rho (IOobject("rho", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::NO_WRITE), alpha1 *rho1+alpha2 *rho2)
Info<< "Reading field p_rgh\"<< endl;volScalarField p_rgh(IOobject("p_rgh", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE), mesh);label pRefCell=0;scalar pRefValue=0.0;setRefCell(p, p_rgh, pimple.dict(), pRefCell, pRefValue);mesh.setFluxRequired(p_rgh.name());dimensionedScalar pMin("pMin", dimPressure, phaseProperties);Info<< "Creating field dpdt\"<< endl;volScalarField dpdt(IOobject("dpdt", runTime.timeName(), mesh), mesh, dimensionedScalar(p.dimensions()/dimTime, 0));autoPtr< phasePair > pair (new orderedPhasePair(phase2, phase1, g, dimensionedScalar::lookupOrDefault("sigma", phaseProperties, dimensionSet(1, 0, -2, 0, 0), 0.0), phaseProperties.subDict("aspectRatio")))
autoPtr< dragModel > drag (dragModel::New(phaseProperties.subDict("drag"), pair()))
if (phaseProperties.found("virtualMass"))
if (phaseProperties.found("lift"))
if (phaseProperties.found("wallLubrication"))
if (phaseProperties.found("turbulentDispersion"))
if (phaseProperties.found("heatTransfer"))
Variables
rhoThermo & thermo1 = phase1->thermo()
volScalarField & p = thermo1.p()
volScalarField & alpha1 = phase1()
volVectorField & U1 = phase1->U()
surfaceScalarField & phi1 = phase1->phi()
surfaceScalarField & alphaPhi1 = phase1->alphaPhi()
surfaceScalarField & alphaRhoPhi1 = phase1->alphaRhoPhi()
volScalarField & rho1 = thermo1.rho()
const volScalarField psi1 = thermo1.psi()
rhoThermo & thermo2 = phase2->thermo()
const volScalarField & rho2 = thermo2.rho()
const volVectorField & U2 = phase2->U()
surfaceScalarField & phi2 = phase2->phi()
surfaceScalarField & alphaPhi2 = phase2->alphaPhi()
surfaceScalarField & alphaRhoPhi2 = phase2->alphaRhoPhi()
autoPtr< virtualMassModel > virtualMass
autoPtr< liftModel > lift
autoPtr< wallLubricationModel > wallLubrication
autoPtr< turbulentDispersionModel > turbulentDispersion
autoPtr< heatTransferModel > heatTransfer
Function Documentation
phase1()
Info<< "Reading phaseProperties\n" << endl;IOdictionary phaseProperties(IOobject ("phaseProperties", runTime.constant(), mesh, IOobject::MUST_READ_IF_MODIFIED, IOobject::NO_WRITE));word dilutePhaseName(phaseProperties.lookup("dilutePhase"));word fluidName(phaseProperties.lookup("continuousPhase"));autoPtr<phaseModel> phase1 (new phaseModelmesh, phaseProperties, fluidName)
Referenced by for(), if(), and while().
phase2()
Info<< "Creating field kinetic energy K\n" << endl;volScalarField K1(IOobject::groupName("K", phase1->name()), 0.5*magSqr(U1));autoPtr<phaseModel> phase2 (new vdfPhaseModelmesh, phaseProperties, dilutePhaseName)
Referenced by for(), forAll(), if(), and while().
alpha2()
volScalarField& alpha2 (phase2())
K2()
volScalarField K2 (IOobject::groupName("K", phase2->name()) , 0.5 * magSqrU2)
rho()
volScalarField rho (IOobject("rho", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::NO_WRITE) , alpha1 *rho1+alpha2 * rho2)
pair()
Info<< "Reading field p_rgh\n" << endl;volScalarField p_rgh(IOobject ("p_rgh", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE), mesh);label pRefCell = 0;scalar pRefValue = 0.0;setRefCell(p, p_rgh, pimple.dict(), pRefCell, pRefValue);mesh.setFluxRequired(p_rgh.name());dimensionedScalar pMin("pMin", dimPressure, phaseProperties);Info<< "Creating field dpdt\n" << endl;volScalarField dpdt(IOobject ("dpdt", runTime.timeName(), mesh), mesh, dimensionedScalar(p.dimensions()/dimTime, 0));autoPtr<phasePair> pair (new orderedPhasePairphase2, phase1, g, dimensionedScalar::lookupOrDefault("sigma", phaseProperties, dimensionSet(1, 0, -2, 0, 0), 0.0), phaseProperties.subDict("aspectRatio"))
Referenced by if().
drag()
autoPtr<dragModel> drag (dragModel::New(phaseProperties.subDict("drag"), pair()))
Referenced by for(), and forAll().
if() [1/5]
if (phaseProperties. found"virtualMass")
Definition at line 162 of file velocityDistributionTransport/diluteVdfTransportFoam/createFields.H.
References pair(), and virtualMass.
if() [2/5]
if (phaseProperties. found"lift")
Definition at line 173 of file velocityDistributionTransport/diluteVdfTransportFoam/createFields.H.
References lift, and pair().
if() [3/5]
if (phaseProperties. found"wallLubrication")
Definition at line 184 of file velocityDistributionTransport/diluteVdfTransportFoam/createFields.H.
References pair(), and wallLubrication.
if() [4/5]
if (phaseProperties. found"turbulentDispersion")
Definition at line 195 of file velocityDistributionTransport/diluteVdfTransportFoam/createFields.H.
References pair(), and turbulentDispersion.
if() [5/5]
if (phaseProperties. found"heatTransfer")
Definition at line 206 of file velocityDistributionTransport/diluteVdfTransportFoam/createFields.H.
References heatTransfer, and pair().
Variable Documentation
thermo1
rhoThermo& thermo1 = phase1->thermo()
Definition at line 29 of file velocityDistributionTransport/diluteVdfTransportFoam/createFields.H.
p
volScalarField& p = thermo1.p()
Definition at line 30 of file velocityDistributionTransport/diluteVdfTransportFoam/createFields.H.
alpha1
alpha1 = phase1()
Definition at line 31 of file velocityDistributionTransport/diluteVdfTransportFoam/createFields.H.
Referenced by forAll(), if(), and while().
U1
volVectorField& U1 = phase1->U()
Definition at line 32 of file velocityDistributionTransport/diluteVdfTransportFoam/createFields.H.
Referenced by forAll(), if(), and while().
phi1
surfaceScalarField& phi1 = phase1->phi()
Definition at line 33 of file velocityDistributionTransport/diluteVdfTransportFoam/createFields.H.
alphaPhi1
alphaPhi1 = phase1->alphaPhi()
Definition at line 34 of file velocityDistributionTransport/diluteVdfTransportFoam/createFields.H.
alphaRhoPhi1
alphaRhoPhi1 = phase1->alphaRhoPhi()
Definition at line 35 of file velocityDistributionTransport/diluteVdfTransportFoam/createFields.H.
rho1
volScalarField& rho1 = thermo1.rho()
Definition at line 36 of file velocityDistributionTransport/diluteVdfTransportFoam/createFields.H.
psi1
const volScalarField psi1 = thermo1.psi()
Definition at line 37 of file velocityDistributionTransport/diluteVdfTransportFoam/createFields.H.
thermo2
rhoThermo& thermo2 = phase2->thermo()
Definition at line 56 of file velocityDistributionTransport/diluteVdfTransportFoam/createFields.H.
rho2
const volScalarField& rho2 = thermo2.rho()
Definition at line 57 of file velocityDistributionTransport/diluteVdfTransportFoam/createFields.H.
U2
const volVectorField& U2 = phase2->U()
Definition at line 58 of file velocityDistributionTransport/diluteVdfTransportFoam/createFields.H.
Referenced by if(), and while().
phi2
surfaceScalarField& phi2 = phase2->phi()
Definition at line 59 of file velocityDistributionTransport/diluteVdfTransportFoam/createFields.H.
alphaPhi2
alphaPhi2 = phase2->alphaPhi()
Definition at line 60 of file velocityDistributionTransport/diluteVdfTransportFoam/createFields.H.
alphaRhoPhi2
alphaRhoPhi2 = phase2->alphaRhoPhi()
Definition at line 61 of file velocityDistributionTransport/diluteVdfTransportFoam/createFields.H.
virtualMass
autoPtr<virtualMassModel> virtualMass
Definition at line 161 of file velocityDistributionTransport/diluteVdfTransportFoam/createFields.H.
Referenced by forAll(), and if().
lift
autoPtr<liftModel> lift
Definition at line 172 of file velocityDistributionTransport/diluteVdfTransportFoam/createFields.H.
Referenced by forAll(), and if().
wallLubrication
autoPtr<wallLubricationModel> wallLubrication
Definition at line 183 of file velocityDistributionTransport/diluteVdfTransportFoam/createFields.H.
Referenced by forAll(), and if().
turbulentDispersion
autoPtr<turbulentDispersionModel> turbulentDispersion
Definition at line 194 of file velocityDistributionTransport/diluteVdfTransportFoam/createFields.H.
Referenced by forAll(), and if().
heatTransfer
autoPtr<heatTransferModel> heatTransfer
Definition at line 205 of file velocityDistributionTransport/diluteVdfTransportFoam/createFields.H.
Referenced by forAll(), and if().