OpenQBMM: createFields.H File Reference
pbeFoam/createFields.H File Reference
Functions
if (mesh.nCells() !=1)
Info<< nl<< "Reading thermophysical properties\"<< endl;autoPtr< psiThermo > pThermo (psiThermo::New(mesh))
thermo validate (args.executable(), "h", "e")
volScalarField rho (IOobject("rho", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE), thermo.rho())
volVectorField U (IOobject("U", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::NO_WRITE), mesh, dimensionedVector("zero", dimVelocity, vector::zero), p.boundaryField().types())
Info<< "Creating turbulence model.\"<< endl;autoPtr< compressible::turbulenceModel > turbulence (compressible::turbulenceModel::New(rho, U, phi, thermo))
Info<< "Reading populationBalanceProperties\"<< endl;IOdictionary populationBalanceProperties(IOobject("populationBalanceProperties", runTime.constant(), mesh, IOobject::MUST_READ_IF_MODIFIED, IOobject::NO_WRITE));autoPtr< populationBalanceModel > populationBalance (populationBalanceModel::New("populationBalance", populationBalanceProperties, phi))
Variables
psiThermo & thermo = pThermo()
volScalarField & p = thermo.p()
Function Documentation
if()
if (mesh.nCells() ! = 1)
Definition at line 1 of file pbeFoam/createFields.H.
pThermo()
Info<< nl << "Reading thermophysical properties\n" << endl; autoPtr<psiThermo> pThermo (psiThermo::New(mesh))
validate()
thermo validate (args. executable(), "h" , "e")
rho()
volScalarField rho (IOobject("rho", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE) , thermo. rho())
U()
volVectorField U (IOobject("U", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::NO_WRITE) , mesh , dimensionedVector("zero", dimVelocity, vector::zero) , p. boundaryField).types()
Referenced by for(), if(), velocityMomentAdvection::updateWallCollisions(), and while().
turbulence()
Info<< "Creating turbulence model.\n" << endl; autoPtr<compressible::turbulenceModel> turbulence (compressible::turbulenceModel::New(rho, U, phi, thermo))
populationBalance()
Info<< "Reading populationBalanceProperties\n" << endl; IOdictionary populationBalanceProperties (IOobject ("populationBalanceProperties", runTime.constant(), mesh, IOobject::MUST_READ_IF_MODIFIED, IOobject::NO_WRITE)); autoPtr<populationBalanceModel> populationBalance (populationBalanceModel::New("populationBalance", populationBalanceProperties, phi))
Variable Documentation
thermo
psiThermo& thermo = pThermo()
Definition at line 14 of file pbeFoam/createFields.H.
p
volScalarField& p = thermo.p()
Definition at line 30 of file pbeFoam/createFields.H.