OpenQBMM: EEqn.H File Reference
velocityDistributionTransport/diluteVdfTransportFoam/EEqn.H File Reference
Functions
if (solveEnergy)
Function Documentation
if()
if (solveEnergy)
Definition at line 1 of file velocityDistributionTransport/diluteVdfTransportFoam/EEqn.H.
References alpha1, alpha2, alphaPhi1, alphaPhi2, alphaRhoPhi1, alphaRhoPhi2, contErr1, contErr2, K1, K2, Kh(), p, phase1(), phase2(), rho1, rho2, thermo1, thermo2, U1, and U2.