OpenQBMM: EEqn.H File Reference
buoyantPbePimpleFoam/EEqn.H File Reference
Functions
fvScalarMatrix EEqn (fvm::ddt(rho, he)+fvm::div(phi, he)+fvc::ddt(rho, K)+fvc::div(phi, K)+(he.name()=="e" ? fvc::div(fvc::absolute(phi/fvc::interpolate(rho), U), p, "div(phiv,p)") :-dpdt) - fvm::laplacian(turbulence->alphaEff(), he)==radiation->Sh(thermo, he)+fvOptions(rho, he))
EEqn relax ()
fvOptions constrain (EEqn)
EEqn solve ()
fvOptions correct (he)
thermo correct ()
Function Documentation
EEqn()
fvScalarMatrix EEqn (fvm::ddt(rho, he)+fvm::div(phi, he)+fvc::ddt(rho, K)+fvc::div(phi, K)+(he.name()=="e" ? fvc::div(fvc::absolute(phi/fvc::interpolate(rho), U), p, "div(phiv,p)") :-dpdt) - fvm::laplacian(turbulence->alphaEff(), he) = =radiation->Sh(thermo, he)+fvOptions(rho, he))
relax()
EEqn relax ()
constrain()
fvOptions constrain (EEqn)
solve()
EEqn solve ()
Referenced by velocityPopulationBalance::explicitMomentSource(), if(), Vandermonde::inv(), TensorProduct::invert(), velocityPopulationBalance::solve(), mixingPopulationBalance::solve(), and while().
correct() [1/2]
fvOptions correct (he)
correct() [2/2]
radiation correct ()