OpenQBMM: pEqn.H File Reference
buoyantPbePimpleFoam/pEqn.H File Reference
Functions
thermo rho () -
volScalarField rAU (1.0/UEqn.A())
surfaceScalarField rhorAUf ("rhorAUf", fvc::interpolate(rho *rAU))
volVectorField HbyA (constrainHbyA(rAU *UEqn.H(), U, p_rgh))
surfaceScalarField phig (-rhorAUf *ghf *fvc::snGrad(rho) *mesh.magSf())
surfaceScalarField phiHbyA ("phiHbyA",(fvc::flux(rho *HbyA)+rhorAUf *fvc::ddtCorr(rho, U, phi))+phig)
MRF makeRelative (fvc::interpolate(rho), phiHbyA)
constrainPressure (p_rgh, rho, U, phiHbyA, rhorAUf, MRF)
fvScalarMatrix p_rghDDtEqn (fvc::ddt(rho)+psi *correction(fvm::ddt(p_rgh))+fvc::div(phiHbyA)==fvOptions(psi, p_rgh, rho.name()))
while (pimple.correctNonOrthogonal())
if (thermo.dpdt())
Variables
p = p_rgh + rho*gh
Function Documentation
rho()
thermo rho ()
Referenced by while().
rAU()
volScalarField rAU (1.0/UEqn. A())
Referenced by while().
rhorAUf()
surfaceScalarField rhorAUf ("rhorAUf" , fvc::interpolate(rho *rAU))
Referenced by while().
HbyA()
volVectorField HbyA (constrainHbyA(rAU *UEqn.H(), U, p_rgh))
Referenced by while().
phig()
surfaceScalarField phig (-rhorAUf *ghf * fvc::snGradrho) *mesh.magSf()
Referenced by while().
phiHbyA()
surfaceScalarField phiHbyA ("phiHbyA" , (fvc::flux(rho *HbyA)+rhorAUf *fvc::ddtCorr(rho, U, phi))+ phig)
Referenced by while().
makeRelative()
MRF makeRelative (fvc::interpolate(rho) , phiHbyA)
constrainPressure()
constrainPressure (p_rgh , rho , U , phiHbyA , rhorAUf , MRF)
Referenced by while().
p_rghDDtEqn()
fvScalarMatrix p_rghDDtEqn (fvc::ddt(rho)+psi *correction(fvm::ddt(p_rgh))+fvc::div(phiHbyA) = =fvOptions(psi, p_rgh, rho.name()))
Referenced by while().
while()
while (pimple. correctNonOrthogonal())
Definition at line 37 of file buoyantPbePimpleFoam/pEqn.H.
References HbyA(), p_rghDDtEqn(), phi, phig(), phiHbyA(), rAU(), rho(), rhorAUf(), and U().
if()
if (thermo. dpdt())
Definition at line 71 of file buoyantPbePimpleFoam/pEqn.H.
References p.
Variable Documentation
p
p = p_rgh + rho*gh
Definition at line 66 of file buoyantPbePimpleFoam/pEqn.H.
Referenced by if().