OpenQBMM: pEqn.H File Reference
multiphase/polydisperseBubbleFoam/pU/pEqn.H File Reference
Functions
surfaceScalarField alphaf1 ("alphaf1", fvc::interpolate(alpha1))
surfaceScalarField alphaf2 ("alphaf2", scalar(1) - alphaf1)
volScalarField rAU1 (IOobject::groupName("rAU", phase1.name()), 1.0/(U1Eqn.A()+max(phase1.residualAlpha() - alpha1, scalar(0)) *rho1/runTime.deltaT()))
volScalarField rAU2 (IOobject::groupName("rAU", phase2.name()), 1.0/(U2Eqn.A()+max(phase2.residualAlpha() - alpha2, scalar(0)) *rho2/runTime.deltaT()))
surfaceScalarField alpharAUf1 (fvc::interpolate(max(alpha1, phase1.residualAlpha()) *rAU1))
surfaceScalarField alpharAUf2 (fvc::interpolate(max(alpha2, phase2.residualAlpha()) *rAU2))
surfaceScalarField snGradAlpha1 (fvc::snGrad(alpha1) *mesh.magSf())
volScalarField pPrime1 (phase1.turbulence().pPrime())
volScalarField pPrime2 (phase2.turbulence().pPrime())
if (implicitPhasePressure)
for (label nodei=0;nodei< phase1.nNodes();nodei++)
while (pimple.correct())
if (thermo1.dpdt()||thermo2.dpdt())
Variables
tmp< surfaceScalarField > phiF1 = fvc::flux(rAU1*F)
tmp< surfaceScalarField > phiF2 = - fvc::flux(rAU2*F)
K1 = 0.5*magSqr(U1)
K2 = 0.5*magSqr(U2)
Function Documentation
alphaf1()
surfaceScalarField alphaf1 ("alphaf1" , fvc::interpolate(alpha1))
Referenced by while().
alphaf2()
surfaceScalarField alphaf2 ("alphaf2" , scalar(1) - alphaf1)
Referenced by while().
rAU1()
volScalarField rAU1 (IOobject::groupName("rAU", phase1.name()) , 1.0/ U1Eqn.A()+max(phase1.residualAlpha() - alpha1, scalar(0)) *rho1/runTime.deltaT())
Referenced by for(), if(), and while().
rAU2()
volScalarField rAU2 (IOobject::groupName("rAU", phase2.name()) , 1.0/ U2Eqn.A()+max(phase2.residualAlpha() - alpha2, scalar(0)) *rho2/runTime.deltaT())
Referenced by for(), and while().
alpharAUf1()
surfaceScalarField alpharAUf1 (fvc::interpolate(max(alpha1, phase1.residualAlpha()) *rAU1))
Referenced by while().
alpharAUf2()
surfaceScalarField alpharAUf2 (fvc::interpolate(max(alpha2, phase2.residualAlpha()) *rAU2))
Referenced by while().
snGradAlpha1()
surfaceScalarField snGradAlpha1 (fvc::snGrad(alpha1) *mesh.magSf())
Referenced by for().
pPrime1()
volScalarField pPrime1 (phase1. turbulence).pPrime()
Referenced by for(), and if().
pPrime2()
volScalarField pPrime2 (phase2. turbulence).pPrime()
Referenced by for().
if() [1/2]
if (implicitPhasePressure)
Definition at line 54 of file multiphase/polydisperseBubbleFoam/pU/pEqn.H.
References pPrime1(), and rAU1().
for()
for ()
Definition at line 78 of file multiphase/polydisperseBubbleFoam/pU/pEqn.H.
References Df2(), phase1(), phiF1, phiF2, pPrime1(), pPrime2(), rAU1(), rAU2(), and snGradAlpha1().
while()
while (pimple. correct())
Definition at line 108 of file multiphase/polydisperseBubbleFoam/pU/pEqn.H.
References alpha1, alpha2, alphaf1(), alphaf2(), alphaPhi1, alphaPhi2, alpharAUf1(), alpharAUf2(), contErr1, contErr2, forAll(), Kd(), max(), MRF(), p, phase1(), phase2(), phi, phi1, phi2, phiF1, phiF2, phiHbyA(), psi1, psi2, rAU1(), rAU2(), rho, rho1, rho2, solve(), U(), U1, and U2.
if() [2/2]
if (thermo1. dpdt)||thermo2.dpdt()
Definition at line 441 of file multiphase/polydisperseBubbleFoam/pU/pEqn.H.
References p.
Variable Documentation
phiF1
phiF1 = fvc::flux(rAU1*F)
Definition at line 35 of file multiphase/polydisperseBubbleFoam/pU/pEqn.H.
Referenced by for(), and while().
phiF2
phiF2 = - fvc::flux(rAU2*F)
Definition at line 36 of file multiphase/polydisperseBubbleFoam/pU/pEqn.H.
Referenced by for(), and while().
K1
K1 = 0.5*magSqr(U1)
Definition at line 437 of file multiphase/polydisperseBubbleFoam/pU/pEqn.H.
Referenced by if(), and while().
K2
K2 = 0.5*magSqr(U2)
Definition at line 438 of file multiphase/polydisperseBubbleFoam/pU/pEqn.H.
Referenced by if().