OpenQBMM: pEqn.H File Reference
multiphase/denseAGFoam/pU/pEqn.H File Reference
Functions
while (pimple.correct())
Function Documentation
while()
while (pimple. correct())
Definition at line 1 of file multiphase/denseAGFoam/pU/pEqn.H.
References AGmodel, alpha1, alpha2, alpharAUf1(), alpharAUf2(), constrainPressure(), forAll(), Kd(), p, phase1(), phase2(), phi, phi1, phi2, phiHbyA(), rAU1, rAU2, rho1, rho2, U(), U1, and U2.