OpenQBMM: pEqn.H File Reference
velocityDistributionTransport/diluteVdfTransportFoam/pEqn.H File Reference
Functions
const volScalarField psip0 (psi1 *p)
volScalarField rAU (1.0/UEqn.A())
surfaceScalarField alpharAUf ("alpharAUf", fvc::interpolate(alpha1 *rAU))
volVectorField HbyA (constrainHbyA(rAU *UEqn.H(), U1, p_rgh))
surfaceScalarField phig (alpharAUf *(-ghf *fvc::snGrad(rho) *mesh.magSf()+fvc::interpolate(alpha2 *(rho1 - rho2)) *(g &mesh.Sf())))
surfaceScalarField phiHbyA ("phiHbyA",(fvc::flux(alpha1 *HbyA)+MRF.zeroFilter(alpharAUf *fvc::ddtCorr(alphaRho1, U1, alphaRhoPhi1)))+phig)
MRF makeRelative (fvc::interpolate(alphaRho1), phiHbyA)
constrainPressure (p_rgh, alphaRho1, U1, phiHbyA, alpharAUf, MRF)
while (pimple.correctNonOrthogonal())
thermo1 correctRho (psi1 *p - psip0)
if (thermo1.dpdt())
if (!thermo1.incompressible())
Variables
rho = alpha1*rho1 + alpha2*rho2
p = p_rgh + rho*gh
alphaPhi1 = fvc::interpolate(alpha1)*phi1
alphaRhoPhi1 = fvc::interpolate(rho1)*alphaPhi1
Function Documentation
psip0()
const volScalarField psip0 (psi1 * p)
rAU()
volScalarField rAU (1.0/UEqn. A())
Referenced by while().
alpharAUf()
surfaceScalarField alpharAUf ("alpharAUf" , fvc::interpolate(alpha1 *rAU))
Referenced by while().
HbyA()
volVectorField HbyA (constrainHbyA(rAU *UEqn.H(), U1, p_rgh))
Referenced by while().
phig()
surfaceScalarField phig (alpharAUf * -ghf *fvc::snGrad(rho) *mesh.magSf()+fvc::interpolate(alpha2 *(rho1 - rho2)) *(g &mesh.Sf()))
Referenced by while().
phiHbyA()
surfaceScalarField phiHbyA ("phiHbyA" , (fvc::flux(alpha1 *HbyA)+MRF.zeroFilter(alpharAUf *fvc::ddtCorr(alphaRho1, U1, alphaRhoPhi1)))+ phig)
Referenced by while().
makeRelative()
MRF makeRelative (fvc::interpolate(alphaRho1) , phiHbyA)
constrainPressure()
constrainPressure (p_rgh , alphaRho1 , U1 , phiHbyA , alpharAUf , MRF)
while()
while (pimple. correctNonOrthogonal())
Definition at line 42 of file velocityDistributionTransport/diluteVdfTransportFoam/pEqn.H.
References alpha1, alpharAUf(), HbyA(), K1, phi1, phig(), phiHbyA(), rAU(), thermo1, and U1.
correctRho()
thermo1 correctRho (psi1 *p - psip0)
if() [1/2]
if (thermo1. dpdt())
Definition at line 80 of file velocityDistributionTransport/diluteVdfTransportFoam/pEqn.H.
References p.
if() [2/2]
if (!thermo1. incompressible())
Definition at line 85 of file velocityDistributionTransport/diluteVdfTransportFoam/pEqn.H.
References alpha1, alphaPhi1, and rho1.
Variable Documentation
rho
thermo rho = alpha1*rho1 + alpha2*rho2
Definition at line 3 of file velocityDistributionTransport/diluteVdfTransportFoam/pEqn.H.
Referenced by collisionKernel::collisionKernel(), forAll(), if(), and while().
p
p = p_rgh + rho*gh
Definition at line 75 of file velocityDistributionTransport/diluteVdfTransportFoam/pEqn.H.
Referenced by if().
alphaPhi1
alphaPhi1 = fvc::interpolate(alpha1)*phi1
Definition at line 102 of file velocityDistributionTransport/diluteVdfTransportFoam/pEqn.H.
Referenced by if().
alphaRhoPhi1
alphaRhoPhi1 = fvc::interpolate(rho1)*alphaPhi1
Definition at line 103 of file velocityDistributionTransport/diluteVdfTransportFoam/pEqn.H.