OpenQBMM: UEqn.H File Reference
velocityDistributionTransport/diluteVdfTransportFoam/UEqn.H File Reference
Functions
volScalarField alphaRho1 (alpha1 *rho1)
MRF correctBoundaryVelocity (U1)
fvVectorMatrix UEqn (fvm::ddt(alphaRho1, U1)+fvm::div(alphaRhoPhi1, U1)+MRF.DDt(alphaRho1+Cvm, U1)+phase1->turbulence().divDevRhoReff(U1)==virtualMassSource - Cvm *(fvm::ddt(U1)+fvm::div(phi1, U1) - fvm::Sp(fvc::div(phi1), U1))+dragSource - fvm::Sp(Kd, U1)+F+fvOptions(alpha1, rho1, U1))
UEqn relax ()
fvOptions constrain (UEqn)
if (pimple.momentumPredictor())
Function Documentation
alphaRho1()
volScalarField alphaRho1 (alpha1 * rho1)
correctBoundaryVelocity()
MRF correctBoundaryVelocity (U1)
UEqn()
fvVectorMatrix UEqn (fvm::ddt(alphaRho1, U1)+fvm::div(alphaRhoPhi1, U1)+MRF.DDt(alphaRho1+Cvm, U1)+phase1->turbulence().divDevRhoReff(U1) = =virtualMassSource - Cvm *(fvm::ddt(U1)+fvm::div(phi1, U1) - fvm::Sp(fvc::div(phi1), U1))+dragSource - fvm::Sp(Kd, U1)+F+fvOptions(alpha1, rho1, U1))
Referenced by if().
relax()
UEqn relax ()
constrain()
fvOptions constrain (UEqn)
if()
if (pimple. momentumPredictor())
Definition at line 28 of file velocityDistributionTransport/diluteVdfTransportFoam/UEqn.H.
References alpha1, alpha2, K1, rho, rho1, rho2, solve(), U1, and UEqn().