OpenQBMM: UEqn.H File Reference
buoyantPbePimpleFoam/UEqn.H File Reference
Functions
MRF correctBoundaryVelocity (U)
fvVectorMatrix UEqn (fvm::ddt(rho, U)+fvm::div(phi, U)+MRF.DDt(rho, U)+turbulence->divDevRhoReff(U)==fvOptions(rho, U))
UEqn relax ()
fvOptions constrain (UEqn)
if (pimple.momentumPredictor())
Function Documentation
correctBoundaryVelocity()
MRF correctBoundaryVelocity (U)
UEqn()
fvVectorMatrix UEqn (fvm::ddt(rho, U)+fvm::div(phi, U)+MRF.DDt(rho, U)+turbulence->divDevRhoReff(U) = =fvOptions(rho, U))
Referenced by for(), and if().
relax()
UEqn relax ()
constrain()
fvOptions constrain (UEqn)
if()
if (pimple. momentumPredictor())
Definition at line 18 of file buoyantPbePimpleFoam/UEqn.H.
References rho, solve(), U(), and UEqn().