OpenQBMM: vEqns.H File Reference
oneWayCoupledVdfTransportFoam/vEqns.H File Reference
Functions
for (label nodei=0;nodei< dilutePhase->nNodes();nodei++)
dilutePhase correct ()
Function Documentation
for()
for (label nodei = 0; nodei < dilutePhase->nNodes(); nodei++)
Definition at line 2 of file oneWayCoupledVdfTransportFoam/vEqns.H.
References dilutePhase(), drag(), Kd(), U(), and UEqn().
correct()
dilutePhase correct ()