var searchData=
[
  ['jacobimatrix',['JacobiMatrix',['../a00169.html#a7e65cdc9e809cd6a315bb1cc38135e3c',1,'Foam::univariateMomentInversion']]],
  ['johnsonjackson',['JohnsonJackson',['../a00070.html',1,'Foam::kineticTheoryModels::frictionalStressModels']]],
  ['johnsonjackson',['JohnsonJackson',['../a00070.html#a7296bb86fc5f0eb4a870ac1887ad077d',1,'Foam::kineticTheoryModels::frictionalStressModels::JohnsonJackson']]],
  ['johnsonjacksonfrictionalstress_2ec',['JohnsonJacksonFrictionalStress.C',['../a00335.html',1,'']]],
  ['johnsonjacksonfrictionalstress_2eh',['JohnsonJacksonFrictionalStress.H',['../a00336.html',1,'']]],
  ['johnsonjacksonparticleslipfvpatchvectorfield',['JohnsonJacksonParticleSlipFvPatchVectorField',['../a00071.html',1,'Foam']]],
  ['johnsonjacksonparticleslipfvpatchvectorfield',['JohnsonJacksonParticleSlipFvPatchVectorField',['../a00071.html#a42f0f792754bdd67df4cc8567525793b',1,'Foam::JohnsonJacksonParticleSlipFvPatchVectorField::JohnsonJacksonParticleSlipFvPatchVectorField(const fvPatch &amp;, const DimensionedField&lt; vector, volMesh &gt; &amp;)'],['../a00071.html#a0ec0ca4edd9b40d033bd3ebb91f0b4e0',1,'Foam::JohnsonJacksonParticleSlipFvPatchVectorField::JohnsonJacksonParticleSlipFvPatchVectorField(const fvPatch &amp;, const DimensionedField&lt; vector, volMesh &gt; &amp;, const dictionary &amp;)'],['../a00071.html#aa97cbe08f1accba351481e330fce7ebd',1,'Foam::JohnsonJacksonParticleSlipFvPatchVectorField::JohnsonJacksonParticleSlipFvPatchVectorField(const JohnsonJacksonParticleSlipFvPatchVectorField &amp;, const fvPatch &amp;, const DimensionedField&lt; vector, volMesh &gt; &amp;, const fvPatchFieldMapper &amp;)'],['../a00071.html#a4308424ef4850dd6ced3b97e4203eb0b',1,'Foam::JohnsonJacksonParticleSlipFvPatchVectorField::JohnsonJacksonParticleSlipFvPatchVectorField(const JohnsonJacksonParticleSlipFvPatchVectorField &amp;)'],['../a00071.html#a91cb111fe011fb94983f881c454deaaf',1,'Foam::JohnsonJacksonParticleSlipFvPatchVectorField::JohnsonJacksonParticleSlipFvPatchVectorField(const JohnsonJacksonParticleSlipFvPatchVectorField &amp;, const DimensionedField&lt; vector, volMesh &gt; &amp;)']]],
  ['johnsonjacksonparticleslipfvpatchvectorfield_2ec',['JohnsonJacksonParticleSlipFvPatchVectorField.C',['../a00337.html',1,'']]],
  ['johnsonjacksonparticleslipfvpatchvectorfield_2eh',['JohnsonJacksonParticleSlipFvPatchVectorField.H',['../a00338.html',1,'']]],
  ['johnsonjacksonparticlethetafvpatchscalarfield',['JohnsonJacksonParticleThetaFvPatchScalarField',['../a00072.html#ab4de2b6aeef0cd5aed0a94d42a80ca16',1,'Foam::JohnsonJacksonParticleThetaFvPatchScalarField::JohnsonJacksonParticleThetaFvPatchScalarField(const fvPatch &amp;, const DimensionedField&lt; scalar, volMesh &gt; &amp;)'],['../a00072.html#ad896ebd47fc1f2f92971dcefbdda839a',1,'Foam::JohnsonJacksonParticleThetaFvPatchScalarField::JohnsonJacksonParticleThetaFvPatchScalarField(const fvPatch &amp;, const DimensionedField&lt; scalar, volMesh &gt; &amp;, const dictionary &amp;)'],['../a00072.html#aa297c89153786acaae10e1c2710a3928',1,'Foam::JohnsonJacksonParticleThetaFvPatchScalarField::JohnsonJacksonParticleThetaFvPatchScalarField(const JohnsonJacksonParticleThetaFvPatchScalarField &amp;, const fvPatch &amp;, const DimensionedField&lt; scalar, volMesh &gt; &amp;, const fvPatchFieldMapper &amp;)'],['../a00072.html#a7a91158a3117d8fcfab3cb29cc279b48',1,'Foam::JohnsonJacksonParticleThetaFvPatchScalarField::JohnsonJacksonParticleThetaFvPatchScalarField(const JohnsonJacksonParticleThetaFvPatchScalarField &amp;)'],['../a00072.html#a4cf6a9245c7d534d37bb0232004d294a',1,'Foam::JohnsonJacksonParticleThetaFvPatchScalarField::JohnsonJacksonParticleThetaFvPatchScalarField(const JohnsonJacksonParticleThetaFvPatchScalarField &amp;, const DimensionedField&lt; scalar, volMesh &gt; &amp;)']]],
  ['johnsonjacksonparticlethetafvpatchscalarfield',['JohnsonJacksonParticleThetaFvPatchScalarField',['../a00072.html',1,'Foam']]],
  ['johnsonjacksonparticlethetafvpatchscalarfield_2ec',['JohnsonJacksonParticleThetaFvPatchScalarField.C',['../a00339.html',1,'']]],
  ['johnsonjacksonparticlethetafvpatchscalarfield_2eh',['JohnsonJacksonParticleThetaFvPatchScalarField.H',['../a00340.html',1,'']]],
  ['johnsonjacksonschaeffer',['JohnsonJacksonSchaeffer',['../a00073.html#a00b7ef071ba9887dfd03409ab651af01',1,'Foam::kineticTheoryModels::frictionalStressModels::JohnsonJacksonSchaeffer']]],
  ['johnsonjacksonschaeffer',['JohnsonJacksonSchaeffer',['../a00073.html',1,'Foam::kineticTheoryModels::frictionalStressModels']]],
  ['johnsonjacksonschaefferfrictionalstress_2ec',['JohnsonJacksonSchaefferFrictionalStress.C',['../a00341.html',1,'']]],
  ['johnsonjacksonschaefferfrictionalstress_2eh',['JohnsonJacksonSchaefferFrictionalStress.H',['../a00342.html',1,'']]]
];
