var searchData=
[
  ['lain',['Lain',['../a00109.html',1,'Foam::dragModels']]],
  ['lamb',['Lamb',['../a00110.html',1,'Foam::virtualMassModels']]],
  ['legendremagnaudet',['LegendreMagnaudet',['../a00111.html',1,'Foam::liftModels']]],
  ['lehr',['Lehr',['../a00112.html',1,'Foam::coalescenceEfficiencyKernels']]],
  ['liftmodel',['liftModel',['../a00113.html',1,'Foam']]],
  ['linear',['linear',['../a00116.html',1,'Foam']]],
  ['linear',['linear',['../a00114.html',1,'Foam::wallDampingModels']]],
  ['linear',['linear',['../a00115.html',1,'Foam::blendingMethods']]],
  ['lognormaleqmom',['lognormalEQMOM',['../a00117.html',1,'Foam']]],
  ['lopezdebertodano',['LopezDeBertodano',['../a00118.html',1,'Foam::turbulentDispersionModels']]],
  ['lun',['Lun',['../a00119.html',1,'Foam::kineticTheoryModels::granularPressureModels']]],
  ['lun',['Lun',['../a00120.html',1,'Foam']]],
  ['lunsavage',['LunSavage',['../a00121.html',1,'Foam::kineticTheoryModels::radialModels']]],
  ['luosvendsen',['LuoSvendsen',['../a00124.html',1,'Foam::bubbleBreakupKernels']]],
  ['luosvendsen',['LuoSvendsen',['../a00122.html',1,'Foam::populationBalanceSubModels::breakupKernels']]],
  ['luosvendsen',['LuoSvendsen',['../a00123.html',1,'Foam::breakupKernels']]]
];
